### ISSUE TITLE
Error after running for several hours. Invalid Server Response

### ISSUE THREAD

**Issue by sulkhanp** [python-telegram-bot/python-telegram-bot#1009]
### Steps to reproduce
1.Leave the bot running.

2.Wait 10 hours, 24, or up to 40 and it will inevitably display this error message.

### Expected behaviour
Bot should be running indefinitely

### Actual behaviour
Crashes with this error.

### Configuration
Windows 10

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 9.0.0
certifi 2018.01.18
future 0.16.0
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]

Also, I'm running on Heroku, but previously I was running on google VPS and it still crashed after some time.
### Logs
```
 tg-farm-bot app/worker.1: Traceback (most recent call last): 
Feb 15 14:19:52 tg-farm-bot app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 150, in _parse 
Feb 15 14:19:52 tg-farm-bot app/worker.1:     data = json.loads(decoded_s) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:   File "/app/.heroku/python/lib/python3.6/json/__init__.py", line 354, in loads 
Feb 15 14:19:52 tg-farm-bot app/worker.1:     return _default_decoder.decode(s) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 339, in decode 
Feb 15 14:19:52 tg-farm-bot app/worker.1:     obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 357, in raw_decode 
Feb 15 14:19:52 tg-farm-bot app/worker.1:     raise JSONDecodeError("Expecting value", s, err.value) from None 
Feb 15 14:19:52 tg-farm-bot app/worker.1:  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:  During handling of the above exception, another exception occurred: 
Feb 15 14:19:52 tg-farm-bot app/worker.1:  Traceback (most recent call last): 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "bot.py", line 138, in <module> 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      main() 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "bot.py", line 49, in main 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      echo(bot) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "bot.py", line 58, in echo 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      for update in bot.get_updates(offset=update_id, timeout=10): 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      result = func(self, *args, **kwargs) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/bot.py", line 1720, in get_updates 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      result = self._request.post(url, data, timeout=float(read_latency) + float(timeout)) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in post 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      **urlopen_kwargs) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 203, in _request_wrapper 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      message = self._parse(resp.data) 
Feb 15 14:19:52 tg-farm-bot app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 152, in _parse 
Feb 15 14:19:52 tg-farm-bot app/worker.1:      raise TelegramError('Invalid server response') 
Feb 15 14:19:52 tg-farm-bot app/worker.1:  telegram.error.TelegramError: Invalid server response 
```

**Comment by tsnoam** [comment]
That is not an issue with ptb here. The Telegram server returned an invalid response and ptb failed to parse it, hence raising TelegramError.

**Comment by danieldaeschle** [comment]
Why does the Telegram Server sends wrong data? I have the same error.

**Comment by cyberboysumanjay** [comment]
I'm facing the same issue.

**Comment by tsnoam** [comment]
@cyberboysumanjay Look as the answer above: this is not an issue with ptb. You should contact telegram bot support.

I've locked this github issue for further comments.
