### ISSUE TITLE
ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out

### ISSUE THREAD

**Issue by ntom** [python-telegram-bot/python-telegram-bot#1022]
Spec & Versions:   
```
Python 3.6.4  
   
Name: python-telegram-bot  
Version: 9.0.0   
  
Name: urllib3  
Version: 1.22  
```

This bot has been running and working absolutely fine with no issues what so ever, running, restarting, zero issues.  
Between 6-9 months of no issues at all, today, suddenly, randomly, it stopped working.   
Every time i restarted, changed settings, just would not work at all.  
Here is the running commands..  
   
```python
bot = telegram.Bot(token= config.botToken)
updater = Updater(bot=bot)  
updater.start_polling(poll_interval=10, clean=True, bootstrap_retries=10, timeout=20)
```  
  
Here is the full breakdown of whats coming back...  
Now i appreciate this is alot of stuff to just dump here, BUT, why not, lets go full blown diagnosis on this...   

```
2018-02-27 01:21:26,208 -- ERROR -- updater 400 -- error in bootstrap phase; try=10 max_retries=10
Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 190, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/ext/updater.py", line 385, in _bootstrap
    self.bot.delete_webhook()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/bot.py", line 1840, in delete_webhook
    result = self._request.post(url, data, timeout=timeout)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 192, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out
2018-02-27 01:21:26,215 -- ERROR -- updater 152 -- unhandled exception
Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 190, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/ext/updater.py", line 149, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/ext/updater.py", line 278, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/ext/updater.py", line 385, in _bootstrap
    self.bot.delete_webhook()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/bot.py", line 1840, in delete_webhook
    result = self._request.post(url, data, timeout=timeout)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 192, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out
Exception in thread updater:
Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 190, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/ext/updater.py", line 149, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/ext/updater.py", line 278, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/ext/updater.py", line 385, in _bootstrap
    self.bot.delete_webhook()
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/bot.py", line 1840, in delete_webhook
    result = self._request.post(url, data, timeout=timeout)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/home/flibbr/.pyenv/versions/3.6.4/lib/python3.6/site-packages/telegram/utils/request.py", line 192, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out

2018-02-27 01:21:26,950 -- CRITICAL -- dispatcher 223 -- stopping due to exception in another thread


``` 
  
A quick check produces the following output...  
  
```python   
import urllib3
http = urllib3.PoolManager()
urllib3.disable_warnings()
r = http.request('POST', 'https://api.telegram.org/')
print(r.status)
print(r.headers)  
   
200
HTTPHeaderDict({'Server': 'nginx/1.12.2', 'Date': 'Tue, 27 Feb 2018 01:53:56 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '39953', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-control': 'no-store', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=15768000'})
```

**Comment by ntom** [comment]
without any bug fixes or changes, this has completely resolved itself.  
Upgraded nothing.   
Fixed nothing.   
Changed nothing.   
  
Can only put this down to some kind of telegram api error or something ?

**Comment by ntom** [comment]
@tsnoam yeah that looks great, nice work

**Comment by ert5k** [comment]
Personally, I had a problem in that the "systemd-resolved" service was not on port 53, where it was originally, everything was decided by the usual "reboot" command :)
