### ISSUE TITLE
"cannot import name signal" on GAE

### ISSUE THREAD

**Issue by SehgalDivij** [python-telegram-bot/python-telegram-bot#1065]
Cannot test it while running in gae-sandbox on local machine.

I have a Django project that is using this library and while running it on the local machine as a in the GAE sandbox, I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/home/divij/Desktop/Divij/Personal/bookie/bookie/wsgi.py", line 18, in <module>
    application = DjangaeApplication(get_wsgi_application())
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/django-1.9/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/django-1.9/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/django-1.9/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/django-1.9/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/django-1.9/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/divij/Desktop/Divij/Personal/bookie/bookie/settings.py", line 38, in <module>
    from telegram.ext import Dispatcher
  File "/home/divij/Desktop/Divij/Personal/bookie/lib/telegram/ext/__init__.py", line 23, in <module>
    from .updater import Updater
  File "/home/divij/Desktop/Divij/Personal/bookie/lib/telegram/ext/updater.py", line 27, in <module>
    from signal import signal, SIGINT, SIGTERM, SIGABRT
ImportError: cannot import name signal
```

I googled  and the closest issue I could find to mine was [this](https://github.com/FollonSaxBass/python-telegram-bot-GAE/issues/1).

Even this guy is suggesting it might be an issue with `python-telegram-bot` and not with his library.

Would someone have an idea about this?

**Comment by tsnoam** [comment]
according to this stack trace it seems like "signal" module (from standard python lib) is missing from gae (or at least from gae sandbox?)
1. we use "signal" only for convenience in this context, we'll need to workaround it for gae. this is an actual bug.
2. I wasn't aware of gae sandbox, but it makes me wonder if we can use it in our travis unitests and by that have gae support a first class citizen.

**Comment by tsnoam** [comment]
@SehgalDivij 
I've tried looking for info about gae sandbox and saw reports that's deprecated? Or I wasn't looking at the right thing? I'd love to get some more info about this, so if you can contact me privately http://t.me/tsnoam that would be great.

Anyhow, since I don't have access to gae to test this issue, I would need your help. Can you please run using an interactive python the following commands, one after another?
```
from signal import signal
from signal import SIGINT
from signal import SIGTERM
from signal import SIGABRT
import signal
```
Copy paste the output and add it to this issue. Thanks.

**Comment by tsnoam** [comment]
@SehgalDivij 
kind ping

**Comment by tsnoam** [comment]
Closing due to lack of response from reporter.
If anyone has access to GAE and execute the commands as specified in the above comment please reopen and assist to better support GAE.

**Comment by KaeonX** [comment]
I'm experiencing a similar error as the original reporter **_(ImportError: cannot import name signal)_**

When I made `bot_gae.py` contain only the following:
```
from signal import signal
from signal import SIGINT
from signal import SIGTERM
from signal import SIGABRT
import signal
```

This was the result in the terminal:

```
"C:\Program Files\JetBrains\PyCharm 2018.1.4\bin\runnerw.exe" "C:\Users\KaeonX\PycharmProjects\testbot01\venv\Scripts\python.exe" "C:/Users/KaeonX/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/dev_appserver.py" --host 127.0.0.1 .
INFO     2018-06-24 14:34:21,726 sdk_update_checker.py:231] Checking for updates to the SDK.
INFO     2018-06-24 14:34:22,509 api_server.py:274] Starting API server at: http://localhost:54464
INFO     2018-06-24 14:34:22,513 dispatcher.py:270] Starting module "default" running at: http://127.0.0.1:8080
INFO     2018-06-24 14:34:22,515 admin_server.py:152] Starting admin server at: http://localhost:8000
INFO     2018-06-24 14:34:25,094 module.py:414] [default] Detected file changes:
  .idea
  .idea\workspace.xml
  .idea\workspace.xml___jb_old___
  .idea\workspace.xml___jb_tmp___
ERROR    2018-06-24 06:34:26,023 wsgi.py:263] 
Traceback (most recent call last):
  File "C:\Users\KaeonX\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "C:\Users\KaeonX\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "C:\Users\KaeonX\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "C:\Users\KaeonX\PycharmProjects\testbot01\bot_gae.py", line 1, in <module>
    from signal import signal
ImportError: cannot import name signal
INFO     2018-06-24 14:34:26,026 module.py:414] [default] Detected file changes:
  bot_gae.pyc
INFO     2018-06-24 14:34:26,073 module.py:846] default: "GET / HTTP/1.1" 500 -

```






More notes after doing some testing and meddling about:
In `updater.py`, there is this line:

`from signal import signal, SIGINT, SIGTERM, SIGABRT`

It seems that `SIGINT`, `SIGTERM` and `SIGABRT` can be imported successfully without error. It is only `signal` that cannot be imported. i.e., `from signal import signal` is the command that fails.

**Comment by tsnoam** [comment]
@KaeonX thanks for the info. i'm re-opening the issue.

**Comment by KaeonX** [comment]
Another note/finding:

```
from signal import signal
from signal import SIGINT
from signal import SIGTERM
from signal import SIGABRT
import signal
```
When these commands are executed in an independent python console (independent of GAE), all modules are imported successfully (nothing is returned, meaning no errors are returned). 
The import error appears when the commands are executed with GAE.

**Comment by Bibo-Joshi** [comment]
Given that this issue has been inactive since >2 years, I'll close.
