### ISSUE TITLE
UnboundLocalError: local variable 'resp' referenced before assignment

### ISSUE THREAD

**Issue by Razzaghnoori** [python-telegram-bot/python-telegram-bot#1070]
I'm getting this exception for an unknown reason.

```
Exception in thread updater:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/.../.../venv/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 149, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/.../.../venv/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 348, in _start_webhook
    allowed_updates=allowed_updates)
  File "/home/.../.../venv/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 390, in _bootstrap
    url=webhook_url, certificate=cert, allowed_updates=allowed_updates)
  File "/home/.../.../venv/local/lib/python2.7/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/home/.../.../venv/local/lib/python2.7/site-packages/telegram/bot.py", line 1813, in set_webhook
    result = self._request.post(url_, data, timeout=timeout)
  File "/home/.../.../venv/local/lib/python2.7/site-packages/telegram/utils/request.py", line 273, in post
    **urlopen_kwargs)
  File "/home/.../.../venv/local/lib/python2.7/site-packages/telegram/utils/request.py", line 199, in _request_wrapper
    if 200 <= resp.status <= 299:
UnboundLocalError: local variable 'resp' referenced before assignment
```

### Configuration
OS: ubuntu 16.04
Python version: 2.7
Python-telegram-bot version: 9.0.0

**Comment by wagnerluis1982** [comment]
We need more information to proceed:

- Does the error continue with the latest version (10.01)?
- Could you give a code snippet to make us understand how you are developing your bot?

**Comment by tsnoam** [comment]
@Razzaghnoori 
1. If you are using v9.0.0 as you reported, you should first upgrade to v10.0.2, we can only support the latest version.
1. Despite the above, I've checked the code according to your stacktrace and there's no indication that `resp` can be used before assignment.This leads me to believe that you have modified code which leads to this error.

as of the above i'm closing this issue.

**Comment by tsnoam** [comment]
In addition to my previous comment, neither does the line number in the stack trace matched the code (of v9.0.0).
