### ISSUE TITLE
I have trouble working with Google place and Python bot telegram

### ISSUE THREAD

**Issue by gukobrist** [python-telegram-bot/python-telegram-bot#1094]
I have method, witch returns me object near me (1000 meters). It's just feature for bot to see how work python-google-places.

![2018-04-28 10-51-22](https://user-images.githubusercontent.com/29799050/39393780-1de864d4-4ad2-11e8-9eb9-cb813e0da07e.png)
It's look like this
![2018-04-28 10-52-42](https://user-images.githubusercontent.com/29799050/39393810-5d84da28-4ad2-11e8-9f80-3d81bfbb55e8.png)
But in in the results not a single result. I just know it, because when there are no errors, it gives 3 results.

But i have errors like this:

Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/romashov/PycharmProjects/bot_notification/myvenv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/romashov/PycharmProjects/bot_notification/myvenv/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/romashov/PycharmProjects/bot_notification/myvenv/lib/python3.6/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/romashov/PycharmProjects/bot_notification/bot/bot.py", line 89, in find_place
    place.get_details()
  File "/home/romashov/PycharmProjects/bot_notification/myvenv/lib/python3.6/site-packages/googleplaces/__init__.py", line 1031, in get_details
    self._query_instance.sensor, language=language)
  File "/home/romashov/PycharmProjects/bot_notification/myvenv/lib/python3.6/site-packages/googleplaces/__init__.py", line 137, in _get_place_details
    'language': language})
  File "/home/romashov/PycharmProjects/bot_notification/myvenv/lib/python3.6/site-packages/googleplaces/__init__.py", line 78, in _fetch_remote_json
    request_url, response = _fetch_remote(service_url, params, use_http_post)
  File "/home/romashov/PycharmProjects/bot_notification/myvenv/lib/python3.6/site-packages/googleplaces/__init__.py", line 71, in _fetch_remote
    return (request_url, urllib.request.urlopen(request))
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:833)>

Can you help me?

**Comment by tsnoam** [comment]
Hi
According to the logs you've provided it seems like you have problems with SSL negotiation and it has nothing to do with the library code (I'll be closing this issue now).

If you happen to be running your bot behind the Russian iron curtain you'd need a VPN/proxy in order to access Telegram servers.

If you haven't joined our users group yet, I invite you to it. We have a vibrant community helping each other. https://telegram.me/pythontelegrambotgroup

**Comment by datamove** [comment]
Conveniently, there is a Wiki page now on how to use this package with proxy.

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy
