### ISSUE TITLE
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/update.py", line 59, in de_json     data['message'] = Message.de_json(data['message']) KeyError: 'message'

### ISSUE THREAD

**Issue by keithlowc** [python-telegram-bot/python-telegram-bot#1121]
Not sure whats going on here. Would greatly appreciate any advice. And I apologize if this issue isn't related to the library.

### Steps to reproduce
1. python3 tesseract_bot.py -v

### Expected behaviour
Should display the bot logs only:

Like such: 

2018-05-25 23:44:31,082 - telegram.bot - DEBUG - Exiting: getMe
{'id': 540761338, 'first_name': 'Test', 'username': 'Testy99_bot'}
2018-05-25 23:44:31,083 - telegram.dispatcher - INFO - Dispatcher thread started
2018-05-25 23:44:31,083 - telegram.updater - INFO - Updater thread started

### Actual behaviour

2018-05-25 23:44:31,976 - telegram.bot - INFO - Getting updates: [377359334, 377359335, 377359336, 377359337, 377359338]
Exception in thread updater:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/updater.py", line 201, in _start_polling
    network_delay=network_delay)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/bot.py", line 127, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/bot.py", line 697, in getUpdates
    return [Update.de_json(x) for x in result]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/bot.py", line 697, in <listcomp>
    return [Update.de_json(x) for x in result]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/update.py", line 59, in de_json
    data['message'] = Message.de_json(data['message'])
KeyError: 'message'

### Configuration
**Operating System:**

Mac OS High Sierra 10.13.3

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot (3.2.0)

**Comment by Eldinnie** [comment]
Hi,

The telegram API has changed quite a lot since we released v3.2 (over 2 years ago) you should start with updating the library.
