### ISSUE TITLE
AttributeError: 'Bot' object has no attribute 'message'

### ISSUE THREAD

**Issue by juange92** [python-telegram-bot/python-telegram-bot#1128]
Hi, while trying to make work example echobot02.py I obtain the following Exception:

> 2018-05-29 13:50:40,971 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
> Traceback (most recent call last):
>   File "C:\Users\jose.perez\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
>     handler.handle_update(update, self)
>   File "C:\Users\jose.perez\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\messagehandler.py", line 169, in handle_update
>     return self.callback(dispatcher.bot, update, **optional_args)
>   File "C:/Telegram/echo00.py", line 45, in echo
>     update.send_message(update.message.text)
> AttributeError: 'Bot' object has no attribute 'message'

Has the .message method been changed?

**Comment by tsnoam** [comment]
Please add all missing information from the new issue template.

**Comment by NgocVan9x** [comment]
same issue when run example

**Comment by imamsetyo** [comment]
i have same problem

**Comment by imamsetyo** [comment]
i try telegram bot and telepot , both same problem , whats happen ?

**Comment by tsnoam** [comment]
Closing issue due to lack of information as requested in issue template.

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by SkYNewZ** [comment]
Check this :
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This program is dedicated to the public domain under the CC0 license.
#
# THIS EXAMPLE HAS BEEN UPDATED TO WORK WITH THE BETA VERSION 12 OF PYTHON-TELEGRAM-BOT.
# If you're still using version 11.1.0, please see the examples at
# https://github.com/python-telegram-bot/python-telegram-bot/tree/v11.1.0/examples

"""
Simple Bot to reply to Telegram messages.

First, a few handler functions are defined. Then, those functions are passed to
the Dispatcher and registered at their respective places.
Then, the bot is started and runs until we press Ctrl-C on the command line.

Usage:
Basic Echobot example, repeats messages.
Press Ctrl-C on the command line or send a signal to the process to stop the
bot.
"""

import logging

from telegram.ext import Updater, CommandHandler, MessageHandler, Filters

# Enable logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)

logger = logging.getLogger(__name__)


# Define a few command handlers. These usually take the two arguments bot and
# update. Error handlers also receive the raised TelegramError object in error.
def start(bot, update):
    """Send a message when the command /start is issued."""
    bot.send_message(chat_id=update.message.chat_id, text='Hi!')


def help(bot, update):
    """Send a message when the command /help is issued."""
    bot.send_message(chat_id=update.message.chat_id, text='Help!')


def echo(bot, update):
    """Echo the user message."""
    bot.send_message(chat_id=update.message.chat_id, text=update.message.text)


def error(bot, update):
    """Log Errors caused by Updates."""
    logger.warning('Update "%s" caused error "%s"', bot, update.error)


def main():
    """Start the bot."""
    # Create the Updater and pass it your bot's token.
    # Make sure to set use_context=True to use the new context based callbacks
    # Post version 12 this will no longer be necessary
    updater = Updater("TOKEN")

    # Get the dispatcher to register handlers
    dp = updater.dispatcher

    # on different commands - answer in Telegram
    dp.add_handler(CommandHandler("start", start))
    dp.add_handler(CommandHandler("help", help))

    # on noncommand i.e message - echo the message on Telegram
    dp.add_handler(MessageHandler(Filters.text, echo))

    # log all errors
    dp.add_error_handler(error)

    # Start the Bot
    updater.start_polling()

    # Run the bot until you press Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT. This should be used most of the time, since
    # start_polling() is non-blocking and will stop the bot gracefully.
    updater.idle()


if __name__ == '__main__':
    main()
```
