### ISSUE TITLE
Solution for those who receives "cannot import 'TelegramError'" while using IPython

### ISSUE THREAD

**Issue by ChabanMaxym** [python-telegram-bot/python-telegram-bot#1139]
### Steps to reproduce
1. pip install python-telegram-bot 

2. from telegram.ext import Updater

3. ImportError: cannot import name 'TelegramError'

### Expected behaviour
Classes must be imported

### Actual behaviour
ImportError: cannot import name 'TelegramError'

### Configuration
**Operating System:** Windows 10 v1709 (OS 16299.431)
**Version of Python, python-telegram-bot & dependencies:**
absl-py==0.1.11
alabaster==0.7.10
algorithmia==1.1.2
arxiv==0.2.2
asn1crypto==0.24.0
astor==0.6.2
attrs==17.4.0
Babel==2.5.3
bcrypt==3.1.4
beautifulsoup4==4.6.0
bleach==1.5.0
boto==2.48.0
boto3==1.5.24
botocore==1.8.38
bs4==0.0.1
bz2file==0.98
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
choice==0.1
chromote==0.4.0
click==3.3
closure-linter==2.3.19
colorama==0.3.9
configparser==3.5.0
confusable-homoglyphs==3.0.0
cryptography==2.2.2
ctrfoobar2000==1.2.0.2
cycler==0.10.0
decorator==4.2.1
Django==2.0.4
django-common-helpers==0.9.1
django-cors-headers==2.2.0
django-graphos-3==1.1
django-slack==5.12.0
django-widget-tweaks==1.4.1
djangorestframework==3.7.7
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
feedparser==5.2.1
Flask==0.11.1
future==0.16.0
gast==0.2.0
gensim==3.3.0
gevent==1.2.2
google-api-python-client==1.6.5
googletrans==2.2.0
greenlet==0.4.13
grpcio==1.10.0
gTTS==2.0.0
gTTS-token==1.1.1
gunicorn==19.7.1
html5lib==0.9999999
httplib2==0.10.3
idna==2.6
ijson==2.3
imagesize==1.0.0
ipgetter==0.7
ipykernel==4.8.0
ipython==5.0.0
ipython-genutils==0.2.0
ipywidgets==7.1.1
isodate==0.6.0
itsdangerous==0.24
jdcal==1.4
Jinja2==2.8
jmespath==0.9.3
jslint==0.6.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
kaggle==1.3.1
kiwisolver==1.0.1
langdetect==1.0.7
locustio==0.8.1
lxml==4.2.1
Markdown==2.6.11
MarkupSafe==0.23
matplotlib==2.2.2
mistune==0.8.3
mpg123==0.4
msgpack-python==0.5.4
mysql-connector-python==8.0.6
nbconvert==5.3.1
nbformat==4.4.0
nltk==3.2.5
notebook==5.4.0
numpy==1.14.0
oauth2client==4.1.2
openpyxl==2.5.3
packaging==17.1
pandas==0.22.0
pandocfilters==1.4.2
paramiko==2.4.0
pbr==3.1.1
pickleshare==0.7.4
pluggy==0.6.0
pocketsphinx==0.1.3
post==0.0.26
prompt-toolkit==1.0.15
protobuf==3.5.2
psutil==5.4.5
py==1.5.2
pyaml==16.9.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
PyAudio==0.2.11
pycparser==2.18
pygame==1.9.3
Pygments==2.2.0
PyJWT==1.6.1
PyMySQL==0.8.0
PyNaCl==1.2.1
pyparsing==2.2.0
pypiwin32==223
pytest==3.4.2
python-dateutil==2.6.1
python-gflags==3.1.2
python-http-client==3.1.0
python-telegram-bot==10.1.0
pytz==2018.3
pywin32==223
pywinpty==0.5.1
PyYAML==3.12
pyzmq==16.0.4
qtconsole==4.3.1
Question==0.1
rdflib==4.2.2
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.12
schedule==0.5.0
scikit-learn==0.19.1
scipy==1.0.0
Send2Trash==1.4.2
sendgrid==5.3.0
simplegeneric==0.8.1
six==1.11.0
sklearn==0.0
slackclient==1.0.2
smart-open==1.5.6
snowballstemmer==1.2.1
sounddevice==0.3.11
SPARQLWrapper==1.8.0
SpeechRecognition==3.8.1
Sphinx==1.7.2
sphinxcontrib-websupport==1.0.1
StackAPI==0.1.9
stackexchange==0.5.0
stevedore==1.28.0
tensorboard==1.6.0
tensorflow==1.6.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
textblob==0.9.0
tornado==4.5.3
traitlets==4.3.2
uiautomation==1.1.6
ujson==1.35
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.22
v==3.0.0
vboxapi==1.0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.8.2
virtualenvwrapper-win==1.2.5
waitress==1.1.0
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.37.0
Werkzeug==0.14.1
widgetsnbextension==3.1.3
wikipedia==1.4.0
win-unicode-console==0.5
win10toast==0.9
WMI==1.4.9
XlsxWriter==1.0.5

``$ python -m telegram``
python-telegram-bot 10.1.0
certifi 2018.01.18
future 0.16.0
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

### Logs
Traceback (most recent call last):
  File "C:\Programs\Python\3.6.4\lib\site-packages\IPython\core\interactiveshell.py", line 2869, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-30f5e78c6668>", line 1, in <module>
    from telegram.ext import Updater
  File "C:\Programs\JetBrains\PyCharm 2018.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Programs\Python\3.6.4\lib\site-packages\telegram\ext\__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher, DispatcherHandlerStop, run_async
  File "C:\Programs\JetBrains\PyCharm 2018.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Programs\Python\3.6.4\lib\site-packages\telegram\ext\dispatcher.py", line 33, in <module>
    from telegram import TelegramError
ImportError: cannot import name 'TelegramError'

### Solution
While writing bug report found out that it can be solved by updating ipython.
I use run cells in Intellij Idea (iPython module interactiveshell). After running pip install --upgrade ipython all is running ok

**Comment by ChabanMaxym** [comment]
@jsmnbom Yep, solution was to update iPython. At least it works for now)
I will investigate and write again if something goes wrong)
Thanks and good luck :)
