### ISSUE TITLE
ImportError: cannot import name escape

### ISSUE THREAD

**Issue by KaeonX** [python-telegram-bot/python-telegram-bot#1140]
### Steps to reproduce
1. Downloaded timerbot.py (https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/timerbot.py) and renamed it as main.py on my computer (in the bot's main directory)

2. Inserted my bot's TOKEN in line 83 of the timerbot.py code.

3. Deployed the bot to Google App Engine using Google App Engine Launcher.

### Expected behaviour
Bot is expected to reply /start command with "Hi! Use /set <seconds> to set a timer", and be able to set timer for user.

### Actual behaviour
Bot is unable to reply to any message or command send by the user. 

### Configuration
**Operating System:**
Windows 10 Home v1803 (OS 17134.48)

**Version of Python, python-telegram-bot & dependencies:**
``$ python -m telegram``
<pre>C:\Python27\python.exe: No module named telegram</pre>

### Logs
<pre>
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/j~enantiobot/1.410494773089768659/main.py", line 18, in <module>
    from telegram.ext import Updater, CommandHandler
  File "/base/data/home/apps/j~enantiobot/1.410494773089768659/telegram/__init__.py", line 22, in <module>
    from .user import User
  File "/base/data/home/apps/j~enantiobot/1.410494773089768659/telegram/user.py", line 23, in <module>
    from telegram.utils.helpers import mention_html as util_mention_html
  File "/base/data/home/apps/j~enantiobot/1.410494773089768659/telegram/utils/helpers.py", line 20, in <module>
    from html import escape
ImportError: cannot import name escape</pre>

### Other notes/information: 
While trying to resolve this "ImportError: cannot import name escape" problem, I've uninstalled and re-installed _pip_, _python-telegram-bot_ and _telegram_ several times in the admin command prompt. Also, I've tried to adjust the environment PATH settings such that the command prompts read python 2.7 instead of python 3.6 which is also installed on my computer, which succeeded. How do I resolve this issue (ImportError: cannot import name escape)? Is there something wrong with my computer's python versions?

**Comment by xamgore** [comment]
@KaeonX, why did you closed the issue? Did you fixed it?

**Comment by KaeonX** [comment]
@xamgore I've tried another method of implementing (coding, deploying) the telegram bot. Hence, this error is no longer applicable.
