### ISSUE TITLE
MARKDOWN issue

### ISSUE THREAD

**Issue by Wirtos** [python-telegram-bot/python-telegram-bot#1150]
### Steps to reproduce
1.  win_text = "And the winner in nomination ``*{0}*`` - {1}".format(winner[1], winner[0]))
     bot.send_message(text=win_text,
                             chat_id=chat_id,
                             parse_mode=telegram.ParseMode.MARKDOWN)
   

### Expected behaviour
We have list winner = ["@Wirtos_new", "noname"]
So, we have simple string with simple MARKDOWN as output:  "And the winner in nomination ``*noname*`` - @Wirtos_new"
Bot just needs to send a message

### Actual behaviour
Error :\
telegram.error.BadRequest

### Configuration
Win 10

**Version of Python, python-telegram-bot & dependencies:**

``$ py -3.6 -m telegram '10.1.0'``

### Logs
ERROR:telegram.utils.promise:An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\telegram\utils\promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "C:/Users/user/PycharmProjects/proj/bot.py", line 360, in main_message
    parse_mode=telegram.ParseMode.MARKDOWN)
  File "C:\Python36\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Python36\lib\site-packages\telegram\bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "C:\Python36\lib\site-packages\telegram\utils\request.py", line 278, in post
    **urlopen_kwargs)
  File "C:\Python36\lib\site-packages\telegram\utils\request.py", line 215, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 47
2018-07-04 17:46:38,798 telegram.utils.promise ERROR    An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\telegram\utils\promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "C:/Users/user/PycharmProjects/proj/bot.py", line 360, in main_message
    parse_mode=telegram.ParseMode.MARKDOWN)
  File "C:\Python36\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Python36\lib\site-packages\telegram\bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "C:\Python36\lib\site-packages\telegram\utils\request.py", line 278, in post
    **urlopen_kwargs)
  File "C:\Python36\lib\site-packages\telegram\utils\request.py", line 215, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 47

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
