### ISSUE TITLE
Error in Tipbot

### ISSUE THREAD

**Issue by DigitalCoin1** [python-telegram-bot/python-telegram-bot#1252]
### Steps to reproduce
I used this tutorial to perform the bot: https://github.com/DigitalCoin1/TipBot_SperoCoin

I am having problems with this bot in the / spero_tip and / spero_withdraw functions only.
The errors I receive are as follows:

> /spero_tip @user <amout>
> telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/dispatcher.py", line 301, in process_update
>     handler.handle_update(update, self)
>   File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/commandhandler.py", line 173, in handle_update
>     return self.callback(dispatcher.bot, update, **optional_args)
>   File "command.py", line 54, in spero_tip
>     amount = float(amount)
> ValueError: could not convert string to float: '@francissantana'

> /spero_withdraw <address> <amount>
> 
> telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/dispatcher.py", line 301, in process_update
>     handler.handle_update(update, self)
>   File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/commandhandler.py", line 173, in handle_update
>     return self.callback(dispatcher.bot, update, **optional_args)
>   File "command.py", line 90, in spero_withdraw
>     amount = float(target)
> ValueError: could not convert string to float: 'rZav53UV5gaV69PKkqUjaBqPz 0.01'

### Configuration
**Google Cloud Engine + Ubuntu 16.04**

**Version of Python, python-telegram-bot & dependencies:**

> $ python3 -m telegram
> python-telegram-bot 11.1.0
> certifi 2018.08.24
> future 0.16.0
> Python 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Comment by Eldinnie** [comment]
actually the error is in the library you linked, not ours. Please open an issue there
