### ISSUE TITLE
Python telegram bot getting phone number issue

### ISSUE THREAD

**Issue by GrayWolfy** [python-telegram-bot/python-telegram-bot#1259]
Hello Guys, I dont know whether it's a bug or my loony head.
But there is the code:

   ```
def contact_callback(bot, update):
       contact = update.effective_message.contact
       phone = contact.phone_number
       print(contact)
       print(phone)
       update.message.reply_text('Thanks your data is accepted', get_authorized(), resize_keyboard=True)

    get_authorized is simply this:

    def get_authorized():
        reply_keyboard = [['Pay', 'Why I'm in debt'], ['Remind Later']]
        return reply_keyboard
```

It prints out phone and contact in console. But crashes, I can't Understand why. And I don't get buttons and text.  After I leave just:
update.message.reply_text('Thanks your data is accepted', resize_keyboard=True)

I see "'Thanks your data is accepted'", so the problem somehow is linked to the function get_authorized().

Here's an Exception text:

```
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/ubuntu/Telegram_bot_OSDI/Telegram_Bot_OSDI_22.py", line 164, in contact_callback
    update.message.reply_text('Thanks your data is accepted', get_authorized(), resize_keyboard=True)
  File "/usr/local/lib/python3.5/dist-packages/telegram/message.py", line 455, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Unsupported parse_mode
```

**Comment by nmlorg** [comment]
You're passing your keyboard positionally rather than by keyword, and the first keyword argument to Bot.send_message happens to be parse_mode, so:
```py
update.message.reply_text('Thanks your data is accepted', get_authorized(), resize_keyboard=True)
```
becomes:
```py
update.message.bot.send_message(chat_id=update.message.chat_id, text='Thanks your data is accepted', parse_mode=[['Pay', "Why I'm in debt"], ['Remind Later']], resize_keyboard=True)
```
I think you meant something like:
```py
update.message.reply_text('Thanks your data is accepted', reply_markup={'keyboard': get_authorized(), 'resize_keyboard': True})
```

**Comment by GrayWolfy** [comment]
@nmlorg, thanks for your answer!  I'll try it asap.

**Comment by Eldinnie** [comment]
Hi,

As far as I can see this question is answered by @nmlorg (Thanks!) For further questions about the usage of this library we invite you to ask them in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
