### ISSUE TITLE
ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

### ISSUE THREAD

**Issue by owneroxxor** [python-telegram-bot/python-telegram-bot#1264]
### Steps to reproduce
set the telegram bot:
1. BOT = telegram.bot.Bot(BOT_TOKEN)

let the script run threads and all the stuff it needs, making requests etc. For me, the error is given with:
2. BOT.edit_message_text(text, chatid, msgid, timeout=30)

### Expected behaviour
Don't kill the thread when timeout error.

### Actual behaviour
Kills my entire thread when timeout error.

### Configuration
**4CPU 16GB RAM Netherlands server with <1.00ms delay with telegram api servers**

`python-telegram-bot 11.1.0
certifi 2018.04.16
future 0.16.0
Python 3.6.5 (default, Apr 10 2018, 17:08:37)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
``

### Logs
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "bot_automation.py", line 1689, in groupAdderThread
    BOT.edit_message_text(text, chat_id=userid, message_id=msg_id, parse_mode=telegram.ParseMode.MARKDOWN, timeout=30)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 205, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out  
```

How to stop this from killing my thread? How to increase the 5.0 timeout? I got this killing my bot everytime I go to sleep, even with a super good server configuration placed at less than 1ms delay from telegram api servers. What am I forgetting here?

**Comment by jsmnbom** [comment]
This does indeed look quite odd. Could you put together a minimal (not) working example for us, so we can look properly into this issue? :)

**Comment by owneroxxor** [comment]
Ok, made a simple exemple...

```
import telegram,threading

**CHAT = '@username'**

BOT = telegram.bot.Bot(BOT_TOKEN)

msg = BOT.send_message_text(CHAT, text, timeout=30)
threading.Thread(target=checkLeftThread,args=(msg.message_id,)).start()

updater.idle()

def checkLeftThread(msg_id, text='bar foo):
  text = 'foo bar' if text == 'bar foo' else 'foo bar'
  BOT.edit_message_text(text, CHAT, msg_id, timeout=30)
  threading.Timer(5, checkLeftThread,args=(msg.message_id,)).start()
  sys.exit()

```

**Comment by owneroxxor** [comment]
I'am wondering how other people are dealing with this? because I almost have this error killing all my other bot's threads. That is really critical. If this error cannot be solved, how to stop this from killing my thread? How to increase the 5.0 timeout? How to prevent this: _socket.timeout: The read operation timed out_ from killing the thread? Thanks!

**Comment by Eldinnie** [comment]
The code you provided is impossible. It will not work, nor do I expect it to.
The positional arguments are wrong, the method `bot.send_message_text` does not exist. Are you sure you;re using `python-telegram-bot`?

**Comment by owneroxxor** [comment]
Oh, sorry about that, I wrote it very quickly just for you to try it. Ok, I've written it again:

```
import telegram,threading

CHAT = '@owneroxxor'
BOT_TOKEN = '632694705:AAGXOQBYFTWZua-qeFcW6efgDoieUxXB7vA'

def checkLeftThread(msg_id, text='bar foo'):
	text = 'foo bar' if text == 'bar foo' else 'foo bar'
	BOT.edit_message(text, CHAT, msg_id, timeout=30)
	threading.Timer(1, checkLeftThread,args=(msg.message_id,)).start()
	sys.exit()

BOT = telegram.bot.Bot(BOT_TOKEN)
text = 'foo bar'
msg = BOT.send_message(CHAT, text, timeout=30)
threading.Thread(target=checkLeftThread, args=(msg.message_id,)).start()
updater.idle()
```

**Comment by owneroxxor** [comment]
Some more logs...

![image](https://user-images.githubusercontent.com/30055123/47096049-c6b12380-d204-11e8-8783-bd8630531463.png)

**Comment by owneroxxor** [comment]
Can see it is intermittent:

![image](https://user-images.githubusercontent.com/30055123/47096303-42ab6b80-d205-11e8-8f9f-c36501175b03.png)

**Comment by jsmnbom** [comment]
I don't understand where you're getting your updater from...?
The code you posted still doesn't actually run.

What I would recommend you go ahead and try is to try and use our JobQueue instead of threading primitives - not saying that it shouldn't work like this, the code just looks a wee bit odd to me. And I suspect the timeout error is possibly raised due to requests being made on other threads, and while urlib3s ConnectionPool should be threadsafe, it might not like cancelled threads (ones that have been "terminated" by a SystemExit exception) very much.

**Comment by owneroxxor** [comment]
Thanks for the response @jsmnbom @tsnoam and @Eldinnie ...

I made the changes you told me. The problem persists... lets get into it...

Here is the brand new code (no errors in this one because I used it myself.

```
#!/usr/local/bin/python3.6
# -*- coding: utf-8 -*-

import telegram,threading,time,sys,logging
from telegram.ext import JobQueue

CHAT = '@test_channel_username' # <<< USE A CHANNEL, NOT A USER CHAT (edit_message_text method takes way longer to complete a channel message editing than an message editing on an user chat ~I dont know why
BOT_TOKEN = 'BOT_TOKEN'
BOT = telegram.bot.Bot(BOT_TOKEN)
JOB = JobQueue(BOT)

def testThread(bot, job):
	job.context['text'] = '🔥' if job.context['text'] == '👈' else '👈'
	while True:
		try:
			bot.edit_message_text(job.context['text'],	
													chat_id = CHAT,
													message_id = job.context['msg_id'],
													timeout=30)
		except Exception as e:
			logging.warning(e)
			logging.warning('Timeouted ... Retrying edit message.')
			continue
		else:
			context = {}
			context['text'] = job.context['text']
			context['msg_id'] = job.context['msg_id']
			JOB.run_once(testThread, 1, context)
			break

context = {}
context['text'] =  '🔥'
msg = BOT.send_message(CHAT, context['text'], timeout=30)
context['msg_id'] = msg.message_id
JOB.run_once(testThread, 1, context)
JOB.start()

time.sleep(500)
```

The script executes the message editing as expected until I get the error:

`telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)`

Then, the script crashes, the bot no longer can edit any messages (all retries get Time Out error) as you can see below:

![image](https://user-images.githubusercontent.com/30055123/47450158-e44d3280-d79a-11e8-8132-039d0cd36c04.png)

JobQueue is being used, so how to deal with this? How to increase the read timeout parameter from 5.0s?

**Comment by Eldinnie** [comment]
I would like to direct you to point 4 of the last comment made by @tsnoam with that, this issue is not only closed but also locked.
