### ISSUE TITLE
send document ,use io.StringIO object will crach

### ISSUE THREAD

**Issue by blue-bird1** [python-telegram-bot/python-telegram-bot#1279]
### Steps to reproduce
1. run code
```
opml_file = io.StringIO(_)
bot.send_document(chat_id=update.message.chat_id, document=opml_file, filename="export.opml")
```
```
(Pdb) p _
'<?xml version="1.0" encoding="UTF-8"?>\n    <opml version="2.0">\n        <body>\n            <outline text="All">\n                <outline title="V2EX - 技术" text="V2EX - 技术" xmlUrl="https://www.v2ex.com/feed/tab/tech.xml" htmlUrl="https://www.v2ex.com/"></outline>\n            </outline>\n     </body>\n    </opml>'
```

### Expected behaviour
send document

### Actual behaviour
```
2018-10-30 20:53:58,370 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/root/code/rssbot/command.py", line 14, in export
    bot.send_document(chat_id=update.message.chat_id, document=opml_file, filename="export.opml")
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 76, in decorator
    url, data = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 560, in send_document
    document = InputFile(document, filename=filename)
  File "/usr/local/lib/python3.7/site-packages/telegram/files/inputfile.py", line 67, in __init__
    self.mimetype = self.is_image(self.input_file_content)
  File "/usr/local/lib/python3.7/site-packages/telegram/files/inputfile.py", line 96, in is_image
    image = imghdr.what(None, stream)
  File "/usr/local/lib/python3.7/imghdr.py", line 23, in what
    res = tf(h, f)
  File "/usr/local/lib/python3.7/imghdr.py", line 45, in test_png
    if h.startswith(b'\211PNG\r\n\032\n'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

### Configuration
**Operating System:**
`Linux iZj6c5fxrmjicz4wette8kZ 4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.16.0
Python 3.7.0 (default, Oct  9 2018, 01:34:21)  [GCC 5.4.0 20160609]
```

### Logs
Insert logs here (if necessary)

**Comment by jsmnbom** [comment]
Files must be opened as bytes.. Therefore use BytesIO instead. For further questions we invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
