### ISSUE TITLE
Strange error when sending certain video

### ISSUE THREAD

**Issue by javad94** [python-telegram-bot/python-telegram-bot#1284]
### Steps to reproduce
1. download the [specific video](https://transfer.sh/B9Esj/gmail2.mp4)
2. fill the token and chat_id
3. run the code
```
from telegram import Bot
token = "Some_token"
bot = Bot(token)
bot.send_video(chat_id= "chat_id", video=open(r"video path", "rb"))
```

### Expected behavior
the video should be sent successfully

### Actual behavior
PTB give an error

### Configuration
**Operating System:**
Windows 10
**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 11.1.0
certifi 2018.10.15
future 0.17.0
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
```
### Logs
```Traceback (most recent call last):
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\Javad\Anaconda3\lib\ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Javad\Anaconda3\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "C:\Users\Javad\Anaconda3\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\utils\request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 70, in request
    **urlopen_kw)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\Javad\Anaconda3\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\Javad\Anaconda3\lib\ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Javad\Anaconda3\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "C:\Users\Javad\Anaconda3\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python-projects/tgManager/testmediagroup.py", line 8, in <module>
    video=open(r"C:\Users\Javad\Desktop\techtube\gmail2.mp4", "rb"))
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\utils\request.py", line 305, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "C:\Users\Javad\Anaconda3\lib\site-packages\telegram\utils\request.py", line 209, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out',))
```

**Comment by tsnoam** [comment]
Hi,
As can be seen in the log you've hit a timeout. Please check the documentation about extending the timeout and also look for the wiki article about network errors.

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
