### ISSUE TITLE
Timed out on startup

### ISSUE THREAD

**Issue by pauloDEv** [python-telegram-bot/python-telegram-bot#1300]
2018-11-22 20:05:20,015 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x7fb747ed8908>
2018-11-22 20:05:20,016 - JobQueue - DEBUG - JobQueue thread started
2018-11-22 20:05:20,016 - telegram.ext.updater - DEBUG - dispatcher - started
2018-11-22 20:05:20,016 - telegram.ext.updater - DEBUG - updater - started
2018-11-22 20:05:20,017 - telegram.ext.updater - DEBUG - Updater thread started (polling)
2018-11-22 20:05:20,017 - telegram.ext.updater - DEBUG - Start network loop retry bootstrap del webhook
2018-11-22 20:05:20,017 - telegram.bot - DEBUG - Entering: delete_webhook
2018-11-22 20:05:20,017 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org
2018-11-22 20:05:20,018 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-11-22 20:05:20,191 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot--TOKEN--o/deleteWebhook HTTP/1.1" 200 68
2018-11-22 20:05:20,193 - telegram.bot - DEBUG - True
2018-11-22 20:05:20,193 - telegram.bot - DEBUG - Exiting: delete_webhook
2018-11-22 20:05:20,193 - telegram.ext.updater - DEBUG - Bootstrap done
2018-11-22 20:05:20,193 - telegram.ext.updater - DEBUG - Start network loop retry getting Updates
2018-11-22 20:05:20,193 - telegram.bot - DEBUG - Entering: get_updates
2018-11-22 20:05:25,196 - telegram.ext.updater - DEBUG - Timed out getting Updates: Timed out
2018-11-22 20:05:25,197 - telegram.bot - DEBUG - Entering: get_updates
2018-11-22 20:05:25,197 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): api.telegram.org
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

### Configuration
Linux elementaryOS based on ubuntu

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 11.1.0
certifi 2018.01.18
future 0.17.1
Python 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]

**Comment by jsmnbom** [comment]
And this doesn't happen when simply connecting to api.telegram.org using other means on your machine?

**Comment by jsmnbom** [comment]
Please have a look at: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors
Futhermore we invite you to ask questions in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
