### ISSUE TITLE
Unable to commit: Error during pylint check

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1321]
Since I have little knowledge of the automatic checking setup, I don't know, if this is even PTB related. However, since I was not able to resolve the issue in not-PTB-related ways, I at least wanted to ask.
I finally hat the time, to implement the global memory suggested in #1318 and would very much like to open a PR 😅 

### Steps to reproduce
1. Follow the Contribution guideline

2. Change something (for testing, I added a whitespace in a comment …)

3. try to commit the changes

### Expected behaviour
Commits

### Actual behaviour
During the `pylint` procedure an error gets thrown: `AttributeError: module 'astroid' has no attribute 'YES'`.

### Configuration
**Operating System:**

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19
```

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

```
python-telegram-bot 11.1.0
certifi 2018.11.29
future 0.17.1
Python 2.7.15rc1
```

### What I have tried

- Update `pylint` and `astroid`
- Reinstall the OS
- check if `astroid.YES` exists (it does!)

**Comment by jsmnbom** [comment]
I will look into this later, for now just use the `--no-verify` arg in git commit to skip the pre-commit hooks :)

**Comment by Bibo-Joshi** [comment]
Thanks for the quick reply!
I just noted, that `make test` also fails (A lot of `INTERNALERROR`s).
If it seems to you, that this is not a general problem, please feel free to close the issue. Sorry for beeing noobish :grimacing:

**Comment by jsmnbom** [comment]
It sounds like there's something wrong with your setup somehow :/
`make test` works fine for me.
Could you humor me and just try using python 3?...

**Comment by Bibo-Joshi** [comment]
Got `make test` fixed by upgrading `flaky`. BTW: I noticed, that AppVeyor and Travis CI throw the same error I got (see outputs in #1322 ) 
`pylint` seems to be rum from `python3`. This is the complete traceback:

```
yapf.....................................................................Passed
Flake8...................................................................Passed
pylint...................................................................Failed
hookid: pylint

No config file found, using default configuration
Traceback (most recent call last):
  File "/home/hinrich/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/checkers/variables.py", line 1153, in visit_importfrom
    self._check_module_attrs(node, module, name.split('.'))
  File "/home/<user>/.cache/pre-commit/repotmz9w1sv/py_env-python3.6/lib/python3.6/site-packages/pylint/checkers/variables.py", line 1218, in _check_module_attrs
    if module is astroid.YES:
AttributeError: module 'astroid' has no attribute 'YES'
```
I even removed `pylint` for `python2.7` … Funnily, after upgrading `flaky`, `git commit` seems to work every other time I try to commit - however, `pylint` still failes throwing some errors that are simply not correct. If that, same output as above.
Running `pylint telegram` diractly from command line does work.

Thanks a lot for looking into this!
