### ISSUE TITLE
Bot.getMe() raises inconsistent exceptions

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#134]
as agreed in the chat, all exceptions raised should be TelegramError (or similar exceptions)

these are the (inconsistent) exceptions I've seen:

```python
>>> telegram.Bot('not-probably-formatted-token').getMe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 176, in getMe
    result = request.get(url)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 67, in get
    return _parse(result)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 48, in _parse
    data = json.loads(json_data.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3621: ordinal not in range(128)

>>> telegram.Bot((9 * '1') + ':' + (35 * 'x')).getMe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 176, in getMe
    result = request.get(url)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 65, in get
    result = urlopen(url).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by tsnoam** [comment]
Forgot to mention the following exception. (reported by a user of the flegxet telegram plugin):

```python
Traceback (most recent call last):
File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 438, in _runplugin
return method(*args, **kwargs)
File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 22, in call
return self.func(*args, **kwargs)
File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/output/send_telegram.py", line 181, in on_task_exit
bot.getMe()
File "/usr/local/flexget/env/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
result = func(self, *args, **kwargs)
File "/usr/local/flexget/env/lib/python2.7/site-packages/telegram/bot.py", line 176, in getMe
result = request.get(url)
File "/usr/local/flexget/env/lib/python2.7/site-packages/telegram/utils/request.py", line 65, in get
result = urlopen(url).read()
File "/usr/local/python/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/local/python/lib/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/usr/local/python/lib/python2.7/urllib2.py", line 449, in _open
'_open', req)
File "/usr/local/python/lib/python2.7/urllib2.py", line 409, in callchain
result = func(*args)
File "/usr/local/python/lib/python2.7/urllib2.py", line 1240, in https_open
context=self._context)
File "/usr/local/python/lib/python2.7/urllib2.py", line 1200, in do_open
r = h.getresponse(buffering=True)
File "/usr/local/python/lib/python2.7/httplib.py", line 1132, in getresponse
response.begin()
File "/usr/local/python/lib/python2.7/httplib.py", line 453, in begin
version, status, reason = self.readstatus()
File "/usr/local/python/lib/python2.7/httplib.py", line 409, in readstatus
line = self.fp.readline(_MAXLINE + 1)
File "/usr/local/python/lib/python2.7/socket.py", line 480, in readline
data = self.sock.recv(self.rbufsize)
File "/usr/local/python/lib/python2.7/ssl.py", line 734, in recv
return self.read(buflen)
File "/usr/local/python/lib/python2.7/ssl.py", line 621, in read
v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)
```

**Comment by tsnoam** [comment]
I'm working on fixes for this issue. I have (mid-way) progress (can be seen on my fork https://github.com/tsnoam/python-telegram-bot )
I'll send PR when it's ready.

**Comment by jh0ker** [comment]
@tsnoam Great, thank you for the work! :)
