### ISSUE TITLE
Wiki of Transition Guide to Version 12.0 might be wrong.

### ISSUE THREAD

**Issue by horstmannmat** [python-telegram-bot/python-telegram-bot#1363]
I was migrating to 12.0 and I realize that this wiki might be wrong.
[There](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0#handler-callbacks)
``` python
def start(update: Update, context: CallbackContext):
    # Stuff here
    # args will be available as context.args
    # jobqueue will be available as context.jobqueue
```
Output this error:
```
Traceback (most recent call last):
  File "bot.py", line 50, in <module>
    class MyHomebot():
  File "bot.py", line 54, in MyHomebot
    def start(self, update: Update, context: CallbackContext):
NameError: name 'Update' is not defined

```

Should be 
``` python
def start(update: Updater, context: CallbackContext):
    # Stuff here
    # args will be available as context.args
    # jobqueue will be available as context.jobqueue
```

Or am I missing something?

**Comment by horstmannmat** [comment]
Need to ```from telegram import Update``` :stuck_out_tongue:
