### ISSUE TITLE
Doesn't work example from 'Your First Bot' article

### ISSUE THREAD

**Issue by intervisionlord** [python-telegram-bot/python-telegram-bot#1396]
### Steps to reproduce
1. Do step by step things, described in https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot

### Expected behaviour
response on "/start" command

### Actual behaviour
Error

### Configuration
**Operating System:** Debian 9

**Version of Python, python-telegram-bot & dependencies:** Python3.5

``$ python -m telegram``
python-telegram-bot 11.1.0
certifi 2019.03.09
future 0.17.1
Python 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]

### Logs
Insert logs here (if necessary)

2019-04-25 14:12:00,317 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "wikiRssBot.py", line 23, in start
    context.bot.send_message(chat_id=update.message.chat_id, text="CH")
AttributeError: 'Update' object has no attribute 'bot'

**Comment by jsmnbom** [comment]
![image](https://user-images.githubusercontent.com/3002987/56769691-3dca0480-67b2-11e9-80b6-1884d4d439ca.png)
