### ISSUE TITLE
PrefixHandler check_update error

### ISSUE THREAD

**Issue by Flowelcat** [python-telegram-bot/python-telegram-bot#1424]
### Steps to reproduce
1. Add at least one PrefixHandler to dispatcher.
2. Create inline markup:
`markup = InlineKeyboardMarkup([[InlineKeyboardButton(_("Test"), callback_data='test')]])`
3. Send photo with markup:
`context.bot.send_photo(chat_id=update.effective_user.chat_id, photo="http://example.com/photo_url.png", reply_markup=markup)`
4. Press inline button on that message.

### Expected behaviour
Processing callback query update.

### Actual behaviour
Exception in PrefixHandler.

### Configuration
**Operating System:** Ubuntu 18.04.2 LTS
**Version of Python, python-telegram-bot & dependencies:** 
``python -m telegram``
 python-telegram-bot 12.0.0b1
 certifi 2019.03.09
 future 0.17.1
 Python 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]

### Logs
2019-06-09,23:24:07 telegram.ext.dispatcher ERROR An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/flowelcat/PycharmProjects/agroport/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 329, in process_update
    check = handler.check_update(update)
  File "/home/flowelcat/PycharmProjects/agroport/.venv/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 335, in check_update
    text_list = message.text.split()
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Eldinnie** [comment]
Hi,

Thanks for the heads up. We already found this bug and fixed it in #1375 .
I'm closing this as already fixed.
