### ISSUE TITLE
Probelm with installing python-telegram-bot : "python setup.py egg_info"

### ISSUE THREAD

**Issue by ex3ploiter** [python-telegram-bot/python-telegram-bot#1444]
i wanna install "python-telegram-bot" 
so i use 

`  pip install python-telegram-bot
`
 in cmd , but i get this , and i already have Microsoft Visual C++ and my python is 3 and i use win10
i tried to install in directly but its failed and i don't know what am i have to do?

  ```
  C:\Users\SomeThing>pip install python-telegram-bot
    Collecting python-telegram-bot
      Using cached https://files.pythonhosted.org/packages/84/6c/47932a4041ee76650ad1f45a80e1422077e1e99c08a4d7a61cfbe5393d41/python_telegram_bot-11.1.0-py2.py3-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): certifi in c:\users\SomeThing\appdata\local\programs\python\python37\lib\site-packages (from python-telegram-bot)
    Collecting cryptography (from python-telegram-bot)
      Using cached https://files.pythonhosted.org/packages/c2/95/f43d02315f4ec074219c6e3124a87eba1d2d12196c2767fadfdc07a83884/cryptography-2.7.tar.gz
    Collecting future>=0.16.0 (from python-telegram-bot)
      Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
    Collecting asn1crypto>=0.21.0 (from cryptography->python-telegram-bot)
      Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in c:\users\SomeThing\appdata\local\programs\python\python37\lib\site-packages (from cryptography->python-telegram-bot)
    Collecting cffi!=1.11.3,>=1.8 (from cryptography->python-telegram-bot)
      Using cached https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
            return self.find_available_vc_vers()[-1]
        IndexError: list index out of range
    
        During handling of the above exception, another exception occurred:
    
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\Users\SomeThing\AppData\Local\Temp\pip-build-9me3gkos\cffi\setup.py", line 127, in <module>
            if sys.platform == 'win32' and uses_msvc():
          File "C:\Users\SomeThing\AppData\Local\Temp\pip-build-9me3gkos\cffi\setup.py", line 105, in uses_msvc
            return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\distutils\command\config.py", line 227, in try_compile
            self._compile(body, headers, include_dirs, lang)
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\distutils\command\config.py", line 133, in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\distutils\_msvccompiler.py", line 346, in compile
            self.initialize()
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\distutils\_msvccompiler.py", line 239, in initialize
            vc_env = _get_vc_env(plat_spec)
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
            return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\site-packages\setuptools\msvc.py", line 843, in __init__
            self.si = SystemInfo(self.ri, vc_ver)
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\site-packages\setuptools\msvc.py", line 485, in __init__
            self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
          File "c:\users\SomeThing\appdata\local\programs\python\python37\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
            raise distutils.errors.DistutilsPlatformError(err)
        distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\SomeThing\AppData\Local\Temp\pip-build-9me3gkos\cffi

```

**Comment by ex3ploiter** [comment]
at least i installed it as downloaded file

**Comment by Nukesor** [comment]
The Problem seems to be an outdated Visual C++ version (as can be seen in the error log)
`distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required`

Since you managed to resolve the issue on your own, I'll close the issue
