### ISSUE TITLE
the thread hangs and nothing happens

### ISSUE THREAD

**Issue by ogyrec** [python-telegram-bot/python-telegram-bot#1455]
I have a list of proxy addresses for which I want to connect the telegrams-bot. Proxies can be blocked over time or simply not work, this can be seen by the MaxRetryError error. But I can't catch an error. I have an error in logs. I want to catch an error and switch to another proxy server.

REQUEST_KWARGS = {
    'proxy_url': proxy_url,
    'urllib3_proxy_kwargs': {
        'retries': 0
    }
}
try:
    updater = Updater(token=TELEGRAM_TOKEN, request_kwargs=REQUEST_KWARGS)
    updater.start_polling(bootstrap_retries=0)
except Error:
   print('yep!')

### Expected behaviour
catch any exception 

### Actual behaviour
the thread hangs and nothing happens

### Configuration
Name: urllib3
Version: 1.23

Name: python-telegram-bot
Version: 11.1.0

python 3.7

### Logs
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot877422445:AAEGBD0D9stJKMF6PvCClChx8MNMGX-vLEY/deleteWebhook (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1102d7048>: Failed to establish a new connection: [Errno 61] Connection refused')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 156, in _thread_wrapper
    target(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 273, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 440, in _bootstrap
    'bootstrap del webhook', bootstrap_interval)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 333, in _network_loop_retry
    onerr_cb(te)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 432, in bootstrap_onerr_cb
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 319, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 410, in bootstrap_del_webhook
    self.bot.delete_webhook()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 2097, in delete_webhook
    result = self._request.post(url, data, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 209, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot877422445:AAEGBD0D9stJKMF6PvCClChx8MNMGX-vLEY/deleteWebhook (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1102d7048>: Failed to establish a new connection: [Errno 61] Connection refused')))

2019-07-26 17:32:23,917 - telegram.ext.dispatcher - CRITICAL - stopping due to exception in another thread

**Comment by tsnoam** [comment]
@ogyrec Hi,
Unfortunately, the Updater is not designed to replace proxy server &quot;on the fly&quot;. 
With the current implementation you would need to stop the entire Updater object and start a new one, which the best way to do it would be to start a new process.

**Comment by ogyrec** [comment]
thx bro!

**Comment by ogyrec** [comment]
There are no options that any error (in the case when we have blocked proxy) would be caught by 'except'?

**Comment by tsnoam** [comment]
@ogyrec Network Errors are handled by the Updater.
The behaviour is as follows:
If bootstrap process failed due to network error the Updater will bail out. 
Afterwards, any network error encountered will only be treated with retry.

Also, take to mind that there is no way for a software to know that the network error is not temporary but rather the proxy being blocked. Since we aim for the majority of the users, we assume that network will be restored eventually.
