### ISSUE TITLE
Can't use SOCKS5 proxy.

### ISSUE THREAD

**Issue by 404neko** [python-telegram-bot/python-telegram-bot#1515]
Traceback (most recent call last):
  File "Core.py", line 125, in <module>
    updater = Updater(TOKEN, request_kwargs=REQUEST_KWARGS)
  File "D:\Bin\Python\Python37\lib\site-packages\telegram\ext\updater.py", line 135, in __init__
    self._request = Request(**request_kwargs)
  File "D:\Bin\Python\Python37\lib\site-packages\telegram\utils\request.py", line 143, in __init__
    mgr = SOCKSProxyManager(proxy_url, **kwargs)
  File "D:\Bin\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\contrib\socks.py", line 160, in __init__
    "Unable to determine SOCKS version from %s" % proxy_url
ValueError: Unable to determine SOCKS version from socks5h://127.0.0.1:1082

I think the reason is python-telegram-bot use an old urllib3.
''Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\contrib\socks.py''

**Comment by tsnoam** [comment]
Please fill all information requested in the issue template and make sure you're working with latest version as I believe this was already solved.
