### ISSUE TITLE
Help with emoji on commandhandler

### ISSUE THREAD

**Issue by devianpctek** [python-telegram-bot/python-telegram-bot#1550]
Hello, I was using a different Python framework which is now deprecated and want to use this one so I can use some new functionalities that comes with Telegram API, but I'm stuck on this

`dp.add_handler(CommandHandler(emojize("yummy :cake:", use_aliases=True),start))`  

If I remove the emojize part, the program runs, but I want to have emojis as commands (I use this on the previous framework and worked fine)
Any ideas on what I'm doing wrong?
I get the following error 

> Traceback (most recent call last):
  File "spdlistener3.py", line 86, in <module>
    main()
  File "spdlistener3.py", line 80, in main
    dp.add_handler(CommandHandler(emojize("yummy :cake:", use_aliases=True),start))
  File "/home/devian/.local/lib/python3.7/site-packages/telegram/ext/commandhandler.py", line 141, in __init__
    raise ValueError('Command is not a valid bot command')
ValueError: Command is not a valid bot command

**Comment by jsmnbom** [comment]
Emojis are not recognized as valid commands by Telegram, so you shouldn't use a command handler. If you really want `/yummy 🍰` as a thing that users have to type to execute a command then use a RegexHandler.
For further questions we invite you to ask them in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Comment by Eldinnie** [comment]
@jsmnbom Prefixhandler would do here

**Comment by devianpctek** [comment]
See right now I have this bot that looks like this, but I want to use this framework, because the one I'm using right now is not maintained any more (telepot) but I can use emojis on my buttons without a problem
![Screenshot_20191014-120029](https://user-images.githubusercontent.com/1848859/66769312-705bdc80-ee7a-11e9-91d8-3b5c7a54e56f.jpg)

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
