### ISSUE TITLE
telegram.vendor.ptb_urllib3 Connection issue in China

### ISSUE THREAD

**Issue by naramiss** [python-telegram-bot/python-telegram-bot#1588]
Hello,

I have issues trying to connect with python to telegram API. I think that's because of the fact that I live in China. I don't know how to fix it, could someone help please ?

Here is the log when I run my program that just want to set functions for the telegram bot group chat that I created :

pi@raspberrypi:~/IoT_Project/test_telegram $ python3 test.py 
test.py:16: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater('TOKEN')
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
telegram.vendor.ptb_urllib3.urllib3.exceptions.ConnectTimeoutError: (<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x752dceb0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 218, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot<TOKEN>/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x752dceb0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 23, in <module>
    main()
  File "test.py", line 19, in main
    updater.start_polling()
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/ext/updater.py", line 213, in start_polling
    self.job_queue.start()
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/ext/jobqueue.py", line 291, in start
    name="Bot:{}:job_queue".format(self._dispatcher.bot.id))
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/bot.py", line 52, in decorator
    self.get_me()
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/bot.py", line 199, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 270, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 224, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot<TOKEN>/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x752dceb0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

**Comment by naramiss** [comment]
The code that I'm trying to run is this one :

from telegram.ext import Updater, InlineQueryHandler, CommandHandler
import requests
import re

def get_url():
    contents = requests.get('https://random.dog/woof.json').json()
    url = contents['url']
    return url

def bop(bot, update):
    url = get_url()
    chat_id = update.message.chat_id
    bot.send_photo(chat_id=chat_id, photo=url)

def main():
    updater = Updater('1066953395:AAGa6nBIYJjuWUYFCGF08hslZTQSI97SyF8')
    dp = updater.dispatcher
    dp.add_handler(CommandHandler('bop',bop))
    updater.start_polling()
    updater.idle()

if __name__ == '__main__':
    main()

**Comment by Bibo-Joshi** [comment]
> updater = Updater('1066953395:AAGa6nBIYJjuWUYFCGF08hslZTQSI97SyF8')

Please revoke the bot token you posted or else anyone might use your bot.

To adress your problem, a proxy might help. See [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy) and [here ](https://github.com/python-telegram-bot/python-telegram-bot/issues/525).
