### ISSUE TITLE
I can not Run the Bot 

### ISSUE THREAD

**Issue by iman-sedgh** [python-telegram-bot/python-telegram-bot#1608]
Hey 
I have Installed packages successfully but the problem is here that I can't able to run a simple code
here is my code 

>from telegram.ext import Updater, CommandHandler
token = 'My token'
updater = Updater(token)
def start_method(bot,update):
    bot.sendMessage(update.message.chat_id,'Hello')
start_command = CommandHandler('start',start_method)
updater.dispatcher.add_handler(start_command)
updater.start_polling()

and this is the error that I get when  run it 

Exception in thread updater:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
   

 self.run()

  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 149, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 266, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 433, in _bootstrap
    'bootstrap del webhook', bootstrap_interval)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 326, in _network_loop_retry
    onerr_cb(te)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 425, in bootstrap_onerr_cb
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 312, in _network_loop_retry
    if not action_cb():
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 403, in bootstrap_del_webhook
    self.bot.delete_webhook()
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 1888, in delete_webhook
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 278, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 213, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized

I tried other versions of the module and again no chance

**Comment by tsnoam** [comment]
Unauthorized exception means that your token is not authorized.

**Comment by iman-sedgh** [comment]
thanks for your reply but this is not the problem (if I get a wrong token I get another error)
same problem here -- > [https://github.com/python-telegram-bot/python-telegram-bot/issues/555#issuecomment-291505201](url)
I use virtual env and there isn't any different

**Comment by tsnoam** [comment]
The error is originated from telegram servers and it is what it is. ptb merely converts the error to an Exception.

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
