### ISSUE TITLE
[BUG] Error on persistence of nested conversation

### ISSUE THREAD

**Issue by ryanfwy** [python-telegram-bot/python-telegram-bot#1710]
### Issue I am facing
When I tried to persistence a nested conversation on [nestedconversationbot.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/nestedconversationbot.py), I got the following error message when I entered the sub-conversation, for example `Add Family Member`:
```
"'NoneType' object has no attribute 'update_conversation'"
```

I guess the sub-conversations will always get `None`, and they cause the issue while saving conversation states.

Is this a known issue? Or Is there a way to solve this problem?

### Traceback to the issue
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 343, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 357, in handle_update
    self.update_state(new_state, conversation_key)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 376, in update_state
    self.persistence.update_conversation(self.name, key, new_state)
AttributeError: 'NoneType' object has no attribute 'update_conversation'
```

### Related part of your code
I wrote my code just like this. Here, `description_conv` and `add_member_conv` are the sub-conversations of the top level `conv_handler`.

```python
# Set up third level ConversationHandler (collecting features)
description_conv = ConversationHandler(
    entry_points=[...]
    states={...},
    fallbacks=[...],
    map_to_parent={...},
    persistent=True,
    name='test',
)

# Set up second level ConversationHandler (adding a person)
add_member_conv = ConversationHandler(
    entry_points=[...]
    states={
        SELECTING_GENDER: [description_conv],
    },
    fallbacks=[...],
    map_to_parent={...},
    persistent=True,
    name='test2',
)

# Set up top level ConversationHandler (selecting action)
conv_handler = ConversationHandler(
    entry_points=[CommandHandler('start', start)],
    states={
        SELECTING_ACTION: [add_member_conv],
        DESCRIBING_SELF: [description_conv],
    },
    fallbacks=[...],
    persistent=True,
    name='test3',
)
```

**Comment by Bibo-Joshi** [comment]
Hi. To be honest, we didn't think of persistence issues when merging nested conversations. I'll look into it, but I fear that this won't be easy to fix.

**Comment by ryanfwy** [comment]
Thanks for your rapid response.
