### ISSUE TITLE
ConnectionResetError - An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#1773]
So I've been getting this error whenever I message the bot after ~20+ minutes. It is very similar to #711 but as it turns out, that issue was also not 'fixed' for everyone. On the 2nd update, everything is fixed and works normally for 20 mins and then the same issue happens again.

### Steps to reproduce
1. Run the script for the bot and don't send any message to it for 20+ minutes

2. Finally send a message to it. This exception will be raised.
The script provided in #711 is an example where this error can be raised.

### Expected behaviour
Bot is supposed to send reply normally without this error.

### Actual behaviour
ConnectionResetError exception is raised within urllib3.

### Configuration
**Operating System:**
Windows 10, 64 bit

**Version of Python, python-telegram-bot & dependencies:**
```
future 0.18.2  
certifi 2019.11.28  
tornado 6.0.3
cryptography 2.8
decorator 4.4.1
Python 3.8.1
python-telegram-bot 12.4.2
```
  

### Logs
```2020-02-11 11:55:40,700 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "D:\Python\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "D:\Python\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\Python\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Python\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\telegram\utils\request.py", line 218, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "D:\Python\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "D:\Python\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\Python\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Python\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "D:\Python\lib\site-packages\telegram\ext\conversationhandler.py", line 355, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "D:\Python\lib\site-packages\telegram\ext\handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "C:\Users\Uncle Sam\Desktop\sthyaVERAT\4 FUN ya Practice\Shani-Sir-Telegram-Bot\conversation.py", line 81, in cancel
    context.bot.send_message(chat_id=update.effective_chat.id,
  File "D:\Python\lib\site-packages\telegram\bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "D:\Python\lib\site-packages\telegram\bot.py", line 256, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "D:\Python\lib\site-packages\telegram\bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "D:\Python\lib\site-packages\telegram\utils\request.py", line 324, in post
    result = self._request_wrapper('POST', url,
  File "D:\Python\lib\site-packages\telegram\utils\request.py", line 224, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

### Temporary fix:

I fixed the issue by requesting to the server again. It required me adding a while loop in `telegram\utils\request.py` on line 224. Here's the code:
```
while True:
    try:
        resp = self._con_pool.request(*args, **kwargs)
        break
    except urllib3.exceptions.TimeoutError:
        raise TimedOut()
    except urllib3.exceptions.HTTPError as error:
        # HTTPError must come last as its the base urllib3 exception class
        # TODO: do something smart here; for now just raise NetworkError
        print(NetworkError('urllib3 HTTPError {0}'.format(error)))
``` 
Yes, I know this is not an elegant fix, but it fixes the problem for me. It prints the network error once and then on the 2nd iteration (requesting again), it works.

**Comment by Poolitzer** [comment]
@harshil21 Hey, have you already checked out our networking wiki page?

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors

**Comment by harshil21** [comment]
> @harshil21 Hey, have you already checked out our networking wiki page?
> 
> https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors

Yea I've tried increasing conn_pool_size to 2 and connect_timeout to 10. I've also tried using a proxy (since telegram calls in my country are blocked), but none of them have worked. The workaround above was the one which actually worked 100% of the time.

**Comment by tsnoam** [comment]
Hi, as you've shared yourself, you're hosting the bot on a server with problematic network connectivity (towards telegram servers).
If the nature network programming requires your software to be resilient to various errors, in this case the errors would be more frequent and severe.
I suggest you try an hosting service with better network connectivity.
