### ISSUE TITLE
[QUESTION] How do I get the chat ID from the incoming message

### ISSUE THREAD

**Issue by stanleybridge** [python-telegram-bot/python-telegram-bot#1814]
### Issue I am facing
Hi there,

My bot responds to messages either direct or from a particular group chat.  I collect the chat.id to then use when sending the response back to the appropriate individual or group chat.  

When my chatbot runs, my main webhook function reports the following error:
**AttributeError: 'NoneType' object has no attribute 'chat'**

This is occurring when I try to retrieve the incoming message's chat.id using:
**chat_id = update.message.chat.id**

Complete log and code below.  Any thoughts on what I am doing wrong?  :)

Cheers
SB

### Traceback to the issue
```
{
 insertId: "000000-e9d0e2cd-c65a-43c4-b79f-3987b04784ce"  
 labels: {…}  
 logName: "myprojectname/logs/myfunctions"  
 receiveTimestamp: "2020-03-01T10:27:57.341846016Z"  
 resource: {…}  
 severity: "ERROR"  
 textPayload: "Traceback (most recent call last):
  File "/env/local/lib/python3.7/site-packages/functions/worker.py", line 346, in run_http_function
    result = _function_handler.invoke_user_function(flask.request)
  File "/env/local/lib/python3.7/site-packages/functions/worker.py", line 217, in invoke_user_function
    return call_user_function(request_or_event)
  File "/env/local/lib/python3.7/site-packages/functions/worker.py", line 210, in call_user_function
    return self._user_function(request_or_event)
  File "/user_code/main.py", line 24, in webhook
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
"  
 timestamp: "2020-03-01T10:27:56.279Z"  
 trace: "projects/myprojectname/traces/495685fcb07e5c0255d29591ce2458a8"  
}
```

### Related part of your code
```python
#######################################################################
# MAIN WEBHOOK FUNCTION
def webhook(request):
    if request.method == "POST":
        # grab the update(s)
        update = telegram.Update.de_json(request.get_json(force=True), settings.bot)
        
        # collect incoming message stuff
        chat_id = update.message.chat.id
        incoming_text = str(update.message.text)
        incoming_entities = update.message.entities
        message_sender = str(update.message.from_user.first_name)

        # process message
        outgoing_text = message_processor.process_message(message_sender, incoming_text, incoming_entities)

        # Reply to message (if something to send)
        if outgoing_text:
            if outgoing_text.startswith( 'SENDIMAGE:' ):
                photo_url = outgoing_text.split("SENDIMAGE:")[1].split("|")[0]
                caption_text = outgoing_text.split("|CAPTION:",1)[1] 
                settings.bot.sendPhoto(chat_id=chat_id, photo=photo_url)
            elif outgoing_text.startswith( 'SENDSTICKER:' ):
                sticker_file_id = outgoing_text.split("SENDSTICKER:",1)[1] 
                settings.bot.sendSticker(chat_id=chat_id, sticker=sticker_file_id)
            else:
                settings.bot.sendMessage(chat_id=chat_id, text=outgoing_text)
    return "ok"
```

**Comment by Poolitzer** [comment]
@stanleybridge Yes, you are facing an update where . message doesn&#x27;t exists. This could be a channel post, an edited message or an edited channel post, from the top of my head. Or a poll. Or a media &quot;message&quot;.

We provide a convenience attribute called .effective_message for this, and also . effective_chat, where you get the chat_id even when its a non message update. Check out <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.update.html#telegram.Update">the documentation</a> for more.
