### ISSUE TITLE
[QUESTION] ERROR - unhandled exception

### ISSUE THREAD

**Issue by AyraHikari** [python-telegram-bot/python-telegram-bot#1832]
### Steps to reproduce
1. clone my WIP bot source
`https://github.com/AyraHikari/EmiliaHikari/tree/emiliabeta`
2. Run it with 
`pipenv run python3 -m emilia`
3. After it running, then i got traceback
```
2020-03-15 22:32:49,413 - telegram.ext.updater - ERROR - unhandled exception in Bot:490508539:dispatcher
Traceback (most recent call last):
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/updater.py", line 214, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 263, in start
    self._init_async_threads(uuid4(), self.workers)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 179, in _init_async_threads
    thread.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Bot:490508539:dispatcher:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/updater.py", line 214, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 263, in start
    self._init_async_threads(uuid4(), self.workers)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 179, in _init_async_threads
    thread.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
4. Then trying to abort with ctrl + c, again got traceback error
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ayra/emiliabeta/emilia/__main__.py", line 518, in <module>
    main()
  File "/home/ayra/emiliabeta/emilia/__main__.py", line 461, in wrapper
    function(*args, **kwargs)
  File "/home/ayra/emiliabeta/emilia/__main__.py", line 512, in main
    updater.start_polling(timeout=15, read_latency=4)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/updater.py", line 264, in start_polling
    dispatcher_ready.wait()
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

### Expected behaviour
It should run correctly, but the threading is got an error.
I think it not my source problem, sometimes it got works, and sometimes got this traceback.

### Actual behaviour
See logcat above

### Configuration
**Operating System:**
Linux Ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**
```
future (0.18.2)
emoji (0.5.4)
requests (2.22.0)
sqlalchemy (1.3.11)
python-telegram-bot (12.4.2)
psycopg2-binary (2.8.4)
feedparser (5.2.1)
pyowm (2.10.0)
googletrans (2.4.0)
wikipedia (1.4.0)
kbbi (0.3.2)
Pillow (6.2.1)
alphabet_detector (0.0.7)
urbandict (0.6.1)
urllib3 (1.25.7)
idna (2.8)
certifi (2019.11.28)
chardet<3.1.0, (3.0.4)
cryptography (2.8)
tornado (6.0.3)
decorator (4.4.2)
geojson (2.5.0)
beautifulsoup4 (4.8.1)
six (1.13.0)
cffi (1.13.2)
soupsieve (1.9.5)
pycparser (2.19)
```

``$ python -m emilia``

### Logs
Full logs
```
ayra@ayrahikari:~/emiliabeta$ pipenv run python3.6 -m emilia
2020-03-15 22:32:40,676 - emilia - INFO - Not loading: ['translation', 'sed', 'rss', 'antiflood', 'blstickers', 'locks', 'log_channel', 'misc', 'msg_deleting', 'reporting', 'rules', 'security', 'special', 'userinfo', 'users', 'welcome']
2020-03-15 22:32:40,676 - emilia - INFO - Modules to load: ['admin', 'afk', 'backups', 'bans', 'blacklist', 'cleaner', 'connection', 'cust_filters', 'devs', 'disable', 'feds', 'global_bans', 'languages', 'muting', 'notes', 'warns', 'weather']
2020-03-15 22:32:44,683 - emilia - INFO - 2 languages loaded: ['en', 'id']
/home/ayra/emiliabeta/emilia/modules/notes.py:547: TelegramDeprecationWarning: RegexHandler is deprecated. See https://git.io/fxJuV for more info
  HASH_GET_HANDLER = RegexHandler(r"^#[^\s]+", hash_get)
/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: message_updates is deprecated. See https://git.io/fxJuV for more info
  edited_updates=edited_updates)
/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: channel_post_updates is deprecated. See https://git.io/fxJuV for more info
  edited_updates=edited_updates)
/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: edited_updates is deprecated. See https://git.io/fxJuV for more info
  edited_updates=edited_updates)
2020-03-15 22:32:49,403 - emilia - INFO - Successfully loaded modules: ['admin', 'afk', 'backups', 'bans', 'blacklist', 'cleaner', 'connection', 'cust_filters', 'devs', 'disable', 'feds', 'global_bans', 'languages', 'muting', 'notes', 'warns', 'weather']
2020-03-15 22:32:49,410 - emilia - INFO - Using long polling.
2020-03-15 22:32:49,413 - telegram.ext.updater - ERROR - unhandled exception in Bot:490508539:dispatcher
Traceback (most recent call last):
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/updater.py", line 214, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 263, in start
    self._init_async_threads(uuid4(), self.workers)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 179, in _init_async_threads
    thread.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Bot:490508539:dispatcher:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/updater.py", line 214, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 263, in start
    self._init_async_threads(uuid4(), self.workers)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 179, in _init_async_threads
    thread.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

^CTraceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ayra/emiliabeta/emilia/__main__.py", line 518, in <module>
    main()
  File "/home/ayra/emiliabeta/emilia/__main__.py", line 461, in wrapper
    function(*args, **kwargs)
  File "/home/ayra/emiliabeta/emilia/__main__.py", line 512, in main
    updater.start_polling(timeout=15, read_latency=4)
  File "/home/ayra/.local/share/virtualenvs/emiliabeta-Cu6hs_2i/lib/python3.6/site-packages/telegram/ext/updater.py", line 264, in start_polling
    dispatcher_ready.wait()
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by Bibo-Joshi** [comment]
Hi. Please try to provide a minimal working example that reproduces the error. Combing through your code to find an error is beyond the scope of an issue.

**Comment by AyraHikari** [comment]
Okay, it seems not this source error, actually i have some bots running background with python-telegram-bot.
So when i using too much workers it will give that error, to make it do error, i am using 8 workers at this current bot (sometimes 8 workers doesn't give that error, and 16 instead).
I forgot how many workers at my others bot, but my bot not only using python-telegram-bot, some bots using flask as webhook, pyrogram with mtproto, and etc.

This code actually give me error
```
WORKERS = 8
updater = tg.Updater(TOKEN, workers=WORKERS, use_context=True)
```
and to make it works, i was set `WORKERS` to `4` instead of `8` because worker limit.

I don't running stopping others bot, maybe others bot trying to running threading and then this current bot trying running 8 workers, then python/os was refused to running more workers
