### ISSUE TITLE
[BUG] Issues with encoding on Python 2.7

### ISSUE THREAD

**Issue by CTassisF** [python-telegram-bot/python-telegram-bot#1899]
Looks like the latest version of `python-telegram-bot` (`12.6.1`) is causing issues with encoding on Python 2.7.

It seems to be related to some `’` characters being used in the documentation instead of `'` when referring to "bot's".

Here's an example of the issue on lines 40 and 43: https://github.com/python-telegram-bot/python-telegram-bot/blob/314f87ec44845c602d484eeeb2de20297f32ebec/telegram/inline/inlinekeyboardbutton.py#L40-L43

And here's the issue I'm getting:

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/96042b99a0720f74/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/96042b99a0720f74/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/96042b99a0720f74/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/.../telegram-bot.py", line 24, in <module>
    from telegram import Bot
  File "/base/data/home/apps/.../libraries/telegram/__init__.py", line 66, in <module>
    from .inline.inlinekeyboardbutton import InlineKeyboardButton
  File "/base/data/home/apps/.../libraries/telegram/inline/inlinekeyboardbutton.py", line 40
SyntaxError: Non-ASCII character '\xe2' in file /base/data/home/apps/.../libraries/telegram/inline/inlinekeyboardbutton.py on line 41, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Maybe there are other files affected too, I didn't test all of them but it seems to be fairly easy to do so: https://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file

Can you please fix this issue so this library can still run on Python 2.7?

Thanks.

**Comment by tsnoam** [comment]
Hi @CTassisF 

Starting 2020, ptb do not support python2.7 any more.
