### ISSUE TITLE
[QUESTION] JobQueue problem

### ISSUE THREAD

**Issue by Beppe1988** [python-telegram-bot/python-telegram-bot#1939]
### Steps to reproduce
```python
Class TgramBot(object):

    def __init__:

        self.updater = Updater(token, use_context=True)

        self.dp = self.updater.dispatcher

        self.jobs = self.dp.job_queue

 

    def parallelfunc(self, update, context, att1, att2):

        job = context.job

       

        #My function datas...

 

        if job.interval <= 1800:

            job.interval += 60

        if job.interval > 1800:

            job.interval += 120

        if job.interval == 3600:

            job.schedule_removal()

 

    #...Conversation Handler States...

 

    def state1(self, update, context):

        #some stuff...

        self.jobs.run_repeating(self.parallelfunc(update, context, att1, att2), 60, context=update.chat_id)
```
(Above code is a sample)

### Expected behaviour
This class will create a telegram Bot. While 
an user wait that job ending, another user can start the bot.

### Actual behaviour
It return this error:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 343, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/user/.local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/user/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/home/user/tegram_bot.py", line 23, in state1
    self.jobs.run_repeating(self.parallelfunc(update, context, att1, att2), 60, context=update.chat_id)
  File "/home/user/tegram_bot.py", line 12, in parallelfunc
    if job.interval <= 1800.0:
AttributeError: 'NoneType' object has no attribute 'interval'
```

### Configuration
**Operating System:**
Debian 10

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 12.7
certifi 2019.11.28
future 0.17.1
Python 3.7.7 (default, Apr  1 2020, 13:48:52)  [GCC 9.3.0]

### Logs
Insert logs here (if necessary)
```python
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 343, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/user/.local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/user/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/home/user/tegram_bot.py", line 23, in state1
    self.jobs.run_repeating(self.parallelfunc(update, context, att1, att2), 60, context=update.chat_id)
  File "/home/user/tegram_bot.py", line 12, in parallelfunc
    if job.interval <= 1800.0:
AttributeError: 'NoneType' object has no attribute 'interval'
```

**Comment by Eldinnie** [comment]
@Beppe1988 Please don&#x27;t use the bug template for a usage question

**Comment by Beppe1988** [comment]
Sorry

**Comment by Bibo-Joshi** [comment]
Callbacks of jobs only take `context` as argument, as stated in the documentation. For the `run_*` methods, you need to pass the function itself, not its return value, (i.e. `self.parallelfunc` instead of `self.parallelfunc(...)` in your case.)
