### ISSUE TITLE
pythonanywhere problem

### ISSUE THREAD

**Issue by kazemihabib** [python-telegram-bot/python-telegram-bot#194]
I got this error when I tested with [pythonanywhere] (https://www.pythonanywhere.com)
python3.4

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    from telegram import Updater
  File "/home/kazemihabib/.local/lib/python3.4/site-packages/telegram/__init__.py", line 43, in <module>
    from .emoji import Emoji
  File "/home/kazemihabib/.local/lib/python3.4/site-packages/telegram/emoji.py", line 27, in <module>
    class Emoji(object):
  File "/home/kazemihabib/.local/lib/python3.4/site-packages/telegram/emoji.py", line 30, in Emoji
    GRINNING_FACE_WITH_SMILING_EYES = n(b'\xF0\x9F\x98\x81')
  File "/usr/local/lib/python3.4/dist-packages/future/utils/__init__.py", line 175, in bytes_to_native_str
    return b.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)
```

**Comment by jh0ker** [comment]
I can't reproduce this error locally with my Python 3.4 installation. I think you should open an issue with the [python-future](https://github.com/PythonCharmers/python-future/) project, because the function we are using is from that package.

**Comment by gpjt** [comment]
PythonAnywhere dev here: it looks like the problem is that we have an old version of the `future` module installed by default, which is trying to decode the bytes as ASCII.  Run this on a bash console to fix (adjusting the Python version after the `pip` as appropriate):

    pip3.4 install  --user --upgrade future
