### ISSUE TITLE
[QUESTION] experiencing multiple timeouts. No clue why.

### ISSUE THREAD

**Issue by Javain** [python-telegram-bot/python-telegram-bot#1947]
### Issue I am facing
I don't really know what's happening. It seems it all happens when I try to send a message. Any ideas on what should I do about this?

### Traceback to the issue
```
Exception in thread Thread-2:
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
httplib_response = conn.getresponse()
File "/app/.heroku/python/lib/python3.7/http/client.py", line 1344, in getresponse
response.begin()
File "/app/.heroku/python/lib/python3.7/http/client.py", line 306, in begin
version, status, reason = self._read_status()
File "/app/.heroku/python/lib/python3.7/http/client.py", line 267, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto
return self._sock.recv_into(b)
File "/app/.heroku/python/lib/python3.7/ssl.py", line 1071, in recv_into
return self.read(nbytes, buffer)
File "/app/.heroku/python/lib/python3.7/ssl.py", line 929, in read
return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 225, in _request_wrapper
resp = self._con_pool.request(*args, **kwargs)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
**urlopen_kw)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
return self.urlopen(method, url, **extra_kw)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
response = conn.urlopen(method, u.request_uri, **kw)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
_stacktrace=sys.exc_info()[2])
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
raise value
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
chunked=chunked)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
exc_cls=ReadTimeoutError)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/app/.heroku/python/lib/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/app/commands.py", line 549, in execute
self.run(update, context)
File "/app/commands.py", line 461, in run
self.__procesar_mail(update, context, usuario.id, lengua)
File "/app/commands.py", line 468, in __procesar_mail
self.__procesar_permisos(update, context, mail, usuario, lengua)
File "/app/commands.py", line 479, in __procesar_permisos
self.__procesar_correos(update, context, mail, lengua, gm_api)
File "/app/commands.py", line 508, in __procesar_correos
self._send_message(update, msg=str(correo))
File "/app/commands.py", line 567, in _send_message
super(Check, self)._send_message(update, **args)
File "/app/commands.py", line 138, in _send_message
self.bot.send_message(**args)
File "<decorator-gen-2>", line 2, in send_message
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
result = func(*args, **kwargs)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 310, in send_message
timeout=timeout, **kwargs)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 172, in _message
result = self._request.post(url, data, timeout=timeout)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 334, in post
**urlopen_kwargs)
File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 227, in _request_wrapper
raise TimedOut()
telegram.error.TimedOut: Timed out
```

### Related part of your code
```python
```

**Comment by Bibo-Joshi** [comment]
Hi. Unfortunately timeouts can always happen when doing networkink stuff. Please see our [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors) about it.
