### ISSUE TITLE
Where does util package come from?

### ISSUE THREAD

**Issue by zubovskiii98** [python-telegram-bot/python-telegram-bot#1961]
### Issue I am facing
I wanted to implement a key menu following the tutorial. Unfortunately, I got following error about not knowing, where does `util` package come from.

### Traceback to the issue
```
Traceback (most recent call last):
  File "/home/ivan/anaconda3/envs/database/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 343, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/ivan/anaconda3/envs/database/lib/python3.7/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "telegram-bot.py", line 93, in receive
    reply_markup = gram.InlineKeyboardMarkup(util.build_menu(button_list, n_cols=n_cols))
NameError: name 'util' is not defined

```

### Related part of your code
```python
import telegram as gram

def send(update, context):

	button_list = [
		gram.InlineKeyboardButton("col1", callback_data='/start'),
		gram.InlineKeyboardButton("col2", callback_data='/stats'),
		gram.InlineKeyboardButton("row 2", callback_data='gg')
	]
	reply_markup = gram.InlineKeyboardMarkup(util.build_menu(button_list, n_cols=n_cols))
	bot.send_message('yahoo', "A two-column menu", reply_markup=reply_markup, text='New menu')

	return receive

def build_menu(buttons,
               n_cols,	
               header_buttons=None,
               footer_buttons=None):
	menu = [buttons[i:i + n_cols] for i in range(0, len(buttons), n_cols)]
	if header_buttons:
		menu.insert(0, [header_buttons])
	if footer_buttons:
		menu.append([footer_buttons])
	return menu
```

**Comment by Bibo-Joshi** [comment]
The snippet from the wiki assumes that you put `build_menu` in a python file/package called `util`. As in your case it's in the same file, you can just call `build_menu`.

**Comment by zubovskiii98** [comment]
Thank you for a quick solution
