### ISSUE TITLE
[BUG] Webhook NotImplementedError on windows with python 3.8

### ISSUE THREAD

**Issue by n5y** [python-telegram-bot/python-telegram-bot#1977]
### Steps to reproduce
```
from telegram.ext import Updater
updater = Updater(TOKEN, use_context=True)
updater.start_webhook()
updater.idle()
```

### Expected behaviour
No console output

### Actual behaviour
An exception is logged
```
Exception in thread Bot:377489430:updater:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\.virtualenvs\sandbox38\lib\site-packages\telegram\ext\updater.py", line 216, in _thread_wrapper
    target(*args, **kwargs)
  File "C:\Users\User\.virtualenvs\sandbox38\lib\site-packages\telegram\ext\updater.py", line 452, in _start_webhook
    self.httpd.serve_forever()
  File "C:\Users\User\.virtualenvs\sandbox38\lib\site-packages\telegram\utils\webhookhandler.py", line 52, in serve_forever
    self.http_server.listen(self.port, address=self.listen)
  File "C:\Users\User\.virtualenvs\sandbox38\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\User\.virtualenvs\sandbox38\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\User\.virtualenvs\sandbox38\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\User\.virtualenvs\sandbox38\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```
The process continues to run, trying to interrupt it results in a different exception being logged.

### Configuration
**Operating System:** Windows 10

**Version of Python, python-telegram-bot & dependencies:** 
```python-telegram-bot 12.7
certifi 2020.04.05.1
future 0.18.2
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
```

### See also
https://github.com/tornadoweb/tornado/issues/2608
https://bugs.python.org/issue37373

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for filing the issue. I haven't looked into the details yet, but I see that I referenced the tornado issue in #1614, where a workaround was added. Can you confirm that the issue persists with ptb>=12.5 (#1614 was released in 12.5)?

**Comment by n5y** [comment]
Sorry, i somehow missed the ptb version in that last block. 
```
python-telegram-bot 12.6.1
certifi 2019.11.28
future 0.18.2
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
```

**Comment by n5y** [comment]
The reason the workaround doesn't work is because it changes event loop policy after an event loop was already created. So one way to fix this is to apply it earlier. 

Event loop policy is a global setting, changing it can break user code, and must be done as soon as possible (if at all). A library generally shouldn't change it. If we must change event loop policy, the change should not be hidden form the user. I believe it would be appropriate to set event loop policy in `start_webhook` and document this in its docstring.


Alternative solution is to create a selector event loop instance specifically for tornado without changing the global event loop policy. ```asyncio.set_event_loop(asyncio.SelectorEventLoop())``` This partially sidesteps the usual event loop policy execution, and therefore might have non obvious implication in non obvious scenarios, but the system + python version + event loop policy check used in original workaround should make this very safe.

**Comment by amin-da75** [comment]
i got the same problem and used 
`import asyncio
asyncio.set_event_loop(asyncio.SelectorEventLoop())` to solved it.
