### ISSUE TITLE
[BUG] Problem with sendDocument

### ISSUE THREAD

**Issue by lorenzo-gabrielli** [python-telegram-bot/python-telegram-bot#1998]
I updated the last version of python - telegram - bot and the following code stop works.

I run a procedure that generates results in an HTML file, then I return this file to the sender.
Can you help me to understand why it does not work? Before updating the library the code works perfectly.

```python
 def tracy(update,context):
    update.message.reply_text('updating  ...')
    %run code.ipynb
    bot=context.bot
    bot.sendDocument(chat_id=update.message.chat_id,document=open('./plots/results.html', 'rb'))
```

**Comment by Bibo-Joshi** [comment]
Hi. Please fill out the _entire_ issue template. It's there for a reason. Please make sure to include error tracebacks.

**Comment by lorenzo-gabrielli** [comment]
Dear,

Please see below the error.
I would like to report that if I send a .csv file I don't have errors. 
In the new version, there are a restrictions for sending HTML file ? 
My file contains a picture generated with plotly.

Best,

Lorenzo


2020-06-15 12:41:23,620 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1055, in _send_output
    self.send(chunk)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 977, in send
    self.sock.sendall(data)
  File "C:\Users\Lorenzo\Anaconda3\lib\ssl.py", line 1015, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Lorenzo\Anaconda3\lib\ssl.py", line 984, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\utils\request.py", line 225, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 70, in request
    **urlopen_kw)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 1055, in _send_output
    self.send(chunk)
  File "C:\Users\Lorenzo\Anaconda3\lib\http\client.py", line 977, in send
    self.sock.sendall(data)
  File "C:\Users\Lorenzo\Anaconda3\lib\ssl.py", line 1015, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Lorenzo\Anaconda3\lib\ssl.py", line 984, in send
    return self._sslobj.write(data)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\utils\promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "<ipython-input-1-461880b77384>", line 141, in tracy
    bot.sendDocument(chat_id=update.message.chat_id,document=open('./plots/analisi_ciclica.html', 'rb'))
  File "<C:\Users\Lorenzo\Anaconda3\lib\site-packages\decorator.py:decorator-gen-133>", line 2, in send_document
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\bot.py", line 70, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\bot.py", line 674, in send_document
    **kwargs)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\bot.py", line 178, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\utils\request.py", line 329, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\telegram\utils\request.py", line 231, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out'))

**Comment by Bibo-Joshi** [comment]
Hi. As you can see from the logs, e.g. the last line

> `telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out'))`

you're simply having timeout errors. You might be able to overcome them by specifying a larger value for the `timeout` parameter of `send_document`. Please also see our wiki page on handling network errors.

As this is no bug with PTB, I'll be closing the issue.
