### ISSUE TITLE
[QUESTION] "Connection reset by peer" after 30 seconds when uploading videos

### ISSUE THREAD

**Issue by casidiablo** [python-telegram-bot/python-telegram-bot#2069]
### Steps to reproduce
1. Upload a video using something like

```python
def test(update, context):
    chat_id = update.message.chat_id
    file_path = '/tmp/video.mp4'

    with open(file_path, 'rb') as f:
        logging.info('Uploading video to Telegram...')
        context.bot.send_video(chat_id, video=f, timeout=1200)
```

The video I'm trying to send is rather small (around ~50mb) and my connection is strong. And notice how I'm using a timeout of 1200 seconds.

### Expected behaviour

Video should be sent without issues

### Actual behaviour

It seems like it usually crashes after 30 seconds (see diff between the first two log lines);

```
2020-08-25 22:27:41,948 - root - INFO - Uploading video to Telegram...
2020-08-25 22:28:12,111 - root - ERROR - Traceback (most recent call last):
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1272, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1318, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1267, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 998, in send
    self.sock.sendall(data)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/utils/request.py", line 224, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1272, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1318, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1267, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/http/client.py", line 998, in send
    self.sock.sendall(data)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/nix/store/ygb3y8kz35xshsv99w4srps6yg5jfy8j-python3-3.6.11/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 101, in test
    context.bot.send_video(chat_id, video=f, timeout=1200)
  File "</home/cristian/.python3-env/lib/python3.6/site-packages/decorator.py:decorator-gen-9>", line 2, in send_video
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/bot.py", line 824, in send_video
    **kwargs)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/utils/request.py", line 328, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/cristian/.python3-env/lib/python3.6/site-packages/telegram/utils/request.py", line 230, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

### Configuration
**Operating System:** Linux
**Version of Python, python-telegram-bot & dependencies:** 

``` bash
$ python -m telegram

python-telegram-bot 12.8
certifi 2019.09.11
Python 3.6.11 (default, Jun 27 2020, 10:02:24)  [GCC 9.3.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. I can't reproduce the issue with ~40MB files. Please double check that your file as actually fits into the upload limit of 50MB for bots. Please also have a look at the [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors) about handling network errors.

**Comment by casidiablo** [comment]
Oh, shoot. That must be it. The file is 54mb. I didn't know bots had such a small file limit. I assumed the limit was more than a gb.

It is unfortunate that the error that surfaces mentions nothing about the file size.

**Comment by Bibo-Joshi** [comment]
Most times, TG will send a corresponding error message. Anyway, I'll go ahead an close :)
