### ISSUE TITLE
[QUESTION] 'Bot' object has no attribute 'effective_chat'

### ISSUE THREAD

**Issue by KaratekHD** [python-telegram-bot/python-telegram-bot#2100]
### Issue I am facing
I am currently porting over my bot from PTB 11.1.0 to PTB 12.8. I need to get whether a chat is a group or a private chat, but I just can't get it to work. I used 'update.effective_chat.type' before, but that gives me an error. Thanks for your help!

### Traceback to the issue
```
Traceback (most recent call last):
  File "/home/jens/Development/NemesisPY/venv/lib64/python3.8/site-packages/telegram/utils/promise.py", line 56, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/jens/Development/NemesisPY/tg_bot/__main__.py", line 116, in start
    if update.effective_chat.type == "private":
AttributeError: 'Bot' object has no attribute 'effective_chat'
```

### Related part of your code
```python
@run_async
def start(update: Update, context: CallbackContext):
    if update.effective_chat.type == "private":
        args = context.args
        if len(args) >= 1:
            if args[0].lower() == "help":
                HELP_STRINGS = get_string("main", "HELP_STRINGS", lang.get_lang(update.effective_chat.id))
                send_help(update.effective_chat.id, HELP_STRINGS)

            elif args[0].lower().startswith("stngs_"):
                match = re.match("stngs_(.*)", args[0].lower())
                chat = dispatcher.bot.getChat(match.group(1))

                if is_user_admin(chat, update.effective_user.id):
                    send_settings(match.group(1), update.effective_user.id, False)
                else:
                    send_settings(match.group(1), update.effective_user.id, True)

            elif args[0][1:].isdigit() and "rules" in IMPORTED:
                IMPORTED["rules"].send_rules(update, args[0], from_pm=True)

        else:
            first_name = update.effective_user.first_name
            update.effective_message.reply_text(
                get_string("main", "PM_START_TEXT", lang.get_lang(update.effective_chat.id)).format(escape_markdown(first_name), escape_markdown(bot.first_name), OWNER_ID),
                parse_mode=ParseMode.MARKDOWN)
    else:
        update.effective_message.reply_text(get_string("main", "START_IN_GROUP", lang.get_lang(update.effective_chat.id))) # START_IN_GROUP
```

**Comment by Bibo-Joshi** [comment]
Hi. You need to pass `use_context=True` to your Updater/Dispatcher. Please follow the [transition guide](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0) and also read the release notes for the versions 12.1-12.8.

**Comment by KaratekHD** [comment]
Thank you for your reply!
But I already have that:
```python
updater = tg.Updater(TOKEN, workers=WORKERS, use_context=True)
dispatcher = updater.dispatcher
```

**Comment by Bibo-Joshi** [comment]
Then please provide a minimal working example (with emphasis on *minimal* ;) ) See [here](https://telegra.ph/Minimal-Working-Example-for-PTB-07-18).

**Comment by KaratekHD** [comment]
I am trying, but strangely, my testfile works just fine...

**Comment by KaratekHD** [comment]
Alright, here we go:
```python
import telegram.ext as tg
from telegram import Update, TelegramError
from telegram.ext import run_async, CallbackContext, CommandHandler, DispatcherHandlerStop, Dispatcher


def process_update(self, update):

    for group in self.groups:
        try:
            for handler in (x for x in self.handlers[group] if x.check_update(update)):
                # I think this line is the problem:
                handler.handle_update(update, self, handler.check_update(update))
                break

        # Stop processing with any other handler.
        except DispatcherHandlerStop:
            self.logger.debug("Stopping further handlers due to DispatcherHandlerStop")
            break

        # Dispatch any error.
        except TelegramError as te:
            self.logger.warning("A TelegramError was raised while processing the Update")

            try:
                self.dispatch_error(update, te)
            except DispatcherHandlerStop:
                self.logger.debug("Error handler stopped further handlers")
                break
            except Exception:
                self.logger.exception("An uncaught error was raised while handling the error")

        # Errors should not stop the thread.
        except Exception:
            self.logger.exception("An uncaught error was raised while processing the update")

@run_async
def start(update: Update, context: CallbackContext):
    if update.effective_chat.type == "private":
        args = context.args
        first_name = update.effective_user.first_name
        update.effective_message.reply_text("Hello " + first_name)
    else:
        update.effective_message.reply_text("You started this bot in a group.")  # START_IN_GROUP



if __name__ == '__main__':
    TOKEN = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    WORKERS=8
    updater = tg.Updater(TOKEN, workers=WORKERS, use_context=True)
    dispatcher = updater.dispatcher
    start_handler = CommandHandler("start", start)
    dispatcher.add_handler(start_handler)
    Dispatcher.process_update = process_update
    updater.start_polling(timeout=15, read_latency=4)
    updater.idle()

```
https://gist.github.com/KaratekHD/7b4fa76d6d79ecd4ffbb60e891fd6d73

After a little experimentation, I figured out that my custom process_update appears to cause the problem, but I can't figure out why.

**Comment by Bibo-Joshi** [comment]
Check the current implementation of `process_update` and you'll see why that is ;) Also, I don't see why you would need a custom `process_update`. Your implementation does nothing, the dispatcher wouldn't do on it's own. Maybe that was different in v11.1.0, but I would recommend to just use the current versions dispatcher as-is.

**Comment by KaratekHD** [comment]
Alright, thank you!

**Comment by KaratekHD** [comment]
Alright, thank you!
That is not the complete function, normally it looks like this:

```python
def process_update(self, update):
    # An error happened while polling
    if isinstance(update, TelegramError):
        try:
            self.dispatch_error(None, update)
        except Exception:
            self.logger.exception(get_string("main", "ERR_UNKNOWN", DEFAULT_LANG)) # ERR_UNKNOWN
        return

    now = datetime.datetime.utcnow()

    cnt = CHATS_CNT.get(update.effective_chat.id, 0)

    t = CHATS_TIME.get(update.effective_chat.id, datetime.datetime(1970, 1, 1))
    if t and now > t + datetime.timedelta(0, 1):
        CHATS_TIME[update.effective_chat.id] = now
        cnt = 0
    else:
        cnt += 1

    if cnt > 10:
        return

    CHATS_CNT[update.effective_chat.id] = cnt


    for group in self.groups:
        try:
            for handler in (x for x in self.handlers[group] if x.check_update(update)):
                handler.handle_update(update, self, handler.check_update(update))
                break

        # Stop processing with any other handler.
        except DispatcherHandlerStop:
            self.logger.debug(get_string("main", "ERR_DISPATCHERHANDLERSTOP", DEFAULT_LANG)) # ERR_DISPATCHERHANDLERSTOP
            break

        # Dispatch any error.
        except TelegramError as te:
            self.logger.warning(get_string("main", "ERR_TELEGRAM", DEFAULT_LANG)) # ERR_TELEGRAM

            try:
                self.dispatch_error(update, te)
            except DispatcherHandlerStop:
                self.logger.debug(get_string("main", "ERR_ERRHANDLER", DEFAULT_LANG)) # ERR_ERRHANDLER
                break
            except Exception:
                self.logger.exception(get_string("main", "ERR_UNKNOWN", DEFAULT_LANG)) # ERR_UNKNOWN

        # Errors should not stop the thread.
        except Exception:
            self.logger.exception(get_string("main", "ERR_UPDATE_UNKNOWN", DEFAULT_LANG)) # ERR_UPDATE_UNKNOWN

```
This was already in there when I took this project, and I don't really wanna touch this...

**Comment by Bibo-Joshi** [comment]
this doesn't really change my answer. All you do in there can be achieved with error handlers and putting `TypeHandlers` in a low group. Again, just check the implementation of `Dispatcher.process_update`, to see what's wrong with your method (hint: it has to do with `use_context`), if you still want to stick with your approach.
If you have questions on how to do things differently, please ask in our user group on telegram.
