### ISSUE TITLE
Strange database issue

### ISSUE THREAD

**Issue by zefoo** [python-telegram-bot/python-telegram-bot#222]
I'm having a database issue I think may be related to polling, but I'm not too sure. I don't intimately understand polling, but I'm having a strange issue and was wondering if anyone here has any two cents. (I'm still troubleshooting, but I've put almost a dozen hours into this now and I'm wondering if I'm missing something obvious since I'm fairly new to Python) 

First, the problem: After 8+ hours (or so) of a polling app running, I get a "MySQL server has gone away'" exception. I realize this may obviously point to MySQL, but based off my troubleshooting (changing mysql config, turning on verbose logging, etc), I'm not sure this is MySQL. This happens a few times, and I can't exactly recreate it every time (although usually it happens in the morning after there is no update from polling between 10pm to 6am, for example)

I have some code similar to this:

```
#!/usr/bin/env python

import myapp
from myapp import create_session
from telegram import Updater

def process(bot, update):
    try:
        context = {
            'session': create_session()
        }
        myapp.save(context, update)
        myapp.reply(context, update)
    context['session'].commit()
    context['session'].close()
    del context

def error(bot, update, error):
    logging.warn('Update "%s" caused error "%s"' % (update, error))

if __name__ == '__main__':
    logging.debug('Starting telegram polling')
    updater = Updater(token=config['telegram_api_key'])
    dp = updater.dispatcher
    dp.addTelegramMessageHandler(process)
    dp.addErrorHandler(error)
    updater.start_polling()
    updater.idle()
```

create_session() gets created this way:

```
#!/usr/bin/env python

from sqlalchemy import create_engine, BigInteger, Column, DateTime, Integer, SmallInteger, String, Table
from sqlalchemy import text as sql_text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from myapp.config import config

engine = create_engine(config['db_conn_string'])
engine.connect()

Base = declarative_base()
metadata = Base.metadata

#...model classes...

create_session = sessionmaker(bind=engine)
```

And with this code, after polling has been running for some time (say, 8+ hours), I sporadically get this error:

```
- Traceback (most recent call last):
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
context)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execute(statement, parameters)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 226, in execute
self.errorhandler(self, exc, value)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
raise errorvalue
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 217, in execute
res = self._query(query)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 378, in _query
rowcount = self._do_query(q)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursor s.py", line 341, in _do_query
db.query(q)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
_mysql.connection.query(self, query)
- _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
- 
The above exception was the direct cause of the following exception:

- Traceback (most recent call last):
- File "/home/www/myapp/play/myapp/polling.py", line 87, in process
myapp.save(context, update)
- File "/home/www/myapp/play/myapp/messages.py", line 20, in save
user = channels.extract_user(context, data)
- File "/home/www/myapp/play/myapp/channels.py", line 39, in extract_user
user['uid'] = get_uid(context, 'uid', user['channel']['uid'])
- File "/home/www/myapp/play/myapp/channels.py", line 99, in get_uid
filter(ChannelData.value==value).\
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/orm/ query.py", line 2724, in scalar
ret = self.one()
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2693, in one
ret = list(self)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
return self._execute_and_instances(context)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
return meth(self, multiparams, params)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/ base.py", line 1010, in _execute_clauseelement
compiled_sql, distilled_params
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
context)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
exc_info
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
raise value.with_traceback(tb)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
context)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execu te(statement, parameters)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 226, in execute
self.errorhandler(self, exc, value)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
raise errorvalue
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 217, in execute
res = self._query(query)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 378, in _query
rowcount = self._do_query(q)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 341, in _do_query
db.query(q)
- File "/home/www/myapp/play/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
_mysql.connection.query(self, query)
- sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [ SQL: 'SELECT channel_data.uid AS channel_data_uid \nFROM channel_data \nWHERE channel_data.channel = %s AND channel_data.field = %s AND channel_data.value = %s'] [parameters: ('telegram', 'uid', 25000000)]
```

Now, I realize "MySQL server has gone away'" would imply MySQL gone away so this is perhaps an issue with MySQL. However, I have triple checked mysql, SQLAlchemy, enabling and double checking all of mysql's logging possibilities, etc... with still no resolution. (Side note: We will move the app to postgres sometime)

What seems to be happening:

Somehow, polling is losing the database connection and unable to create a new session after an extended length of time. I should be seeing this at the database level, but I'm not seeing anything in the mysql logs which implies the connection might never even be reaching mysql... somehow. 

Any tips on troubleshooting? Even something as simple as, "Your code looks good, that should be working" would be helpful. 

Thank you for any time -

**Comment by jh0ker** [comment]
I think I can safely say that this is unrelated to this library or polling in general.
