### ISSUE TITLE
using webhook in google app engine

### ISSUE THREAD

**Issue by jbhv12** [python-telegram-bot/python-telegram-bot#223]
i tried to host a bot on gae which uses webhook. however google does not provide socket service on free account and i get following error: FeatureNotEnabledError: The Socket API will be enabled for this application once billing has been enabled in the admin console

full error:

Exception on /set_webhook [GET]
Traceback (most recent call last):
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/bot_gae.py", line 33, in set_webhook
    s = bot.setWebhook('https://bot3-1263.appspot.com/HOOK')
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/telepot/__init__.py", line 285, in setWebhook
    timeout=self._http_timeout)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/base/data/home/apps/s~bot3-1263/1.391677743694943952/lib/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 339, in getaddrinfo
    canonical=(flags & AI_CANONNAME))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 212, in _Resolve
    canon, aliases, addresses = _ResolveName(name, families)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 230, in _ResolveName
    apiproxy_stub_map.MakeSyncCall('remote_socket', 'Resolve', request, reply)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 95, in MakeSyncCall
    return stubmap.MakeSyncCall(service, call, request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 329, in MakeSyncCall
    rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
FeatureNotEnabledError: The Socket API will be enabled for this application once billing has been enabled in the admin console.

any help on this???any other alternative that i can use?? can i use .getMessage() method? how?

**Comment by taemery** [comment]
I use Google app engine exclusively. Can you please comment with the code you are using?

**Comment by jbhv12** [comment]
@taemery https://github.com/jbhv12/bot3.git

**Comment by taemery** [comment]
You should set your webhook in your main.py then using GAE route requests to different classes. Don't use getUpdates becuase the webhook will be set to your appspot domain name. 

Here is a code snippet example: https://gist.github.com/taemery/a27788a93aedd8e4fce1

**Comment by jbhv12** [comment]
@taemery i updated my code as you suggested, still i get the same error.
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/bot_gae.py", line 13, in <module>
    bot.setWebhook('https://bot3-1263.appspot.com/201258891:AAHjPNikeWk27BzOwFUfcNJ_cUCBQxZmaz0')
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/telepot/__init__.py", line 285, in setWebhook
    timeout=self._http_timeout)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/base/data/home/apps/s~bot3-1263/1.391695834318303037/lib/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 339, in getaddrinfo
    canonical=(flags & AI_CANONNAME))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 212, in _Resolve
    canon, aliases, addresses = _ResolveName(name, families)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 230, in _ResolveName
    apiproxy_stub_map.MakeSyncCall('remote_socket', 'Resolve', request, reply)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 95, in MakeSyncCall
    return stubmap.MakeSyncCall(service, call, request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 329, in MakeSyncCall
    rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
FeatureNotEnabledError: The Socket API will be enabled for this application once billing has been enabled in the admin console.

here's main.py file:
https://gist.github.com/jbhv12/a1c2179db5cf96e36ae3

**Comment by taemery** [comment]
Enable billing on your Google Cloud Project. setWebhook uses a socket to connect to telegram servers

**Comment by jbhv12** [comment]
that's the problem, i don't have any credit card to spare. any other solution or other alternative to gae??

**Comment by leandrotoledo** [comment]
Hi @jbhv12, please take a look at [Where-to-host-Telegram-Bots](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Where-to-host-Telegram-Bots) wiki's page, some services even offer trials so you can test your bot for free for a limited time.

Resolving.
