### ISSUE TITLE
How to handle 400, 403 errors

### ISSUE THREAD

**Issue by giacomocerquone** [python-telegram-bot/python-telegram-bot#225]
Hi everyone, my problem is similar to this one: https://github.com/python-telegram-bot/python-telegram-bot/issues/103

And in the final message veralfre tells that it's better to handle all the exceptions, but can I do that? I need to know this since I'm running into a bad bad problem. 
My bot shares news and I keep a global list of all the subscribed chat id and I cycle on this list to forward everyone the news. Now a few times it happened that I've got 400 and 403 errors on some chat id located at a certain point of the list and all the other chat id below the first one that caused the error are not able to receive any news.

An example:

```
[
    2334322
    2436546 #bad chat id that will cause the error
    2340234 #he doesn't receive any news
    9586794 #and neither does he
]
```

This is one of the two errors I have to solve:

```
Traceback (most recent call last):
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\utils\request.py", line 67,
n decorator
    return func(*args, **kwargs)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\utils\request.py", line 140
in post
    result = urlopen(request, timeout=timeout).read()
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 589, in http_error_defaul
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\jobqueue.py", line 114, in
ck
    j.run(self.bot)
  File "botcore.py", line 76, in notify_news
    bot.sendMessage(chat_id, parse_mode='Markdown', text=news_to_string)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\bot.py", line 127, in decor
or
    result = func(self, *args, **kwargs)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\bot.py", line 159, in decor
or
    result = request.post(url, data)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\utils\request.py", line 79,
n decorator
    raise TelegramError(message)
telegram.error.TelegramError: Bad request: chat not found
```

And here you can find the code: https://github.com/UnivaqTelegramBot/UnivaqInformaticaBot/blob/dev/botcore.py

Thank you so much for all your work and for everything you do for the community and for the folks like me! :)

**Comment by rahiel** [comment]
Thanks for reporting this issue. I see your bot is using version 3.2 of `python-telegram-bot`, could you first update it to the latest version? You only have to change [this line](https://github.com/UnivaqTelegramBot/UnivaqInformaticaBot/blob/47c2cd1ffd120e3e337cec96dd5b2e68a0264915/botcore.py#L9) to `from telegram.ext import Updater`.

**Comment by giacomocerquone** [comment]
Ok updating the library seems all fine except for the fact that in Powershell I can't get out with ctrl+c and I must close and open it again.

Anyway this is the error with the 3.4:

```
2016-04-02 20:44:11,626 - libs.utils.utils - INFO - Bot started
2016-04-02 20:44:21,639 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): www.disim.
univaq.it
2016-04-02 20:44:22,572 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): www.disim.
univaq.it
2016-04-02 20:44:23,473 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): www.disim.
univaq.it
2016-04-02 20:44:24,921 - telegram.ext.jobqueue - ERROR - An uncaught error was raised while executing job notify_news
Traceback (most recent call last):
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\utils\request.py", line 77, i
n decorator
    return func(*args, **kwargs)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\utils\request.py", line 173,
in post
    result = urlopen(request, **urlopen_kwargs).read()
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\ext\jobqueue.py", line 111, i
n tick
    j.run(self.bot)
  File "botcore.py", line 76, in notify_news
    bot.sendMessage(chat_id, parse_mode='Markdown', text=news_to_string)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\bot.py", line 128, in decorat
or
    result = func(self, *args, **kwargs)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\bot.py", line 145, in decorat
or
    return Bot._post_message(url, data, kwargs)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\bot.py", line 175, in _post_m
essage
    network_delay=network_delay)
  File "C:\Users\Giacomo\AppData\Local\Programs\Python\Python35\lib\site-packages\telegram\utils\request.py", line 94, i
n decorator
    raise NetworkError('{0} ({1})'.format(message, errcode))
telegram.error.NetworkError: Bad request: chat not found (400)
```

**Comment by rahiel** [comment]
Okay, it sounds like your bot is trying to send a message to a user Telegram can't find. You can handle errors by adding an `ErrorHandler` that acts on the exception like [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/ba0ea4f2689de9616c88d492ac29dfd37fd8f507/examples/echobot2.py#L64). The `error` function receives the update and error, so you can read the message of the error and check for the "chat not found", be sure to keep logging all the other errors. Then you should probably remove this chat_id from your news user list.

**Comment by jh0ker** [comment]
Actually, that would not suffice here. The Error is raised inside a loop:

```
        for chat_id in utils.SUBSCRIBERS:
            bot.sendMessage(chat_id, parse_mode='Markdown', text=news_to_string)
```

I recommend you change it to something like this:

```
        invalid_chats = list()
        for chat_id in utils.SUBSCRIBERS:
            try:
                bot.sendMessage(chat_id, parse_mode='Markdown', text=news_to_string)
            except TelegramError:
                invalid_chats.append(chat_id)
        for chat_id in invalid_chats:
            utils.SUBSCRIBERS.remove(chat_id)
```

You will have to do `from telegram import TelegramError` too

**Comment by giacomocerquone** [comment]
@rahiel Yes, I was already attaching the error handler in the local scripts of the bot to try to handle the situation.
@jh0ker you rock! I modified what you gave me a bit, but it's perfect!
Anyway I think the documentation should be heavily improved, I don't know if it's me being dumb, but everytime I come here asking for help I discover something new about this library like this TelegramError (the only hint I had about this was only in the first log when I was using the 3.2 version, in the second log there isn't anything).

Thank you again :)

**Comment by rahiel** [comment]
> Anyway I think the documentation should be heavily improved

Yeah we will document how to do exception handling in the library, it's currently missing. Thanks for your patience.
