### ISSUE TITLE
[BUG]Error that only happens in Groups : telegram.error.TimedOut: Timed out

### ISSUE THREAD

**Issue by vic131** [python-telegram-bot/python-telegram-bot#2274]
Piece of code : 
```
def received_information_selecionar(update: Update, context: CallbackContext) -> int:
    print('ue , to aqui, como ????')
    text = update.message.text
    user_id = update.effective_user.id
    group_id = update.message.chat.id

    if user_id != group_id :
        id_correto = group_id
    else:
        id_correto = user_id
        
    pwd = os.getcwd()

    npath=pwd+'/'+str(id_correto)+'/'+text
    path_cat=npath+'/'+'categorias.csv'
    path_data=npath+'/'+'database.csv'
    
    path_universal.clear()
    path_universal.append(npath)
    path_universal.append(path_cat)
    path_universal.append(path_data)
    

    datai=datetime.today().strftime('%d/%m/%Y')
    datai=datetime.strptime(datai, '%d/%m/%Y')

    df=pd.read_csv(path_universal[2])
    df['dataseparada'] = pd.to_datetime(df.dataseparada, format='%d/%m/%Y')
        
    dataf= datai+relativedelta(days=+3)
    df3=df[(df.dataseparada == dataf)]
    df3=df3.fillna('none')


    dataf= datai+relativedelta(days=+2)
    df2=df[(df.dataseparada == dataf)]
    df2=df2.fillna('none')


    dataf= datai+relativedelta(days=+1)
    df1=df[(df.dataseparada == dataf)]
    df1=df1.fillna('none')


    df0=df[(df.dataseparada == datai)]
    df0=df0.fillna('none')

    df00=df[(df.dataseparada < datai)]
    df00=df00.fillna('none')
    
    

    lista3=[]
    lista2=[]
    lista1=[]
    lista0=[]
    lista00=[]


    for index,row in df3.iterrows():
        if row['pagamento_efetuado'] == 'n' or row['pagamento_efetuado'] == 'none' :
            lista3.append(row['nome'])
            lista3.append(str(index))
    for index,row in df2.iterrows():
        if row['pagamento_efetuado'] == 'n' or row['pagamento_efetuado'] == 'none' :
            lista2.append(row['nome'])
            lista2.append(str(index))
    for index,row in df1.iterrows():
        if row['pagamento_efetuado'] == 'n' or row['pagamento_efetuado'] == 'none' :
            lista1.append(row['nome'])
            lista1.append(str(index))
            
    for index,row in df0.iterrows():
        if row['pagamento_efetuado'] == 'n' or row['pagamento_efetuado'] == 'none' :
            lista0.append(row['nome'])
            lista0.append(str(index))

    for index,row in df00.iterrows():
        if row['pagamento_efetuado'] == 'n' or row['pagamento_efetuado'] == 'none' :
            lista00.append(row['nome'])
            lista00.append(str(index))
            
    if lista3 or lista2 or lista1 or lista0 or lista00:
        
        update.message.reply_text(
        "Lembretes : "
    )
       

        if lista00:
             update.message.reply_text(
        "Atrasadas : %s" % (', '.join(lista00))
        )

            
        if lista0:
            update.message.reply_text(
        "Hoje : %s" % (', '.join(lista0))
        )
        if lista1:
            update.message.reply_text(
        "Amanhã : %s" % (', '.join(lista1))
        )
        if lista2:
            update.message.reply_text(
        "Daqui há 2 dias : %s" % (', '.join(lista2))
        )

        if lista3:
            update.message.reply_text(
        "Daqui há 3 dias : %s" % (', '.join(lista3))
        )

        
        update.message.reply_text(
        "Escolha uma opção",
        reply_markup=markup_inicial
        )

        return INICIO

        
        
    else:
        
        update.message.reply_text(
            "Não há nenhum lembrete"
        )
        
        return INICIO

```
Expected behaviour : 
It should send 6 messages (lines 85,91,97,101,105,110) then 1 more final message (line 115) together with a Replykeyboardmarkup (markup_inicial), and then return INICIO (line 120). All this in a group with 2 peoples (and 1 bot).

Actual behaviour : 
50% of the time, it works. But in the other 50% i receive this in the terminal: 

```
2020-12-26 21:09:37,987 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 252, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 404, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout,
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "registro_financeiro_telegram.py", line 472, in received_information_selecionar
    update.message.reply_text(
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/message.py", line 603, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "<decorator-gen-2>", line 2, in send_message
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/bot.py", line 135, in decorator
    result = func(*args, **kwargs)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/bot.py", line 458, in send_message
    return self._message(  # type: ignore[return-value]
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/bot.py", line 281, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/bot.py", line 245, in _post
    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 349, in post
    result = self._request_wrapper(
  File "/home/lubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 254, in _request_wrapper
    raise TimedOut() from error
telegram.error.TimedOut: Timed out
```
 And it then fails to return INICIO(line 120), so it keep stucked in that function forever.

Tests : 

1. This only occours in groups, when using the group_id (update.message.chat.id) , instead of user_id(update.effective_user.id). The error wont happens in a individual chat.
2. The error disapears if i limit the messages sent inside the function to 6, instead of 7. So, i can only have 6 `update.message.reply_text(`.
3. There is not aparently variation (on the desktop, or android devices) that explains why sometimes it works, and sometimes dont. 
4. The error only happens inside this function so far. All the others i tested dosent seems to result in this error.

I really cant see any problem with my code, so i'm assuming its a bug. Please let me know if i'm wrong.

Configuration : 
Lubuntu 20.04

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 13.1
certifi 2019.11.28
Python 3.8.2 (default, Mar 13 2020, 10:14:16)  [GCC 9.3.0]

**Comment by Bibo-Joshi** [comment]
Hi. Try increasing the `timeout` parameter of `send_message` and please also have a look at the wiki page "Handling network errors".
