### ISSUE TITLE
SSL handshake errror

### ISSUE THREAD

**Issue by IsmoilovMuhriddin** [python-telegram-bot/python-telegram-bot#229]
2016-04-04 11:01:50,474 - telegram.bot - DEBUG - Entering: getUpdates
2016-04-04 11:02:02,623 - telegram.ext.updater - ERROR - Error while getting Updates: URLError: _ssl.c:584: The handshake operation timed out
2016-04-04 11:02:03,624 - telegram.bot - DEBUG - Entering: getUpdates
2016-04-04 11:02:09,415 - telegram.ext.dispatcher - WARNING - Error was raised while processing Update.
2016-04-04 11:02:09,415 - telegram.ext.dispatcher - DEBUG - Processed Update: URLError: _ssl.c:584: The handshake operation timed out with context None
2016-04-04 11:02:24,612 - telegram.ext.updater - ERROR - Error while getting Updates: URLError: _ssl.c:584: The handshake operation timed out
2016-04-04 11:02:24,613 - telegram.ext.dispatcher - DEBUG - Processed Update: URLError: _ssl.c:584: The handshake operation timed out with context None

**Comment by leandrotoledo** [comment]
Hi @IsmoilovMuhriddin, does the issue still persists?

Thanks.

**Comment by leandrotoledo** [comment]
Resolving. Please feel free to reopen if this error persists.

**Comment by diakbar** [comment]
Got same error here, any solution for this?
```

# python echobot.py 
2016-05-11 22:36:30,751 - telegram.bot - DEBUG - Entering: getUpdates
Traceback (most recent call last):
  File "echobot.py", line 56, in <module>
    main()
  File "echobot.py", line 21, in main
    update_id = bot.getUpdates()[0].update_id
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 114, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1315, in getUpdates
    result = request.post(url, data, timeout=urlopen_timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 83, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
telegram.error.NetworkError: URLError: ('_ssl.c:574: The handshake operation timed out',)

```

**Comment by jh0ker** [comment]
@diakbar Please refer to #285

**Comment by diakbar** [comment]
@jh0ker when i install from source and use example echobot2.py it's worked as charm. But when I tried run again old echobot.py, it's still get the error.

here's the old echobot.py script :
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Simple Bot to reply to Telegram messages
# This program is dedicated to the public domain under the CC0 license.

import logging
import telegram
from telegram.error import NetworkError, Unauthorized
from time import sleep
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

def main():
    # Telegram Bot Authorization Token
    bot = telegram.Bot('TOKEN')

    # get the first pending update_id, this is so we can skip over it in case
    # we get an "Unauthorized" exception.
    try:
        update_id = bot.getUpdates()[0].update_id
    except IndexError:
        update_id = None

    logging.basicConfig(
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    while True:
        try:
            update_id = echo(bot, update_id)
        except NetworkError:
            sleep(1)
        except Unauthorized:
            # The user has removed or blocked the bot.
            update_id += 1


def echo(bot, update_id):

    # Request updates after the last update_id
    for update in bot.getUpdates(offset=update_id):
        # chat_id is required to reply to any message
        chat_id = update.message.chat_id
        update_id = update.update_id + 1
        message = update.message.text

        if message:
            # Reply to the message
            bot.sendMessage(chat_id=chat_id,
                            text=message)

    return update_id


if __name__ == '__main__':
    main()

```

new echobot2.py
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Simple Bot to reply to Telegram messages
# This program is dedicated to the public domain under the CC0 license.

"""
This Bot uses the Updater class to handle the bot.

First, a few handler functions are defined. Then, those functions are passed to
the Dispatcher and registered at their respective places.
Then, the bot is started and runs until we press Ctrl-C on the command line.

Usage:
Basic Echobot example, repeats messages.
Press Ctrl-C on the command line or send a signal to the process to stop the
bot.
"""

from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
import logging

# Enable logging
logging.basicConfig(
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        level=logging.INFO)

logger = logging.getLogger(__name__)


# Define a few command handlers. These usually take the two arguments bot and
# update. Error handlers also receive the raised TelegramError object in error.
def start(bot, update):
    bot.sendMessage(update.message.chat_id, text='Hi!')


def help(bot, update):
    bot.sendMessage(update.message.chat_id, text='Help!')


def echo(bot, update):
    bot.sendMessage(update.message.chat_id, text=update.message.text)


def error(bot, update, error):
    logger.warn('Update "%s" caused error "%s"' % (update, error))


def main():
    # Create the EventHandler and pass it your bot's token.
    updater = Updater("TOKEN")

    # Get the dispatcher to register handlers
    dp = updater.dispatcher

    # on different commands - answer in Telegram
    dp.addHandler(CommandHandler("start", start))
    dp.addHandler(CommandHandler("help", help))

    # on noncommand i.e message - echo the message on Telegram
    dp.addHandler(MessageHandler([Filters.text], echo))

    # log all errors
    dp.addErrorHandler(error)

    # Start the Bot
    updater.start_polling()

    # Run the bot until the you presses Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT. This should be used most of the time, since
    # start_polling() is non-blocking and will stop the bot gracefully.
    updater.idle()

if __name__ == '__main__':
    main()

```

**Comment by jh0ker** [comment]
It seems that in the last update we may have broken non-long-polling (so running `getUpdates` without setting a timeout)
You can modify the old `echobot.py` by simply adding `timeout=10` to the `getUpdates` call and see if it works then.
I'll do a few tests myself and, if confirmed, create a PR to fix the problem.

**Comment by jh0ker** [comment]
@diakbar forgot to ping you

**Comment by jh0ker** [comment]
@diakbar I just tried and the `echobot.py` works fine for me. It's also possible that your internet connection is too slow - you can try passing `network_delay=1.0` to `getUpdates` to counter that.
