### ISSUE TITLE
[QUESTION] Unable to set token to variable

### ISSUE THREAD

**Issue by ofefo** [python-telegram-bot/python-telegram-bot#2366]
### Issue I am facing
I'm storing the token outside the script and trying to pass it's value as an argument to the Updater() function.

### Traceback to the issue
```
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    updater = Updater(token)
  File ".../venv/lib/python3.8/site-packages/telegram/ext/updater.py", line 176, in __init__
    self.bot = Bot(
  File ".../venv/lib/python3.8/site-packages/telegram/bot.py", line 196, in __init__
    self.token = self._validate_token(token)
  File ".../venv/lib/python3.8/site-packages/telegram/bot.py", line 286, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

### Related part of your code
```python
with open('./token', 'r') as f:
    tk = f.read()

updater = Updater(tk)
```

**Comment by starry69** [comment]
Did you try printing `tk` like:
```python
with open('./token', 'r') as f:
    tk = f.read()
    print(tk)
```

To make sure it doesn't contain any newlines and spaces?

**Comment by ofefo** [comment]
Yes I've tried that but didn't took attention to the fact a new line was actually printed, not the \n character... my fault. Thanks!
