### ISSUE TITLE
[QUESTION] paymentbot.py: telegram.error.BadRequest: Payment_provider_invalid

### ISSUE THREAD

**Issue by kenorb** [python-telegram-bot/python-telegram-bot#2394]
### Issue I am facing

I'm testing `examples/paymentbot.py` and when clicking `/noshipping` or `/shipping` it generates the error.

### Traceback to the issue
```
2021-02-18 20:12:30,992 - apscheduler.scheduler - INFO - Scheduler started
2021-02-18 20:12:36,664 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "examples/./paymentbot.py", line 90, in start_without_shipping_callback
    context.bot.send_invoice(
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 117, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 3343, in send_invoice
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 271, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 235, in _post
    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 349, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 272, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Payment_provider_invalid
```

Is this expected?

### Related part of your code

- `examples/paymentbot.py`

**Comment by Poolitzer** [comment]
you change the provider token to yours?

**Comment by kenorb** [comment]
> you change the[ provider token](https://github.com/python-telegram-bot/python-telegram-bot/blob/a34f0b9beece9f503d0c02dd9ac04477438fa68a/examples/paymentbot.py#L44) to yours?

I've missed that part, thanks. Was doing all examples in sequence and didn't notice this one is different from the others. Thanks.
