### ISSUE TITLE
[QUESTION] How can i deal with "The list of positional arguments is longer than the target callable can handle " with job_queue

### ISSUE THREAD

**Issue by buinguyenhoangtho** [python-telegram-bot/python-telegram-bot#2435]
### Issue I am facing
Please describe the issue here in as much detail as possible
Hello. I'm using flask app with python-telegram-bot. I facing the bug "The list of positional arguments is longer than the target callable can handle " when using job_queue() method.
### This is my log
```
2021-03-18 19:15:57,610 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x000001B0D003E790>
Traceback (most recent call last):
  File "main.py", line 138, in <module>
    job_queue.run_repeating(fetchRSS, delay)
  File "C:\Users\hoangtho\AppData\Roaming\Python\Python38\site-packages\telegram\ext\jobqueue.py", line 292, in run_repeating
    j = self.scheduler.add_job(
  File "C:\Users\hoangtho\AppData\Roaming\Python\Python38\site-packages\apscheduler\schedulers\base.py", line 434, in add_job
    job = Job(self, **job_kwargs)
  File "C:\Users\hoangtho\AppData\Roaming\Python\Python38\site-packages\apscheduler\job.py", line 49, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "C:\Users\hoangtho\AppData\Roaming\Python\Python38\site-packages\apscheduler\job.py", line 180, in _modify
    check_callable_args(func, args, kwargs)
  File "C:\Users\hoangtho\AppData\Roaming\Python\Python38\site-packages\apscheduler\util.py", line 412, in check_callable_args
    raise ValueError(
ValueError: The list of positional arguments is longer than the target callable can handle (allowed: 0, given in args: 1)

```

```python
# Core
  # start the bot in a thread instead
updater = Updater(token=BOT_TOKEN)
dp = updater.dispatcher
job_queue = updater.job_queue
dp.add_handler(CommandHandler("add", add))
# dp.add_handler(MessageHandler(filters=Filters.text, callback=reponse))

# @app.route('/list')
# list 
# load RSS and fetch it 📰 
# but first, check news availablity
feeds = [] #feed cointainter

 
def fetchRSS():
    # feed url:
    print("Feed url trong 5s")
    cur.execute("SELECT feed_url FROM feed_source")
    rows = cur.fetchall()
    for row in rows:
        row_result = ("".join(row))
        feeds.append(row_result)
    for url in feeds:
        print("URL để feed:",url)
        article = feedparser.parse(url)
        for article_news in article.entries:
        # get titles
            print("Title:",article_news.title)
            time.sleep(1)   
@app.route('/')
def main():
    # fetch
    # test job_queue với 5s
    cur.execute("SELECT * FROM feed_source")
    data = cur.fetchall()
    job_queue.run_repeating(fetchRSS, delay)
    
    return render_template('index.html',data=data) 
   
t = threading.Thread(target=updater.start_polling, daemon=True)
t.start()
if __name__ == '__main__':
    app.run()
```

**Comment by Bibo-Joshi** [comment]
`fetchRSS` must accept exactly one argument of type `CallbackContext`. Please see the wiki page on `JobQueue` and the `timerbot.py` example for an introduction to how `JobQueue` works.

**Comment by buinguyenhoangtho** [comment]
Hello. Thanks for your information. Just one more thing. Let said my fetchRss function it fetch all RSS from feed. It possible to wait them finish and then start start again with delay i set?

**Comment by Bibo-Joshi** [comment]
If you want to schedule a new job from within `fetchRSS`, you can do that via `context.job_queue.run_*(…)`

**Comment by buinguyenhoangtho** [comment]
Sorry for miss information. Let said: The job ``fetchRSS`` fetch 100 articles and my ``` delay ``` is 30 second
Now i want to wait all articles has been FETCHED ( 100 ) and then start a new job ``` fetchRSS``` loop after ``` delay``` .  Is that impossible?

**Comment by Bibo-Joshi** [comment]
Yes. Just call `context.job_queue.run_once(fetchRSS, 30, …)` after fetching the articles.

**Comment by buinguyenhoangtho** [comment]
> Yes. Just call `context.job_queue.run_once(fetchRSS, 30, …)` after fetching the articles.

Hey . Thanks for your help. It work as i expected. :D Thanks you very very much :D
