### ISSUE TITLE
Really need an explanation with jobs persistence

### ISSUE THREAD

**Issue by exusr** [python-telegram-bot/python-telegram-bot#2436]
Following the documentation to save a job it says,  you have to follow the systems of the apscheduler library. And that's what I did, adding persistence via SQLAlchemyJobStore. However, despite the database being generated, the process fails due to the fact that it cannot be picked on the JobQueue. I searched a lot before asking here but found only one example of Queue persistence for version 12x of the library which is incompatible with 13x. 

### My Traceback
```
starting..
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "{$my_working_path}/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "{$my_working_path}/lib/python3.8/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "{$my_working_path}/src/utils/auth.py", line 27, in __call__
    return self.function(*args)
  File "main.py", line 68, in queue_searches
    context.job_queue.run_daily(search_over_time, options["time"], options["days"], context = job_args, name =  str(update.message.chat_id))
  File "{$my_working_path}/lib/python3.8/site-packages/telegram/ext/jobqueue.py", line 439, in run_daily
    j = self.scheduler.add_job(
  File "{$my_working_path}/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 443, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "{$my_working_path}/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 867, in _real_add_job
    store.add_job(job)
  File "{$my_working_path}/lib/python3.8/site-packages/apscheduler/jobstores/sqlalchemy.py", line 95, in add_job
    'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
AttributeError: Can't pickle local object 'PoolManager.__init__.<locals>.<lambda>'
```

### Code:
```python
def search_over_time(string = 'only a test'):
    print(string)

def queue_searches(update: Update, context: CallbackContext) -> None:
    options = set_options(update.message)
    context.job_queue.run_daily(search_over_time, options["time"], options["days"],context = None, name =  str(update.message.chat_id), job_kwargs = { })


updater = Updater(...)
jobstores = SQLAlchemyJobStore(url = "mysql+pymysql://<user>:<password>@localhost/<dbname>", tablename="apscheduler_jobs")
updater.job_queue.scheduler.add_jobstore(jobstores)
updater.dispatcher.add_handler(CommandHandler('query', queue_searches, pass_args=True, pass_update_queue=True, pass_job_queue=True))
updater.start_polling()
updater.idle()
```

**Comment by dreamwhite** [comment]
Can reproduce the bug on my side. Probably the issue must be fixed on 13x release version of the library :/

**Comment by Bibo-Joshi** [comment]
please have a look at python-telegram-bot/ptbcontrib#9. The PR was never finished by the authore, but it may be a good starting point for you.

**Comment by exusr** [comment]
Thank you Sir! I will try to implement it by myself. Is there any other method already tested and working? Even if it means changing the data storage method? Just in case everything goes wrong

**Comment by Bibo-Joshi** [comment]
> Is there any other method already tested and working?

not that I would be aware of, no.
