### ISSUE TITLE
Weird network problems

### ISSUE THREAD

**Issue by Avanatiker** [python-telegram-bot/python-telegram-bot#244]
This error cames up over night again. Any idears? (bot stopped working and i had to RESTART my pc!)

```
2016-04-21 09:43:53,371 - telegram.ext.updater - ERROR - Error while getting Updates: URLError: [Errno 10055] Ein Socketvorgang konnte nicht ausgef³hrt werden, da dem System Pufferspeicher fehlte oder eine Warteschlange voll war
2016-04-21 09:43:53,934 - telegram.ext.updater - ERROR - failed to set webhook; try=0 max_retries=0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\telegram\ext\updater.py", line 254, in _set_webhook
    self.bot.setWebhook(webhook_url=webhook_url)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 128, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 832, in setWebhook
    result = request.post(url, data)
  File "C:\Python27\lib\site-packages\telegram\utils\request.py", line 97, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
NetworkError: URLError: [Errno 10055] Ein Socketvorgang konnte nicht ausgef³hrt werden, da dem System Pufferspeicher fehlte oder eine Warteschlange voll war
2016-04-21 09:43:53,943 - telegram.ext.updater - ERROR - unhandled exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\telegram\ext\updater.py", line 146, in _thread_wrapper
    target(*args, **kwargs)
  File "C:\Python27\lib\site-packages\telegram\ext\updater.py", line 217, in _start_polling
    self._set_webhook(None, bootstrap_retries)
  File "C:\Python27\lib\site-packages\telegram\ext\updater.py", line 254, in _set_webhook
    self.bot.setWebhook(webhook_url=webhook_url)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 128, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 832, in setWebhook
    result = request.post(url, data)
  File "C:\Python27\lib\site-packages\telegram\utils\request.py", line 97, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
NetworkError: URLError: [Errno 10055] Ein Socketvorgang konnte nicht ausgef³hrt werden, da dem System Pufferspeicher fehlte oder eine Warteschlange voll war
Exception in thread updater:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\site-packages\telegram\ext\updater.py", line 146, in _thread_wrapper
    target(*args, **kwargs)
  File "C:\Python27\lib\site-packages\telegram\ext\updater.py", line 217, in _start_polling
    self._set_webhook(None, bootstrap_retries)
  File "C:\Python27\lib\site-packages\telegram\ext\updater.py", line 254, in _set_webhook
    self.bot.setWebhook(webhook_url=webhook_url)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 128, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 832, in setWebhook
    result = request.post(url, data)
  File "C:\Python27\lib\site-packages\telegram\utils\request.py", line 97, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
NetworkError: URLError: [Errno 10055] Ein Socketvorgang konnte nicht ausgef³hrt werden, da dem System Pufferspeicher fehlte oder eine Warteschlange voll war
```

**Comment by leandrotoledo** [comment]
Hey @Avanatiker, any clue on how to reproduce this issue?

**Comment by leandrotoledo** [comment]
@Avanatiker Friendly ping! :smile:

**Comment by leandrotoledo** [comment]
Hi @Avanatiker, feel free to reopen this issue if you feel like the problem still persists in the latest version.
