### ISSUE TITLE
[BUG] updater.start_webhook problem

### ISSUE THREAD

**Issue by hamedmkazemi** [python-telegram-bot/python-telegram-bot#2444]
I think there is an issue with the `updater.start_webhook` in the latest version 13.4.1. I got the following log for this issue, but after I install the previous version of your package 13.3, everything works well.
Error:
_telegram.error.BadRequest: Bad webhook: webhook can be set up only on ports 80, 88, 443 or 8443_

### Configuration
I'm using Heroku.

### Logs
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  self.run()
File "/app/.heroku/python/lib/python3.6/threading.py", line 864, in run
  self._target(*self._args, **self._kwargs)
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/updater.py", line 236, in _thread_wrapper
  target(*args, **kwargs)
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/updater.py", line 602, in _start_webhook
  ip_address=ip_address,
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/updater.py", line 674, in _bootstrap
  bootstrap_interval,
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/updater.py", line 530, in _network_loop_retry
  onerr_cb(telegram_exc)
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/updater.py", line 652, in bootstrap_onerr_cb
  raise exc
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/updater.py", line 516, in _network_loop_retry
  if not action_cb():
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/updater.py", line 640, in bootstrap_set_webhook
  drop_pending_updates=drop_pending_updates,
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/bot.py", line 127, in decorator
  result = func(*args, **kwargs)
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/bot.py", line 2863, in set_webhook
  result = self._post('setWebhook', data, timeout=timeout, api_kwargs=api_kwargs)
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/bot.py", line 260, in _post
  f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 354, in post
  **urlopen_kwargs,
File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in _request_wrapper
 raise BadRequest(message)
telegram.error.BadRequest: Bad webhook: webhook can be set up only on ports 80, 88, 443 or 8443

**Comment by Bibo-Joshi** [comment]
Please check out this channel post and let me know if that solves your problem: https://t.me/pythontelegrambotchannel/100

**Comment by hamedmkazemi** [comment]
Thanks. Please clearly inform this change in [#2419](https://github.com/python-telegram-bot/python-telegram-bot/pull/2419)
