### ISSUE TITLE
[QUESTION] NoneType on from_user

### ISSUE THREAD

**Issue by sjosegarcia** [python-telegram-bot/python-telegram-bot#2479]
Hey, so I am encountering an issue where it states that I am getting a `NoneType` on from_users.

Example:
```python
    def _ban_user_command(self, update: Update, context: CallbackContext) -> None:
        bot = update.message.bot
        # banned = bot.kick_chat_member(
        #    update.message.chat_id,
        #    update.message.
        # )
        # if banned:
        update.message.reply_text(
            f"{update.message.reply_to_message.from_user.name} has been eviscerated from the face of the earth."
        )
```

Stack trace:
```
"Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/bot-Z2emI11w/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "/root/.local/share/virtualenvs/bot-Z2emI11w/lib/python3.9/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/app/bot/controllers/ban_controller.py", line 33, in _ban_user_command
    f"{update.message.reply_to_message.from_user.name} has been eviscerated from the face of the earth."
AttributeError: 'NoneType' object has no attribute 'from_user'"
```

I am looking to ban a user by quoting their chat bubble. But I am not sure why I am getting the error. What might I be missing?

**Comment by CosmiX-6** [comment]
Try this method to retrieve user id.

```python
    def _ban_user_command(self, update: Update, context: CallbackContext) -> None:
        chat = update.effective_chat
        user = update.effective_user
        message = update.effective_message
        user_id = message.reply_to_message.from_user.id
        member = chat.get_member(user_id)
        #kick member with user_id
        chat.kick_member(user_id)
        #reply to message
        update.message.reply_text("{member.user.first_name} has been eviscerated from the face of the earth.")
```

**Comment by sjosegarcia** [comment]
I still could not get it to work. Here is a working example:

```python
from controllers.singleton import Singleton
from setup.config import get_settings
from schema.token_info import GenericTokenInfo
from .token_controller import TokenController
from telegram.ext import CommandHandler, MessageHandler, Filters
from telegram.ext.callbackcontext import CallbackContext
from telegram.update import Update
from telegram import ParseMode, Bot
from telegram.ext.dispatcher import Dispatcher
from telegram.ext import Updater


class BotController(metaclass=Singleton):

    dispatcher: Dispatcher
    updater: Updater

    def __init__(self) -> None:
        bot = Bot(get_settings().telegram_bot_api_key)
        self.updater = Updater(bot=bot, workers=0)
        self.dispatcher = self.updater.dispatcher
        # self._process_handlers()
        self._generate_token_commands()

    def set_webhook(self) -> bool:
        hooked = self.updater.bot.set_webhook(
            url=f"{get_settings().telegram_bot_webhook_url}/{get_settings().telegram_bot_api_key}",
        )
        return hooked

    def main_menu(self, update: Update, context: CallbackContext) -> None:
        update.message.reply_text("Here are a list of commands available for to you!")

    def tokens(self, update: Update, context: CallbackContext) -> None:
        update.message.reply_text(
            "GODZ tokens:\n\n\tGODZ - GodZilliqa DAO token.\n\n\tGDFI - GodZilliqa DeFi token."
        )

    def whitepaper(self, update: Update, context: CallbackContext) -> None:
        update.message.reply_text("Whitepaper can be found here:")

    def new_member(self, update: Update, context: CallbackContext) -> None:
        for member in update.message.new_chat_members:
            if not member.is_bot:
                update.message.reply_text("Welcome to GodZilliqa DeFi,")

    def unknown(self, update: Update, context: CallbackContext):
        context.bot.send_message(
            chat_id=update.effective_chat.id,
            text="Use /start to find a list of commands.",
        )

    def _generate_token_commands(self) -> None:

        token_controller = TokenController()
        tokens = token_controller.get_all_tokens()
        for token in tokens:
            self._register_token_command(token, token_controller)

    def _register_token_command(
        self, token: GenericTokenInfo, token_controller: TokenController
    ) -> None:
        price = token_controller.get_token_info(token.symbol)
        token_website = (
            f"\n<a href='{token.website}'>Website</a>" if token.website else ""
        )
        token_whitepaper = (
            f"\n<a href='{token.whitepaper}'>Whitepaper</a>" if token.whitepaper else ""
        )
        token_address = (
            f"\n<a href='https://viewblock.io/zilliqa/address/{token.address_bech32}'>{token.symbol} contract on viewblock.io</a>"
            if token.address_bech32
            else ""
        )
        token_zilstream = f"\n<a href='https://zilstream.com/tokens/{token.symbol}'>View {token.symbol} on zilstream.com</a>"
        token_price = f"\n<b>{price.rate:.2f} ZIL - ${price.rate_usd:.2f}</b>"
        token_info = (
            f"<b>{token.name} ({token.symbol})\nScore: {token.viewblock_score}/100</b>"
        )

        self.dispatcher.add_handler(
            CommandHandler(
                token.symbol.lower(),
                lambda update, context: update.message.reply_text(
                    f"{token_info}{token_price}{token_website}{token_whitepaper}{token_address}{token_zilstream}",
                    parse_mode=ParseMode.HTML,
                    disable_notification=True,
                    disable_web_page_preview=True,
                    allow_sending_without_reply=True,
                ),
            )
        )

    def _process_handlers(self) -> None:
        self.dispatcher.add_handler(CommandHandler("menu", self.main_menu))
        self.dispatcher.add_handler(CommandHandler("tokens", self.tokens))
        self.dispatcher.add_handler(CommandHandler("whitepaper", self.whitepaper))
        self.dispatcher.add_handler(
            MessageHandler(Filters.status_update.new_chat_members, self.new_member)
        )
        self.dispatcher.add_handler(MessageHandler(Filters.command, self.unknown))
```
```python
from telegram.ext.filters import Filters
from telegram.ext.messagehandler import MessageHandler
from controllers.bot_controller import BotController
from telegram.ext import dispatcher
from controllers.singleton import Singleton
from telegram.ext.dispatcher import Dispatcher
from telegram.bot import Bot
from typing import Union
from telegram.ext import CommandHandler
from telegram.ext.callbackcontext import CallbackContext
from telegram.update import Update


class BanController(metaclass=Singleton):
    def blanket_ban(
        self, bot: Bot, chat_id: Union[str, int], user_id: Union[str, int]
    ) -> None:
        pass

    def _unban_user_command(self, update: Update, context: CallbackContext) -> None:
        bot = update.message.bot
        unbanned = bot.unban_chat_member(
            update.message.chat_id,
            update.message.reply_to_message.from_user.id,
        )

    def _ban_user_command(self, update: Update, context: CallbackContext) -> None:
        bot = update.message.bot
        chat = update.effective_chat
        user = update.effective_user
        message = update.effective_message
        user_id = message.reply_to_message.from_user.id
        member = chat.get_member(user_id)
        # kick member with user_id
        chat.kick_member(user_id)
        # reply to message
        update.message.reply_text(
            f"{member.user.first_name} has been eviscerated from the face of the earth."
        )

    def process_handlers(self, bot_controller: BotController) -> None:
        bot_controller.dispatcher.add_handler(
            CommandHandler(
                "ban", filters=Filters.command, callback=self._ban_user_command
            )
        )
        bot_controller.dispatcher.add_handler(
            CommandHandler("unban", self._unban_user_command)
        )
```

**Comment by Bibo-Joshi** [comment]
Add `Filters.reply` to this handler: (Also you don't need `Filters.command`, it's already a `CommandHandler`)

```python
bot_controller.dispatcher.add_handler(
            CommandHandler(
                "ban", filters=Filters.command, callback=self._ban_user_command
            )
        )
```

For the future: this example is neither minimal nor self-contained (notice the imports that are neither for ptb nor for modules from the std lib) nor contained in 1 file, all of which where requested in the link I sent you 😉

**Comment by sjosegarcia** [comment]
> Add `Filters.reply` to this handler: (Also you don't need `Filters.command`, it's already a `CommandHandler`)
> 
> ```python
> bot_controller.dispatcher.add_handler(
>             CommandHandler(
>                 "ban", filters=Filters.command, callback=self._ban_user_command
>             )
>         )
> ```
> 
> For the future: this example is neither minimal nor self-contained (notice the imports that are neither for ptb nor for modules from the std lib) nor contained in 1 file, all of which where requested in the link I sent you 😉

I am sorry about that, I was half asleep lol.
