### ISSUE TITLE
[QUESTION]Help using this module with pyinstaller

### ISSUE THREAD

**Issue by garagesteve1155** [python-telegram-bot/python-telegram-bot#2499]
### Issue I am facing
Trying to use Pyinstaller to create exe of my tg bot but running into error

### Traceback to the issue
```

C:\Users\Stephen\Desktop\PowerTrader\backend\ku>pyinstaller --onefile icoin_tg_bot.py
659 INFO: PyInstaller: 4.2
660 INFO: Python: 3.7.3
662 INFO: Platform: Windows-8-6.2.9200-SP0
666 INFO: wrote C:\Users\Stephen\Desktop\PowerTrader\backend\ku\icoin_tg_bot.spec
684 INFO: UPX is not available.
692 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Stephen\\Desktop\\PowerTrader\\backend\\ku',
 'C:\\Users\\Stephen\\Desktop\\PowerTrader\\backend\\ku']
pygame 2.0.1 (SDL 2.0.14, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
870 INFO: checking Analysis
870 INFO: Building Analysis because Analysis-00.toc is non existent
871 INFO: Initializing module dependency graph...
877 INFO: Caching module graph hooks...
901 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
920 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\tokenize.py", line 35, in <module>
    from token import *
  File "C:\Users\Stephen\Desktop\PowerTrader\backend\ku\token.py", line 1, in <module>
    from kucoin_futures.base_request.base_request import KucoinFuturesBaseRestApi
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\kucoin_futures\base_request\base_request.py", line 5, in <module>

    import requests
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\logging\__init__.py", line 40, in <module>
    import threading
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\threading.py", line 8, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc' from 'traceback' (c:\users\stephen\appdata\local\programs\python\python37-32\lib\traceback.py)
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\tokenize.py", line 35, in <module>
    from token import *
  File "C:\Users\Stephen\Desktop\PowerTrader\backend\ku\token.py", line 1, in <module>
    from kucoin_futures.base_request.base_request import KucoinFuturesBaseRestApi
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\kucoin_futures\base_request\base_request.py", line 5, in <module>

    import requests
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\logging\__init__.py", line 40, in <module>
    import threading
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\threading.py", line 8, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc' from 'traceback' (c:\users\stephen\appdata\local\programs\python\python37-32\lib\traceback.py)
8408 INFO: Caching module dependency graph...
8538 INFO: running Analysis Analysis-00.toc
8588 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\stephen\appdata\local\programs\python\python37-32\python.exe
9836 INFO: Analyzing C:\Users\Stephen\Desktop\PowerTrader\backend\ku\icoin_tg_bot.py
11029 INFO: Processing pre-find module path hook distutils from 'c:\\users\\stephen\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages
\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
11041 INFO: distutils: retargeting to non-venv dir 'c:\\users\\stephen\\appdata\\local\\programs\\python\\python37-32\\lib'
11293 INFO: Processing pre-find module path hook site from 'c:\\users\\stephen\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyI
nstaller\\hooks\\pre_find_module_path\\hook-site.py'.
11304 INFO: site: retargeting to fake-dir 'c:\\users\\stephen\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\fake-mo
dules'
16457 INFO: Processing pre-safe import module hook setuptools.extern.six.moves from 'c:\\users\\stephen\\appdata\\local\\programs\\python\\python37-32
\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-setuptools.extern.six.moves.py'.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 6, in <module>
    import distutils.core
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 17, in <module>
    from distutils.cmd import Command
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 9, in <module>
    from distutils import util, dir_util, file_util, archive_util, dep_util
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\distutils\archive_util.py", line 11, in <module>
    import zipfile
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\zipfile.py", line 12, in <module>
    import shutil
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\shutil.py", line 22, in <module>
    import bz2
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\bz2.py", line 17, in <module>
    from threading import RLock
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\threading.py", line 8, in <module>
    from traceback import format_exc as _format_exc
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\tokenize.py", line 35, in <module>
    from token import *
  File "C:\Users\Stephen\Desktop\PowerTrader\backend\ku\token.py", line 1, in <module>
    from kucoin_futures.base_request.base_request import KucoinFuturesBaseRestApi
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\kucoin_futures\base_request\base_request.py", line 5, in <module>

    import requests
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\logging\__init__.py", line 210, in <module>
    _lock = threading.RLock()
AttributeError: module 'threading' has no attribute 'RLock'
pre-safe-import-module hook failed, needs fixing.


```

### Related part of your code

i guess this part??
```
import logging
logging.basicConfig(
	format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO
)
logger = logging.getLogger(__name__)
```

**Comment by Bibo-Joshi** [comment]
Hi. In the traceback I see no mention of `python-telegram-bot` or even just `telegram`, so this seems like a problem of pyinstaller to me.

**Comment by garagesteve** [comment]
> Hi. In the traceback I see no mention of `python-telegram-bot` or even just `telegram`, so this seems like a problem of pyinstaller to me.

Yeah for sure, was just wondering if anyone had experienced this using it with pyinstaller and what they did.. pyinstaller works great for my other codes, just not this tg bot. (This tg bot is using totally different modules than other codes)

**Comment by Poolitzer** [comment]
This repository where you opened this issue is about python-telegram-bot though. Not pyinstaller or the module which gives you the actual issue. I would recommend StackOverflow or pyinstallers community help.
