### ISSUE TITLE
[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC]

### ISSUE THREAD

**Issue by hypy13** [python-telegram-bot/python-telegram-bot#2529]
### Steps to reproduce
1. i use python host to serve my bot with webhook

2. and i use this module on django 3.2 on apache

3. sometimes bot respond with error:

```python
File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 647, in urlopen
    raise SSLError(e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC]
```

### Expected behaviour
i dont know really what is problem i searched a lot but didnt find any solution

### Configuration
**Operating System:**
Ubuntu
python 3.7.10
python-telegram-bot is 13.5

### Logs

this the complete log

```python
Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 253, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 71, in request
    **urlopen_kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 272, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 602, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/home/rezwanaw/production/apps/telbot/telegrambot.py", line 83, in start
    update.message.reply_text(get_msg('WELCOME', context))
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/message.py", line 715, in reply_text
    entities=entities,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 483, in send_message
    api_kwargs=api_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 357, in post
    **urlopen_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
OSError: LSAPI: Socket read/write error
```

**Comment by Bibo-Joshi** [comment]
Hi. The long traceback you provided does not match the `SSLError` you first mentioned. Can you provide the correct traceback? Also, do I understand correctly that this doesn't happen always, only on some API calls? If yes, can you see a pattern, e.g. is this error raised only for some specific Bot methods?

**Comment by hypy13** [comment]
@Bibo-Joshi 
hi. thanks

yes this is just happen on reply_text() method
but the trace back is true
i get this traceback
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 483, in send_message
    api_kwargs=api_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 357, in post
    **urlopen_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

**Comment by Bibo-Joshi** [comment]
Hi. This is not a full traceback, though. it should start with `Traceback (most recent call last):`.

The fact that it only happens for `reply_text`/`send_message` is somewhat strange. Otherwise I'd say that it's just some random networking error. Can you tell if this error relibaly *always* happens, when you call `send_message`/`reply_text`? If not, does it e.g. always happen for one specific call of `send_message`/`reply_text`?

**Comment by hypy13** [comment]
@Bibo-Joshi Hi again. sorry for late response

this bot runs on a host
i dont think its about networking error! am i right?


i thisnk this is the complete one


2021-05-16 10:19:13,546  apps.telbot.telegrambot  INFO  Exception while handling an update:
Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 253, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 71, in request
    **urlopen_kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 272, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 602, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/home/rezwanaw/production/apps/telbot/telegrambot.py", line 83, in start
    update.message.reply_text(get_msg('WELCOME', context))
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/message.py", line 715, in reply_text
    entities=entities,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 483, in send_message
    api_kwargs=api_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 357, in post
    **urlopen_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
OSError: LSAPI: Socket read/write error
2021-05-16 10:19:13,546  apps.telbot.telegrambot  INFO  Exception while handling an update:
Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/opt/alt/python37/lib64/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/alt/python37/lib64/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/opt/alt/python37/lib64/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/alt/python37/lib64/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 253, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 71, in request
    **urlopen_kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 272, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 647, in urlopen
    raise SSLError(e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 602, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/home/rezwanaw/production/apps/telbot/telegrambot.py", line 90, in start
    reply_markup=ReplyKeyboardMarkup([list(languages)], resize_keyboard=True)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/message.py", line 715, in reply_text
    entities=entities,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 483, in send_message
    api_kwargs=api_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 357, in post
    **urlopen_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

**Comment by Bibo-Joshi** [comment]
Hi.

> i dont think its about networking error!

It is. It literally says `telegram.error.NetworkError` 😉

Note that you have three different errors in your traceback:

* `telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`
* `OSError: LSAPI: Socket read/write error`
* `telegram.error.NetworkError: urllib3 HTTPError [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)`

Maybe the third one is caused by the second? That one seems related to you host, as it doesn't have a traceback.
Anyway, I don't think there's anything we can do you for here …

**Comment by hypy13** [comment]
hi thanks
i couldnt solve the problem on that
and now i changed the method to POLLING

but getting this error

```
Traceback (most recent call last):
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 602, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/home/rezwanaw/production/apps/telbot/telegrambot.py", line 78, in start_voting
    return start(update, context)
  File "/home/rezwanaw/production/apps/telbot/telegrambot.py", line 98, in start
    update.message.reply_text(get_msg('WELCOME', context))
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/message.py", line 715, in reply_text
    entities=entities,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 483, in send_message
    api_kwargs=api_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 356, in post
    **urlopen_kwargs,
  File "/home/rezwanaw/virtualenv/production/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 271, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Forbidden: bot was blocked by the user
```

**Comment by hypy13** [comment]
ooop 

thanks alot ❤️❤️❤️
