### ISSUE TITLE
[BUG] context.bot.editMessageText causing TypeError: Object of type Message is not JSON serializable

### ISSUE THREAD

**Issue by MaxMatti** [python-telegram-bot/python-telegram-bot#2559]
### Steps to reproduce
1. send message using `item_messages[item_id] = context.bot.send_message(context.job.context["chat_id"], text = printstr)`

2. edit same message using the code seen below in the stack trace

3. Error happens

### Expected behaviour
No exception

### Actual behaviour
Exception, see log below

### Configuration
**Operating System:** Archlinux

**Version of Python, python-telegram-bot & dependencies:**

```
$ python -m telegram
python-telegram-bot 13.6
Bot API 5.2
certifi 2020.12.05
Python 3.9.5 (default, May 24 2021, 12:50:35)  [GCC 11.1.0]
```

### Logs

```
$ ./main.py                              
2021-06-10 20:40:56,075 - apscheduler.scheduler - INFO - Scheduler started
2021-06-10 20:41:05,709 - apscheduler.scheduler - INFO - Added job "27588466" to job store "default"
2021-06-10 20:41:05,710 - apscheduler.scheduler - INFO - Added job "27588466_once" to job store "default"
2021-06-10 20:41:05,710 - apscheduler.executors.default - INFO - Running job "27588466_once (trigger: date[2021-06-10 18:41:05 UTC], next run at: 2021-06-10 18:41:05 UTC)" (scheduled at 2021-06-10 18:41:05.709449+00:00)
2021-06-10 20:41:05,710 - apscheduler.scheduler - INFO - Removed job 87ecb88f55ba41cb9d8397c2d706d4fb
skipping item 20417: no change in item itself.
skipping item 17645: no change in item itself.
skipping item 18944: no change in item itself.
skipping item 83934: no change in item itself.
2021-06-10 20:41:06,392 - apscheduler.executors.default - INFO - Job "27588466_once (trigger: date[2021-06-10 18:41:05 UTC], next run at: 2021-06-10 18:41:05 UTC)" executed successfully
2021-06-10 20:42:05,710 - apscheduler.executors.default - INFO - Running job "27588466 (trigger: interval[0:01:00], next run at: 2021-06-10 18:43:05 UTC)" (scheduled at 2021-06-10 18:42:05.709149+00:00)
skipping item 20417: no change in item itself.
skipping item 17645: no change in item itself.
skipping item 18944: no change in item itself.
skipping item 418399: no change in item itself.
skipping item 83934: no change in item itself.
2021-06-10 20:42:06,250 - apscheduler.executors.default - INFO - Job "27588466 (trigger: interval[0:01:00], next run at: 2021-06-10 18:43:05 UTC)" executed successfully
2021-06-10 20:43:05,709 - apscheduler.executors.default - INFO - Running job "27588466 (trigger: interval[0:01:00], next run at: 2021-06-10 18:44:05 UTC)" (scheduled at 2021-06-10 18:43:05.709149+00:00)
2021-06-10 20:43:06,006 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/mnt/ssd/Syncthing/Projekte/Python/tgtgbot/./main.py", line 185, in notification
    context.bot.editMessageText(text = printstr, chat_id = context.job.context["chat_id"], message_id = item_messages[item_id])
  File "/usr/lib/python3.9/site-packages/telegram/bot.py", line 129, in decorator
    result = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/telegram/bot.py", line 2536, in edit_message_text
    return self._message(
  File "/usr/lib/python3.9/site-packages/telegram/ext/extbot.py", line 198, in _message
    result = super()._message(
  File "/usr/lib/python3.9/site-packages/telegram/bot.py", line 331, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/lib/python3.9/site-packages/telegram/bot.py", line 294, in _post
    return self.request.post(
  File "/usr/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    body=json.dumps(data).encode('utf-8'),
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable
^C2021-06-10 20:43:21,221 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-06-10 20:43:21,221 - apscheduler.scheduler - INFO - Scheduler has been shut down
```
The message in question is one of those two:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/1584478/121580418-03bd2a80-ca2d-11eb-8ebd-0332c380b0b5.png">

**Comment by Bibo-Joshi** [comment]
You're storing the return value of `send_message` in `item_message[item_id]` but that return value is a `Message` object, not the messages id. Hence you're passing that to `edit_message_text` instead of the messages id.
