### ISSUE TITLE
[QUESTION] the correct way to setup job_queue.run_custom()?

### ISSUE THREAD

**Issue by buinguyenhoangtho** [python-telegram-bot/python-telegram-bot#2581]
### Issue I am facing
I want to make my bot send message daily by using cron_expression. But i keep getting Mapping issue ( the log below)

### Traceback to the issue
```log
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    main()
  File "main.py", line 126, in main
    job_queue.run_custom(callback=my_cron_job1,job_kwargs=CronTrigger.from_crontab('* * * * *'),context=None)
  File "/home/hoangtho/.local/lib/python3.8/site-packages/telegram/ext/jobqueue.py", line 487, in run_custom
    j = self.scheduler.add_job(callback, args=self._build_args(job), name=name, **job_kwargs)
TypeError: add_job() argument after ** must be a mapping, not CronTrigger
```

### Related part of your code
```python
"""Job 1: The bot send simple messeage """
def my_cron_job1(update: Update, context: CallbackContext) -> None:
    user = update.effective_user
    chat_id = user.id
    print ("cron job 1")
    bot.send_message(chat_id,"Cron Job success")
def main():

  from apscheduler.schedulers.blocking import BlockingScheduler
  from apscheduler.triggers.cron import CronTrigger
  
   job_queue = updater.job_queue
   job_queue.run_custom(callback=my_cron_job1,job_kwargs=CronTrigger.from_crontab('* * * * *'),context=None)
    
    updater.start_polling()
    updater.idle()
```
I'm alway stuck at here :(. Can't deal with it.

**Comment by starry69** [comment]
You're passing `job_kwargs` incorrectly, `job_kwargs` is a dictionary of arbitrary argument. This should look like:

```python
job_queue.run_custom(callback=my_cron_job1, job_kwargs={"trigger": CronTrigger.from_crontab('* * * * *')} ,context=None)
```

Also remove the `update` argument from you job callback: `my_corn_job1`, since jobqueue calls the job callbacks with only one argument which is `CallbackContext`.

**Comment by buinguyenhoangtho** [comment]
> Also remove the update argument from you job callback: my_corn_job1, since jobqueue calls the job callbacks with only one argument which is CallbackContext.. 


Thanks for your help . It working without update. But i need to use `update` to get my `chat_id`. And if i remove `update` it giving this error log : 
```
021-07-05 18:39:36,244 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2021-07-05 18:39:36,244 - apscheduler.scheduler - INFO - Added job "my_cron_job1" to job store "default"
2021-07-05 18:39:36,244 - apscheduler.scheduler - INFO - Scheduler started
2021-07-05 18:40:00,000 - apscheduler.executors.default - INFO - Running job "my_cron_job1 (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*'], next run at: 2021-07-05 18:40:00 +07)" (scheduled at 2021-07-05 18:40:00+07:00)
2021-07-05 18:40:00,002 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/hoangtho/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "main.py", line 83, in my_cron_job1
    user = update.effective_user
NameError: name 'update' is not defined
```

**Comment by starry69** [comment]
You can pass the chat id via `context` parameter: `jq.run_custom(..., context=chat_id)` and access it in the job callback like: `chat_id = context.job.context`

**Comment by buinguyenhoangtho** [comment]
> You can pass the chat id via `context` parameter: `jq.run_custom(..., context=chat_id)` and access it in the job callback like: `chat_id = context.job.context`


Hmn i start to understand `chat_id = context.job.context`. But i want to use `update.effective_user` to get my chat_id (without show it to the code). But the result it return me as `object` 

```python
def main(update=Update,context=None) -> None:
    """Start the bot."""
    dispatcher.add_handler(CommandHandler("start", start))
 
    user = update.effective_user
    print(user)
    job_queue = updater.job_queue
    job_queue.run_custom(callback=my_cron_job1,job_kwargs={ "trigger" : CronTrigger . from_crontab ( '* * * * *' )},name="ok",context=user) 
    updater.start_polling()
    updater.idle()
```
And my current `cron_job_1`
```python
def my_cron_job1(context: CallbackContext) -> None:
        # print(update.effective_chat.id)
        user = context.job.context
        id_chat = user.id 
        # name = user.username
        print(id_chat)
```
and this interested happend
```
<property object at 0x7fe7e9fddc70> -> Note : This is where i print( user = update.effective_user)
    print(user)
2021-07-05 19:51:35,888 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2021-07-05 19:51:35,889 - apscheduler.scheduler - INFO - Added job "ok" to job store "default"
2021-07-05 19:51:35,889 - apscheduler.scheduler - INFO - Scheduler started
2021-07-05 19:52:00,001 - apscheduler.executors.default - INFO - Running job "ok (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*'], next run at: 2021-07-05 19:52:00 +07)" (scheduled at 2021-07-05 19:52:00+07:00)
2021-07-05 19:52:00,004 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/hoangtho/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "main.py", line 86, in my_cron_job1
    id_chat = user.id 
AttributeError: 'property' object has no attribute 'id'
```

**Comment by buinguyenhoangtho** [comment]
Thanks for helping me. Already solved
