### ISSUE TITLE
No error handlers are registered, logging exception. -> AttributeError: 'NoneType' object has no attribute 'search' ERROR

### ISSUE THREAD

**Issue by doron-yaakobov** [python-telegram-bot/python-telegram-bot#2690]
###
I keep getting this error after trying to integrate a local mongoDB server to my bot.
the same code (with .txt files and sqlite3 DB instead of the mongoDB) works. 

the error: 
```
No error handlers are registered, logging exception. 
Traceback (most recent call last): 
  File "/homes/dorony/DCTelegramBot/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 548, in process_update 
    check = handler.check_update(update) 
  File "/homes/dorony/DCTelegramBot/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 565, in check_update 
    check = entry_point.check_update(update) 
  File "/homes/dorony/DCTelegramBot/lib/python3.7/site-packages/telegram/ext/messagehandler.py", line 196, in check_update 
    return self.filters(update) 
  File "/homes/dorony/DCTelegramBot/lib/python3.7/site-packages/telegram/ext/filters.py", line 233, in call 
    return self.filter(update) 
  File "/homes/dorony/DCTelegramBot/lib/python3.7/site-packages/telegram/ext/filters.py", line 326, in filter 
    comp_output = self.and_filter(update) 
  File "/homes/dorony/DCTelegramBot/lib/python3.7/site-packages/telegram/ext/filters.py", line 198, in call 
    return self.filter(update.effective_message) 
  File "/homes/dorony/DCTelegramBot/lib/python3.7/site-packages/telegram/ext/filters.py", line 639, in filter 
    match = self.pattern.search(message.text) 
AttributeError: 'NoneType' object has no attribute 'search'
```
my code:
https://github.com/doron-yaakobov/DCTelegramBot/tree/MongoDB_integration

**Comment by Bibo-Joshi** [comment]
For completeness: https://t.me/pythontelegrambotgroup/527735
