### ISSUE TITLE
example program timerbot.py bug

### ISSUE THREAD

**Issue by batycoon** [python-telegram-bot/python-telegram-bot#270]
DL'd the newest python-telegram-bot on an Ubuntu Virtual Machine. Tried python example.

`$ cd ~/python-telegram-bot/examples`
`$ python timerbot.py`

Program seemed to properly initiate, the bot responded to `/start` as expected.
Entered `/set 13` expecting to wait 13 seconds- no response. Checking back on terminal yeilded an error:

```
2016-04-29 11:38:22,002 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/telegram/ext/dispatcher.py", line 180, in processUpdate
    handler.handleUpdate(update, self)
  File "build/bdist.linux-i686/egg/telegram/ext/commandhandler.py", line 66, in handleUpdate
    self.callback(dispatcher.bot, update, **optional_args)
TypeError: set() takes exactly 3 arguments (2 given)

```
I dont think it passed the `optional_args`. This seems like a slightly large problem.

Fairly new to developing API, I could have my own knowledge to blame--- just mentioning it now before I start cracking down to edit a program which was just downloaded.

**Comment by jh0ker** [comment]
Thank you, you're right.

**Comment by batycoon** [comment]
Thanks!
