### ISSUE TITLE
[QUESTION] Error editing message (Error 400 - 'Bad Request: MESSAGE_ID_INVALID')

### ISSUE THREAD

**Issue by MacKey-255** [python-telegram-bot/python-telegram-bot#2733]
### Steps to Reproduce

1. Create message with text and simple reply_markup
2. Try to edit it with other text and other reply_markup
3. Error 400 BadRequest :( Message_id_invalid

### Expected behaviour

Edit message success!

### Actual behaviour

Error 400 BadRequest: Message_id_invalid

### Operating System

Linux 5.10.50-amd64-desktop

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.7
python-telegram-bot (13.7)
pytz>=2018.6 (from python-telegram-bot) (2020.1)
tornado>=6.1 (from python-telegram-bot) (6.1)
certifi (from python-telegram-bot) (2019.9.11)
cachetools==4.2.2 (from python-telegram-bot) (4.2.2)
APScheduler==3.6.3 (from python-telegram-bot) (3.6.3)
setuptools>=0.7 (from APScheduler==3.6.3->python-telegram-bot) (51.0.0)
six>=1.4.0 (from APScheduler==3.6.3->python-telegram-bot) (1.10.0)
tzlocal>=1.2 (from APScheduler==3.6.3->python-telegram-bot) (2.0.0)
```

### Relevant log output

```python
Traceback (most recent call last):
  File "bot.py", line X, in _update_ad
    message = bot.edit_message_text(message_id=message_id, chat_id=chat_id, parse_mode=ParseMode.HTML, text=message_body, reply_markup=InlineKeyboardMarkup(keyboard))
  File "my_bot_project/venv/lib/python3.7/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "my_bot_project/venv/lib/python3.7/site-packages/telegram/bot.py", line 2587, in edit_message_text
    api_kwargs=api_kwargs,
  File "my_bot_project/venv/lib/python3.7/site-packages/telegram/bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "my_bot_project/venv/lib/python3.7/site-packages/telegram/bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "my_bot_project/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 361, in post
    **urlopen_kwargs,
  File "my_bot_project/venv/lib/python3.7/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message_id_invalid
```

### Additional Context

The chat_id is hidden channel (Ex: -100000000) where the messages are and I forward ok to other chats but when I edit any message inside the channel, I get error 400 :/ I need help with it!

**Comment by Bibo-Joshi** [comment]
> 1. Create message with text and simple reply_markup
> 2. Try to edit it with other text and other reply_markup
> 3. Error 400 BadRequest :( Message_id_invalid

How is the message created? does the bot send it? does another chaannel admin do that? How exactly do you obtain the `message_id` of the message that you want to edit?

**Comment by MacKey-255** [comment]
> How is the message created? does the bot send it? does another chaannel admin do that? How exactly do you obtain the `message_id` of the message that you want to edit?

Context:
I use a database to store the message_id that I get when I create the message. 

Code:
```
import sys
import time
import traceback

from telegram import InlineKeyboardButton, InlineKeyboardMarkup, ParseMode
from telegram.bot import Bot
from telegram.error import BadRequest

bot_id = 'XXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
hide_channel = '-1000000000000'
delay = 5
message_body = "⚠️⚠️ Lorem ipsum ⚠️⚠️\n " \
               "👉dolor sit amet \n" \
               "👉consectetur adipiscing elit \n" \
               "👉sed do eiusmod tempor incididunt\n" \
               "👉ut labore et dolore magna aliqua.\n" \
               "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
keyboard = [
    [InlineKeyboardButton("🔎 Keyboard", url=None)]
]

bot = Bot(token=bot_id)
database_model = DatabaseModel()

# Publish my message in hide channel
message = bot.send_message(chat_id=hide_channel, parse_mode=ParseMode.HTML, text=message_body,
                           reply_markup=InlineKeyboardMarkup(keyboard), disable_notification=True)

# Save message_id
database_model.save(message.message_id)
# message_id = message.message_id

# Use message_id for forward message
message_id = database_model.get_message_id()
chat_id = '@testing1'
for _ in range(0, 5):
    # It is success
    message_forward = bot.forward_message(chat_id=chat_id, from_chat_id=hide_channel, message_id=int(message_id),
                                          disable_notification=True)
    time.sleep(delay)
    bot.delete_message(chat_id=chat_id, message_id=message_forward.message_id)

# Edit Message in Hide Channel
try:
    message = bot.edit_message_text(message_id=message_id, chat_id=str(hide_channel), parse_mode=ParseMode.HTML,
                                    text=message_body + '\n Hello World!', reply_markup=InlineKeyboardMarkup(keyboard))

    # Save message_id
    database_model.save(message.message_id)
except BadRequest as ex:
    # Failed (Error 400 - MESSAGE_ID_INVALID)
    print(f'Error Editing message: {str(ex)}')
    traceback.print_exc(file=sys.stdout)
```
