### ISSUE TITLE
timeout when start_polling with clean=True

### ISSUE THREAD

**Issue by shouya** [python-telegram-bot/python-telegram-bot#275]
code to reproduce the problem:

```python
updater = Updater(token=xxx)
updater.start_polling(clean=True)
```

error output:
```
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    main()
  File "main.py", line 34, in main
    updates = bot.getUpdates()
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 114, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 1315, in getUpdates
    result = request.post(url, data, timeout=urlopen_timeout)
  File "/usr/local/lib/python3.5/site-packages/telegram/utils/request.py", line 83, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
telegram.error.NetworkError: URLError: _ssl.c:629: The handshake operation timed out
```

```
$ pip3 list | grep telegram
python-telegram-bot (4.0.3)
```

I'll fire a PR to fix this later.

**Comment by jh0ker** [comment]
#282 hopefully fixed this issue - if the issue persists in the next release (or current github master), please re-open :)
