### ISSUE TITLE
[DOCS] Installation failure (cryptography/cffi dependency)

### ISSUE THREAD

**Issue by hackery** [python-telegram-bot/python-telegram-bot#2794]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Platform: Debian 9 (stretch) Python 3.5.3.

Installing fails if package `cryptography` is not already installed - it seems to have a dependency on `cffi` but doesn't install it as a dep:

```
jmb@artie:~/src$ pip3 install python-telegram-bot --upgrade
Collecting python-telegram-bot
  Using cached https://files.pythonhosted.org/packages/cc/b3/f363e9c5c2e4690a1fd352c01263eb2938952888c09d73c824b49d288dcc/python_telegram_bot-13.1-py3-none-any.whl
Collecting cryptography (from python-telegram-bot)
  Using cached https://files.pythonhosted.org/packages/94/5c/42de91c7fbdb817b2d9a4e64b067946eb38a4eb36c1a09c96c87a0f86a82/cryptography-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'cffi' (maybe misspelled?)
    No local packages or working download links found for cffi!=1.11.3,>=1.8
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tx7tnzwh/cryptography/setup.py", line 122, in <module>
        "src/_cffi_src/build_padding.py:ffi",
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True, 
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in easy_install
        raise DistutilsError(msg) 
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi!=1.11.3,>=1.8')
```
Similar message appears using just `pip3 install cryptography`.

### Describe the solution you'd like

Docs addition:
Try installing `cffi` (and maybe `cryptography`) separately before PTB.

```
jmb@artie:~$ pip3 install cffi
Collecting cffi
  Downloading https://files.pythonhosted.org/packages/00/9e/92de7e1217ccc3d5f352ba21e52398372525765b2e0c4530e6eb2ba9282a/cffi-1.15.0.tar.gz (484kB)
    100% |████████████████████████████████| 491kB 1.3MB/s
Collecting pycparser (from cffi)  
  Downloading https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 3.7MB/s
Building wheels for collected packages: cffi
  Running setup.py bdist_wheel for cffi ... done
  Stored in directory: /home/jmb/.cache/pip/wheels/52/4b/d4/af20f7da0f464f24f1ce5ccfe0a5c3a5fd0c1aed518cd652de
Successfully built cffi
Installing collected packages: pycparser, cffi
Successfully installed cffi-1.15.0 pycparser-2.21
```

**Comment by harshil21** [comment]
hi, we've made `cryptography` an optional dependency and pinned its version since [`v13.3`](https://github.com/python-telegram-bot/python-telegram-bot/releases/tag/v13.3). My guess is that your `pip` is installing an older version of our library (13.1) because your python version is not supported by us. We support python versions 3.6.8 and above.

**Comment by hackery** [comment]
Righto, looks like this is the latest Python available on this distro ... time to suck up the pain of remotely upgrading the VM again. 🦺
