### ISSUE TITLE
How can I  get pictures from Bot users ?

### ISSUE THREAD

**Issue by yous6637** [python-telegram-bot/python-telegram-bot#2828]
### Issue I am facing

I run this code to get pictures from bot users but I get error

```python
   from telegram import update,Update
    from telegram.ext.callbackcontext import CallbackContext
    from telegram.ext.messagehandler import MessageHandler
    from telegram.ext import (
    Updater,
    CommandHandler,
    CallbackQueryHandler,
    filters)
    from io import BytesIO
    import numpy as np
    updater = Updater("TOKEN",use_context=True)
    def start(update:Update,context:CallbackContext):
         update.message.reply_text('Upload your image:')
    def Photo(update,context):
    
    
        file = context.bot.get_file(update.message.photo[-1].file_id)
        f = BytesIO(file.download_as_bytearray)
        file_bytes = np.asarray(bytearray(f.read(), dtype=np.uint8))

   updater.dispatcher.add_handler(CommandHandler('start', start))
   updater.dispatcher.add_handler(MessageHandler(filters.Filters.document.mime_type("image/jpeg"), Photo))
   updater.start_polling()
   updater.idle()
```

### Traceback to the issue

```python
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\STAR-PRO-X\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\STAR-PRO-X\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "c:\Users\STAR-PRO-X\Documents\GitHub\Python-Telegram-Bot\Exprts\Sketch bot\main.py", line 23, in Photo
    file = context.bot.get_file(update.message.photo[-1].file_id)
IndexError: list index out of range
```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by Poolitzer** [comment]
Hi, your handler listens to a [document](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.document), and you apparently send a document because you get the error, but the "get photo" part is not for a document, its for a normal photo.

What you want to use for a document is

```python
file = context.bot.get_file(update.message.document.file_id)
```

or you can use the shortcuts from this library.

```python
file = update.message.document.get_file()
```
