### ISSUE TITLE
telegram.error.NetworkError: URLError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#283]
Hi
In python2 : 
`
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160409] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import telegram
>>> bot = telegram.Bot(token="234157057:AAFCH-PCGa1x1jHYHUFtMIoYT*********")
>>> print(bot.getMe())
{'username': u'********Bot', 'first_name': u'*******Bot', 'last_name': '', 'type': '', 'id': XXXXXXXX}
>>> bot.getUpdates()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ali/.local/lib/python2.7/site-packages/telegram/bot.py", line 114, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ali/.local/lib/python2.7/site-packages/telegram/bot.py", line 1315, in getUpdates
    result = request.post(url, data, timeout=urlopen_timeout)
  File "/home/ali/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 83, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
telegram.error.NetworkError: URLError: [Errno 101] Network is unreachable`

in python3
`Python 3.5.1+ (default, Jan 13 2016, 15:09:18) 
[GCC 5.3.1 20160101] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import telegram
>>> bot = telegram.Bot(token="234157057:AAFCH-PCGa1x1jHYHUFtMIoY*************")
>>> print(bot.getMe())
{'id': XXXXXXXXXX, 'last_name': '', 'type': '', 'first_name': '******Bot', 'username': '*******Bot'}
>>> bot.getUpdates()
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1229, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ali/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 63, in decorator
    return func(*args, **kwargs)
  File "/home/ali/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 154, in post
    result = urlopen(request, **urlopen_kwargs).read()
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ali/.local/lib/python3.5/site-packages/telegram/bot.py", line 114, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ali/.local/lib/python3.5/site-packages/telegram/bot.py", line 1315, in getUpdates
    result = request.post(url, data, timeout=urlopen_timeout)
  File "/home/ali/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 83, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
telegram.error.NetworkError: URLError: [Errno 101] Network is unreachable
`

I unset all proxy in my env and there is no problem in python having access to network : 
`
>>> def internet_on():
    try:
        response=urllib2.urlopen('https://api.telegram.org/bot234157057:AAFCH-PCGa1x1jHYHUFtMIoYT31********/getUpdates',timeout=1)
        return True
    except urllib2.URLError as err: pass
    return False

>>> internet_on()
True
`

**Comment by alirezaimi** [comment]
I solved it with set timeout param to something other than 0.

**Comment by hiquer** [comment]
Hello,
I'm having the same problem with telegram script, however I need to use the proxy.
I'm breaking my head rsrs.

Script:
=================================================
#!/usr/bin/env python

import telebot,sys

BOT_TOKEN='MYTOKEN'
DESTINATION=sys.argv[1]
SUBJECT=sys.argv[2]
MESSAGE=sys.argv[3]

MESSAGE = MESSAGE.replace('/n','\n')

tb = telebot.TeleBot(BOT_TOKEN)
tb.send_message(DESTINATION,SUBJECT + '\n' + MESSAGE, disable_web_page_preview=True, parse_mode='HTML')

=================================================

Error message:
=================================================
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/telegram_notification.py", line 13, in <module>
tb.send_message(DESTINATION,SUBJECT + '\n' + MESSAGE, disable_web_page_preview=True, parse_mode='HTML')
File "build/bdist.linux-x86_64/egg/telebot/__init__.py", line 599, in send_message
File "build/bdist.linux-x86_64/egg/telebot/apihelper.py", line 141, in send_message
File "build/bdist.linux-x86_64/egg/telebot/apihelper.py", line 54, in _make_request
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 419, in send
raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot600892207:AAEp-2UOfZMPOadmQ6_H7xkpWJJA4XDJqWo/sendMessage?text=%2310.6.40.2+-+Firewall+Arquivo+Publico%3A+Memory+usage+too+high+PROBLEM%0AValue%3A+1.68+GB+PROBLEM%0D%0ADate%3A+2019.03.27+Time%3A+09%3A01%3A07&parse_mode=HTML&chat_id=-359189210&disable_web_page_preview=True (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f474432e410>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
=================================================

**Comment by tsnoam** [comment]
@hiquer This stacktrace refers to a different library. Therefore I'm deleting your comment.
