### ISSUE TITLE
[QUESTION] How to set parameters for BOT_COMMAND_SCOPE_CHAT_MEMBER

### ISSUE THREAD

**Issue by Happy-Ferret** [python-telegram-bot/python-telegram-bot#2847]
### Issue I am facing

This is really confusing.
According to the docs, `BOT_COMMAND_SCOPE_CHAT_MEMBER` takes parameters `chat_id` and `user_id`.
However, BOT_COMMAND_SCOPE_CHAT_MEMBER appears to be a mere string constant.

I'm trying to create bot commands for a group owner only, but using the scope like this obviously fails.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "main.py", line 281, in <module>
    main()
  File "main.py", line 231, in main
    utils.bot.set_my_commands(list(OwnerCommands.values()), scope=BotCommandScope(telegram.constants.BOT_COMMAND_SCOPE_CHAT_MEMBER(chat_id="", user_id="")))
TypeError: 'str' object is not callable
```

### Related part of your code

```python
utils.bot.set_my_commands(list(OwnerCommands.values()), scope=BotCommandScope(telegram.constants.BOT_COMMAND_SCOPE_CHAT_MEMBER(chat_id="", user_id="")))
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.9
Bot API 5.5
certifi 2021.10.08
Python 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
```

**Comment by Bibo-Joshi** [comment]
Hi.

[`telegram.BotCommandScopeChatMember`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.botcommandscopechatmember.html) is a class and a subclass of [`telegram.BotCommandScope`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.botcommandscope.html). The [`type`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.botcommandscopechatmember.html#telegram.BotCommandScopeChatMember.type) of `BotCommandScopeChatMember` instances is the constant string value of [`telegram.constants.BOT_COMMAND_SCOPE_ALL_CHAT_ADMINISTRATORS`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.constants.html#telegram.constants.BOT_COMMAND_SCOPE_ALL_CHAT_ADMINISTRATORS).

What you'll need is `telegram.BotCommandScopeChatMember(chat_id=…, user_id=…)`

**Comment by Bibo-Joshi** [comment]
Well, there's also [`BotCommandScopeChatAdministrators`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.botcommandscopechatadministrators.html#telegram.BotCommandScopeChatAdministrators) if that suits your use case. See also the [official docs](https://core.telegram.org/bots/api#botcommandscope)

**Comment by Happy-Ferret** [comment]
> Well, there's also [`BotCommandScopeChatAdministrators`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.botcommandscopechatadministrators.html#telegram.BotCommandScopeChatAdministrators) if that suits your use case. See also the [official docs](https://core.telegram.org/bots/api#botcommandscope)

I'm already using that one. Thanks.

I needed a way to narrow the scope further.

My bot's command scopes are: __Bot DMs__, __Group Members__, __Group Admins__ and __Group Owner__.

**Comment by Bibo-Joshi** [comment]
Then that's probably the way to go, yes

**Comment by Happy-Ferret** [comment]
Actually, one more question in that regard.

What's the difference between `BOT_COMMAND_SCOPE_ALL_CHAT_ADMINISTRATORS` and `BOT_COMMAND_SCOPE_CHAT_ADMINISTRATORS`?

**Comment by Happy-Ferret** [comment]
Oh. I think I see it now.
One is universal, the other is group specific so one could have different scopes for different groups.
