### ISSUE TITLE
[BUG] Job execution fails with error related to thread lock

### ISSUE THREAD

**Issue by anarchist912** [python-telegram-bot/python-telegram-bot#2863]
### Steps to Reproduce

Create job in job_queue according to run_once example in [Docs](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue
)

```python
from telegram.ext import Updater

u = Updater('TOKEN', use_context=True)
j = u.job_queue

def callback_30(context: telegram.ext.CallbackContext):
    context.bot.send_message(chat_id='@examplechannel', 
                             text='A single message with 30s delay')

j.run_once(callback_30, 30)
```

### Expected behaviour

Job is executed without error

### Actual behaviour

Error is thrown, job not executed.

### Operating System

Xubuntu 21.10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.10
Bot API 5.6
certifi 2021.10.08
Python 3.9.7 (default, Sep 10 2021, 14:59:43)  [GCC 11.2.0]
```

### Relevant log output

```python
2022-01-15 15:22:26,538 - apscheduler.scheduler - INFO - Added job "delete_job" to job store "default"

2022-01-15 15:22:27,384 - apscheduler.scheduler - ERROR - Error submitting job "delete_job (trigger: date[2022-01-15 14:22:27 UTC], next run at: 2022-01-15 14:22:27 UTC)" to executor "default"
Traceback (most recent call last):
  File "/NWOzqCVf/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 974, in _process_jobs
    executor.submit_job(job, run_times)
  File "/NWOzqCVf/lib/python3.9/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/NWOzqCVf/lib/python3.9/site-packages/apscheduler/executors/pool.py", line 22, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

2022-01-15 15:22:27,387 - apscheduler.scheduler - INFO - Removed job dbc37dd0c58b46e3a5562baad52932ec
```

### Additional Context

The error is thrown in concurrent.futures.thread module:

```python
def submit(self, fn, /, *args, **kwargs):
        with self._shutdown_lock, _global_shutdown_lock:
            if self._broken:
                raise BrokenThreadPool(self._broken)

            if self._shutdown:
                raise RuntimeError('cannot schedule new futures after shutdown')
            if _shutdown:
                raise RuntimeError('cannot schedule new futures after '
                                   'interpreter shutdown')

            f = _base.Future()
            w = _WorkItem(f, fn, args, kwargs)

            self._work_queue.put(w)
            self._adjust_thread_count()
            return f
```

As far as I understand the _shutdown is set to True here only (top of the thread module):

```python
def _python_exit():
    global _shutdown
    with _global_shutdown_lock:
        _shutdown = True
    items = list(_threads_queues.items())
    for t, q in items:
        q.put(None)
    for t, q in items:
        t.join()

# Register for `_python_exit()` to be called just before joining all
# non-daemon threads. This is used instead of `atexit.register()` for
# compatibility with subinterpreters, which no longer support daemon threads.
# See bpo-39812 for context.
threading._register_atexit(_python_exit)
```

But you never know with global variables.

**Comment by anarchist912** [comment]
Similar "reported" here: https://stackoverflow.com/questions/70673175/runtimeerror-cannot-schedule-new-futures-after-interpreter-shutdown. Cannot confirm whether it is python-telegram-bot involved. Only talks about a Telegram bot.

**Comment by Poolitzer** [comment]
Hi, the issue is not with a python version, but with you/the job queue trying to run a job when the interpreter was never properly started. This happens in the library with `.start_webhook/polling` and then running `.idle()`. So to fix your code you'd need to add it like
```
import telegram

from telegram.ext import Updater

u = Updater('TOKEN', use_context=True)
j = u.job_queue


def callback_30(context: telegram.ext.CallbackContext):
    context.bot.send_message(chat_id='@examplechannel',
                             text='A single message with 30s delay')


j.run_once(callback_30, 5)
u.start_polling()
u.idle()
```

**Comment by anarchist912** [comment]
So I was just missing the idle() call. This fixes it. Thank you very much!
