### ISSUE TITLE
[QUESTION] SOCKS5 Support

### ISSUE THREAD

**Issue by chrisyang2003** [python-telegram-bot/python-telegram-bot#2902]
### Steps to Reproduce

here is my code

```
from telegram import Update
from telegram.ext import Updater, CallbackContext, CommandHandler


TOKEN = ''

def start(update: Update, context: CallbackContext):
    context.bot.send_message(chat_id=update.effective_chat.id, text="I'm a bot, please talk to me!")



if __name__ == '__main__':
    updater = Updater(token=TOKEN, request_kwargs={'proxy_url': 'socks5://127.0.0.1:7890/'})
    dispatcher = updater.dispatcher
    start_handler = CommandHandler('start', start)
    dispatcher.add_handler(start_handler)
    updater.start_polling()
```

### Expected behaviour

goes well

### Actual behaviour

i install the last version of urllib3, i  don't where the problem is
```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 342, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 352, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "C:\Python39\lib\ssl.py", line 416, in match_hostname
    raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname 'api.telegram.org' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\telegram\utils\request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 68, in request    return self.request_encode_body(method, url, fields=fields,
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 647, in urlopen
    raise SSLError(e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.SSLError: ("hostname 'api.telegram.org' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com'",)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10179\Desktop\tgBot\main.py", line 17, in <module>
    updater.start_polling()
  File "C:\Python39\lib\site-packages\telegram\ext\updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "C:\Python39\lib\site-packages\telegram\ext\updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 369, in id
    return self.bot.id
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 363, in bot
    self._bot = self.get_me()
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 450, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "C:\Python39\lib\site-packages\telegram\utils\request.py", line 361, in post
    result = self._request_wrapper(
  File "C:\Python39\lib\site-packages\telegram\utils\request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ("hostname 'api.telegram.org' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com'",)
```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Please make sure that you have installed the required dependencies for socks-support as detailed in the [readme](https://github.com/python-telegram-bot/python-telegram-bot#optional-dependencies).
Please note that PTB uses a vendored version of urllib3 instead of the upstream one - which can be seen from the traceback as well:

> `File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py"`

**Comment by chrisyang2003** [comment]
yeah,i had install the dependencies `python-telegram-bot[socks]`, but still the problem
```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\telegram\utils\request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 68, in request    return self.request_encode_body(method, url, fields=fields,
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python39\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 647, in urlopen
    raise SSLError(e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10179\Desktop\tgBot\main.py", line 17, in <module>
    updater.start_polling()
  File "C:\Python39\lib\site-packages\telegram\ext\updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "C:\Python39\lib\site-packages\telegram\ext\updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 369, in id
    return self.bot.id
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 363, in bot
    self._bot = self.get_me()
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 450, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Python39\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "C:\Python39\lib\site-packages\telegram\utils\request.py", line 361, in post
    result = self._request_wrapper(
  File "C:\Python39\lib\site-packages\telegram\utils\request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:1129)   
```
