### ISSUE TITLE
[QUESTION] _pickle.UnpicklingError: odd number of items for SETITEMS

### ISSUE THREAD

**Issue by sharath-dev** [python-telegram-bot/python-telegram-bot#2903]
### Issue I am facing

Hey,

I'm having this issue with PicklePersistence. Every time I start the bot the bot is unable to load the pickle file and it throws me an error saying

 `_pickle.UnpicklingError: odd number of items for SETITEMS`

I have to delete the Pickle file that is being created to get the bot to start again, but eventually the error shows up again.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/EPass-telegram-bot/main.py", line 171, in main
    updater = Updater(Auth.API_TOKEN, persistence=persistence)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/updater.py", line 297, in __init__
    self.dispatcher = Dispatcher(
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 265, in __init__
    self.user_data = self.persistence.get_user_data()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/basepersistence.py", line 136, in get_user_data_insert_bot
    return instance.insert_bot(get_user_data())
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 235, in get_user_data
    self._load_singlefile()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 186, in _load_singlefile
    raise TypeError(f"File {filename} does not contain valid pickle data") from exc
TypeError: File conversationbot does not contain valid pickle data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 172, in _load_singlefile
    data = pickle.load(file)
_pickle.UnpicklingError: odd number of items for SETITEMS

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/EPass-telegram-bot/main.py", line 171, in main
    updater = Updater(Auth.API_TOKEN, persistence=persistence)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/updater.py", line 297, in __init__
    self.dispatcher = Dispatcher(
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 265, in __init__
    self.user_data = self.persistence.get_user_data()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/basepersistence.py", line 136, in get_user_data_insert_bot
    return instance.insert_bot(get_user_data())
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 235, in get_user_data
    self._load_singlefile()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 186, in _load_singlefile
    raise TypeError(f"File {filename} does not contain valid pickle data") from exc
TypeError: File conversationbot does not contain valid pickle data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 172, in _load_singlefile
    data = pickle.load(file)
_pickle.UnpicklingError: odd number of items for SETITEMS

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/EPass-telegram-bot/main.py", line 171, in main
    updater = Updater(Auth.API_TOKEN, persistence=persistence)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/updater.py", line 297, in __init__
    self.dispatcher = Dispatcher(
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 265, in __init__
    self.user_data = self.persistence.get_user_data()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/basepersistence.py", line 136, in get_user_data_insert_bot
    return instance.insert_bot(get_user_data())
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 235, in get_user_data
    self._load_singlefile()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/picklepersistence.py", line 186, in _load_singlefile
    raise TypeError(f"File {filename} does not contain valid pickle data") from exc
TypeError: File conversationbot does not contain valid pickle data
```

### Related part of your code

```python
def main() -> None:
    """Run the bot."""
    # Create the Updater and pass it your bot's token.
    persistence = PicklePersistence(filename=TelegramConstants.PRESISTANCE_FILENAME)
    updater = Updater(Auth.API_TOKEN, persistence=persistence)
    
    update = telegram.update.Update.de_json(request.get_json(force=True), bot)

    # Get the dispatcher to register handlers
    dispatcher = updater.dispatcher

    # Add conversation handler with the states CHOOSING, TYPING_CHOICE and TYPING_REPLY
    conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],
        states={
               ...
         },
        fallbacks=[MessageHandler((Filters.regex('^Exit$') | Filters.regex('^exit$')), done)],
        name="my_conversation",
        persistent=True,
        allow_reentry = True
    )

    dispatcher.add_handler(conv_handler)

    show_data_handler = CommandHandler('show_data', show_data)
    dispatcher.add_handler(show_data_handler)

    dispatcher.process_update(update)

    return 'OK'
```

### Operating System

Ubuntu 20.04.2 LTS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
Python 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
```

**Comment by Amal-David** [comment]
I'm facing the same issue, it works fine when tested locally but when deployed on a server it breaks in the middle.

**Comment by harshil21** [comment]
Hello, thanks for the issue.

Is it possible to give a [minimal working example](https://github.com/python-telegram-bot/python-telegram-bot/wiki/MWE) for this?

We'd like to know what is being saved and why this error happens when the data is loaded.
