### ISSUE TITLE
[BUG] bot instance unable to send message to private channel

### ISSUE THREAD

**Issue by ouzkagan** [python-telegram-bot/python-telegram-bot#2910]
### Steps to Reproduce

After adding bot to private channel as admin I was unable to send message with bot instance. **I tried with official api and it worked.**

1. get channel id from forwarded message
```
channel_id = update.message.forward_from_chat.id
print(channel_id)
```
prints: 
```bash
-10015040*****
```
2. send message to channel with bot
```
# bot = Bot(token='token123')
sent_msg = bot.send_message(channel_id, text="example")
```
3. Chat not found error
```bash
telegram.error.BadRequest: Chat not found
```

While it's possible to send message via official api by: 
https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id=-10015040*****&text=example

### Expected behaviour

It should send text

### Actual behaviour

telegram.error.BadRequest: Chat not found

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
```

### Relevant log output

```python
2022-02-19 17:06:35,033 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "C:\Users\oguzkagan\Desktop\coding\bot\conversationbot2.py", line 346, in screen_source_expect_post_channel
    user_data = db.User(username=username,post_channels=post_channels,chat_id=chat_id).__dict__
NameError: name 'chat_id' is not defined
2022-02-19 17:07:23,991 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
    sent_msg = bot.send_message(channel_id, text="deneme")
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\bot.py", line 130, in decorator    result = func(*args, **kwargs)
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\bot.py", line 336, in _message 
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\bot.py", line 295, in _post    
    return self.request.post(
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\utils\request.py", line 361, in post
    result = self._request_wrapper(
  File "C:\Users\oguzkagan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found
```

### Additional Context

I just used official api with requests library to create this function and **it works** as expected:
```
def send_message_to_private(chat_id, text):
    api = f'https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={chat_id}&text={text}'
    response = requests.get(api).json()
    return  response
```

**Comment by Bibo-Joshi** [comment]
Hi. Since we thoroughly unit test the Bot methods, I would be highly surprised if they would yield different results that manual requests to the API. Can you please double check that you passed the same token and chat_id to `Bot` and `bot.send_message` that you used to build the query URL (`api.telegram.org/...`)?
If this doesn't help, please provide a [minimal working example](../wiki/MWE) so that we can try & reproduce the issue.

**Comment by ouzkagan** [comment]
Yes. It seems since I run 2 several bots they mixed up. after separating them it solved. Sorry for mistake.
