### ISSUE TITLE
TypeError: start() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2938]
### Issue I am facing

Hello!

I am trying to replicate your echo bot example with a few modifications but it does not work. As soon as I send the /start message (or any other message) i get the error "TypeError: start() takes 2 positional arguments but 3 were given".

what I did is take all the def blocks in your example and put them in a class, instanced it, and tried to run it... the bot stats, and awaits messages, but as soon as I send a message it crashes.

### Traceback to the issue

```python
Scheduler started
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
TypeError: start() takes 2 positional arguments but 3 were given
```

### Related part of your code

```python
# Enable logging
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO
)

logger = logging.getLogger(__name__)

....

class main():
    self.telegram = cTelegram()
    self.telegram.run()


class cTelegram():
    def start(update: Update, context: CallbackContext) -> None:
        """Send a message when the command /start is issued."""
        user = update.effective_user
        update.message.reply_markdown_v2(
            fr'Hi {user.mention_markdown_v2()}\!',
            reply_markup=ForceReply(selective=True),
        )

    def help_command(update: Update, context: CallbackContext) -> None:
        """Send a message when the command /help is issued."""
        update.message.reply_text('Help!')

    def echo(update: Update, context: CallbackContext):
        """Echo the user message."""
        update.message.reply_text(update.message.text)

    def run(self):
        updater = Updater(token='xxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxx', use_context=True)
        dispatcher = updater.dispatcher
        dispatcher.add_handler(CommandHandler("start", self.start))
        dispatcher.add_handler(CommandHandler("help", self.help_command))

        dispatcher.add_handler(MessageHandler(Filters.text, self.echo))
        updater.start_polling()
        updater.idle()
```

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hi. Since you put the methods in a class, self will be given to the methods as the first parameter. So you would need to add `self,` as the first parameter to each function and it will work.

**Comment by tanzerlana** [comment]
that did the trick! thank you very much!! :)
