### ISSUE TITLE
App crashes crashes

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2943]
### Issue I am facing

Hi all,

I am having an issue I am not able to understand. I have my app with the bot, and trying to send an image with the code below. sometimes it sends one, and then on the next image 20 seconds later the app crashes with the error code below...

The internet connection is stable, so that is not the reason.

Code:

```
    def sendImage(self, im0, depot, score, classname):
        im0rgb = im0[:, :, ::-1]
        # convert numpy array to Pil image
        PIL_image = Image.fromarray(im0rgb.astype('uint8'), 'RGB')
        # convert pil image to byte stream
        image_stream = BytesIO()
        PIL_image.save(image_stream, format="PNG")
        image_stream.seek(0)
        # prepare text message
        text = depot + '\n\nScore: ' + f'{score:0.2f}' + '\nRec. crate: ' + classname
        self.bot.send_photo(-720329337, image_stream, text)
```

Error:

```
Traceback (most recent call last):
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1067, in _send_output
    self.send(chunk)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 989, in send
    self.sock.sendall(data)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1003, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 70, in request
    **urlopen_kw)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1067, in _send_output
    self.send(chunk)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 989, in send
    self.sock.sendall(data)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1003, in send
    return self._sslobj.write(data)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\yolov5\CrateVision\TelegramClass.py", line 35, in sendImage
    self.bot.send_photo(-720329337, image_stream, text)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 738, in send_photo
    protect_content=protect_content,
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "C:\Users\video\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out'))
```

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
This likely just means that the image is too large/your internet connection too slow such that the image is not completely transmitted to TG after the default timeout of 20s. Please have a look at [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors) for more details.

**Comment by tanzerlana** [comment]
@Bibo-Joshi thank you for your answer. I doubt that this can be the case in this situation. we have a 500 mbit industrial fiber connection and the image is 640x640 pixel.. just a few kb in size...

**Comment by Bibo-Joshi** [comment]
Well, the error message is "The write operation timed out" and the traceback clearly says that this is caused by a call to `send_photo`. So there must be some cause for the request taking so long. Anyway, not minding the cause you can still try to increase the timeout - either only for that call via the parameter of `send_photo` or globally as explained in the wiki page above.

**Comment by tanzerlana** [comment]
Thank you! will try it right away... Do you know how i can catch this? should I put the send_photo in a try: except? just to be sure that if there is no internet the app doesnt crash?

**Comment by Bibo-Joshi** [comment]
If you're using the `Dispatcher` to process updates, errors in callbacks won't terminate the process - see also [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling). But sure, you can try-except `send_photo` if you want to handle errors directly where you call that method

**Comment by tanzerlana** [comment]
Thank you! I will give it a read and try both variations..
