### ISSUE TITLE
Intallation issue:  IndexError: list index out of range

### ISSUE THREAD

**Issue by zyma** [python-telegram-bot/python-telegram-bot#297]
```
  Using cached pyterminalsize-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\<local_user>\appdata\local\temp\pip-build-as_7k0\pyterminalsize\setup.py", line 13, in <module>
        vs = sorted(versions, key=lambda s: int(re.search('\d+', s).group()))[-1]
    IndexError: list index out of range

```

**Comment by rahiel** [comment]
What are you doing? The command to install python-telegram-bot is
```pip install python-telegram-bot```

We do not depend on pyterminalsize.

**Comment by zyma** [comment]
http://c2n.me/3yfggVz

**Comment by rahiel** [comment]
You do not need to install the dependencies from `requirements-dev.txt` to use the library. Try again with just `pip install python-telegram-bot`

**Comment by zyma** [comment]
fine, works 
thanks

please remove it from your documentation 

Install dependencies:
$ pip install -r requirements.txt -r requirements-dev.txt

**Comment by yerzhanserikbay** [comment]
pip3 install python-telegram-bot

Collecting python-telegram-bot
  Using cached python_telegram_bot-9.0.0-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 664, in _prepare_file
    dist = abstract_dist.dist(finder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 110, in dist
    self.req_to_install.source_dir))[0]
IndexError: list index out of range


Please, help me. in Google is nothing

**Comment by yerzhanserikbay** [comment]
Actually, I can't install anything :(
