### ISSUE TITLE
[BUG] Errors when stopping bot with CTRL-C

### ISSUE THREAD

**Issue by super22n** [python-telegram-bot/python-telegram-bot#3006]
### Issue I am facing

When I stop the bot by pressing CTRL-C, I get several errors printed out. This didn't happen with the older version of python-telegram-bot.
The errors can be seen in the traceback. Do I need to catch those errors in the error handler?

### Traceback to the issue

```python
^C2022-05-07 15:46:38,842 - telegram.ext._updater - ERROR - Error while getting Updates: Unknown error in HTTP implementation: CancelledError()
Update None caused error Unknown error in HTTP implementation: CancelledError()
2022-05-07 15:46:38,842 - telegram.ext._application - ERROR - An error was raised and an uncaught error was raised while handling the error with an error_handler.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/python_telegram_bot-20.0a0-py3.7.egg/telegram/ext/_application.py", line 1445, in process_error
    await callback(update, context)
TypeError: object NoneType can't be used in 'await' expression
2022-05-07 15:46:39,844 - telegram.ext._application - INFO - Application is stopping. This might take a moment.
2022-05-07 15:46:39,845 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-05-07 15:46:39,856 - telegram.ext._application - INFO - Application.stop() complete
```

### Related part of your code

```python
import logging
from telegram import Update
from telegram.ext import Application, CallbackContext, CommandHandler

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

def error(update, context):
        print(f"Update {update} caused error {context.error}")

async def start(update: Update, context: CallbackContext.DEFAULT_TYPE):
    await context.bot.send_message(chat_id=update.effective_chat.id, text="I'm a bot, please talk to me!")

if __name__ == '__main__':
    application = Application.builder().token('TOKEN').build()
    start_handler = CommandHandler('start', start)
    application.add_handler(start_handler)
    application.add_error_handler(error)
    application.run_polling()
```

### Operating System

Debian 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a0
Bot API 6.0
Python 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for the well-written report!

I can indeed reproduce the issue. THe problem is that `asyncio.CancelledError` is a subclass of `Exception` in py3.7 instead of `BaseException` (which is the case in py3.8+). so `except Exception` will catch `asyncio.CancelledError` while we usually don't want that.
I pushed a potential fix to [this branch](https://github.com/python-telegram-bot/python-telegram-bot/tree/ctrl-c-py3.7). Could you check if this improves the behavior for you? To test that, please do the following:

1. Uninstall PTB (`pip uninstall python-telegram-bot -y`)
2. install PTB from that branch (`pip install git+https://github.com/python-telegram-bot/python-telegram-bot.git@ctrl-c-py3.7`)
3. run your script & hit CTRL + C

BTW the error 

```python
2022-05-07 15:46:38,842 - telegram.ext._application - ERROR - An error was raised and an uncaught error was raised while handling the error with an error_handler.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/python_telegram_bot-20.0a0-py3.7.egg/telegram/ext/_application.py", line 1445, in process_error
    await callback(update, context)
TypeError: object NoneType can't be used in 'await' expression
```

is in fact due to a bug in your code snippet: error handlers also need to be coroutine functions in v20, so it should be `async def error(update, context):` 🙂

**Comment by super22n** [comment]
I have tested, and it seems to be solved, I get no more errors when pressing CTRL-C.

**Comment by Bibo-Joshi** [comment]
Nice 👍 I'll open a PR then
