### ISSUE TITLE
[QUESTION] ImportError and confusion with 'python-telegram-bot' and 'telegram' package

### ISSUE THREAD

**Issue by T1mS22** [python-telegram-bot/python-telegram-bot#3083]
### Issue I am facing

Hey, my bot worked but while looking around i did install the 'telegram' package too. I do not use it for my bot. But my code stopped working and throw an Error:
ImportError: cannot import name 'Animation' from 'telegram' (unknown location)

So i tried removing this package again with `pip uninstall telegram` and ran my code but same error came up again.
Tried `pip uninstall telegram` again. Now giving me: 'WARNING: Skipping telegram as it is not installed.' and still the ImportError in my code.
`pip list` only shows me 'python-telegram-bot' as well

Is there another way to fully remove a the false 'telegram' package or is there another fix for it?

Thanks for help.
T1m

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/home/pi/pi-status-bot/raspicontrol.py", line 1, in <module>
    from telegram.ext import Updater, CommandHandler
  File "/home/pi/.local/lib/python3.9/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .extbot import ExtBot
  File "/home/pi/.local/lib/python3.9/site-packages/telegram/ext/extbot.py", line 24, in <module>
    import telegram.bot
  File "/home/pi/.local/lib/python3.9/site-packages/telegram/bot.py", line 56, in <module>
    from telegram import (
ImportError: cannot import name 'Animation' from 'telegram' (unknown location)
```

### Operating System

Raspbian GNU/Linux 11

### Version of Python, python-telegram-bot & dependencies

```shell
Python: 3.9.2
python-telegram-bot 13.12
```

**Comment by T1mS22** [comment]
Fixed it by reinstalling the 'python-telegram-bot' package.
