### ISSUE TITLE
All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.[QUESTION]

### ISSUE THREAD

**Issue by silsuer** [python-telegram-bot/python-telegram-bot#3087]
### Issue I am facing

My bot always stops after running for a few minutes

it throws an exception:  All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.

I try to set builder: 
```
builder.connection_pool_size(50000)
builder.get_updates_connection_pool_size(50000)
builder.pool_timeout(100)
builder.get_updates_pool_timeout(100)
```

But it doesn't seem to work

How do I fix it ?

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/ext/_application.py", line 945, in process_update
    await coroutine
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/ext/_handler.py", line 135, in handle_update
    return await self.callback(update, context)
  File "/www/wwwroot/bot3/basic_bot.py", line 106, in private_message_handler
    await self.message_handler(d)
  File "/www/wwwroot/bot3/bot.py", line 1042, in handle_telegram_msg
    await handle_hot_rank_message(chat_id, msg['text'])
  File "/www/wwwroot/bot3/bot.py", line 1851, in handle_hot_rank_message
    await bot.sendMessage(chat_id, html, parse_mode='MarkdownV2', reply_markup=options)
  File "/www/wwwroot/bot3/basic_bot.py", line 66, in sendMessage
    reply_to_message_id=reply_to_message_id)
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/_bot.py", line 238, in decorator
    result = await func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/_bot.py", line 649, in send_message
    protect_content=protect_content,
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/ext/_extbot.py", line 265, in _send_message
    protect_content=protect_content,
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/_bot.py", line 353, in _send_message
    api_kwargs=api_kwargs,
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/_bot.py", line 316, in _post
    pool_timeout=pool_timeout,
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/request/_baserequest.py", line 167, in post
    pool_timeout=pool_timeout,
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/request/_baserequest.py", line 279, in _request_wrapper
    raise exc
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/request/_baserequest.py", line 276, in _request_wrapper
    pool_timeout=pool_timeout,
  File "/usr/local/python3/lib/python3.7/site-packages/telegram/request/_httpxrequest.py", line 190, in do_request
    ) from err
telegram.error.TimedOut: Pool timeout: All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.
```

### Related part of your code

```python
builder = Application.builder()
        builder.token(self.token)
        if self.proxy_url != "":
            builder.proxy_url(self.proxy_url)
            builder.get_updates_proxy_url(self.proxy_url)
        builder.connection_pool_size(50000)
        builder.get_updates_connection_pool_size(50000)
        builder.pool_timeout(100)
        builder.get_updates_pool_timeout(100)
        self.application = builder.build()
        echo_handler = MessageHandler(filters.ALL, self.private_message_handler)
        callback_query_handler = CallbackQueryHandler(self.private_callback_query_handler)
        self.application.add_handler(echo_handler)
        self.application.add_handler(callback_query_handler)
```

### Operating System

CentOS

### Version of Python, python-telegram-bot & dependencies

```shell
python3.7.2
python-telegram-bot   20.0a0
```

**Comment by Bibo-Joshi** [comment]
Hi. That's certainly not expected to happen … Let's try to find out the exact cause.

1. Can you show the full traceback? there should be more to it, specifically you should see something like `httpx.PoolTimeout: … This error was the direct cause of:… `
2. Are you using `block=False`, `(context.)application.create_task(bot.some_method(…))`, or `asyncio.create_task`? Are you making bot methods calls in jobs via the `JobQueue`?
3. can you give a rough estimate of how many updates your bot handlers (per second/minute/hour) and how many requests it makes to TG per second?
4. We can also try to add a counter to do_request so that we see the exact number at which you get the exception. I've modified the implementation of `HTTPXRequest` slightly at https://nekobin.com/nozuqiviro.py. You can either edit `"/usr/local/python3/lib/python3.7/site-packages/telegram/request/_httpxrequest.py"` directly or use `builder.request(instance_of_the_modified_class)` to use that class. you can ofc also convert the prints into log statements or similar. Please run your bot with this modifications and capture the prints/logs.

**Comment by silsuer** [comment]
Our previous project used telepot,But it is no longer maintained. So we want to use python-telegra-bot to make minimal changes to the project.

The telepot API:  `bot.sendMessage()...`, It doesnt have Context.

We create a global class for this.

```
class TelegramBot:
    token = ""
    proxy_url = ""
    message_handler = None
    callback_query_handler = None
    applicationBuilder = None
    application = None

    def __init__(self, token):
        self.token = token

    def set_proxy_url(self, proxy_url):
        self.proxy_url = proxy_url

    def message_handler(self, handler):
        self.message_handler = handler

    def callback_query_handler(self, handler):
        self.callback_query_handler = handler

    async def kickChatMember(self, chat_id, user_id, until_date=None):
        await self.application.bot.ban_chat_member(chat_id, user_id, until_date=None)

    async def editMessageText(self, info, text, parse_mode=None, reply_markup=None, disable_web_page_preview=None):
        return await  self.application.bot.edit_message_text(text, chat_id=info[0], message_id=info[1],
                                                             parse_mode=parse_mode,
                                                             reply_markup=reply_markup,
                                                             disable_web_page_preview=disable_web_page_preview)

    async def deleteMessage(self, chat_id, message_id, delay=0):
            await  self.application.bot.delete_message(chat_id, message_id)

    async def sendPhoto(self, chat_id, photo, parse_mode=None, caption=None, reply_markup=None,
                        reply_to_message_id=None):
        m = await self.application.bot.send_photo(chat_id, photo, caption=caption, parse_mode=parse_mode,
                                                  reply_to_message_id=reply_to_message_id, reply_markup=reply_markup,
                                                  )
        return m

    async def sendMessage(self, chat_id, text, disable_web_page_preview=False, parse_mode=None, reply_markup=None,
                          reply_to_message_id=None):
        m = await self.application.bot.send_message(chat_id, text, parse_mode=parse_mode,
                                                    disable_web_page_preview=disable_web_page_preview,
                                                    reply_markup=reply_markup,
                                                    reply_to_message_id=reply_to_message_id)
        return m

    async def private_callback_query_handler(self, update: Update, context: CallbackContext):
        j = json.loads(update.to_json())
        # print(j["callback_query"])
        if self.callback_query_handler is not None:
            await self.callback_query_handler(j["callback_query"])

    def format_update_message_from(self, from_dict):
        d = {
            "id": from_dict.id,
            "is_bot": from_dict["is_bot"],
            "first_name": from_dict["first_name"],
            "username": from_dict["username"],
            "language_code": from_dict["language_code"]
        }
        return d

    def format_update_message(self, message):
        if message is None:
            return {}
        d = {
            "message_id": message.message_id,
            "from": self.format_update_message_from(message["from"]),
            "chat": {
                "id": message["chat"].id,
                "first_name": message["chat"]["first_name"],
                "username": message["chat"]["username"],
                "type": str(message["chat"]["type"].name).lower(),
            },
            "date": int(round(message["date"].timestamp())),
            "text": message["text"]
        }
        return d

    async def private_message_handler(self, update: Update, context: CallbackContext.DEFAULT_TYPE):
        d = self.format_update_message(update.message)
        if self.message_handler is not None:
            await self.message_handler(d)

    def build(self):
        builder = Application.builder()
        builder.token(self.token)
        if self.proxy_url != "":
            builder.proxy_url(self.proxy_url)
            builder.get_updates_proxy_url(self.proxy_url)
        builder.connection_pool_size(50000)
        builder.get_updates_connection_pool_size(50000)
        builder.pool_timeout(100)
        builder.get_updates_pool_timeout(100)
        self.application = builder.build()
        echo_handler = MessageHandler(filters.ALL, self.private_message_handler)
        callback_query_handler = CallbackQueryHandler(self.private_callback_query_handler)
        self.application.add_handler(echo_handler)
        self.application.add_handler(callback_query_handler)

    def run_forever(self):
        self.build()
        self.application.run_polling()
```

Then create a global bot:
```
    bot = TelegramBot('TEST_TOKEN')
    bot.message_handler(handle_telegram_msg)
    bot.callback_query_handler(on_callback_query)
    bot.run_forever()
```

All business callback function `message_handler`, no context. The global bot object is application.bot.

Then change the original business code: `await bot.sendMessage()`

We dont use `JobQueue` or Something

**Comment by Bibo-Joshi** [comment]
Sorry, but your code snippet doesn't really answer my questions - You only said that you don't use `JobQueue`.
