### ISSUE TITLE
[BUG] when the codes run in the docker, get the Error of InvalidToken

### ISSUE THREAD

**Issue by oldjerry** [python-telegram-bot/python-telegram-bot#3163]
### Steps to Reproduce

The codes is doing well in the local, but can't run in the docker, the Error was InvalidToken

1. codes
```
TOKEN='XXXXX'
updater = Updater(token=TOKEN, base_url=f"{API_URL}bot", base_file_url=f"{API_URL}file/bot")
```

2. Dockerfile
```
# syntax=docker/dockerfile:1

FROM python:3.9-slim-buster

ENV LANG en_US.utf8

ADD ./myBot /code

WORKDIR /code

RUN pip3 install -r requirements.txt

CMD [ "python3", "myBot.py"]
```

### Expected behaviour

`2022-07-22 13:13:32,246 - INFO - Scheduler started`

### Actual behaviour

```
Traceback (most recent call last):
 TOKEN: 'XXXXX'  # print token
  File "myBot.py", line 32, in <module>
    updater = Updater(token=TOKEN, base_url=f"{API_URL}/bot", base_file_url=f"{API_URL}/file/bot")
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/updater.py", line 279, in __init__
    self.bot = ExtBot(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/extbot.py", line 99, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 194, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 358, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

### Operating System

Ubuntu, Docker

### Version of Python, python-telegram-bot & dependencies

```shell
3.8, 3.9
```

**Comment by Bibo-Joshi** [comment]
Hi. Have you double checked with botfather if the token is correct? what is `API_URL`? Are you using a local bit API server? If so, does the same token work when using the standard server? What happens if you modify PTB to not call `_validate_token`?

**Comment by oldjerry** [comment]
> Hi. Have you double checked with botfather if the token is correct? what is `API_URL`? Are you using a local bit API server? If so, does the same token work when using the standard server? What happens if you modify PTB to not call `_validate_token`?

HI. Yes I checked. When I tried a fake token in local server, I got an error "telegram.error.Unauthorized: Unauthorized", but I got the error "File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 358, in _validate_token raise InvalidToken()" both with the real and fake token.

it just happened at first when I created an updater

updater = Updater(token=TOKEN, base_url="https://api.telegram.org/bot", base_file_url="https://api.telegram.org/file/bot")

**Comment by Bibo-Joshi** [comment]
Please edit 

```
File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 194, in __init__
    self.token = self._validate_token(token)
```

to `self.token = token` and report on what happens then.

**Comment by oldjerry** [comment]
I got more errors as follows

`Traceback (most recent call last):
  File "/code/pikpakTgBot.py", line 942, in <module>
    updater.start_polling()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 373, in id
    return self.bot.id
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 367, in bot
    self._bot = self.get_me()
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 454, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 234, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 176, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 186, in connection_from_context
    pool_key_constructor = self.key_fn_by_scheme[scheme]
KeyError: "'https"`

**Comment by Bibo-Joshi** [comment]
please try just with `Updater(token=TOKEN)`, without the `base(_file)_url`.

**Comment by oldjerry** [comment]
Thanks again.
