### ISSUE TITLE
[QUESTION] httpx Network Error

### ISSUE THREAD

**Issue by PaulCardLord** [python-telegram-bot/python-telegram-bot#3188]
### Issue I am facing

I tried running the bot on different servers. Including on the local machine. I also tried different versions of this library. But still sometimes network errors fall.
As a rule, all bots crash with an error at the same time (I have 2 servers with several running bots). Apparently the reason is on the telegram server. Can I specify a generic handler for this type of error?

### Traceback to the issue

```python
1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 552, in _network_loop_retry
    if not await action_cb():
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 314, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 303, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 283, in get_updates
    updates = await super().get_updates(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 238, in decorator
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 3678, in get_updates
    await self._post(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 310, in _post
    return await request.post(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 160, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 279, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 269, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 195, in do_request
    raise NetworkError(f"httpx HTTPError: {err}") from err
telegram.error.NetworkError: httpx HTTPError: All connection attempts failed


2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 552, in _network_loop_retry
    if not await action_cb():
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 314, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 303, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 283, in get_updates
    updates = await super().get_updates(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 238, in decorator
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 3678, in get_updates
    await self._post(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 310, in _post
    return await request.post(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 160, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 279, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 269, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 195, in do_request
    raise NetworkError(f"httpx HTTPError: {err}") from err
telegram.error.NetworkError: httpx HTTPError: All connection attempts failed
Error while getting Updates: httpx HTTPError: All connection attempts failed
No error handlers are registered, logging exception.
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable
----------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('149.154.167.220', 443)
```

### Related part of your code

```python
application = Application.builder().token(TOKEN).build()
application.add_handler(handler)
# add handlers...
application.run_polling()
```

### Operating System

Ubuntu 18.04.6 LTS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot==20.0a0
sentry-sdk==1.5.0
psycopg2==2.8.6
geopy==2.2.0
sqlalchemy==1.4.35

python3.8
```

**Comment by harshil21** [comment]
Have a look at [Handling Network Errors](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors) & [errorhandlerbot.py](https://docs.python-telegram-bot.org/en/v20.0a2/examples.html#examples-errorhandlerbot)

Also upgrading to a2 is recommended (`pip install python-telegram-bot --pre -U`)
