### ISSUE TITLE
[QUESTION] How to use bots in test environment?

### ISSUE THREAD

**Issue by EugeneLoy** [python-telegram-bot/python-telegram-bot#3191]
### Issue I am facing

[This documentation](https://core.telegram.org/bots/webapps#using-bots-in-the-test-environment) describes how to set up test environment.
However, when passing test environment bot token to `Updater` I am getting `telegram.error.Unauthorized: Unauthorized` error when sending `/start` to the bot.
How to properly use `python-telegram-bot` with test environment?

### Traceback to the issue

```python
Traceback (most recent call last):
  File "C:\Users\Leo\workspace\telegram-webapp-test\main.py", line 87, in <module>
    updater.start_polling()
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\ext\updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\ext\updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\bot.py", line 372, in id
    return self.bot.id
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\bot.py", line 366, in bot
    self._bot = self.get_me()
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\bot.py", line 453, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\bot.py", line 298, in _post
    return self.request.post(
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\utils\request.py", line 361, in post
    result = self._request_wrapper(
  File "C:\Users\Leo\workspace\telegram-webapp-test\venv\lib\site-packages\telegram\utils\request.py", line 277, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized

Process finished with exit code 1
```

### Related part of your code

```python
if __name__ == '__main__':
    updater = Updater(
        token="test environment bot token here"
    )

    def on_start(update: Update, context: CallbackContext):
        ...

    def on_callback_query(update: Update, context: CallbackContext):
        ...

    updater.dispatcher.add_handler(CommandHandler("start", on_start))
    updater.dispatcher.add_handler(CallbackQueryHandler(on_callback_query))

    updater.start_polling()
```

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.13
Bot API 6.1
certifi2022.06.15
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
```

**Comment by harshil21** [comment]
Unfortunately, PTB doesn't support bots in the test environment. We may add support for this in the future.

Meanwhile, if modifying the source code locally is an option for you, you can modify these lines

https://github.com/python-telegram-bot/python-telegram-bot/blob/2ae3d4d63cefd2c84bcf76601342ba8b499a1e0e/telegram/bot.py#L212-L213

to add `/test`. And then it should work.

**Comment by EugeneLoy** [comment]
Thanks. I appended `/test` to token itself and it *seems* to work (at least for my minimal example). Native test env support would be great though.
