### ISSUE TITLE
[BUG] Arbitrary callback data does not dereference callback data even though it is configured properly

### ISSUE THREAD

**Issue by Rustem** [python-telegram-bot/python-telegram-bot#3194]
### Steps to Reproduce

1. Setup
```
persistence = PicklePersistence(
            filename='arbitrarycallbackdatabot.pickle', store_callback_data=True
        )
        self.updater = Updater(token=telegram_token, persistence=persistence, arbitrary_callback_data=True)
```
2. 

### Expected behaviour

it should dereference callback data with simple id and store it in pickled cache. 
The request should return 200 OK instead of 400

### Actual behaviour

throws telegram.error.BadRequest: Button_data_invalid because `callback_data` size is greater than 65 bytes

from http debug logs:

```
send: b'{"chat_id": "616312662", "text": "\\nHere is your activities:\\n1. Math\\n", "reply_markup": "{\\"inline_keyboard\\": [[{\\"callback_data\\": \\"{\\\\\\"pagination_token\\\\\\": \\\\\\"eebf148ec5ee2f332261c7d508fc0cb512cfcd45c9\\\\\\", \\\\\\"page\\\\\\": 1}\\", \\"text\\": \\"1\\"}]]}"}'
```

### Operating System

MAC OS Monterey 12.4

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.10
python-telegram-bot==13.13
```

### Relevant log output

```python
{'inline_keyboard': [[{'callback_data': '{"pagination_token": "eebf148ec5ee2f332261c7d508fc0cb512cfcd45c9", "page": 1}', 'text': '1'}]]}
send: b'POST /bot5332711805:AAElPbG7bvZMYxCwaHlv0r_MgcADjTovYvg/sendMessage HTTP/1.1\r\nHost: api.telegram.org\r\nAccept-Encoding: identity\r\nContent-Length: 257\r\nContent-Type: application/json\r\nconnection: keep-alive\r\nuser-agent: Python Telegram Bot (https://github.com/python-telegram-bot/python-telegram-bot)\r\n\r\n'
send: b'{"chat_id": "616312662", "text": "\\nHere is your activities:\\n1. Math\\n", "reply_markup": "{\\"inline_keyboard\\": [[{\\"callback_data\\": \\"{\\\\\\"pagination_token\\\\\\": \\\\\\"eebf148ec5ee2f332261c7d508fc0cb512cfcd45c9\\\\\\", \\\\\\"page\\\\\\": 1}\\", \\"text\\": \\"1\\"}]]}"}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Server: nginx/1.18.0
header: Date: Sun, 14 Aug 2022 07:53:02 GMT
header: Content-Type: application/json
header: Content-Length: 78
header: Connection: keep-alive
header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
header: Access-Control-Allow-Origin: *
header: Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
ERROR 2022-08-14 07:53:01,895 - An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 569, in process_update
    self.dispatch_error(update, exc)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/tgbot/core/base_bot.py", line 51, in _error_handler
    raise error_context.error
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/tgbot/core/base_bot.py", line 58, in wrapper
    handler(context)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/tgbot/core/decorators.py", line 43, in wrapper
    fn(self, ctx, *args, **kwargs)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/tgbot/core/decorators.py", line 21, in wrapper
    cmd_func(base_bot, context)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/tgbot/core/happy_rabbit.py", line 112, in cmd_show_activities
    self.message_sender.send_message_for_context(context,
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/tgbot/core/message_sender.py", line 20, in send_message_for_context
    context.message.reply_text(text, reply_markup=kwargs['reply_markup'])
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/message.py", line 912, in reply_text
    return self.bot.send_message(
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/Users/rustem/code/src/kz-geekabitz-happy-rabbit/happy-rabbit-venv/lib/python3.10/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid

```
```


### Additional Context

_No response_

**Comment by Rustem** [comment]
@harshil21  lemme know please what could be the issue? I also tried setting callback data to 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' (more than 64 bytes) and it fails with the same reason under the same settings. This is just to make sure that issue is in data length and callback data not dereferencing.

**Comment by Bibo-Joshi** [comment]
Please provide an [mwe](https://github.com/python-telegram-bot/python-telegram-bot/wiki/MWE). Also please don't mention people unless you're directly replying to them.

**Comment by Rustem** [comment]
Thanks. Actually I was incorrectly implementing custom ReplyMarkup. I thought to_duct is enough but not. However instead of core to throw an error or capture a log, it just proceed silently without dereferencing  callback data with id. I ll prepare MWE but this particular bug I opened can be closed now.

**Comment by Bibo-Joshi** [comment]
Please note that callback data only works with `InlineKeyboardButton` & `InlineKeyboardMarkup`, not with `KeyboardButton` & `ReplyKeyboardMarkup`. Also you should pass actual instances of `InlineKeyboardButton` & `InlineKeyboardMarkup` instead of manually `to_dict`-ing them. Anyway, I'll close this issue. Feel free to open a new one with an MWE that describes the problem that you have.

**Comment by Rustem** [comment]
Thank you @Bibo-Joshi
