### ISSUE TITLE
[QUESTION] How to change the message after the bot sends it？

### ISSUE THREAD

**Issue by flyzstu** [python-telegram-bot/python-telegram-bot#3207]
### I am new to python-telegram-bot. One problem hit me when I was creating a bot. I don't know how to change the message the bot has sent.

![image](https://user-images.githubusercontent.com/94161727/187016763-43cbd7b0-c30d-42a4-b475-16315ed432fc.png)

**I would appreciate if someone could help me or give me an example**

### Traceback to the issue

```python
C:\Users\wf09\miniconda3\python.exe C:/Users/wf09/Desktop/telegram-bot/main.py 
2022-08-27 13:41:33,064 - apscheduler.scheduler - INFO - Scheduler started
2022-08-27 13:41:33,064 - telegram.ext._application - INFO - Application started
2022-08-27 13:41:39,908 - telegram.ext._application - ERROR - An error was raised and an uncaught error was raised while handling the error with an error_handler.
Traceback (most recent call last):
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\ext\_application.py", line 945, in process_update
    await coroutine
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\ext\_handler.py", line 135, in handle_update
    return await self.callback(update, context)
  File "C:\Users\wf09\Desktop\telegram-bot\main.py", line 39, in hello
    await update.message.edit_text("hello2")
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\_message.py", line 2159, in edit_text
    return await self.get_bot().edit_message_text(
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\_bot.py", line 238, in decorator
    result = await func(*args, **kwargs)
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\_bot.py", line 3338, in edit_message_text
    return await self._send_message(
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\ext\_extbot.py", line 253, in _send_message
    result = await super()._send_message(
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\_bot.py", line 346, in _send_message
    result = await self._post(
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\_bot.py", line 310, in _post
    return await request.post(
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\request\_baserequest.py", line 160, in post
    result = await self._request_wrapper(
  File "C:\Users\wf09\miniconda3\lib\site-packages\telegram\request\_baserequest.py", line 319, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message can't be edited
```

### Related part of your code

```python
async def hello(update: Update, context: CallbackContext.DEFAULT_TYPE) -> None:
    await update.message.reply_text("hello1")
    await update.message.edit_text("hello2") # wanna to change "hello1" to "hello2"

bot_builder = ApplicationBuilder().token(BOT_TOKEN)
app = bot_builder.build()

app.add_handler(CommandHandler("hello", hello))

app.run_polling(stop_signals=None)
```

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a0
Bot API 6.0
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
```

**Comment by tech-fever** [comment]
hope it works:
```python3
msg_to_edit = await update.message.reply_text("hello1")
await msg_to_edit.edit_text("hello2")
```

**Comment by Bibo-Joshi** [comment]
Closing due to inactivity
