### ISSUE TITLE
[BUG] socks5 proxy raises "unhashable type: 'bytearray'"

### ISSUE THREAD

**Issue by JamzumSum** [python-telegram-bot/python-telegram-bot#3211]
### Steps to Reproduce

1. Use a socks5 proxy:
```py
# ... construct a builder
proxy = "socks5://localhost:1234"
builder = builder.proxy_url(proxy).get_updates_proxy_url(proxy)
```
2. initialize the app
3. error occurs in `initialize` (actually, in the first request sent behind proxy)

### Expected behaviour

socks5 proxy works as expected

### Actual behaviour

Using socks5 proxy will trigger an error in `get_me` called by `initialize`,
while **http proxy works well.**

### Operating System

windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4 (0.2.12.dev1-24-gc012470)
Bot API 6.2
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
```

### Relevant log output

```python
Traceback (most recent call last):
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\request\_baserequest.py", line 271, in _request_wrapper
    code, payload = await self.do_request(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\request\_httpxrequest.py", line 174, in do_request
    res = await self._client.request(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpx\_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpx\_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpx\_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpx\_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 290, in handle_async_request
    raise exc
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 238, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 93, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\socksio\socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\socksio\socks5.py", line 262, in loads
    addr=decode_address(AddressType.from_socks5_atype(atype), data[4:-2]),
TypeError: unhashable type: 'bytearray'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Documents\CODE_ROOT\aioqzone\Qzone3TG\src\qzone3tg\__main__.py", line 29, in main
    await app.run()
  File "E:\Documents\CODE_ROOT\aioqzone\Qzone3TG\src\qzone3tg\app\interact.py", line 187, in run
    await self.app.initialize()
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\ext\_application.py", line 339, in initialize
    await self.bot.initialize()
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\ext\_extbot.py", line 227, in initialize
    await super().initialize()
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\_bot.py", line 403, in initialize
    await self.get_me()
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\ext\_extbot.py", line 1525, in get_me
    return await super().get_me(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\_bot.py", line 242, in decorator
    result = await func(*args, **kwargs)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\_bot.py", line 564, in get_me
    result = await self._post(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\_bot.py", line 303, in _post
    return await self._do_post(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\ext\_extbot.py", line 301, in _do_post
    return await self.rate_limiter.process_request(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\ext\_aioratelimiter.py", line 245, in process_request
    return await self._run_request(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\ext\_aioratelimiter.py", line 201, in _run_request
    return await callback(*args, **kwargs)
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\_bot.py", line 334, in _do_post
    return await request.post(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\request\_baserequest.py", line 162, in post
    result = await self._request_wrapper(
  File "e:\Documents\CODE_ROOT\aioqzone\Qzone3TG\.venv\lib\site-packages\telegram\request\_baserequest.py", line 287, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {repr(exc)}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: TypeError("unhashable type: 'bytearray'")
```

### Additional Context

- socksio version: 1.0.0
- There's a discussion in `httpx` with the same error [httpx #2035](https://github.com/encode/httpx/discussions/2305), but might not help.

**Comment by Bibo-Joshi** [comment]
Thanks for the report. I guess the main question here is whether this is a bug in PTB or in httpx … Could you maybe try to check if making a manual request with httpx works better? If it does, we must have a look at what PTB does wrong. If it doesn't one can at least provide an MWE for [encode/httpx#2035](https://github.com/encode/httpx/discussions/2305) :D  BTW I see that you're using the new `AIORateLimiter` - does the same behavior occur if you skip that? Did/does it work better on v20.0a{0, 1, 2}?

**Comment by JamzumSum** [comment]
> Thanks for the report. I guess the main question here is whether this is a bug in PTB or in httpx … Could you maybe try to check if making a manual request with httpx works better? If it does, we must have a look at what PTB does wrong. If it doesn't one can at least provide an MWE for [encode/httpx#2035](https://github.com/encode/httpx/discussions/2305) :D BTW I see that you're using the new `AIORateLimiter` - does the same behavior occur if you skip that? Did/does it work better on v20.0a{0, 1, 2}?

Well, there is nothing wrong with `AIORateLimiter`. 
I've tried to request in `httpx` and it raises the same exception:

```py
async def test_socks5_proxy():
    async with AsyncClient(proxies="socks5://localhost:7890") as client:
        r = await client.post(f"https://api.telegram.org/bot{token}/getMe")    # TypeError
        r.raise_for_status()
```

I'll add a reply under [encode/httpx#2035](https://github.com/encode/httpx/discussions/2305).

**Comment by Bibo-Joshi** [comment]
As this is reproducable with httpx alone, I'll close this for now. If the result of the discussion over at httpx is that PTB can improve anything, please do reach out again :)
