### ISSUE TITLE
[BUG] Timeout on sending huge local file via `open()` even after set the write timeout to `None`

### ISSUE THREAD

**Issue by brainwo** [python-telegram-bot/python-telegram-bot#3288]
### Steps to Reproduce

1. Set write timeout to None 
```py
app = ApplicationBuilder().token(token).write_timeout(
        None).get_updates_write_timeout(None).build()`
# ...
app.run_polling(write_timeout=None)
```
2. Use one of the send command (`send_document`, `send_audio`, `send_video`, ..) on huge file: `context.bot.send_document(chat_id=id, document=open('file', 'rb')`
3. Still got a timeout error

### Expected behaviour

Based on the trace, it should be an error on write timeout (`httpx.WriteTimeout`) so changing `write_timeout` to bigger number or set it to `None` should fix it

### Actual behaviour

Still got the error on ~10 secs the command running, no matter what configuration used:
- Increase write timeout
- Set write timeout to None
- Increase read timeout
- Set read timeout to None
- Increase connection timeout
- Set `app.run_polling(timeout=9999999)`

### Operating System

Linux 5.19

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
```

### Relevant log output

```python
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 49, in write
    await self._stream.send(item=buffer)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 202, in send
    await self._call_sslobject_method(self._ssl_object.write, item)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 168, in _call_sslobject_method
    await self.transport_stream.send(self._write_bio.read())
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1307, in send
    await self._protocol.write_event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 48, in write
    with anyio.fail_after(timeout):
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 105, in handle_async_request
    raise exc
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 75, in handle_async_request
    await self._send_request_body(**kwargs)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 128, in _send_request_body
    await self._send_event(event, timeout=timeout)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 137, in _send_event
    await self._network_stream.write(bytes_to_send, timeout=timeout)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 47, in write
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.WriteTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 174, in do_request
    res = await self._client.request(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in      handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.WriteTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 1002, in process_update
    await coroutine
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/ext/_handler.py", line 137, in handle_update
    return await self.callback(update, context)
  File "/home/brian/git/embeddertg/embeddertg/__main__.py", line 33, in youtube
    await context.bot.send_document(chat_id=update.message.chat_id, document=output)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 2042, in send_document
    return await super().send_document(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 242, in decorator
    result = await func(*args, **kwargs)
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 1233, in send_document
    return await self._send_message(  # type: ignore[return-value]
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 449, in _send_message
    result = await super()._send_message(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 371, in _send_message
    result = await self._post(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 303, in _post
    return await self._do_post(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 281, in _do_post
    return await super()._do_post(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 334, in _do_post
    return await request.post(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 162, in post
    result = await self._request_wrapper(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 285, in _request_wrapper
    raise exc
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 271, in _request_wrapper
    code, payload = await self.do_request(
  File "/home/brian/.cache/pypoetry/virtualenvs/embeddertg-m1gYEhvl-py3.10/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 191, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

**Comment by harshil21** [comment]
Hey,

Did you also set the `write_timeout` to None in file sending methods like `send_document`? Because [by default](https://docs.python-telegram-bot.org/en/doc-fixes/telegram.bot.html#telegram.Bot.send_document.params.write_timeout), the `write_timeout` is set to `20`.

**Comment by brainwo** [comment]
@harshil21 yes that was the issue! Thank you. I was completely missed that when reading [this](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors)
