### ISSUE TITLE
telegram.error.BadRequest: Chat not found  problem

### ISSUE THREAD

**Issue by jenya7** [python-telegram-bot/python-telegram-bot#3298]
### Issue I am facing

in bot.py

```python
import telegram

bot = telegram.Bot("MY_API_ID")

def bot_send_text(text):
        bot.send_message(text, MY_CHAT_ID) 
```

in main.py

```python
bot_send_text('Hello from control board')
````

I get

```python
Traceback (most recent call last):
  File "/home/pi/SysScripts/main.py", line 13, in <module>
    bot_send_text('Hello from AgroLogic')
  File "/home/pi/SysScripts/bot.py", line 15, in bot_send_text
    bot.send_message(text, 123456789) 
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 534, in send_message
    protect_content=protect_content,
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 299, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 366, in post
    **urlopen_kwargs,
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found 
```

MY_API_ID and MY_CHAT_ID are validated.

What do I do wrong?

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.7
```

**Comment by jenya7** [comment]
Oh...Sorry.
As I see it's mandatory to name the arguments implicitly 
bot.send_message(text = text, chat_id = MY_CHAT_ID)
