### ISSUE TITLE
IncompleteRead exception

### ISSUE THREAD

**Issue by pyankoff** [python-telegram-bot/python-telegram-bot#330]
Hi, I'm having the following error when sending document. Error happens intermittently once in a few hundred calls of `sendDocument`. Happens on both ubuntu and mac os. Seems exactly like #153  

**Version of Python:**
`Python 3.5.1`

**Version of python-telegram-bot:**
`4.2.1`
### Logs

```
Traceback (most recent call last):
  File "gifs.py", line 29, in <module>
    document=gif[0])
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/utils/request.py", line 71, in decorator  
    message = _parse(error.read())
  File "/home/ubuntu/anaconda3/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/http/client.py", line 440, in read
    return self._readall_chunked()
  File "/home/ubuntu/anaconda3/lib/python3.5/http/client.py", line 550, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(0 bytes read)
```

Thank you!

**Comment by giuscri** [comment]
`gifs.py` is code you wrote, right?

Could you please post the line that contains `document=gif[0])` — plus the variable used such as the `gif` list?

**Comment by pyankoff** [comment]
Sure, `gif` is a tuple i'm getting from database where `gif[0]` is a gif url. So the code is:
```
m = tlg.sendDocument(document='https://31.media.tumblr.com/5fe79527c438e87ee1589754e454ad7a/tumblr_nr0xuomYVF1uqy5dho1_250.gif',
chat_id=chat_id)
```

**Comment by tsnoam** [comment]
@pyankoff 
with v4.3 we switched to urllib3 for the underlying HTTP(s) communication.
so:
1. the above exception should not be seen anymore. (but another might)
2. can you try to reproduce with the new version?

**Comment by tsnoam** [comment]
closing as no reply received.
