### ISSUE TITLE
[BUG]Failed to upload an audio file.

### ISSUE THREAD

**Issue by DahaWong** [python-telegram-bot/python-telegram-bot#3307]
### Steps to Reproduce

Upload a small audio file (about 3MB) using `bot.send_audio(open(file_path, 'rb'))`.

### Expected behaviour

The audio file should be sent successfully.

### Actual behaviour

Got `Invalid server response` error message, then I printed out the payload, it says `413 Request Entity Too Large`. But the file is actually small.

I've also tried uploading an audio file with `bot.send_audio(file_path)`, and it was sent successfully. However, audio metadata like duration and thumbnail lost in this way. So I wonder if using `open(...)` as `audio` arg could recognize metadata properly...

And, sending photos in a similar way(`bot.send_photo(open(...))`) won't get this error.

### Operating System

Linux (CentOS 8)

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.10.7 (main, Sep 20 2022, 21:33:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]
```

### Relevant log output

```python
Traceback (most recent call last):
  File "/home/daha/project/castpod/helpers.py", line 28, in parse_json_payload
    print(json.loads(decoded_s))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 903, in __create_task_callback
    return await coroutine
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/ext/_handler.py", line 137, in handle_update
    return await self.callback(update, context)
  File "/home/daha/project/castpod/castpod/callbacks/message.py", line 248, in download_episode
    raise e
  File "/home/daha/project/castpod/castpod/callbacks/message.py", line 226, in download_episode
    audio_msg = await message.reply_audio(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/_message.py", line 1143, in reply_audio
    return await self.get_bot().send_audio(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 1902, in send_audio
    return await super().send_audio(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 242, in decorator
    result = await func(*args, **kwargs)
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 1090, in send_audio
    return await self._send_message(  # type: ignore[return-value]
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 449, in _send_message
    result = await super()._send_message(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 371, in _send_message
    result = await self._post(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 303, in _post
    return await self._do_post(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 281, in _do_post
    return await super()._do_post(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 334, in _do_post
    return await request.post(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 162, in post
    result = await self._request_wrapper(
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 293, in _request_wrapper
    response_data = self.parse_json_payload(payload)
  File "/home/daha/project/castpod/helpers.py", line 32, in parse_json_payload
    raise TelegramError("Invalid server response") from exc
telegram.error.TelegramError: Invalid server response
```

### Additional Context

I'm using local Bot API with `--local` enabled, by the way.

**Comment by Bibo-Joshi** [comment]
Hi. Your traceback looks like you are using a custom logic for JSON en-/decoding. What happens if you use the built-in solution of PTB?

**Comment by DahaWong** [comment]
I just add a `print()` to figure out what's happening inside 😅, no other special logic added.

**Comment by Bibo-Joshi** [comment]
The traceback has this part though:

```python
  File "/home/daha/project/castpod/.venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 293, in _request_wrapper
    response_data = self.parse_json_payload(payload)
  File "/home/daha/project/castpod/helpers.py", line 32, in parse_json_payload
    raise TelegramError("Invalid server response") from exc
```

Line 293 in baserequest usually calls

https://github.com/python-telegram-bot/python-telegram-bot/blob/76c2fc177646829d2738766edef9d37ffdf4f88f/telegram/request/_baserequest.py#L333

So you have overridden *something* … Can you show your function `parse_json_payload` in `/home/daha/project/castpod/helpers.py`, line 32?

Have you also tried with 

a) a local bot api server that does *not* use the `--local` flag?
b) the public bot api server `api.telegram.org`?

**Comment by DahaWong** [comment]
Well, local bot api without `--local` flag also failed; but with `api.telegram.org` succeeded. I found that my local bot api is not the latest, maybe that's the point. I'll try it later.

**Comment by DahaWong** [comment]
I've tried the latest local bot api version(6.2) today, but still got `TelegramError: Invalid server response` as before.

**Comment by Bibo-Joshi** [comment]
Interesting. Can you print out the JSON data that causes the error?

**Comment by DahaWong** [comment]
oh, I see, the returned payload is not JSON, but html...

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by Poolitzer** [comment]
That is a misconfigured nginx instance. Look at e.g. https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/
