### ISSUE TITLE
Initialization in Python 3 failing

### ISSUE THREAD

**Issue by danya02** [python-telegram-bot/python-telegram-bot#332]
### Steps to reproduce
1. Install the version of the library currently available on pip.

2. Get the echobot2.py (or some other example) file and launch it.

### Expected behaviour
The script should connect to the Telegram API and provide interactivity from there.

### Actual behaviour
In actuality, the script doesn't connect to Telegram, instead showing an error message and not doing anything apart from that.

### Configuration
**Operating System:**
GNU/Linux Debian/Raspbian 8

**Version of Python:**

``$ python3 -V

Python 3.4.2``

**Version of python-telegram-bot:**

``$ python3 -c 'import telegram; print(telegram.__version__)'

4.3``

#### Traceback log
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 105, in _thread_wrapper
        target(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 216, in _start_polling
        self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
      File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 320, in _bootstrap
        self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
      File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 121, in decorator
        result = func(self, *args, **kwargs)
       File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 1263, in setWebhook
        result = request.post(url, data, timeout=kwargs.get('timeout'))
      File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 174, in post
        headers={'Content-Type': 'application/json'})
      File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 100, in _request_wrapper
        resp = _get_con_pool().request(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/urllib3/request.py", line 72, in request
        **urlopen_kw)
      File "/usr/lib/python3/dist-packages/urllib3/request.py", line 135, in request_encode_body
        **urlopen_kw)
    TypeError: urlopen() got multiple values for keyword argument 'body'
    Exception in thread updater:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.4/threading.py", line 868, in run
         self._target(*self._args, **self._kwargs)
      File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 105, in _thread_wrapper
        target(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 216, in _start_polling
        self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
      File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 320, in _bootstrap
        self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
      File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 121, in decorator
        result = func(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 1263, in setWebhook
        result = request.post(url, data, timeout=kwargs.get('timeout'))
      File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 174, in post
        headers={'Content-Type': 'application/json'})
      File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 100, in _request_wrapper
        resp = _get_con_pool().request(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/urllib3/request.py", line 72, in request
        **urlopen_kw)

      File "/usr/lib/python3/dist-packages/urllib3/request.py", line 135, in request_encode_body
        **urlopen_kw)

    TypeError: urlopen() got multiple values for keyword argument 'body'
    2016-06-29 06:17:45,248 - telegram.ext.dispatcher - CRITICAL - stopping due to exception in another thread

**Comment by jh0ker** [comment]
Can you post the output of `pip freeze`?

**Comment by danya02** [comment]
Sure. See [here] (https://gist.github.com/danya02/33c2b728590ef91f44b3d5fbb2ce7b72).

**Comment by jh0ker** [comment]
Thank you. I think we might chose a too old version of `urllib3` as minimum requirement. Can you run `pip3 install -U urllib3`, or if that's not an option for you, run `pip3 install python-telegram-bot` in a fresh `virtualenv`?

**Comment by danya02** [comment]
Upgraded `urllib3` to 1.16, but no dice. The only thing of note is that at the beginning of `pip3 freeze` output, it says something about `urllib3` being dependent on `PySocks` for SOCKS connections, but that doesn't seem very relevant.

**Comment by jh0ker** [comment]
Are you sure the upgrade was successful? I could reproduce the bug with `1.9.1` but it was fixed by upgrading to `1.10`. What is the output of `python3 -c "import urllib3; print(urllib3.__version__)"`

**Comment by danya02** [comment]
No, it _actually_ shows the string `'1.16'`. Maybe it works specifically on version 1.10? Trying to find some way of downgrading `pip` packages.

**Comment by jh0ker** [comment]
You can downgrade with `pip3 install urllib3==1.10`, but it works with 1.16 for me as well.

**Comment by jh0ker** [comment]
Make sure you aren't installing `urllib3` inside a virtualenv and running the bot outside of it.

**Comment by danya02** [comment]
Odd. Only after downgrading to 1.10 did it work for me. Maybe it's the inherent oddness of `armv7l` systems. Or maybe it's some other random problem. But it works, and *not* only for small values of 'works', so I guess the ticket's closed.

**Comment by jh0ker** [comment]
Weird, but good to hear! :+1:

**Comment by AmirGhazaei** [comment]
I have the same problem and `pip3 install urllib3==1.10` not work.
