### ISSUE TITLE
[QUESTION] No module named 'telegram.ext'; 'telegram' is not a package

### ISSUE THREAD

**Issue by ronardcaktus** [python-telegram-bot/python-telegram-bot#3337]
### Steps to Reproduce

1. Create a virtual environment (Python must be installed)
2. pip install `python-telegram-bot` (I have 13.14)
3. Try to run .py file that contains telegram

### Expected behaviour

Script running.

### Actual behaviour

```Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/username/Desktop/bots/first_bot/telegram.py", line 2, in <module>
    from telegram.ext import updater, CommandHandler
  File "/Users/username/Desktop/bots/first_bot/telegram.py", line 2, in <module>
    from telegram.ext import updater, CommandHandler
ModuleNotFoundError: No module named 'telegram.ext'; 'telegram' is not a package```

### Operating System

MacOS

### Version of Python, python-telegram-bot & dependencies

```shell
`Python 3.9`
`python-telegram-bot==13.14`
```

### Relevant log output

```python
Output from pip freeze:

APScheduler==3.6.3
cachetools==4.2.2
certifi==2022.9.24
python-telegram-bot==13.14
pytz==2022.6
pytz-deprecation-shim==0.1.0.post0
six==1.16.0
tornado==6.1
tzdata==2022.6
tzlocal==4.2
```
```


### Additional Context

_No response_

**Comment by Poolitzer** [comment]
Hi, I think the reasons stems from you naming the file you execute`telegram.py`. Try naming it differently and it should work.
