### ISSUE TITLE
since 4.3 can´t connect behind proxy

### ISSUE THREAD

**Issue by kalety** [python-telegram-bot/python-telegram-bot#336]
### Steps to reproduce
1. pip3 install python-telegram-bot --upgrade

2. Don´t send anything

3. pip3 install python-telegram-bot-4.2.1

4. Works again!

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python:**

``$ python -V`` 3.5

**Version of python-telegram-bot:**
4.3.2,  4.2.1
``$ python -c 'import telegram; print(telegram.__version__)'``

### Logs
Insert logs here (if necessary)

**Comment by jh0ker** [comment]
Hi! Thanks for reporting this issue. Do you see any errors in the log (if not, make sure you set up the `logging` module)? Did you try anything to solve the issue?

**Comment by kalety** [comment]
The only thing I've done is downgrade version to 4.2.1.... I think the trouble is in urllib3 change....

Thanks!

**Comment by jh0ker** [comment]
Again: Do you see any errors in the log (if not, make sure you set up the `logging` module)?

**Comment by tsnoam** [comment]
@kalety 
yes, i see the problem. it appears that urllib3 doesn't use the same HTTPS_PROXY semantics.

**Comment by tsnoam** [comment]
@kalety 
thank you for bringing this to our attention.
we released v4.3.3 with a fix (which honors the `HTTPS_PROXY` or `https_proxy` env. var.)

**Comment by kalety** [comment]
Oooops, I test the new version and.....
```
Exception in thread updater:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 589, in url open
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 267, in connect
    self._tunnel()
  File "/usr/lib/python3.5/http/client.py", line 832, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authentication Required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 157, in _request_wrapper
    resp = _get_con_pool().request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 73, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 363, in url open
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 248, in url open
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 668, in url open
    release_conn=release_conn, **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 668, in url open
    release_conn=release_conn, **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 668, in url open
    release_conn=release_conn, **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 640, in url open
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXX/setWebhook (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/updater.py", line 105, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/updater.py", line 216, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/updater.py", line 320, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 1263, in setWebhook
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 232, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 163, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXX/setWebhook (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))
```

**Comment by tsnoam** [comment]
@kalety
I see according to the exception that you're using a proxy with authentication.
1. can you please open a new issue about connecting to a proxy which requires authentication.
2. when you open the issue, please specify the manner in which you configure the proxy.
for example I'd guess you're using something like
```export HTTPS_PROXY=http://user@pass:ip:port```
I want to make sure that we're in sync on the manner that you expect this to work.
