### ISSUE TITLE
[BUG] PicklePersistence: AttributeError: 'Chat' object has no attribute 'all_members_are_administrators'

### ISSUE THREAD

**Issue by Trifase** [python-telegram-bot/python-telegram-bot#3379]
### Steps to Reproduce

1. Run a bot with some picklepersistence files from previous version (v20a4)

### Expected behaviour

1. Run a bot with some picklepersistence files from previous version (v20a4)
2. Bot will start.

### Actual behaviour

1. Run a bot with some picklepersistence files from previous version (v20a4)
2. Bot won't start.

### Operating System

Debian GNU/Linux 11 (bullseye) aarch64 

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a5
Bot API 6.3
Python 3.10.2 (main, Feb 12 2022, 01:26:02) [GCC 10.2.1 20210110]
```

### Relevant log output

```python
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_picklepersistence.py", line 246, in _load_singlefile
    data = _BotUnpickler(self.bot, file).load()
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_picklepersistence.py", line 56, in _reconstruct_to
    obj.__setstate__(kwargs)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/_telegramobject.py", line 200, in __setstate__
    setattr(self, key, val)
AttributeError: 'Chat' object has no attribute 'all_members_are_administrators'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Desktop/emily/main.py", line 711, in <module>
    main()
  File "/home/pi/Desktop/emily/main.py", line 341, in main
    app.run_polling(drop_pending_updates=True, allowed_updates=Update.ALL_TYPES)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 667, in run_polling
    return self.__run(
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 855, in __run
    raise exc
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 844, in __run
    loop.run_until_complete(self.initialize())
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 365, in initialize
    await self._initialize_persistence()
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 445, in _initialize_persistence
    self._user_data.update(await self.persistence.get_user_data())
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_picklepersistence.py", line 307, in get_user_data
    self._load_singlefile()
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_picklepersistence.py", line 264, in _load_singlefile
    raise TypeError(f"Something went wrong unpickling {self.filepath.name}") from exc
TypeError: Something went wrong unpickling picklepersistence
```

**Comment by Trifase** [comment]
While this _does_ fix the aforementioned bug, now the AttributeError is raised for the new (and missing in old files) attributes, like is_forum.

Traceback:
`Traceback (most recent call last):
  File "/home/pi/Desktop/emily/main.py", line 711, in <module>
    main()
  File "/home/pi/Desktop/emily/main.py", line 341, in main
    app.run_polling(drop_pending_updates=True, allowed_updates=Update.ALL_TYPES)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 667, in run_polling
    return self.__run(
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 855, in __run
    raise exc
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 844, in __run
    loop.run_until_complete(self.initialize())
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 365, in initialize
    await self._initialize_persistence()
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_application.py", line 455, in _initialize_persistence
    persistent_data = await self.persistence.get_callback_data()
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/ext/_picklepersistence.py", line 366, in get_callback_data
    return deepcopy(self.callback_data)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 211, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 211, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/_telegramobject.py", line 233, in __deepcopy__
    setattr(result, k, deepcopy(getattr(self, k), memodict))
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/_telegramobject.py", line 233, in __deepcopy__
    setattr(result, k, deepcopy(getattr(self, k), memodict))
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/pi/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telegram/_telegramobject.py", line 233, in __deepcopy__
    setattr(result, k, deepcopy(getattr(self, k), memodict))
AttributeError: 'Chat' object has no attribute 'is_forum'
`

**Comment by Bibo-Joshi** [comment]
@Trifase A bit discussion on the second problem: https://t.me/pythontelegrambotgroup/639791
