### ISSUE TITLE
[BUG] Job Queue not working

### ISSUE THREAD

**Issue by VitaliyIvanovSPB** [python-telegram-bot/python-telegram-bot#3388]
### Steps to Reproduce

1. Copy timer example
2. add my token
3. run bot
4.  send command to set timer

### Expected behaviour

set timer

### Actual behaviour

AttributeError: 'NoneType' object has no attribute 'get_jobs_by_name'

### Operating System

Win11

### Version of Python, python-telegram-bot & dependencies

```shell
20.06
```

### Relevant log output

```python
Traceback (most recent call last):
  File "D:\python\WelcomeBot\venv\lib\site-packages\telegram\ext\_application.py", line 1042, in process_update
    await coroutine
  File "D:\python\WelcomeBot\venv\lib\site-packages\telegram\ext\_handler.py", line 143, in handle_update
    return await self.callback(update, context)
  File "D:\python\WelcomeBot\main.py", line 98, in set_timer
    job_removed = remove_job_if_exists(str(chat_id), context)
  File "D:\python\WelcomeBot\main.py", line 80, in remove_job_if_exists
    current_jobs = context.job_queue.get_jobs_by_name(name)
AttributeError: 'NoneType' object has no attribute 'get_jobs_by_name'
```

**Comment by clot27** [comment]
Hi, timerbot example works fine for me on V20.0a6. Note that you have to now install ptb with optional dependencies to make certain features work after v20.0a6 #3267, to make job queue work you have to do `pip install python-telegram-bot[job-queue]`
