### ISSUE TITLE
[BUG] - AttributeError: 'ExtBot' object has no attribute 'wrong_method_name'

### ISSUE THREAD

**Issue by livxy** [python-telegram-bot/python-telegram-bot#3422]
### Steps to Reproduce

Code (https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/errorhandlerbot.py):
```py

#!/usr/bin/env python
# pylint: disable=unused-argument, wrong-import-position
# This program is dedicated to the public domain under the CC0 license.

"""This is a very simple example on how one could implement a custom error handler."""
import html
import json
import logging
import traceback

from telegram import __version__ as TG_VER

try:
    from telegram import __version_info__
except ImportError:
    __version_info__ = (0, 0, 0, 0, 0)  # type: ignore[assignment]

if __version_info__ < (20, 0, 0, "alpha", 1):
    raise RuntimeError(
        f"This example is not compatible with your current PTB version {TG_VER}. To view the "
        f"{TG_VER} version of this example, "
        f"visit https://docs.python-telegram-bot.org/en/v{TG_VER}/examples.html"
    )
from telegram import Update
from telegram.constants import ParseMode
from telegram.ext import Application, CommandHandler, ContextTypes

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

# This can be your own ID, or one for a developer group/channel.
# You can use the /start command of this bot to see your chat id.
DEVELOPER_CHAT_ID = 9889089080


async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Log the error and send a telegram message to notify the developer."""
    # Log the error before we do anything else, so we can see it even if something breaks.
    logger.error(msg="Exception while handling an update:", exc_info=context.error)

    # traceback.format_exception returns the usual python message about an exception, but as a
    # list of strings rather than a single string, so we have to join them together.
    tb_list = traceback.format_exception(None, context.error, context.error.__traceback__)
    tb_string = "".join(tb_list)

    # Build the message with some markup and additional information about what happened.
    # You might need to add some logic to deal with messages longer than the 4096 character limit.
    update_str = update.to_dict() if isinstance(update, Update) else str(update)
    message = (
        f"An exception was raised while handling an update\n"
        f"<pre>update = {html.escape(json.dumps(update_str, indent=2, ensure_ascii=False))}"
        "</pre>\n\n"
        f"<pre>context.chat_data = {html.escape(str(context.chat_data))}</pre>\n\n"
        f"<pre>context.user_data = {html.escape(str(context.user_data))}</pre>\n\n"
        f"<pre>{html.escape(tb_string)}</pre>"
    )

    # Finally, send the message
    await context.bot.send_message(
        chat_id=DEVELOPER_CHAT_ID, text=message, parse_mode=ParseMode.HTML
    )


async def bad_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Raise an error to trigger the error handler."""
    await context.bot.wrong_method_name()  # type: ignore[attr-defined]


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Displays info on how to trigger an error."""
    await update.effective_message.reply_html(
        "Use /bad_command to cause an error.\n"
        f"Your chat id is <code>{update.effective_chat.id}</code>."
    )


def main() -> None:
    """Run the bot."""
    # Create the Application and pass it your bot's token.
    application = Application.builder().token("TOKEN").build()

    # Register the commands...
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("bad_command", bad_command))

    # ...and the error handler
    application.add_error_handler(error_handler)

    # Run the bot until the user presses Ctrl-C
    application.run_polling()


if __name__ == "__main__":
    main()
```

### Expected behaviour

I could be really stupid, or have no idea what I'm saying, but this line was causing my error:
https://github.com/python-telegram-bot/python-telegram-bot/blob/ff645c6fe2238b39b2d0274d00950ecac0cefacd/examples/errorhandlerbot.py#L69

It should make a error saying:
https://github.com/python-telegram-bot/python-telegram-bot/blob/ff645c6fe2238b39b2d0274d00950ecac0cefacd/examples/errorhandlerbot.py#L52-L59
```html
An exception was raised while handling an update
<pre>update = {html.escape(json.dumps(update_str, indent=2, ensure_ascii=False))}
</pre>

<pre>context.chat_data = {html.escape(str(context.chat_data))}</pre>

<pre>context.user_data = {html.escape(str(context.user_data))}</pre>

<pre>{html.escape(tb_string)}</pre>
```

So it would produce something like this as a message sent in Telegram (not entirely sure, apologies):
```bash
2022-12-13 19:49:17,431 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "C:\Users\{REDACTED}\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\_application.py", line 1042, in process_update
    await coroutine
  File "C:\Users\{REDACTED}\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\_handler.py", line 143, in handle_update
    return await self.callback(update, context)
  File "c:\Users\{REDACTED}\OneDrive\Documents\{REDACTED}\{REDACTED}\test.py", line 77, in bad_command
    await context.bot.wrong_method_name()  # type: ignore[attr-defined]
AttributeError: 'ExtBot' object has no attribute 'wrong_method_name'
```

or so I'm guessing? 

### Actual behaviour

![image](https://user-images.githubusercontent.com/67598470/207477473-4ec2a336-4b47-4209-b1aa-eed7ea555127.png)
Error in console, but there is no message that was supposed to be sent in Telegram.

### Operating System

Windows 11 x64

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a6
Bot API 6.3
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
```

### Relevant log output

```python
PS C:\Users\{REDACTED}\OneDrive\Documents\{REDACTED}\{REDACTED}> & C:/Users/{REDACTED}/AppData/Local/Programs/Python/Python310/python.exe c:/Users/{REDACTED}/OneDrive/Documents/{REDACTED}/{REDACTED}/test.py
2022-12-13 19:49:14,055 - apscheduler.scheduler - INFO - Scheduler started
2022-12-13 19:49:14,056 - telegram.ext._application - INFO - Application started
2022-12-13 19:49:17,431 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "C:\Users\{REDACTED}\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\_application.py", line 1042, in process_update
    await coroutine
  File "C:\Users\{REDACTED}\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\_handler.py", line 143, in handle_update
    return await self.callback(update, context)
  File "c:\Users\{REDACTED}\OneDrive\Documents\{REDACTED}\{REDACTED}\test.py", line 70, in bad_command
    await context.bot.wrong_method_name()  # type: ignore[attr-defined]
AttributeError: 'ExtBot' object has no attribute 'wrong_method_name'
```

**Comment by livxy** [comment]
Please forgive me, as I am new to GitHub and started using this application in August!

**Comment by Bibo-Joshi** [comment]
Hi. I just re-ran the example on my machine and the error message is sent just fine to the `DEVELOPER_CHAT_ID` for me … Can you set the logging level in line 30 to `logging.DEBUG`, rerun the example and report the debug logs here? Make sure to replace any mention of your token though.

**Comment by livxy** [comment]
Woops I just didn't even see the dev channel 😂 
![image](https://user-images.githubusercontent.com/67598470/207709652-a512d3e0-1dd8-4a96-b6eb-6d120d8d23b2.png)
Works!
