### ISSUE TITLE
[BUG] Apscheduler crashes on repeating jobs when running in webhook mode

### ISSUE THREAD

**Issue by Nukesor** [python-telegram-bot/python-telegram-bot#3424]
### Steps to Reproduce

1. Start a bot in webhook mode
2. Add repeating job
3. Check the log output

[This bot](https://github.com/Nukesor/hetznerbot) is very minimalistic and might be a good way to reproduce this issue.

More specifically, this is the onlyjob that is added:
https://github.com/Nukesor/hetznerbot/blob/main/hetznerbot/hetznerbot.py#L32

### Expected behaviour

No crash, just as in polling mode.

### Actual behaviour

The jobs fail with the message that can be seen below

### Operating System

Arch Linux 6.0.10. But this happens since the switch to apscheduler.

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.14 (v1.6.0-111-g02d5e88)
Bot API 6.2
certifi2022.09.24
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
```

### Relevant log output

```python
Dec 15 12:18:31 jarvis poetry[655584]: 2022-12-15 12:18:31,130 - apscheduler.scheduler - ERROR - Error submitting job "Scan new sticker sets (trigger: interval[0:00:10], next run at: 2022-12-15 12:18:31 UTC)" to executor "default"
Dec 15 12:18:31 jarvis poetry[655584]: Traceback (most recent call last):
Dec 15 12:18:31 jarvis poetry[655584]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 974, in _process_jobs
Dec 15 12:18:31 jarvis poetry[655584]:     executor.submit_job(job, run_times)
Dec 15 12:18:31 jarvis poetry[655584]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
Dec 15 12:18:31 jarvis poetry[655584]:     self._do_submit_job(job, run_times)
Dec 15 12:18:31 jarvis poetry[655584]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 22, in _do_submit_job
Dec 15 12:18:31 jarvis poetry[655584]:     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
Dec 15 12:18:31 jarvis poetry[655584]:   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
Dec 15 12:18:31 jarvis poetry[655584]:     raise RuntimeError('cannot schedule new futures after '
Dec 15 12:18:31 jarvis poetry[655584]: RuntimeError: cannot schedule new futures after interpreter shutdown
```

### Additional Context

The problem happens on these three bots I'm trying to run in webhook mode.
https://github.com/Nukesor/ultimate-poll-bot
https://github.com/Nukesor/sticker-finder
https://github.com/Nukesor/hetznerbot

Exactly the same error on all three bots.

IIRC, this bug already exists since the very first version apscheduler was introduced, but I simply switched to polling mode back then as I didn't care too much.

Since @ultimate_pollbot is currently experiencing some reliability issues, I tried to re-enable webhook mode and found out why I disabled it in the first place :sweat_smile: .

There seems to be a related issue on the apscheduler wiki: https://github.com/agronholm/apscheduler/issues/285
The issue is marked as fixed, but there seem to be other people that still experience this problem.

I thought you might have some insight, as this error seems to be somehow related to the way apscheduler is used in poll/webhook mode.

**Comment by Bibo-Joshi** [comment]
Thank for reaching out.

The linked issue agronholm/apscheduler#285 mentions "very short interval triggers" and I see that the job that you linked uses `first=0`. Can you please try to change https://github.com/Nukesor/hetznerbot/blob/main/hetznerbot/hetznerbot.py#L33 to

```python
job = job_queue.run_repeating(process_all, interval=120, name="Process all")
job.run(dispatcher)
```

and report if this changes the behavior?

**Comment by Nukesor** [comment]
Nope.

The RuntimeError happens every time the job is scheduled for execution.
Every 2 minutes on the second.

**Comment by Bibo-Joshi** [comment]
Sad, that would have been a quick solution … 

As mentioned in #3425, we do not provide bug fixes for v13.x anymore, so tbh I won't investigate this further.

I did however run an MWE with webhooks on v20.0b0 to check for any issues. The below MWE worked fine for me. Could you run this on the same setup where you run into issues on v13? In case v20 also gives you problems there, that would be valuable information :)

**Comment by Bibo-Joshi** [comment]
I only now realize that I forgot to add the mwe 🤦‍♂️ 

```python
import logging

from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)

logger = logging.getLogger(__name__)


async def alarm(_: ContextTypes.DEFAULT_TYPE) -> None:
    logger.info("This is the job callback. I executed successfully.")


async def start(update: Update, _: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text("Update successfully received.")


def main() -> None:
    application = (
        Application.builder().token("TOKEN").build()
    )

    application.add_handler(CommandHandler(["start", "help"], start))
    application.job_queue.run_repeating(alarm, interval=5, first=5)

    application.run_webhook(
        listen="127.0.0.1",
        webhook_url="https://my.tld",
        port=5000,
    )


if __name__ == "__main__":
    main()
```

**Comment by code-ksu** [comment]
> I only now realize that I forgot to add the mwe 🤦‍♂️

I've got the same error but in polling. Maybe I've also forgot "mwe". But... what is "mwe"?
Could you help me out here?

**Comment by Bibo-Joshi** [comment]
@code-ksu If you get the same problem in polling mode then it&#x27;s likely that the issue is the Apscheduler and not with PTB... Have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/MWE">this short article</a> for information on what a MWE is.

**Comment by Bibo-Joshi** [comment]
Closing because I was not able to reproduce the issue, because the issue seems to be with APS rather than PTB and due to lack of response by OP.

**Comment by Nukesor** [comment]
Works for me.

I'll try to reproduce this once I'm back from my christmas family trip.
Once v20 is released, we'll see if the problem persists and I'll re-open the issue with a proper minimal example.

Same for https://github.com/python-telegram-bot/python-telegram-bot/issues/3425
