### ISSUE TITLE
[BUG] Multiple bots behind proxy trigger BadRequest

### ISSUE THREAD

**Issue by Nukesor** [python-telegram-bot/python-telegram-bot#3425]
### Steps to Reproduce

1. Run two bots in webhook mode behind a Proxy
2. Both should listen on `127.0.0.1`
3. They should have different ports (`7000` and `7001` in my case)

The `start_webhook` calls look like this:
```
updater.start_webhook(
    listen="127.0.0.1",
    port=7000,
    url_path="/MY_SECRET_TOKEN",
    webhook_url=f"https://MY_DOMAIN/MY_SECRET_TOKEN"",
    cert="path_to_my_cert",
)
```

The token and port are different for the two different bots.

### Expected behaviour

Everything should work just fine

### Actual behaviour

The bot crashes.

### Operating System

Arch Linux 6.0.10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.14 (v1.6.0-111-g02d5e88)
Bot API 6.2
certifi2022.09.24
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
```

### Relevant log output

```python
Dec 15 12:50:28 jarvis poetry[658627]: Exception in thread Bot:627741767:updater:
Dec 15 12:50:28 jarvis poetry[658627]: Traceback (most recent call last):
Dec 15 12:50:28 jarvis poetry[658627]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Dec 15 12:50:28 jarvis poetry[658627]:     self.run()
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
Dec 15 12:50:28 jarvis poetry[658627]:     reraise(*_capture_exception())
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 56, in reraise
Dec 15 12:50:28 jarvis poetry[658627]:     raise value
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
Dec 15 12:50:28 jarvis poetry[658627]:     return old_run_func(self, *a, **kw)
Dec 15 12:50:28 jarvis poetry[658627]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Dec 15 12:50:28 jarvis poetry[658627]:     self._target(*self._args, **self._kwargs)
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/ext/updater.py", line 353, in _thread_wrapper
Dec 15 12:50:28 jarvis poetry[658627]:     target(*args, **kwargs)
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/ext/updater.py", line 732, in _start_webhook
Dec 15 12:50:28 jarvis poetry[658627]:     self._bootstrap(
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/ext/updater.py", line 811, in _bootstrap
Dec 15 12:50:28 jarvis poetry[658627]:     self._network_loop_retry(
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/ext/updater.py", line 665, in _network_loop_retry
Dec 15 12:50:28 jarvis poetry[658627]:     onerr_cb(telegram_exc)
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/ext/updater.py", line 793, in bootstrap_onerr_cb
Dec 15 12:50:28 jarvis poetry[658627]:     raise exc
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
Dec 15 12:50:28 jarvis poetry[658627]:     if not action_cb():
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/ext/updater.py", line 775, in bootstrap_set_webhook
Dec 15 12:50:28 jarvis poetry[658627]:     self.bot.set_webhook(
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/bot.py", line 133, in decorator
Dec 15 12:50:28 jarvis poetry[658627]:     result = func(*args, **kwargs)
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/bot.py", line 3170, in set_webhook
Dec 15 12:50:28 jarvis poetry[658627]:     result = self._post('setWebhook', data, timeout=timeout, api_kwargs=api_kwargs)
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/bot.py", line 298, in _post
Dec 15 12:50:28 jarvis poetry[658627]:     return self.request.post(
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/utils/request.py", line 359, in post
Dec 15 12:50:28 jarvis poetry[658627]:     result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
Dec 15 12:50:28 jarvis poetry[658627]:   File "/var/lib/bot/apps/stickerfinder/.venv/lib/python3.10/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
Dec 15 12:50:28 jarvis poetry[658627]:     raise BadRequest(message)
Dec 15 12:50:28 jarvis poetry[658627]: telegram.error.BadRequest: Bad webhook: ip address 127.0.0.1 is reserved
```

### Additional Context

I'm not sure why the bot tries to reserve localhost instead of only the port.

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out. I tried to reproduce the issue with the following findings:

* on windows, I don't get any error messages
* on linux, I do get error messages, but different ones: The error is `OSError: [Errno 98] Address already in use` and the traceback leads to the line `self.http_server.listen(self.port, address=self.listen)` in `webhookhandler.py`.

What I find strange about the traceback you presented is that it points to the call of `set_webhook` and the error is a `BadRequest` - this means that the error is ussed by `Telegram` and not by your OS/webserver/any other *local* thing.

While we do not do bug fixes for v13.x anymore, this issue is indeed still revelant for v20.x, since we still use tornado in v20. I was indeed able to reproduce the same behavior as mentioned above in v20. Whether this issue can be improved may be a revelant info for #2966 .

@Nukesor could you run the following snippet on your machine with PTB v20.0b0 and report the result?

```python
import asyncio

from telegram import Bot
from telegram.ext import Updater

update_queue = asyncio.Queue()
bot = Bot("TOKEN1")
bot_2 = Bot("TOKEN2")
updater = Updater(bot, update_queue=update_queue)
updater_2 = Updater(bot_2, update_queue=update_queue)


async def main():
    async with updater, updater_2:
        await updater.start_webhook(
            listen="127.0.0.1",
            port=7000,
            url_path="/MY_SECRET_TOKEN",
            webhook_url=f"https://MY_DOMAIN",
        )
        await updater_2.start_webhook(
            listen="127.0.0.1",
            port=8000,
            url_path="/MY_SECRET_TOKEN",
            webhook_url=f"https://MY_DOMAIN",
        )

        await asyncio.sleep(5)
        await updater.stop()
        await updater_2.stop()


if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by Nukesor** [comment]
Your snippet seems to work just fine.
It terminates after ~5 seconds and shows no errors.

I tried to come up with a minimal reproducable example and had the same result as you.
I was only able to reproduce the `Address already in use` error, which is still confusing but a bit less confusing.

I guess if this is already fixed in v20, I could try to use the beta branch for my projects :)

**Comment by Bibo-Joshi** [comment]
Let me double check: The v20 version does not produce `Address already in use` errors for you? Because it does for me 🤔

**Comment by Nukesor** [comment]
Your script didn't throw exceptions on v20 for me.

I made a minimal setup which starts two v13 instances and I got a `Address already in use`.

**Comment by Bibo-Joshi** [comment]
I checked back with someone more familiar with webservers and stuff and their guess is that there's just something else listening for one of the ports. On my windows machine I don't have any services running, but on my linux machine, `netstat` reminded me that I do in fact have a service running that listens to port 8000. Changing that to 9000 in my above MWE, the example works smoothely for me as well.

Can you please also double check for other services running on ports that you want to use? If you tested both v13  and v20 on the same machine, it's strange though that only one of them makes problems. For completeness, please find below the v13-MWE that I used (keep in mind that you'll have to press CTRL+C twice to shut it down).

```python
from telegram.ext import Updater

updater = Updater("TOKEN1")
updater_2 = Updater("TOKEN2")

updater.start_webhook(
    listen="127.0.0.1",
    port=7000,
    url_path="/MY_SECRET_TOKEN",
    webhook_url=f"https://MY_DOMAIN",
)
updater_2.start_webhook(
    listen="127.0.0.1",
    port=8000,
    url_path="/MY_SECRET_TOKEN",
    webhook_url=f"https://MY_DOMAIN",
)
updater.idle()
updater_2.idle()
```

**Comment by Bibo-Joshi** [comment]
Closing since I was not *actually* able to reproduce the issue (only due to faulty server configs) and due to lack of response by OP.
