### ISSUE TITLE
[QUESTION] How to react to exceptions in getUpdates?

### ISSUE THREAD

**Issue by eikowagenknecht** [python-telegram-bot/python-telegram-bot#3430]
### Issue I am facing

I'm updating from v13 to v20. It's mostly running fine now, but I noticed that some behaviour seems to have changed regarding the handling of exceptions.

Previously (v13) I could react to the "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running" inside my custom error handler (added with application.add_error_handler(...)).

Now this method only seems to handle other errors but not this one? How can I catch the "Two bots running at the same time" conflict in v20 and properly react to it (e.g. shutting the bot down gracefully)?

The error_handler() method is never called for this error.

### Traceback to the issue

```python
2022-12-18 00:10:07,021 httpx._client [DEBUG] HTTP Request: POST https://api.telegram.org/*****:*****/getUpdates "HTTP/1.1 409 Conflict"      
2022-12-18 00:10:07,027 telegram.ext._updater [ERROR] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-12-18 00:10:07,027 telegram.ext._updater [ERROR] Exception happened while polling for updates.
Traceback (most recent call last):
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\ext\_updater.py", line 603, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\ext\_updater.py", line 329, in polling_action_cb
    raise exc
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\ext\_updater.py", line 314, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 513, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\_bot.py", line 313, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\_bot.py", line 3528, in get_updates
    await self._post(
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\_bot.py", line 395, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\_bot.py", line 426, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 167, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\repos\project\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 332, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-12-18 00:10:08,043 telegram._bot [DEBUG] Entering: get_updates
```

### Related part of your code

```python
async def start(self) -> None:
        # Build application
        token = self.config.telegram_access_token
        rate_limiter = AIORateLimiter(max_retries=3)
        self.application = (
            Application.builder().token(token).rate_limiter(rate_limiter).build()
        )

...

        self.application.add_error_handler(self.error_handler)

...

        await self.application.initialize()
        await self.application.start()
        if self.application.updater is not None:
            await self.application.updater.start_polling()
            logger.info("Started listening for messages from Telegram")

...

    async def error_handler(
        self, update: Update, context: ContextTypes.DEFAULT_TYPE
    ) -> None:
        # Log the error before we do anything else, so we can see it even if something breaks.
        logger.error(msg="Exception while handling an update:", exc_info=context.error)

...
```

### Operating System

Windows / Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a6 (v0.6.0-79-g4952ff1)                                           Bot API 6.3                                                                               Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Hi. Since the connection between `Updater` and the new `Application` is a bit different than the previous connection between `Updater` and `Dispatcher`, forwarding exceptions from the long-polling loop to the `Application` is a bit more intricate. You can customize the behavior via the [`error_callback` parameter of `Application.start_polling`](docs.python-telegram-bot.org/telegram.ext.updater.html#telegram.ext.Updater.start_polling.params.error_callback). To make the error handlers handle these errors, you can e.g. use something like

```python
async def error_callback(error, application):
    application.create_task(application.process_error(update=None, error=error)

application.start_polling(error_callback=functools.parital(error_callback, application=application)
```

(Disclaimer: I've not actually tested this snippet, but I'm confident that at least the overall idea of it should work :D)

**Comment by eikowagenknecht** [comment]
Thank you, that was the right hint. Though the function signature seems to be a bit different. I ended up with the following code (just in case anyone else needs this):

```python
...
            await self.application.updater.start_polling(
                error_callback=self.updater_error_handler
            )
...

    async def stop(self) -> None:
        if self.application is None or self.application.updater is None:
            return

        await self.application.updater.stop()
        await self.application.stop()
        await self.application.shutdown()

...

    def updater_error_handler(self, error: TelegramError) -> None:
        # Multiple bot instances, abort to avoid Telegram punishing API key misuse!
        if isinstance(error, telegram.error.Conflict):
            error_text = "Multiple instances of the same bot running, shutting down myself to avoid further conflicts."
            logger.critical(error_text)

            # We need to run this in a separate task, because it runs asynchroniously
            asyncio.get_running_loop().create_task(
                self.notify_admin_and_stop(error_text)
            )
            return

        logger.error(f"Error while polling for messages from Telegram: {error}")

```
