### ISSUE TITLE
Unable to gracefully shutdown application when running on webhook

### ISSUE THREAD

**Issue by polars05** [python-telegram-bot/python-telegram-bot#3455]
### Issue I am facing

When shutting down an application that is using `run_webhook` (via  <kbd>Ctrl</kbd> + <kbd>C</kbd>), the shutdown would throw the following error:
```
sys:1: RuntimeWarning: coroutine 'Application.initialize' was never awaited
sys:1: RuntimeWarning: coroutine 'Application.shutdown' was never awaited
```
(Pls see [Related part of your code](###Related-part-of-your-code) for a working code snippet)

Is there something that I'm missing here?

### Traceback to the issue

```python
2023-01-01 10:38:46,369 - telegram.ext._application - INFO - Application is stopping. This might take a moment.
2023-01-01 10:38:46,370 - apscheduler.scheduler - INFO - Scheduler has been shut down
2023-01-01 10:38:46,370 - telegram.ext._application - INFO - Application.stop() complete
Traceback (most recent call last):
  File "C:\Users\Fong\.conda\envs\boredbot\lib\site-packages\telegram\ext\_application.py", line 886, in __run
    raise exc
  File "C:\Users\Fong\.conda\envs\boredbot\lib\site-packages\telegram\ext\_application.py", line 875, in __run
    loop.run_until_complete(self.initialize())
  File "C:\Users\Fong\.conda\envs\boredbot\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_closed()
  File "C:\Users\Fong\.conda\envs\boredbot\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fong\Desktop\tooboredbot\test.py", line 17, in <module>
    # application.run_webhook(
  File "C:\Users\Fong\.conda\envs\boredbot\lib\site-packages\telegram\ext\_application.py", line 825, in run_webhook
    return self.__run(
  File "C:\Users\Fong\.conda\envs\boredbot\lib\site-packages\telegram\ext\_application.py", line 895, in __run
    loop.run_until_complete(self.shutdown())
  File "C:\Users\Fong\.conda\envs\boredbot\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_closed()
  File "C:\Users\Fong\.conda\envs\boredbot\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Application.initialize' was never awaited
sys:1: RuntimeWarning: coroutine 'Application.shutdown' was never awaited
```

### Related part of your code

```python
import logging
from telegram.ext import ApplicationBuilder

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

TELEGRAM_AUTH_TOKEN = 'xxx'


if __name__ == '__main__':
    application = ApplicationBuilder().token(TELEGRAM_AUTH_TOKEN).build()

    application.run_polling()

    application.run_webhook(
        listen='127.0.0.1',
        port=8080,
        url_path=TELEGRAM_AUTH_TOKEN,
        webhook_url=f'http://127.0.0.1:8080/{TELEGRAM_AUTH_TOKEN}',
    )
```

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0b0
Bot API 6.3
Python 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
You're calling both `run_polling` and `run_webhook` one after the other. Both will by default close the event loop on shutdown, which is why you get the corresponding exception. Apart from me seeing no reason to first run the application an polling mode and then in webhook mode, you can tell both methods not to close the event loop via the [corresponding parameter](https://docs.python-telegram-bot.org/en/v20.0b0/telegram.ext.application.html#telegram.ext.Application.run_polling.params.close_loop).

**Comment by polars05** [comment]
@Bibo-Joshi thanks for your reply! In that case, when do you recommend we use `run_polling` vs `run_webhook`?

**Comment by Bibo-Joshi** [comment]
In my experience running in webhook mode is mostly useful if you run PTB alongside another webserver application or if your host does not support polling. It also _can_ have some scalability benefits. More many use cases, polling works just fine though.
