### ISSUE TITLE
[QUESTION] in version 20 emoji don't send

### ISSUE THREAD

**Issue by Naidjel** [python-telegram-bot/python-telegram-bot#3458]
### Issue I am facing

In old versions code work fine but after update fail.

I must send emoji with code: \ud83d\udc69\ud83c\udffc\u200d\ud83c\udfeb.
In version 20 release emoji don't send anymore with error below.

### Traceback to the issue

```python
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Job.run() done, defined at /usr/local/lib/python3.9/site-packages/aioschedule/__init__.py:455> exception=NetworkError('Unknown error in HTTP implementation: UnicodeEncodeError('utf-8', '\ud83d\udc69\ud83c\udffc\u200d\ud83c\udfeb', 0, 4, 'surrogates not allowed')')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 183, in do_request
    res = await self._client.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1520, in request
    request = self.build_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 360, in build_request
    return Request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 339, in __init__
    headers, stream = encode_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_content.py", line 209, in encode_request
    return encode_urlencoded_data(data)
  File "/usr/local/lib/python3.9/site-packages/httpx/_content.py", line 142, in encode_urlencoded_data
    body = urlencode(plain_data, doseq=True).encode("utf-8")
  File "/usr/lib64/python3.9/urllib/parse.py", line 972, in urlencode
    v = quote_via(v, safe, encoding, errors)
  File "/usr/lib64/python3.9/urllib/parse.py", line 882, in quote_plus
    return quote(string, safe, encoding, errors)
  File "/usr/lib64/python3.9/urllib/parse.py", line 865, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-3: surrogates not allowed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioschedule/__init__.py", line 462, in run
    ret = await self.job_func()
  File "/home/naidjel/bot/new-age2.py", line 26, in GoogleCalendar
    await bot.send_message('177198117', mark2Replace('\ud83d\udc69\ud83c\udffc\u200d\ud83c\udfeb'), parse_mode='MarkdownV2')
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 334, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 767, in send_message
    return await self._send_message(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 515, in _send_message
    result = await self._post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 422, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 453, in _do_post
    return await request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 290, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {repr(exc)}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: UnicodeEncodeError('utf-8', '\ud83d\udc69\ud83c\udffc\u200d\ud83c\udfeb', 0, 4, 'surrogates not allowed')
```

### Related part of your code

```python
def mark2Replace(word):
    word = word.replace('(','\\(').replace(')','\\)').replace('~','\\~').replace('>','\\>').replace('#','\\#').replace('+','\\+').replace('-','\\-').replace('=','\\=').replace('|','\\|').replace('{','\\{').replace('}','\\}').replace('.','\\.').replace('!','\\!')
    return word

await bot.send_message('client_number', mark2Replace('\ud83d\udc69\ud83c\udffc\u200d\ud83c\udfeb'), parse_mode='MarkdownV2')
```

### Operating System

MAC OS 13.1

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.9.13 (main, Jun 24 2022, 15:32:51)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
```

**Comment by clot27** [comment]
You are passing the wrong unicodes or in wrong way, passing them like:

**Comment by Bibo-Joshi** [comment]
I also double checked and your snippet works neither on v13.15 nor on v20.0, so an upgrade to v20.0 is highly unlikely to be the sole cause if your issue. I'd also like to point out that inserting your emoji directly into the code is also an option: `await bot.send_message(chat_id=123, text="👩🏼‍🏫")`.

This StackOverflow answer may be of interest for you: https://stackoverflow.com/a/62935174/10606962

**Comment by Naidjel** [comment]
> I'd also like to point out that inserting your emoji directly into the code is also an option: `await bot.send_message(chat_id=123, text="👩🏼‍🏫")`.
> 


OMG!! so it was possible))) tnx! Now work great.
