### ISSUE TITLE
[QUESTION] httpx HTTPError, no shutdown

### ISSUE THREAD

**Issue by AlexFoxalt** [python-telegram-bot/python-telegram-bot#3519]
### Issue I am facing

Hello guys, any ideas what cat it be?
Running app on local machine is ok, no problems
But on remote VM, where i have ~25 users i periodically have this traceback.
I can add, that this problem did not shut down app. It brings alot problems while reading logs

### Traceback to the issue

```python
tg_app  | Error while getting Updates: httpx HTTPError: 
tg_app  | No error handlers are registered, logging exception.
tg_app  | Traceback (most recent call last):
tg_app  |   File "/opt/bitnami/python/lib/python3.9/asyncio/selector_events.py", line 854, in _read_ready__data_received
tg_app  |     data = self._sock.recv(self.max_size)
tg_app  | ConnectionResetError: [Errno 104] Connection reset by peer
tg_app  | 
tg_app  | The above exception was the direct cause of the following exception:
tg_app  | 
tg_app  | Traceback (most recent call last):
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
tg_app  |     yield
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 34, in read
tg_app  |     return await self._stream.receive(max_bytes=max_bytes)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/anyio/streams/tls.py", line 195, in receive
tg_app  |     data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
tg_app  |     data = await self.transport_stream.receive()
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1274, in receive
tg_app  |     raise self._protocol.exception
tg_app  | anyio.BrokenResourceError
tg_app  | 
tg_app  | During handling of the above exception, another exception occurred:
tg_app  | 
tg_app  | Traceback (most recent call last):
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
tg_app  |     yield
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
tg_app  |     resp = await self._pool.handle_async_request(req)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
tg_app  |     raise exc
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
tg_app  |     response = await connection.handle_async_request(request)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
tg_app  |     return await self._connection.handle_async_request(request)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
tg_app  |     raise exc
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
tg_app  |     ) = await self._receive_response_headers(**kwargs)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
tg_app  |     event = await self._receive_event(timeout=timeout)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
tg_app  |     data = await self._network_stream.read(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 36, in read
tg_app  |     return b""
tg_app  |   File "/opt/bitnami/python/lib/python3.9/contextlib.py", line 137, in __exit__
tg_app  |     self.gen.throw(typ, value, traceback)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
tg_app  |     raise to_exc(exc)
tg_app  | httpcore.ReadError
tg_app  | 
tg_app  | The above exception was the direct cause of the following exception:
tg_app  | 
tg_app  | Traceback (most recent call last):
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 183, in do_request
tg_app  |     res = await self._client.request(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_client.py", line 1533, in request
tg_app  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_client.py", line 1620, in send
tg_app  |     response = await self._send_handling_auth(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
tg_app  |     response = await self._send_handling_redirects(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
tg_app  |     response = await self._send_single_request(request)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_client.py", line 1722, in _send_single_request
tg_app  |     response = await transport.handle_async_request(request)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
tg_app  |     resp = await self._pool.handle_async_request(req)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/contextlib.py", line 137, in __exit__
tg_app  |     self.gen.throw(typ, value, traceback)
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
tg_app  |     raise mapped_exc(message) from exc
tg_app  | httpx.ReadError
tg_app  | 
tg_app  | The above exception was the direct cause of the following exception:
tg_app  | 
tg_app  | Traceback (most recent call last):
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/ext/_updater.py", line 600, in _network_loop_retry
tg_app  |     if not await action_cb():
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/ext/_updater.py", line 327, in polling_action_cb
tg_app  |     raise exc
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/ext/_updater.py", line 312, in polling_action_cb
tg_app  |     updates = await self.bot.get_updates(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
tg_app  |     updates = await super().get_updates(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/_bot.py", line 334, in decorator
tg_app  |     result = await func(*args, **kwargs)  # skipcq: PYL-E1102
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/_bot.py", line 3584, in get_updates
tg_app  |     await self._post(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/_bot.py", line 422, in _post
tg_app  |     return await self._do_post(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
tg_app  |     return await super()._do_post(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/_bot.py", line 453, in _do_post
tg_app  |     return await request.post(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 165, in post
tg_app  |     result = await self._request_wrapper(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
tg_app  |     raise exc
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
tg_app  |     code, payload = await self.do_request(
tg_app  |   File "/opt/bitnami/python/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 204, in do_request
tg_app  |     raise NetworkError(f"httpx HTTPError: {err}") from err
tg_app  | telegram.error.NetworkError: httpx HTTPError:
```

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
if __name__ == "__main__":
    app = ApplicationBuilder().token(Cfg.TG_TOKEN).build()
    job_queue = app.job_queue
    app.add_handler(
        ConversationHandler(
            entry_points=[CallbackQueryHandler(handler.callback_handler)],
            fallbacks=[CallbackQueryHandler(handler.callback_handler)],
            states={
                handler.SUPPORT_MSG: [
                    MessageHandler(
                        filters.ALL, handler.register_support_message
                    )
                ]
            },
        )
    )
    app.add_handler(
        ConversationHandler(
            entry_points=[CommandHandler("start", handler.start)],
            fallbacks=[],
            states={
                handler.SELECTED_NONE: [
                    MessageHandler(filters.ALL, handler.register_step_one)
                ],
                handler.SELECTED_HOME: [
                    MessageHandler(
                        filters.Regex(r"^(8Б|8В|8Г|Пропустить)$"),
                        handler.register_step_two,
                    )
                ],
                handler.SELECTED_FLAT: [
                    MessageHandler(
                        filters.Regex(r"^([0-9]{1,3}|Пропустить)$"),
                        handler.register_end,
                    )
                ],
            },
        )
    )

    app.add_handler(CommandHandler("migrate", handler.migrate))
    app.add_handler(CommandHandler("msg", handler.msg))
    app.add_handler(CommandHandler("msgpin", handler.msgpin))
    app.add_handler(CommandHandler("msgall", handler.msgall))
    job_status_update = job_queue.run_repeating(
        run_status_update, interval=60, first=60
    )
    logger.info("Bot starting")
    app.run_polling()
```

**Comment by AlexFoxalt** [comment]
Srry, made some mistakes with topics, here is my setup:
`aiomysql==0.1.1
anyio==3.6.2
APScheduler==3.9.1.post1
async-cache==1.1.1
async-sqlalchemy==1.0.0
asyncpg==0.27.0
black==22.12.0
certifi==2022.12.7
charset-normalizer==3.0.1
click==8.1.3
emoji==2.2.0
greenlet==2.0.1
h11==0.14.0
httpcore==0.16.3
httpx==0.23.3
idna==3.4
loguru==0.6.0
mypy-extensions==0.4.3
pathspec==0.10.3
platformdirs==2.6.2
PyMySQL==1.0.2
python-dotenv==0.21.0
python-telegram-bot==20.0
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
requests==2.28.2
rfc3986==1.5.0
six==1.16.0
sniffio==1.3.0
SQLAlchemy==1.4.46
tomli==2.0.1
typing_extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
urllib3==1.26.14`

**Comment by Bibo-Joshi** [comment]
@AlexFoxalt Please have a look at this wiki page: <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors">Handling network errors</a>

**Comment by AlexFoxalt** [comment]
@Bibo-Joshi Maybe i can do some kind for try-except block for ignoring such traceback? But i don't see the source function of my app, where it's calling

**Comment by Bibo-Joshi** [comment]
The traceback tells me that the exception happens while polling for updates using `get_updates`, i.e. not in one of your callback functions.
