### ISSUE TITLE
[QUESTION] Basic example not working.  Intermitent errors of different types

### ISSUE THREAD

**Issue by CodeCanna** [python-telegram-bot/python-telegram-bot#3533]
### Issue I am facing

Hello!  I'm working through the basic example on [Your first bot tutorial](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot).  I'm using Python 3.11 on Windows 11 x64(Sadly).

When I run my bot, I don't get any replies to the `/start` command.

Sometimes I get no errors and it looks like this:
```
2023-02-04 00:11:11,507 - apscheduler.scheduler - INFO - Scheduler started
2023-02-04 00:11:11,508 - telegram.ext._application - INFO - Application started
```

However when I `ctrl-c` and re-run I get a lot of errors.
[This](https://github.com/python-telegram-bot/python-telegram-bot/issues/3519) question seems a little similar but not quite the same behavior.

Even when I run the bot and I get no errors I still get no response from my bot.  At this point I'm unsure of what I'm doing wrong.

### Traceback to the issue

```python
2023-02-04 00:17:45,074 - apscheduler.scheduler - INFO - Scheduler started
2023-02-04 00:17:45,074 - telegram.ext._application - INFO - Application started
2023-02-04 00:17:45,389 - telegram.ext._updater - ERROR - Error while getting Updates: httpx HTTPError: 
2023-02-04 00:17:45,390 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 489, in finish_recv
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 841, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 493, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 841, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 493, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method    
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\backends\asyncio.py", line 66, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\mgraf\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\mgraf\Documents\programming\python\telegram_bot_test\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError
```

### Related part of your code

```python
import logging, asyncio
from telegram import Update, Chat
from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler, Application


logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

async def start(update_obj: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await context.bot.send_message(chat_id=update_obj.effective_chat.id, text="Hello, World!")

def main():
    app: Application = ApplicationBuilder().token('MY_TOKEN').build()

    handle_start = CommandHandler('start', start)
    app.add_handler(handle_start)

    app.run_polling()

if __name__ == '__main__':
    main()
```

### Operating System

Windows 11 x64

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Hi. 

> `OSError: [WinError 64] The specified network name is no longer available`

This line indicates that the problem originates on an operating system level, which is beyond the control of `python-telegram-bot`. In fact, searching for "The specified network name is no longer available" on your favorite search engine will yield a number of results that are independent of `python-telegram-bot` or even Python in general.

**Comment by CodeCanna** [comment]
I dont know how much this helps me, I'm running a very simple example with hopefully not much that can go wrong.  I'm also using a python virtual environment.  `OSError` is a pretty generic error, does this mean that this library isn't compatible with Windows?  I'm following the beginners tutorial.

**Comment by Poolitzer** [comment]
Hi.

I agree that you should be able to run this if you are in an unmodified environment. I did the same steps as you did. Windows 11, python 3.11.1, I made a venv, installed python-telegram-bot[all] into it. I run your code, the /start command works for me.

```
2023-02-04 11:15:51,457 - apscheduler.scheduler - INFO - Scheduler started
2023-02-04 11:15:51,457 - telegram.ext._application - INFO - Application started
(I press Ctrl + C)
2023-02-04 11:15:56,257 - telegram.ext._application - INFO - Application is stopping. This might take a moment.
2023-02-04 11:15:56,272 - apscheduler.scheduler - INFO - Scheduler has been shut down
2023-02-04 11:15:56,272 - telegram.ext._application - INFO - Application.stop() complete
```

Not sure how I could help further debugging your issue.
