### ISSUE TITLE
[BUG] HTTP/2 yields errors

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3556]
We introduced HTTP/2 support by default in #3506. This lead to two problems:

1) Connection to a local bot api instance without proxy leads to a broken connection, since the local api only supports HTTP/1.0 or HTTP/1.1. While this can be fixed by the user if they run a proxy in front of it which is capable of resolving HTTP/2 requests, this is an unnecessary strain to the end user. I propose the following:
    - [ ] whenever local_mode or http_version is called, check if the http is set to 2/local mode is set to true. If yes, raise a PTBUserWarning that this will probably not work out.
        - [ ] (maybe also when changing the URLs?)
    - [ ] when building, reset http to 1.1 if we still decide it should be 2 by default and if local mode is true. Don't do that if http is explicitly set to 2.
    - [ ] add a big note to the docs about all this to the http_version command

2) For two users in our report chat, the long polling getUpdates process broke. For now, we do not know why. I will try to see if I can get it to fail with curl or a different back-end over the coming days, but if I can't find the reason why/reproduce it reliable enough to report it to the api developer, we should consider changing our default to 1.1.

    Related traceback, courtesy of @Trifase https://nekobin.com/fuluyanoja.py

### Workaround

If you're getting connection errors, such as the one in the traceback, add this to your builder:

```python
builder.get_updates_http_version('1.1').http_version('1.1').build()
```

**Comment by gpchelkin** [comment]
Just to report what works and doesn't work for me right now (to extend what I reported in chat):

v20.0: http1 + webhook/polling + local mode = Works
v20.1: http1/http2 + polling + official API = Works
v20.1: http1/http2 + webhook + official API = I don't know, but should work TODO check
v20.1: http1 + webhook/polling + local mode = Doesn't work **TODO** logs/details
v20.1: http2 + webhook/polling + local mode = Doesn't work as stated in issue

Maybe I would complete the TODO stuff later.

**Comment by Poolitzer** [comment]
> v20.1: http1/http2 + webhook + official API = I don't know, but should work TODO check
> v20.1: http1 + webhook/polling + local mode = Doesn't work TODO logs/details

Both of these work for me...

**Comment by Trifase** [comment]
So, from my logs:

```Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
[2023-02-17 22:02:44] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-17 22:02:45] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-17 22:02:46] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-17 22:02:49] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-17 22:02:52] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
[2023-02-18 00:45:16] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 00:45:17] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 00:45:18] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 00:45:20] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 00:45:24] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
[2023-02-18 03:32:14] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 03:32:15] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 03:32:17] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 03:32:19] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 03:32:22] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
[2023-02-18 06:19:17] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 06:19:18] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 06:19:20] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 06:19:22] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 06:19:25] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
[2023-02-18 08:59:45] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 08:59:46] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 08:59:47] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 08:59:49] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
[2023-02-18 08:59:53] ERROR!
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
```

It seems the the error is caused by a single `RECV_WINDOW_UPDATE` whatever that is, and chains 4 more errors down the line, in the next 8 seconds. The timings are always the same. 
This occur even when the bot is doing literally nothing and just fetching updates, like in the middle of the night.

Here is the full traceback of one chain:

```Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/h2/connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.RECV_WINDOW_UPDATE: 13>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/http2.py", line 114, in handle_async_request
    status, headers = await self._receive_response(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/http2.py", line 231, in _receive_response
    event = await self._receive_stream_event(request, stream_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/http2.py", line 262, in _receive_stream_event
    await self._receive_events(request, stream_id)
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/http2.py", line 283, in _receive_events
    events = await self._read_incoming_data(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/http2.py", line 345, in _read_incoming_data
    events = self._h2_state.receive_data(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/h2/connection.py", line 1487, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/h2/connection.py", line 1728, in _receive_window_update_frame
    events = self.state_machine.process_input(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/h2/connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 252, in handle_async_request
    raise exc
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpcore/_async/http2.py", line 144, in handle_async_request
    raise LocalProtocolError(exc)  # pragma: nocover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
httpcore.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 200, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
    raise exc
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/_bot.py", line 3510, in get_updates
    await self._post(
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 224, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED```

**Comment by Bibo-Joshi** [comment]
https://github.com/python-hyper/h2/issues/1199 looks related to the traceback that @Trifase posted

**Comment by Bibo-Joshi** [comment]
About issuing warnings: Pools suggestions mention the methods of `ApplicationBuilder`. If we issue the warnings there, then the user won't get a warnings if they build a `Bot` instance manually. Hence an alternative approach would be to issue the warning in `Bot.__init__`. For that we need to be able to know the http version of the `(get_updates_)request` - for that we could add corresponding property to `HTTPXRequest`.

**Comment by gpchelkin** [comment]
> > v20.1: http1 + webhook/polling + local mode = Doesn't work TODO logs/details

> Both of these work for me...

So I realised what doesn't work for me exactly - I use separate (non-Application) telegram.Bot object (for standalone send_audio/video functions), and it is not possible to set it to use http 1.1 as of now if I understood correctly. Maybe it would be nice to have such an option as quick fix :)

**Comment by Bibo-Joshi** [comment]
You can specify that via Parameter http_version of telegram.request.HTTPXRequest if you manually pass Parameter request of telegram.Bot and Parameter get_updates_request of telegram.Bot :)

**Comment by gpchelkin** [comment]
Thank you! [It resolved](https://github.com/gpchelkin/scdlbot/commit/fa1ac9ce81f0092f0ddd45271a98135a7266186b#diff-aec2c573455106fd918e0a9c44dd7036048ca50b7a8511dbeec5fe6b06b18ce6) my issue with fallback http 1.1 on v20.1. Updated my first post.

**Comment by Bibo-Joshi** [comment]
@Bibo-Joshi test comment

**Comment by digitalfox** [comment]
same issue here (same stack trace - happens randomly) with official telegram API server (not local mode) and no proxy.

**Comment by Poolitzer** [comment]
Yes, that it happens with the api.telegram.org api is not an open question, next step is to find a proper way to reproduce them.

**Comment by Poolitzer** [comment]
Alright. I finally got my act together to properly test this, sorry for the delay. 

I let a curl script run for the better part of a day and while it got a disconnect error, it never had the ProtocolError the other people where facing. I let the script do the same but implemented it in python-telegram-bot and I also got the error! (_Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED_ and _Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED_).
So either curl hides the error or we trust the find of hinrich and the http2 implementation of httpx is flawed in this regard. I tend towards the latter option.

Given that, I would vote to revert the http version back to 1.1 by default until that issue is closed. I would still want to implement the UserWarning when setting http to 2 and local mode/custom URL is enabled.

**Comment by Bibo-Joshi** [comment]
> Given that, I would vote to revert the http version back to 1.1 by default until that issue is closed. I would still want to implement the UserWarning when setting http to 2 and local mode/custom URL is enabled.

Would be fine with me. About the warning, I'd like to go with https://github.com/python-telegram-bot/python-telegram-bot/issues/3556#issuecomment-1435718414

I subscribed to https://github.com/python-hyper/h2/issues/1199 to get notified about status changes.

> add a big note to the docs about all this to the http_version command

IMO it suffices for the note to contain two points:

1. self-hosted api servers don't support HTTP/2 out of the box
2. v1.1 should be considered more robest than v2. Maybe link to https://www.python-httpx.org/http2/

Who would like to send a PR for this?

**Comment by Poolitzer** [comment]
I thought about the issue and was able to verify that the error comes from nginx (which runs in front of the bot API) closing the connection with this minimal example:
```python
import httpx

client = httpx.Client(http2=True, verify=False)
response = client.get("https://localhost:1908")
response2 = client.get("https://localhost:1908")
response3 = client.get("https://localhost:1908")
```

and

```
server {
        listen 1908 http2 ssl;
        http2_max_requests 2;
        ssl_certificate /home/poolitzer/RootCA.crt;
        ssl_certificate_key /home/poolitzer/RootCA.key;
}
```

This results in the same error we face, thus we can enable http2 again when python-hyper/h2#1199 is fixed.
