### ISSUE TITLE
[QUESTION] Local bot api server

### ISSUE THREAD

**Issue by klynch999** [python-telegram-bot/python-telegram-bot#3567]
### Local bot api server

I am trying to get my bot running in local mode on the telegram bot api server. I have downloaded and installed all prerequisites, and set up the server. Here is my main() function.

```
async def main() -> None:

builder = Application.builder()
builder.token(token)
builder.http_version('1.1')
builder.get_updates_http_version('1.1')
builder.base_url(r'http://localhost:8081/bot')
builder.base_file_url(r'http://localhost:8081/file/bot')
builder.local_mode(local_mode = True)
app = builder.build()
         
conv_handler1 = ...
conv_handler2 = ...

app.add_handler(conv_handler1)
app.add_handler(conv_handler2)

await app.run_polling()
token = "..."
nest_asyncio.apply()

if __name__ == "__main__":
    asyncio.run(main())
```

I have looked at netstat and I've found the following:

TCP 127.0.0.1:8081 127.0.0.1:53515 ESTABLISHED 25732
TCP MY_IP:53513 149.154.167.92:443 ESTABLISHED 25732

with the pid 25732 the one belonging to the running of telegram-bot-api.exe

When I run the bot it connects and I can send/recieve commands, messages and files perfectly well. But when I attempt to send the
bot a file of size > 50mb I get the telegram.error.BadRequest: File is too big error, indicating that the bot is not running is local mode.
FTR here is the command I am using to start the api server:

./telegram-bot-api --api-id=??? --api-hash=??? --local

When I ping the server with:
curl -X POST 127.0.0.1:8081/bot{MYTOKEN}/getUpdates
I get:
{"ok":true,"result":[]}

What am I doing wrong???

### Traceback to the issue

```python
Traceback (most recent call last):
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\ext\_conversationhandler.py", line 826, in handle_update
    new_state: object = await handler.handle_update(
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "C:\Users\kiera\AppData\Local\Temp/ipykernel_42528/880042335.py", line 44, in detect_file_type
    file = await bot.get_file(file_id)
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\_bot.py", line 2879, in get_file
    result = await self._post(
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "C:\Users\kiera\anaconda3\lib\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: File is too big
```

### Operating System

WINDOWS 64 BIT

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
```

**Comment by Bibo-Joshi** [comment]
Just to clarify: the exception originates from the API Server, i.e. PTB just forwards it. This is at least a strong indication that there's nothing wrong on PTBs side.
Did you maybe forget to `logOut` from the cloud API instance?

**Comment by klynch999** [comment]
I have called logOut() , I have even generated a new bot and token.

**Comment by Bibo-Joshi** [comment]
All right. Can you provide an [MWE](../wiki/MWE) and an example file so that someone can try and reproduce the issue?
Can you also please try to run your code with vanilly python instead of ipython?
