### ISSUE TITLE
[BUG] SSL read failure in edit_message_reply_markup 

### ISSUE THREAD

**Issue by IlyaBizyaev** [python-telegram-bot/python-telegram-bot#3570]
### Steps to Reproduce

I have a bot with multiple command and callback query handlers that I am migrating from a pre-async PTB version. It mostly works as expected, but there is a mysterious error that often (~50% of the time) gets raised from `edit_message_reply_markup` when I update inline keyboards (see traceback below). The keyboards are basically like counters, nothing crazy. So far I could not reproduce it with other methods. The pre-async PTB never raised similar exceptions from `edit_message_reply_markup`.

### Expected behaviour

`edit_message_reply_markup` completes successfully.

### Actual behaviour

`edit_message_reply_markup` raises an exception from `anyio`'s code when handling `SSLWantReadError`. AFAIU `SSLWantReadError` itself does not indicate a problem: https://docs.python.org/3/library/ssl.html#notes-on-non-blocking-sockets. The problem is that some internal future gets cancelled, but I definitely don't cancel any futures from my code :)

The error gets converted to `TimeoutError` in `httpcore` and handled accordingly afterwards, but the root cause does not look like a timeout (and it is raised shortly after the request).

### Operating System

Ubuntu 22.04.2 LTS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

### Relevant log output

```python
Traceback (most recent call last):
  File "python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.10/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "python3.10/site-packages/httpcore/backends/asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "python3.10/site-packages/httpcore/_async/http2.py", line 144, in handle_async_request
    raise exc
  File "python3.10/site-packages/httpcore/_async/http2.py", line 112, in handle_async_request
    status, headers = await self._receive_response(
  File "python3.10/site-packages/httpcore/_async/http2.py", line 229, in _receive_response
    event = await self._receive_stream_event(request, stream_id)
  File "python3.10/site-packages/httpcore/_async/http2.py", line 260, in _receive_stream_event
    await self._receive_events(request, stream_id)
  File "python3.10/site-packages/httpcore/_async/http2.py", line 281, in _receive_events
    events = await self._read_incoming_data(request)
  File "python3.10/site-packages/httpcore/_async/http2.py", line 341, in _read_incoming_data
    raise exc
  File "python3.10/site-packages/httpcore/_async/http2.py", line 327, in _read_incoming_data
    data = await self._network_stream.read(self.READ_NUM_BYTES, timeout)
  File "python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "python3.10/site-packages/telegram/request/_httpxrequest.py", line 199, in do_request
    res = await self._client.request(
  File "python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mybot/bot.py", line 40, in report_error
    raise error
  File "mybot/mybot.py", line 1012, in refresh_fb_command
    await self.get_tg_bot().edit_message_reply_markup(channel_id, msg_id,
  File "python3.10/site-packages/telegram/ext/_extbot.py", line 1423, in edit_message_reply_markup
    return await super().edit_message_reply_markup(
  File "python3.10/site-packages/telegram/_bot.py", line 331, in decorator
    result = await  func(*args, **kwargs)  # skipcq: PYL-E1102
  File "python3.10/site-packages/telegram/_bot.py", line 3422, in edit_message_reply_markup
    return await self._send_message(
  File "python3.10/site-packages/telegram/ext/_extbot.py", line 488, in _send_message
    result = await super()._send_message(
  File "python3.10/site-packages/telegram/_bot.py", line 512, in _send_message
    result = await self._post(
  File "python3.10/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "python3.10/site-packages/telegram/ext/_extbot.py", line 326, in _do_post
    return await self.rate_limiter.process_request(
  File "python3.10/site-packages/telegram/ext/_aioratelimiter.py", line 247, in process_request
    return await self._run_request(
  File "python3.10/site-packages/telegram/ext/_aioratelimiter.py", line 203, in _run_request
    return await callback(*args, **kwargs)
  File "python3.10/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "python3.10/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "python3.10/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
  File "python3.10/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

### Additional Context

Relevant library versions:
```
anyio==3.6.2
httpcore==0.16.3
httpx==0.23.3
python-telegram-bot==20.1
```

I tried disabling HTTP/2 per https://github.com/python-telegram-bot/python-telegram-bot/issues/3556, it doesn't help, so it's probably unrelated.

**Comment by IlyaBizyaev** [comment]
Turns out that the traceback was simply confusing, and it is, in fact, a timeout: somehow reading Telegram's responses for `edit_message_reply_markup` timed out. I set an override for `read_timeout` in all `edit_message_reply_markup` calls to 10 seconds, and now the error is gone. I wonder why I never had to do this with old versions of PTB, but it might be that my code is somehow to blame, so I will close this issue for now.

**Comment by Poolitzer** [comment]
> I  set an override for read_timeout in all edit_message_reply_markup calls to 10 seconds, and now the error is gone.

That sounds a lot of work and I doubt just this method will raise the error, you can set the read_timeout globally: https://docs.python-telegram-bot.org/en/stable/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.read_timeout

**Comment by IlyaBizyaev** [comment]
Thanks — indeed, reproduced the timeout issue with another method, so set the `read_timeout` globally now.
