### ISSUE TITLE
[BUG] Unexpected File too large

### ISSUE THREAD

**Issue by gaardiolor** [python-telegram-bot/python-telegram-bot#3608]
### Steps to Reproduce

1. version 13.15
2. Create an html string in variable `html`
3. Check the size: `logger.info(f"Document size: {len(html)}")`
4. Send it: `bot.send_document(chat_id=chat_id, document=html, filename=f"test.html")`

### Expected behaviour

According to the documentation, I should be able to send html files of 50MB. 

### Actual behaviour

Document size: 3613274
telegram.error.NetworkError: File too large. Check telegram api limits https://core.telegram.org/bots/api#senddocument

```
2023-03-19 22:23:05,453 [    INFO] Document size: 3613274
2023-03-19 22:23:05,598 [   ERROR] No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/sp/user_data/scripts/sendplot.py", line 132, in plot_handler
    gen_graph_mp(trade_id, timeframe)
  File "/sp/user_data/scripts/sendplot.py", line 158, in gen_graph_mp
    bot.send_document(chat_id=chat_id, document=html, filename=f"test.html")
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/bot.py", line 1007, in send_document
    return self._message(  # type: ignore[return-value]
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/gaardiolor/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 285, in _request_wrapper
    raise NetworkError(
telegram.error.NetworkError: File too large. Check telegram api limits https://core.telegram.org/bots/api#senddocument
```

### Operating System

docker

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.10
python-telegram-bot 13.15
```

**Comment by harshil21** [comment]
Hmm, I don't think doing `len(html)` is going to give you the correct size occupied by the html file. You should use [`os.path.getsize`](https://docs.python.org/3/library/os.path.html#os.path.getsize) instead. In any case, this is outside the scope of the PTB library, this exception is just forwarded from the Telegram servers.
