### ISSUE TITLE
[BUG] A network error occurred after changing http version to 1.1

### ISSUE THREAD

**Issue by ImZhangAo** [python-telegram-bot/python-telegram-bot#3612]
### Steps to Reproduce

1. Docker will appear after deploying the application and using the proxy and placing it for a period of time

### Expected behaviour

Normal continuous operation without error reporting or catch or retry after an error occurs

### Actual behaviour

A network error has occurred and cannot be captured

### Operating System

Windows11

### Version of Python, python-telegram-bot & dependencies

```shell
python==3.10
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
APScheduler==3.10.1
async-timeout==4.0.2
attrs==22.2.0
charset-normalizer==3.1.0
frozenlist==1.3.3
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.16.3
httpx==0.23.3
hyperframe==6.0.1
idna==3.4
multidict==6.0.4
pydantic==1.10.6
python-dotenv==1.0.0
python-telegram-bot==20.1
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
rfc3986==1.5.0
six==1.16.0
sniffio==1.3.0
socksio==1.0.0
typing_extensions==4.5.0
tzdata==2022.7
tzlocal==4.2
wincertstore==0.2
yarl==1.8.2
```

### Relevant log output

```python
2023-03-21 00:54:43,076 - telegram.ext._updater - ERROR - Error while getting Updates: httpx.ConnectError: 
 2023-03-21 00:54:43,077 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
     result = func(*args)
   File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
     self._sslobj.do_handshake()
 ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:997)
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
     yield
   File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 78, in start_tls
     raise exc
   File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 69, in start_tls
     ssl_stream = await anyio.streams.tls.TLSStream.wrap(
   File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 122, in wrap
     await wrapper._call_sslobject_method(ssl_object.do_handshake)
   File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 151, in _call_sslobject_method
     raise BrokenResourceError from exc
 anyio.BrokenResourceError
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
     yield
   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
     resp = await self._pool.handle_async_request(req)
   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
     raise exc
   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
     response = await connection.handle_async_request(request)
   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http_proxy.py", line 289, in handle_async_request
     stream = await stream.start_tls(**kwargs)
   File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 66, in start_tls
     with map_exceptions(exc_map):
   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
     self.gen.throw(typ, value, traceback)
   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
     raise to_exc(exc)
 httpcore.ConnectError
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 199, in do_request
     res = await self._client.request(
   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
     response = await self._send_handling_auth(
   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
     response = await self._send_handling_redirects(
   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
     response = await self._send_single_request(request)
   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
     response = await transport.handle_async_request(request)
   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
     with map_httpcore_exceptions():
   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
     self.gen.throw(typ, value, traceback)
   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
     raise mapped_exc(message) from exc
 httpx.ConnectError

 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
     if not await action_cb():
   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
     raise exc
   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
     updates = await self.bot.get_updates(
   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
     updates = await super().get_updates(
   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 331, in decorator
     result = await func(*args, **kwargs)  # skipcq: PYL-E1102
   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 3510, in get_updates
     await self._post(
   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 419, in _post
     return await self._do_post(
   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
     return await super()._do_post(
   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 450, in _do_post
     return await request.post(
   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
     result = await self._request_wrapper(
   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
     raise exc
   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
     code, payload = await self.do_request(
   File "/usr/local/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 223, in do_request
     raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
 telegram.error.NetworkError: httpx.ConnectError:
```

### Additional Context

Hi guys, I have modified the http version to 1.1, but the problem still exists. However, it may be due to fluctuations in the http proxy that caused it to disconnect, but there should be a way to capture and process it or try it again. Currently, I am still unable to process it. 
```python
self.application = ApplicationBuilder().token(self.token).proxy_url(self.proxy_url).http_version("1.1") \
            .get_updates_http_version("1.1").get_updates_proxy_url(self.proxy_url).build()
```
I hope there can be a better way to handle it, thank you

**Comment by Bibo-Joshi** [comment]
Hi. Using HTTP/1.1 doesn't guarantee that all networking transactions will always be sucessful. In this case there apparently has been an issue with the SSL handshake, which in turn may be due to your proxy configurations. Please also have a look at our wiki page on [network errors](../wiki/Handling-network-errors).

If you'd like for failing http requests to be automatically retried, I recommend to implement your own version of [`BaseRequest`](wiki/Handling-network-errors) or to subclass the built-in [`HTTPXRequest`](https://docs.python-telegram-bot.org/en/stable/telegram.request.httpxrequest.html). See also [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Architecture)

As far as I see, this is not a bug in PTB.
