### ISSUE TITLE
[FEATURE] More convenient exception logging

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3613]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Pythons default tracbeack representation can make it hard for users to find the place in *their* code that triggered the exception, i.e. a line in a job/handler callback. Example from https://t.me/pythontelegrambotgroup/664696

<details>

```python
2023-03-14 03:48:40,949 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/becky/Letters-With-Friends/telegram/ext/_application.py", line 1115, in process_update
    await coroutine
  File "/home/becky/Letters-With-Friends/telegram/ext/_conversationhandler.py", line 826, in handle_update
    new_state: object = await handler.handle_update(
  File "/home/becky/Letters-With-Friends/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/home/becky/Letters-With-Friends/HottieBottie copy 2.py", line 290, in waitforanswer
    await poll(update, context, str(currentPuzzle), values)
  File "/home/becky/Letters-With-Friends/HottieBottie copy 2.py", line 179, in poll
    message = await context.bot.send_poll(
  File "/home/becky/Letters-With-Friends/telegram/ext/_extbot.py", line 2690, in send_poll
    return await super().send_poll(
  File "/home/becky/Letters-With-Friends/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/home/becky/Letters-With-Friends/telegram/_bot.py", line 6033, in send_poll
    return await self._send_message(
  File "/home/becky/Letters-With-Friends/telegram/ext/_extbot.py", line 488, in _send_message
    result = await super()._send_message(
  File "/home/becky/Letters-With-Friends/telegram/_bot.py", line 512, in _send_message
    result = await self._post(
  File "/home/becky/Letters-With-Friends/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/home/becky/Letters-With-Friends/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "/home/becky/Letters-With-Friends/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/home/becky/Letters-With-Friends/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/home/becky/Letters-With-Friends/telegram/request/_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse options json object
```

</details>

The lines most relevant for the user are

```python
  File "/home/becky/Letters-With-Friends/HottieBottie copy 2.py", line 290, in waitforanswer
    await poll(update, context, str(currentPuzzle), values)
  File "/home/becky/Letters-With-Friends/HottieBottie copy 2.py", line 179, in poll
    message = await context.bot.send_poll(
  File "/home/becky/Letters-With-Friends/telegram/ext/_extbot.py", line 2690, in send_poll
    return await super().send_poll(
```

and

```python
telegram.error.BadRequest: Can't parse options json object
```

### Describe the solution you'd like

It would be nice if we could provide the user with a way to narrow down the tracebacks to the parts relevant for them. The full traceback should still also be available for debug purposes.

If we find a satisfying solution for that, one could think about using that for the default logging at 

https://github.com/python-telegram-bot/python-telegram-bot/blob/33b677aeb4a3e601668103914a70e633908e90b2/telegram/ext/_application.py#L1641

and logging the full traceback only at debug level.

How exactly such a mechanism would look like is not entirely clear. Challenges include, but are not limited to,

* parse tracebacks - the functions and classes of the [`traceback`](https://docs.python.org/3/library/traceback.html) std-lib may help
* We'd want to filter out any non-user code, which includes 3rd party libraries (i.e. non-ptb libs)
* There may be cases where there is no user-code at all - see #3556, where the exception happens during the `get_updates` calls of `run_polling`

### Additional context

* apparently some frameworks have a custom solution for things like this: https://stackoverflow.com/questions/39361321/whats-the-usage-of-traceback-hide. I haven't investigated yet how that's done
* After thinking about this a bit more, I would actually tend to say that coming up with a custom solution is beyond the scope of PTB. Feasible solutions would IMO include
  * providing the users with pointers to best-practice/viable solutions
  * if there is some 3rd party library that can help with these issues, include that as optional dependency

**Comment by Bibo-Joshi** [comment]
About pytests `__tracebackhidden__`: The logic for traceback handling in pytest is apparently rather involved. Apart from the `ishidden` function at

https://github.com/pytest-dev/pytest/blob/2369bed1db7a2c840e2f651bbef37eaa112f1c0d/src/_pytest/_code/code.py#L275-L300

the file basically contains wrappers for frames, traceback entries and tracebacks + a lot more. Note also the lines 

https://github.com/pytest-dev/pytest/blob/2369bed1db7a2c840e2f651bbef37eaa112f1c0d/src/_pytest/_code/code.py#L310-L312

**Comment by Bibo-Joshi** [comment]
I dug around this topic a bit more and actually found a library that highlights a specified directory in the traceback: https://github.com/skorokithakis/tbvaccine/

Also I found that there really are quite a number of traceback formatting libraries - see e.g. "Alternatives" listed here: https://pypi.org/project/pretty-traceback/

The more I think about this the more I get the impression that even a best practice guide is out of scope for ptb …

**Comment by Bibo-Joshi** [comment]
I'll just go ahead and close this …
