### ISSUE TITLE
[QUESTION] telegram.error.NetworkError: Bad Gateway

### ISSUE THREAD

**Issue by decayassault** [python-telegram-bot/python-telegram-bot#3650]
### Steps to Reproduce

Cannot reproduce.

### Expected behaviour

Error while getting Updates: Bad Gateway
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
    if not await action_cb():
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/_extbot.py", line 530, in get_updates
    updates = await super().get_updates(
  File "/usr/local/lib/python3.8/dist-packages/telegram/_bot.py", line 368, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/usr/local/lib/python3.8/dist-packages/telegram/_bot.py", line 3623, in get_updates
    await self._post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/_bot.py", line 456, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/_extbot.py", line 312, in _do_post
    return await super()._do_post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/_bot.py", line 487, in _do_post
    return await request.post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.8/dist-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    raise NetworkError(description or "Bad Gateway")

### Actual behaviour

After restarting, it's ok.

### Operating System

Ubuntu 20

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2
Bot API 6.6
Python 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]
```

**Comment by Poolitzer** [comment]
@decayassault There was an issue with the connection to the Telegram API. It&#x27;s the internet, that can happen. Either a middleman errored out or Telegram did. Where exactly is your question?

**Comment by decayassault** [comment]
I have wrapped all code into try except block in every Python function. How to catch this Exception?

**Comment by Poolitzer** [comment]
@decayassault You cant when using application.start_polling, since this call happens inside the library. But you can use an error_handler if you still want to do something with it.
