### ISSUE TITLE
[QUESTION] How do I send photo to telegram user? I would like to broadcast photos to user of my another app, where I already collected their telegram id. 

### ISSUE THREAD

**Issue by JonahTzuChi** [python-telegram-bot/python-telegram-bot#3679]
### Issue I am facing

My bot failed to send photo to user. Below I have two functions, `sendPhoto` and `sendMessage`. I manage to execute `sendMessage` without issue, however `sendPhoto` return error I attached below. 

What I did tried was

1. python-telegram-bot version might be overkill, so I tried with PTB13.13. But failed with the same error.

```
import telegram
import asyncio

async def sendPhoto(bot, target_id):
    res = await bot.send_photo(
        chat_id=target_id,
        photo=open("./Static/arG92Ld_460s.jpg", "rb"),
        caption="Telegram Trial Photo",
        reply_to_message_id=6197492143,
    )
    print(res)

async def sendMessage(bot, target_id):
    res = await bot.bot.sendMessage(chat_id=target_id, text="happy")
    print(res)

TOKEN = "<TOKEN>" # str
bot = telegram.Bot(token=TOKEN)
USER_TELEGRAM_ID = <chat_id> # int
asyncio.run(sendPhoto(bot, USER_TELEGRAM_ID))
```

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/home/jonah/Documents/projects/Telehealth/Scripts/simple_bot.py", line 24, in <module>
    asyncio.run(sendPhoto(bot, USER_TELEGRAM_ID))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/jonah/Documents/projects/Telehealth/Scripts/simple_bot.py", line 8, in sendPhoto
    res = await bot.send_photo(
  File "/home/jonah/.local/lib/python3.10/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/home/jonah/.local/lib/python3.10/site-packages/telegram/_bot.py", line 996, in send_photo
    return await self._send_message(
  File "/home/jonah/.local/lib/python3.10/site-packages/telegram/_bot.py", line 512, in _send_message
    result = await self._post(
  File "/home/jonah/.local/lib/python3.10/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/home/jonah/.local/lib/python3.10/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/home/jonah/.local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/home/jonah/.local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Replied message not found
```

### Related part of your code

```python
async def sendPhoto(bot, target_id):
    res = await bot.send_photo(
        chat_id=target_id,
        photo=open("./Static/arG92Ld_460s.jpg", "rb"),
        caption="Telegram Trial Photo",
        reply_to_message_id=6197492143,
    )
    print(res)
```
```


### Operating System

Ubuntu 22.04, Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
# Ubuntu 22.04
python-telegram-bot 20.1
Bot API 6.5
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

# Windows 11
python-telegram-bot 13.13
Bot API 6.1
certifi2022.12.07
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC V.1932 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Well, it didn't find the reply to message id, so that's why it can't send the photo. Either pass a correct one or set `allow_sending_without_reply` to True to not have it fail.

**Comment by JonahTzuChi** [comment]
> Well, it didn't find the reply to message id, so that's why it can't send the photo. Either pass a correct one or set `allow_sending_without_reply` to True to not have it fail.

Wao! It works!!! Thank you very much!!!

```
async def sendPhoto(bot, target_id):
    res = await bot.send_photo(
        chat_id=target_id,
        photo=open("./Static/arG92Ld_460s.jpg", "rb"),
        caption="Telegram Trial Photo",
        reply_to_message_id=6197492143,
        allow_sending_without_reply=True
    )
    print(res)

```
