### ISSUE TITLE
[QUESTION] TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by masoudnick** [python-telegram-bot/python-telegram-bot#3699]
### Issue I am facing

Hi
I have run my bot on an Ubuntu server, when I checked the log file of the bot, I noticed that an error was registered several times, but I don't know what the error is and why it happens.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/root/omidfadavi_bot/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 1115, in process_update
    await coroutine
  File "/root/omidfadavi_bot/venv/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
TypeError: object NoneType can't be used in 'await' expression
```

### Related part of your code

```python
2023-05-10 13:37:32,444 - telegram.ext._application - process_error - 1641 - No error handlers are registered, logging exception.
```

### Operating System

ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python V3.10
python-telegram-bot V20.2
```

**Comment by Bibo-Joshi** [comment]
Have have passed `None` to the `callback` argument of one of your handlers. It must be a callback function. Please be sure to read the [tutorial](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions---Your-first-Bot).

**Comment by masoudnick** [comment]
Ok, thankss ;)
