### ISSUE TITLE
[QUESTION] How to be sure that a message is sent in version 20?

### ISSUE THREAD

**Issue by Rabelaiss** [python-telegram-bot/python-telegram-bot#3704]
### Issue I am facing

When I was on versions < 20, I used to use a loop like this to be sure that a message was sent

```
for i in range(99):
    try:
        bot.send_media_group(...)
        break
    except:
        ...
```

After updating to 20 and reading the new "Introduction to the API" and the "Transition guide to Version 20.0", I edited the code to comply the structural changes.
Sometimes the new code works, i.e. the message is sent and the loop is stopped, but other times it raises a `TimedOut` error and the message is sent anyway, but since an error was raised the loop is not stopped and it tries to send the message again.
Sometimes it raises `TimedOut` multiple times and it ends up sending several times the same message.

I tried to assign the returned value of `asyncio.run(...)` to the variable `output`, to see that if it could be used to properly stop the loop in the case the message was sent, but when the message is sent without errors `output` just contains `None`.

Am I doing something wrong?

### Related part of your code

```python
import telegram, asyncio, time, traceback

async def send_media(media_group):
    bot = telegram.Bot(token = "...")
    async with bot:
        await bot.send_media_group(chat_id="...", media=media_group, disable_notification=True)

for i in range(3):
    try:
        media_group = []
        media_group.append(telegram.InputMediaDocument(open('image_path', 'rb'), caption=f'try number {i}'))
        output = asyncio.run(send_media(media_group))
        print('success', output)
        break
    except:
        traceback.print_exc()
        print('\n---------------------------------\n')
        time.sleep(2)
```

### Traceback to the issue

```python
Traceback (most recent call last):
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 921, in read
    v = self._sslobj.read(len)
        ^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2576)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\streams\tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_core\_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_httpxrequest.py", line 216, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gianni\Desktop\python ubuntu wsl\breg_w.py", line 12, in <module>
    output = asyncio.run(send_media(media_group))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\gianni\Desktop\python ubuntu wsl\breg_w.py", line 6, in send_media
    await bot.send_media_group(chat_id="@testcvid19", media=media_group, disable_notification=True)
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 381, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 2100, in send_media_group
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 469, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 497, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 291, in _request_wrapper
    raise exc
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 277, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gianni\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_httpxrequest.py", line 233, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

### Operating System

Windows 10 Home 22H2

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3
Bot API 6.7
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
```

**Comment by Rabelaiss** [comment]
Thanks @harshil21 do you mean this?

```
async def send_media(media_group):
    async with bot:
        return await bot.send_media_group(chat_id="...", media=media_group, read_timeout=33, write_timeout=33)

for i in range(3):
    try:
        path = 'C:\\Users\\gianni\\Desktop\\python ubuntu wsl\\test.jpg'
        media_group = []
        media_group.append(telegram.InputMediaDocument(open(path, 'rb'), caption=f'attempt {i}'))
        media_group.append(telegram.InputMediaDocument(open(path, 'rb'), caption=f'try number {i}'))
        media_group.append(telegram.InputMediaDocument(open(path, 'rb'), caption=f'try number {i}'))
        media_group.append(telegram.InputMediaDocument(open(path, 'rb'), caption=f'try number {i}'))
        media_group.append(telegram.InputMediaDocument(open(path, 'rb'), caption=f'try number {i}'))

        start = time.time()
        output = asyncio.run(send_media(media_group))
        print(f'{time.time() - start:.1f} seconds, ', end='')
        if type(output) == tuple:
            print('success')
            break
        else:
            print('fail', type(output))

    except
```

It seems to work, however in few cases it still gives "Timed out" error and the message is sent anyway. When this occurs, even if I have a `output = asyncio.run(send_media(media_group))`

**Comment by Bibo-Joshi** [comment]
In this case, TG receives your request and the timeout happens while your bot as waiting for a reply from TG. That reply would contain the information about the resulting messages. So a timeout exception does not necessarily imply that the request was unsuccessful.

**Comment by Rabelaiss** [comment]
Many thanks @Bibo-Joshi 
From what you said it seems that using my code above is not possible to be 100% certain that a message is not sent twice or more times, is it?
Maybe we can avoid the problem by checking the id of the last message sent in the channel before sending a new one? If after a timeout the id has changed anyway, then it means that the message was successfully sent despite the timeout.
What do you think?
Many thanks really appreciated

**Comment by Bibo-Joshi** [comment]
> From what you said it seems that using my code above is not possible to be 100% certain that a message is not sent twice or more times, is it?

Yes

> Maybe we can avoid the problem by checking the id of the last message sent in the channel before sending a new one? If after a timeout the id has changed, then it means that the message was successfully sent despite the timeout. What do you think?

That doesn't sound feasible to me, no

**Comment by Poolitzer** [comment]
@Bibo-Joshi There is no way to get the last message id in a channel either

**Comment by Rabelaiss** [comment]
@Poolitzer Not even the date of the last message, the total number of messages in the channel, or something else in this fashion?

It seems very strange that there is no way to be 100% sure that a message is sent only once. With versions < 20: timeout exception raised -> message was never sent. Now: timeout exception raised -> message is always sent. It seems like something is broken, at least on my installation.

**Comment by Poolitzer** [comment]
@Rabelaiss I am actually surprised that V13 didn&#x27;t result in a send message when a timeout happens, it feels that you either set time out high enough that you always stayed below the threshold or the api changed. But a response timeout error could have meant a send message by design in V13.



Imagine you send the send message request to telegram, before it can return 200 you cut the internet. Telegram will still send the message, even though you get a timeout error, because Telegram can&#x27;t even know that an error happened on your end.

**Comment by Rabelaiss** [comment]
With v13 I never set a custom timeout, all I had to do was

```
import telegram
bot = telegram.Bot(token=...)

for attempt in range(6):
    try:
        ...
        bot.send_media_group(chat_id=..., media=...)
        break
    except:
        ...
```
I used this hundreds of times and never a message was sent after a timeout exception.

Anyway, I found a telegram python library which let me fetch channel messages, so I will use that.
