### ISSUE TITLE
[QUESTION] Reply markup on send_invoice giving error

### ISSUE THREAD

**Issue by susonsapkota** [python-telegram-bot/python-telegram-bot#3736]
### Issue I am facing

I am trying to have a close button below the pay button while sending the invoice but it's giving me errors. I tried different variations of it but had no luck.
I am getting `telegram.error.BadRequest: Reply_markup_buy_empty`

The documentation says 'reply_markup (telegram.InlineKeyboardMarkup, optional) – An object for an inline keyboard. If empty, one ‘Pay total price’ button will be shown. If not empty, the first button must be a Pay button.'

### Traceback to the issue

```python
2023-06-03 03:20:48,883 - httpx - INFO - HTTP Request: POST https://api.telegram.org/XXX/sendInvoice "HTTP/1.1 400 Bad Request"
2023-06-03 03:20:48,886 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/Users/suson/PycharmProjects/teletest/tt.py", line 83, in start_with_shipping_callback
    await context.bot.send_invoice(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 2490, in send_invoice
    return await super().send_invoice(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/_bot.py", line 381, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/_bot.py", line 4424, in send_invoice
    return await self._send_message(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 507, in _send_message
    result = await super()._send_message(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/_bot.py", line 561, in _send_message
    result = await self._post(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/_bot.py", line 469, in _post
    return await self._do_post(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 325, in _do_post
    return await super()._do_post(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/_bot.py", line 497, in _do_post
    return await request.post(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
  File "/Users/suson/PycharmProjects/teletest/venv/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Reply_markup_buy_empty
```

### Related part of your code

```python
async def start_with_shipping_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Sends an invoice with shipping-payment."""
    chat_id = update.message.chat_id
    title = "Payment Example"
    description = "Payment Example using python-telegram-bot"
    # select a payload just for you to recognize its the donation from your bot
    payload = "Custom-Payload"
    # In order to get a provider_token see https://core.telegram.org/bots/payments#getting-a-token
    currency = "USD"
    # price in dollars
    price = 1
    # price * 100 so as to include 2 decimal points
    # check https://core.telegram.org/bots/payments#supported-currencies for more details
    prices = [LabeledPrice("Test", price * 100)]

    keyboard = [
        [
            InlineKeyboardButton("Pay", callback_data="Pay"),
            InlineKeyboardButton("Close", callback_data="Close"),
        ],
        [InlineKeyboardButton("Option 3", callback_data="3")],
    ]

    reply_markup = InlineKeyboardMarkup(keyboard)

    # optionally pass need_name=True, need_phone_number=True,
    # need_email=True, need_shipping_address=True, is_flexible=True
    await context.bot.send_invoice(
        chat_id,
        title,
        description,
        payload,
        PAYMENT_PROVIDER_TOKEN,
        currency,
        prices,
        need_name=True,
        need_phone_number=True,
        need_email=True,
        need_shipping_address=True,
        is_flexible=True,
        reply_markup=reply_markup
    )
```

### Operating System

Mac

### Version of Python, python-telegram-bot & dependencies

```shell
Bot API 6.7
Python 3.9.6 (default, Mar 10 2023, 20:16:38)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
```

**Comment by Bibo-Joshi** [comment]
@susonsapkota You must pass the Parameter <a href="https://docs.python-telegram-bot.org/telegram.inlinekeyboardbutton.html#telegram.InlineKeyboardButton.params.pay">pay</a> of <a href="https://docs.python-telegram-bot.org/telegram.inlinekeyboardbutton.html#telegram.InlineKeyboardButton">telegram.InlineKeyboardButton</a> for the first inline button as described in the docs of Parameter <a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.send_invoice.params.reply_markup">reply_markup</a> of <a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.send_invoice">telegram.Bot.send_invoice</a>

**Comment by susonsapkota** [comment]
Thanks, that worked. I misunderstood the documentation.
