### ISSUE TITLE
[BUG] could nor import modules from telegram 

### ISSUE THREAD

**Issue by 0de554kw** [python-telegram-bot/python-telegram-bot#3756]
### Steps to Reproduce

1. pip install python-telegram-bot --upgrade
2. from telegram import Update
3. from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler

### Expected behaviour

1. package is installed
2. module Update available to use
3.  modules ApplicationBuilder, ContextTypes, CommandHandler available to use 

### Actual behaviour

1. passed
2.  Import error

`from telegram import Update
Traceback (most recent call last):
  File "[Userfolder]\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-92b0e05c9f4c>", line 1, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (unknown location)`

3. Import error

`
Traceback (most recent call last):
  File "[Userfolder]\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-2259acf6d76e>", line 1, in <module>
    from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[Userfolder]\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\__init__.py", line 60, in <module>
    from . import filters
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[Userfolder]\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\filters.py", line 113, in <module>
    from telegram import Chat as TGChat
ImportError: cannot import name 'Chat' from 'telegram' (unknown location)

`

### Operating System

Windows11

### Version of Python, python-telegram-bot & dependencies

```shell
$ python --version
Python 3.10.7

the package has got from https://pypi.org/project/python-telegram-bot/ version 20.3
```

### Additional Context

Tried tutorial https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions---Your-first-Bot

**Comment by Bibo-Joshi** [comment]
@0de554kw Wiki of <i>python-telegram-bot</i> - Category <i>FAQ</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram">Why am I getting ImportError: cannot import name &#x27;XY&#x27; from &#x27;telegram&#x27;?</a>

**Comment by 0de554kw** [comment]
> @0de554kw Wiki of python-telegram-bot - Category FAQ [Why am I getting ImportError: cannot import name 'XY' from 'telegram'?](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram)

No way, firstly i've really couth on 'telegram' package but after that I realize my mistake. Now the picture is 
$ pip freeze | grep telegram
python-telegram-bot==20.3
