### ISSUE TITLE
[QUESTION] TypeError: start() missing 2 required positional arguments: 'update' and 'context'

### ISSUE THREAD

**Issue by Vihria** [python-telegram-bot/python-telegram-bot#3771]
### Issue I am facing

Hello

Im trying to launch any examples of bots (from this git) and always get this error when send command to bot -

[2023-06-23 13:36:19,078] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/user/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/python3.8/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/user/lib/python3.8/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
TypeError: start() missing 2 required positional arguments: 'update' and 'context'

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3
Bot API 6.7
Python 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
```

**Comment by Bibo-Joshi** [comment]
@Vihria Hi. None of our examples work with flask. Please show the code of the example that you are using and/or provide a link to it.

**Comment by Vihria** [comment]
You are right, sorry. I missed this about Flask. I updated my code to work with Flask and all now is fine!
