### ISSUE TITLE
[QUESTION] Asynchronous code won't run: RuntimeError

### ISSUE THREAD

**Issue by iyamk** [python-telegram-bot/python-telegram-bot#3794]
### Steps to Reproduce

Code:
```
import asyncio
from telegram import Update, BotCommand
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes

async def hello(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(f'Hello {update.effective_user.first_name}')

app = ApplicationBuilder().token('your token').build()

app.add_handler(CommandHandler('hello', hello))

async def test():
    await app.bot.set_my_commands([
        BotCommand('start', 'Starting')
    ])

def main():
    asyncio.run(test())
    app.run_polling()

if __name__ == '__main__':
    main()
```

### Expected behaviour

Everything is working

### Actual behaviour

```
Traceback (most recent call last):
  File "/FILES/bot/main.py", line 22, in <module>
    main()
  File "/FILES/bot/main.py", line 19, in main
    app.run_polling()
  File "/FILES/bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 752, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/FILES/bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 917, in __run
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 677, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
sys:1: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited
```

### Operating System

Arch linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4
Bot API 6.7
Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
```

### Additional Context

I need examples of how to use the bot with asyncio, where can I find them?

**Comment by Bibo-Joshi** [comment]
@iyamk Hi. asyncio.run closes the event loop once it&#x27;s done so <a href="https://docs.python-telegram-bot.org/telegram.ext.application.html#telegram.ext.Application.run_polling">telegram.ext.Application.run_polling</a> can&#x27;t reuse it. For your use case, there is <a href="https://docs.python-telegram-bot.org/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.post_init">telegram.ext.ApplicationBuilder.post_init</a> available.
