### ISSUE TITLE
[QUESTION]How to use apscheduler to send information periodically

### ISSUE THREAD

**Issue by lingyunQAQ** [python-telegram-bot/python-telegram-bot#3795]
### Issue I am facing

I want to use apscheduler to send messages periodically. I pass the context parameter to the report file in the same directory

### Traceback to the issue

```python
Traceback (most recent call last):
  File "D:\do\ur\op\venv\lib\site-packages\telegram\ext\_application.py", line 1173, in process_update
    await coroutine
  File "D:\do\ur\op\venv\lib\site-packages\telegram\ext\_basehandler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "D:\do\ur\op\man.py", line 120, in personal
    await rep_trx.trx_process_list(rep_trx.get_TRX_transaction()['data'],
  File "D:\do\ur\op\report.py", line 204, in trx_process_list
    await context.bot.send_message(chat_id=self.user_id,
  File "D:\do\ur\op\venv\lib\site-packages\telegram\ext\_extbot.py", line 2644, in send_message
    return await super().send_message(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\_bot.py", line 388, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
  File "D:\do\ur\op\venv\lib\site-packages\telegram\_bot.py", line 814, in send_message
    return await self._send_message(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\ext\_extbot.py", line 514, in _send_message
    result = await super()._send_message(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\_bot.py", line 566, in _send_message
    result = await self._post(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\_bot.py", line 476, in _post
    return await self._do_post(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\ext\_extbot.py", line 332, in _do_post
    return await super()._do_post(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\_bot.py", line 504, in _do_post
    return await request.post(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\request\_baserequest.py", line 168, in post
    result = await self._request_wrapper(
  File "D:\do\ur\op\venv\lib\site-packages\telegram\request\_baserequest.py", line 325, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: character '-' is reserved and must be escaped with the preceding '\'
2023-07-11 22:06:59,548 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2023-07-11 22:06:59,549 - apscheduler.scheduler - INFO - Scheduler has been shut down
2023-07-11 22:06:59,549 - telegram.ext.Application - INFO - Application.stop() complete
```

### Related part of your code

```python
# main file
if str(update.message.text) == 'cs':
        print('cs')
        rep_trx = trx(address='address', user_id=update.effective_chat.id)
        await rep_trx.trx_process_list(rep_trx.get_TRX_transaction()['data'],
                                       latest_hash=sql.query_hash_by_address(
                                           address='addresss',
                                           user_id=update.effective_chat.id), context=context)
# report file
 async def trx_process_list(self, data_list, latest_hash, context):
        ret_list = []
        data_list.reverse()
        all_data_list = data_list
        for item in data_list[:]:
            if item["transactionHash"] != latest_hash:
                if len(data_list) == 1 and data_list[-1]["Hash"] != latest_hash:
                    for items in all_data_list:
                        await context.bot.send_message(chat_id=self.user_id,
                                                       text='try',
                                                       parse_mode='MarkdownV2')
```

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4
Bot API 6.7
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Hi. The traceback that you're showing has nothing to do with scheduling ot tasks. It's  a problem of markup formatting. Please have a look at [this wiki section](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#message-formatting-bold-italic-code-) and sepeciall at the official Bot API docs linked therein.
Passing the context parameter to the `trx_process_list` function also looks fine and the traceback in fact shows that this works as expected.
For actually scheduling tasks, note that PTB comes with a built-in integration for `apscheduler` via the [`JobQueue`](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions---JobQueue).
