### ISSUE TITLE
[BUG] Getting Timeout when bot starts polling

### ISSUE THREAD

**Issue by Prakash4844** [python-telegram-bot/python-telegram-bot#3819]
### Steps to Reproduce

1. when bot reaches the line `application.run_polling()`
2. it returns timeout errors 90% of time.
3. occasionally bot can connect fine.

NOTE: Internet connection is fine.

![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/81550376/68322304-0fc4-4a77-a095-eb88713ff06d)

### Expected behaviour

Bot should start polling.

### Actual behaviour

time out error is shown.

### Operating System

EndeavourOS(Linux)

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3
Bot API 6.7
Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
```

### Relevant log output

```python
/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/bin/python /home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/bot.py 
Traceback (most recent call last):
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 186, in connect_tcp
    addr_obj = ip_address(remote_host)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'api.telegram.org' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 189, in connect_tcp
    gai_res = await getaddrinfo(
              ^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 113, in connect_tcp
    with anyio.fail_after(timeout):
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 261, in handle_async_request
    raise exc
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
    raise exc
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/_async/connection.py", line 117, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/bot.py", line 129, in <module>
    application.run_polling(timeout=1000, pool_timeout=1000, read_timeout=1000, write_timeout=1000,
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 727, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 921, in __run
    raise exc
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 910, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 399, in initialize
    await self.bot.initialize()
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 271, in initialize
    await super().initialize()
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/_bot.py", line 591, in initialize
    await self.get_me()
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1706, in get_me
    return await super().get_me(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/_bot.py", line 381, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/_bot.py", line 736, in get_me
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/_bot.py", line 469, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 325, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/_bot.py", line 497, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 291, in _request_wrapper
    raise exc
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 277, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphkiel/Documents/Github/Python/Telegram_Song_Uploader_bot/venv/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 233, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out

Process finished with exit code 1
```

### Additional Context

I am just trying to upload some song to telegram but bot can't start polling most of the time,

i have tried to increase the timeout parameters in `application.run_polling` like this

```py
application.run_polling(timeout=1000, pool_timeout=1000, read_timeout=1000, write_timeout=1000, connect_timeout=1000)
```

**Comment by Bibo-Joshi** [comment]
Hi. The traceback tells me that the timeout happens on the call of `Application.initialize()` → `Bot.initialize()` → `Bot.get_me()`. Here, `Bot.get_me()` is indeed called with the default timeout values. The timeout values that you specify for `run_polling` are relevant only for the calls to `Bot.get_updates`.
There is currently no way to specify the timeout values for `Bot.get_me()` as called in `Bot.initialize()` through `run_polling`. What you could do instead is set them via [`Defaults`](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Adding-defaults-to-your-bot). Please try this and report back if it helps. If it does, we might discuss adding timeout parameters to the `initialize` methods.

**Comment by Prakash4844** [comment]
Hey, Reading the Doc, i can't figure out how can i set timeout value with it? it doesn't mention anything related to that. only following are mentioned.

- parse_mode
- disable_notification
- disable_web_page_preview
- allow_sending_without_reply
- quote
- tzinfo
- block
- protect_content

**Comment by Bibo-Joshi** [comment]
@Prakash4844 Damn, my bad. My memory told me about v13 … in v20 you set these via <a href="https://docs.python-telegram-bot.org/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.connect_timeout">telegram.ext.ApplicationBuilder.connect_timeout</a>, <a href="https://docs.python-telegram-bot.org/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.read_timeout">telegram.ext.ApplicationBuilder.read_timeout</a> etc :)
