### ISSUE TITLE
[QUESTION] Cannot pass InlineKeyboardMarkup in reply_photo or reply_text

### ISSUE THREAD

**Issue by ChenMorSays** [python-telegram-bot/python-telegram-bot#3832]
### Issue I am facing

For some reason this doesn't seem to work.

Curious if a known issue or if I'm missing something

I can send the photo but as soon as I add a keyword with options getting the following error

Update: I can also send text without inlinekeyboard

2nd update: Tried with other versions of python-telegram-bot (post 20.0) and none work. Prior to 20.0 it DID work!

3rd update: Tried upgrading to Python 3.11, still doesnt work.

It seems that just the inlinekeyboard doesn't work no matter what

### Traceback to the issue

```python
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/chen/Documents/Projects/AIGF/KoboldAI-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 278, in _request_wrapper
    code, payload = await self.do_request(
  File "/Users/chen/Documents/Projects/AIGF/KoboldAI-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 213, in do_request
    data = request_data.json_parameters if request_data else None
  File "/Users/chen/Documents/Projects/AIGF/KoboldAI-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/request/_requestdata.py", line 74, in json_parameters
    return {
  File "/Users/chen/Documents/Projects/AIGF/KoboldAI-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/request/_requestdata.py", line 77, in <dictcomp>
    if param.json_value is not None
  File "/Users/chen/Documents/Projects/AIGF/KoboldAI-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/request/_requestparameter.py", line 76, in json_value
    return json.dumps(self.value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InlineKeyboardMarkup is not JSON serializable
```

### Related part of your code

```python
async def send_photo(message, uri):
    photoUriHandler = open(uri, 'rb')
    photo = InputFile(photoUriHandler)

    keyboard = [
        [InlineKeyboardButton("Show", callback_data="show_photo")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    await message.reply_photo(
        photo=photo,
        caption="",
        reply_markup=reply_markup
    )
```

### Operating System

MacOS Monterey 12.5

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4 (v0.1.1-alpha-3-g3f332ad)
Bot API 6.7
Python 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58)  [Clang 6.0 (clang-600.0.57)]
```

**Comment by ChenMorSays** [comment]
Here's a full mwe

```
pip install Pillow pyrogram python-telegram-bot python-dotenv
```

```
import requests
import json
import os
import io
import re
import base64
from pathlib import Path
from dotenv import load_dotenv
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, InputFile
from telegram.ext import Application, MessageHandler, CallbackContext, CallbackQueryHandler
from telegram.ext import filters
from pyrogram import Client
from pyrogram.types import *
from dotenv import load_dotenv
from PIL import Image, ImageFilter

load_dotenv()
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

async def send_photo(message, photo_uri):
    photoUriHandler = open(photo_uri, 'rb')
    photo = InputFile(photoUriHandler)
    
    keyboard = [
        [InlineKeyboardButton("Show", callback_data="show_photo")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    print(reply_markup)
    print(type(reply_markup))

    await message.reply_photo(
        photo=photo,
        caption="",
        reply_markup=reply_markup
    )

async def handle_message(update, context):
    await send_photo(update.message, "./photo.png")

def main():
    application = Application.builder().token(TELEGRAM_BOT_TOKEN).build()

    # Add the handler to the dispatcher
    application.add_handler(MessageHandler(filters.TEXT, handle_message))
    
    # Start the bot
    print("Starting bot polling")
    application.run_polling()

if __name__ == '__main__':
    main()
```

**Comment by ChenMorSays** [comment]
Holy crap. Found it.

It was: ```from pyrogram.types import *```

What the hell.
