### ISSUE TITLE
Running with Trio - trio._core._traps.CancelShieldedCheckpoint

### ISSUE THREAD

**Issue by Corfucinas** [python-telegram-bot/python-telegram-bot#3838]
### Steps to Reproduce

run this having [trio](https://trio.readthedocs.io/en/stable/) installed 

<details>

```python
#!/usr/bin/env python
# pylint: disable=unused-argument, wrong-import-position
# This program is dedicated to the public domain under the CC0 license.

"""
Simple Bot to handle '(my_)chat_member' updates.
Greets new users & keeps track of which chats the bot is in.

Usage:
Press Ctrl-C on the command line or send a signal to the process to stop the
bot.
"""

import trio
import logging
from typing import Optional, Tuple

from telegram import __version__ as TG_VER

try:
    from telegram import __version_info__
except ImportError:
    __version_info__ = (0, 0, 0, 0, 0)  # type: ignore[assignment]

if __version_info__ < (20, 0, 0, "alpha", 1):
    raise RuntimeError(
        f"This example is not compatible with your current PTB version {TG_VER}. To view the "
        f"{TG_VER} version of this example, "
        f"visit https://docs.python-telegram-bot.org/en/v{TG_VER}/examples.html"
    )
from telegram import Chat, ChatMember, ChatMemberUpdated, Update
from telegram.constants import ParseMode
from telegram.ext import (
    Application,
    ChatMemberHandler,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

# Enable logging

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)

# set higher logging level for httpx to avoid all GET and POST requests being logged
logging.getLogger("httpx").setLevel(logging.WARNING)

logger = logging.getLogger(__name__)


def extract_status_change(chat_member_update: ChatMemberUpdated) -> Optional[Tuple[bool, bool]]:
    """Takes a ChatMemberUpdated instance and extracts whether the 'old_chat_member' was a member
    of the chat and whether the 'new_chat_member' is a member of the chat. Returns None, if
    the status didn't change.
    """
    status_change = chat_member_update.difference().get("status")
    old_is_member, new_is_member = chat_member_update.difference().get("is_member", (None, None))

    if status_change is None:
        return None

    old_status, new_status = status_change
    was_member = old_status in [
        ChatMember.MEMBER,
        ChatMember.OWNER,
        ChatMember.ADMINISTRATOR,
    ] or (old_status == ChatMember.RESTRICTED and old_is_member is True)
    is_member = new_status in [
        ChatMember.MEMBER,
        ChatMember.OWNER,
        ChatMember.ADMINISTRATOR,
    ] or (new_status == ChatMember.RESTRICTED and new_is_member is True)

    return was_member, is_member


async def track_chats(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Tracks the chats the bot is in."""
    result = extract_status_change(update.my_chat_member)
    if result is None:
        return
    was_member, is_member = result

    # Let's check who is responsible for the change
    cause_name = update.effective_user.full_name

    # Handle chat types differently:
    chat = update.effective_chat
    if chat.type == Chat.PRIVATE:
        if not was_member and is_member:
            # This may not be really needed in practice because most clients will automatically
            # send a /start command after the user unblocks the bot, and start_private_chat()
            # will add the user to "user_ids".
            # We're including this here for the sake of the example.
            logger.info("%s unblocked the bot", cause_name)
            context.bot_data.setdefault("user_ids", set()).add(chat.id)
        elif was_member and not is_member:
            logger.info("%s blocked the bot", cause_name)
            context.bot_data.setdefault("user_ids", set()).discard(chat.id)
    elif chat.type in [Chat.GROUP, Chat.SUPERGROUP]:
        if not was_member and is_member:
            logger.info("%s added the bot to the group %s", cause_name, chat.title)
            context.bot_data.setdefault("group_ids", set()).add(chat.id)
        elif was_member and not is_member:
            logger.info("%s removed the bot from the group %s", cause_name, chat.title)
            context.bot_data.setdefault("group_ids", set()).discard(chat.id)
    elif not was_member and is_member:
        logger.info("%s added the bot to the channel %s", cause_name, chat.title)
        context.bot_data.setdefault("channel_ids", set()).add(chat.id)
    elif was_member and not is_member:
        logger.info("%s removed the bot from the channel %s", cause_name, chat.title)
        context.bot_data.setdefault("channel_ids", set()).discard(chat.id)


async def show_chats(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Shows which chats the bot is in"""
    user_ids = ", ".join(str(uid) for uid in context.bot_data.setdefault("user_ids", set()))
    group_ids = ", ".join(str(gid) for gid in context.bot_data.setdefault("group_ids", set()))
    channel_ids = ", ".join(str(cid) for cid in context.bot_data.setdefault("channel_ids", set()))
    text = (
        f"@{context.bot.username} is currently in a conversation with the user IDs {user_ids}."
        f" Moreover it is a member of the groups with IDs {group_ids} "
        f"and administrator in the channels with IDs {channel_ids}."
    )
    await update.effective_message.reply_text(text)


async def greet_chat_members(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Greets new users in chats and announces when someone leaves"""
    result = extract_status_change(update.chat_member)
    if result is None:
        return

    was_member, is_member = result
    cause_name = update.chat_member.from_user.mention_html()
    member_name = update.chat_member.new_chat_member.user.mention_html()

    if not was_member and is_member:
        await update.effective_chat.send_message(
            f"{member_name} was added by {cause_name}. Welcome!",
            parse_mode=ParseMode.HTML,
        )
    elif was_member and not is_member:
        await update.effective_chat.send_message(
            f"{member_name} is no longer with us. Thanks a lot, {cause_name} ...",
            parse_mode=ParseMode.HTML,
        )


async def start_private_chat(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Greets the user and records that they started a chat with the bot if it's a private chat.
    Since no `my_chat_member` update is issued when a user starts a private chat with the bot
    for the first time, we have to track it explicitly here.
    """
    user_name = update.effective_user.full_name
    chat = update.effective_chat
    if chat.type != Chat.PRIVATE or chat.id in context.bot_data.get("user_ids", set()):
        return

    logger.info("%s started a private chat with the bot", user_name)
    context.bot_data.setdefault("user_ids", set()).add(chat.id)

    await update.effective_message.reply_text(
        f"Welcome {user_name}. Use /show_chats to see what chats I'm in."
    )


async def main() -> None:
    """Start the bot."""
    # Create the Application and pass it your bot's token.
    application = Application.builder().token("5933246368:AAH4uvxGd1PV1dwCp7mVDt3gXTxVBnIMx5g").build()

    # Keep track of which chats the bot is in
    application.add_handler(ChatMemberHandler(track_chats, ChatMemberHandler.MY_CHAT_MEMBER))
    application.add_handler(CommandHandler("show_chats", show_chats))

    # Handle members joining/leaving chats.
    application.add_handler(ChatMemberHandler(greet_chat_members, ChatMemberHandler.CHAT_MEMBER))

    # Interpret any other command or text message as a start of a private chat.
    # This will record the user as being in a private chat with bot.
    application.add_handler(MessageHandler(filters.ALL, start_private_chat))

    # Run the bot until the user presses Ctrl-C
    # We pass 'allowed_updates' handle *all* updates including `chat_member` updates
    # To reset this, simply pass `allowed_updates=[]`
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    trio.run(main)
```

</details>

### Expected behaviour

it works

### Actual behaviour

<details>

```
Traceback (most recent call last):
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 218, in handle_async_request
    async with self._pool_lock:
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/httpcore/_synchronization.py", line 39, in __aenter__
    await self._trio_lock.acquire()
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/trio/_sync.py", line 533, in acquire
    await trio.lowlevel.cancel_shielded_checkpoint()
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/trio/_core/_traps.py", line 44, in cancel_shielded_checkpoint
    return (await _async_yield(CancelShieldedCheckpoint)).unwrap()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/trio/_core/_traps.py", line 22, in _async_yield
    return (yield obj)
            ^^^^^^^^^
RuntimeError: Task got bad yield: <class 'trio._core._traps.CancelShieldedCheckpoint'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/the-box/Github/watchers-alerts/test.py", line 194, in <module>
    trio.run(main)
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/trio/_core/_run.py", line 2093, in run
    raise runner.main_task_outcome.error
  File "/home/the-box/Github/watchers-alerts/test.py", line 190, in main
    application.run_polling(allowed_updates=Update.ALL_TYPES)
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 725, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 919, in __run
    raise exc
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 908, in __run
    loop.run_until_complete(self.initialize())
  File "/home/the-box/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 397, in initialize
    await self.bot.initialize()
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 258, in initialize
    await super().initialize()
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 581, in initialize
    await self.get_me()
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1691, in get_me
    return await super().get_me(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 368, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in get_me
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 456, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 312, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 487, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/the-box/Github/watchers-alerts/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 290, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {repr(exc)}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: RuntimeError("Task got bad yield: <class 'trio._core._traps.CancelShieldedCheckpoint'>")
```

</details>

### Operating System

ubuntu-latest

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2 (0.6.1-78-g6340a92)
Bot API 6.6
Python 3.11.2 (main, Mar 18 2023, 12:39:58) [GCC 12.2.0]
```

### Relevant log output

```python
Left them in 'actual behavior'
```

### Additional Context

Can you make sense of the error? I'm trying to use `trio` to replace `asyncio` in a program that uses this library.

**Comment by Bibo-Joshi** [comment]
Hi. Please have a look at https://github.com/python-telegram-bot/python-telegram-bot/discussions/3451 to see if the discussion in there already answers your quesiton.

**Comment by Corfucinas** [comment]
> Hi. Please have a look at #3451 to see if the discussion in there already answers your question.

Unfortunately, it does.

Want to leave this issue open for other users? [I tried searching on close and open issues for this problem that #3451  addresses, but there were none](https://github.com/python-telegram-bot/python-telegram-bot/issues?q=trio)

**Comment by Bibo-Joshi** [comment]
Let's close it as it will show up in searches for open and closed issues :)
