### ISSUE TITLE
How to run in QT5 applications？

### ISSUE THREAD

**Issue by GodFatherClover** [python-telegram-bot/python-telegram-bot#3879]
### Issue I am facing

I have a QT5 UI application and I would like to run the Telegram bot on my QT5 UI application. How can I do this?
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/129489866/3537a6dc-4789-4be1-831d-29efe96613a3)

### Traceback to the issue

```python
Exception in thread Thread-1 (set_up):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MySecretProject\SecretProject\mmproject\superBot\qtgui.py", line 105, in set_up
    tgbot.set_up()
  File "D:\MySecretProject\SecretProject\mmproject\superBot\tgbot.py", line 75, in set_up
    application.run_polling(allowed_updates=Update.ALL_TYPES)
  File "D:\MySecretProject\SecretProject\mmproject\superBot\venv\Lib\site-packages\telegram\ext\_application.py", line 752, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "D:\MySecretProject\SecretProject\mmproject\superBot\venv\Lib\site-packages\telegram\ext\_application.py", line 917, in __run
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\events.py", line 677, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (set_up)'.
C:\Program Files\Python311\Lib\threading.py:1040: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

### Related part of your code

```python
def setupTgBot(self):
        def set_up():
            tgbot.set_up()
        print('setupTgBot called')
        thread = Thread(target=set_up)
        thread.start()
```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
anyio==4.0.0
beautifulsoup4==4.12.2
certifi==2023.7.22
charset-normalizer==3.2.0
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
idna==3.4
pyperclip==1.8.2
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.2
python-telegram-bot==20.4
requests==2.31.0
sniffio==1.3.0
soupsieve==2.5
urllib3==2.0.4
```

**Comment by Poolitzer** [comment]
@GodFatherClover This is mixing up threading and async. PTB is not thread safe but you can probably still do this, you would just need to read up on mixing these two.
