### ISSUE TITLE
[QUESTION] httpx Network Error

### ISSUE THREAD

**Issue by Qolorerr** [python-telegram-bot/python-telegram-bot#3964]
### Issue I am facing

I wrote a bot on my local Windows PC, and it worked perfectly. However, when I tried to run it on Debian with the same parameters and library version, I encountered the following error. Can you help me solve or work around this issue?

### Traceback to the issue

```python
Traceback (most recent call last):                                                                                              
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 278, in _request_wrapper                
    code, payload = await self.do_request(                                                                                      
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 219, in do_request                     
    res = await self._client.request(                                                                                           
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1517, in request                                        
    request = self.build_request(                                                                                               
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 346, in build_request                                   
    url = self._merge_url(url)                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 376, in _merge_url                                      
    merge_url = URL(url)                                                                                                        
  File "/usr/local/lib/python3.10/site-packages/httpx/_urls.py", line 113, in __init__                                          
    self._uri_reference = urlparse(url, **kwargs)                                                                               
  File "/usr/local/lib/python3.10/site-packages/httpx/_urlparse.py", line 160, in urlparse                                      
    raise InvalidURL("Invalid non-printable ASCII character in URL")                                                            
httpx.InvalidURL: Invalid non-printable ASCII character in URL                                                                  
                                                                                                                                
The above exception was the direct cause of the following exception:                                                            
                                                                                                                                
Traceback (most recent call last):                                                                                              
  File "/root/BinaParser/main.py", line 296, in <module>                                                                        
    application.run_polling(allowed_updates=Update.ALL_TYPES)                                                                   
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 779, in run_polling                         
    return self.__run(                                                                                                          
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 967, in __run                               
    raise exc                                                                                                                   
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 956, in __run                               
    loop.run_until_complete(self.initialize())                                                                                  
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete                                      
    return future.result()                                                                                                      
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 467, in initialize                          
    await self.bot.initialize()                                                                                                 
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 293, in initialize                               
    await super().initialize()                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 729, in initialize                                      
    await self.get_me()                                                                                                         
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 1704, in get_me                                  
    return await super().get_me(                                                                                                
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 519, in decorator                                       
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102                                                             
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 769, in get_me                                          
    result = await self._post(                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 607, in _post                                           
    return await self._do_post(                                                                                                 
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post                                 
    return await super()._do_post(                                                                                              
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 635, in _do_post                                        
    return await request.post(                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 168, in post                            
    result = await self._request_wrapper(                                                                                       
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 290, in _request_wrapper                
    raise NetworkError(f"Unknown error in HTTP implementation: {exc!r}") from exc                                               
telegram.error.NetworkError: Unknown error in HTTP implementation: InvalidURL('Invalid non-printable ASCII character in URL')
```

### Related part of your code

```python
application = ApplicationBuilder().token(TOKEN).build()
# adding handlers
application.run_polling(allowed_updates=Update.ALL_TYPES)
```

### Operating System

Debian 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.6                                                                                                        
Bot API 6.9                                                                                                                     
Python 3.10.13 (main, Nov  3 2023, 17:59:48) [GCC 9.4.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. Please double check that you have set your bot token correctly.

**Comment by Qolorerr** [comment]
It looks like the problem was in the encoding of the token file. When I entered it manually, it started
