### ISSUE TITLE
ERROR - line 34, in <module> bot.set_webhook(url=callurl) CRASH

### ISSUE THREAD

**Issue by kikimick** [python-telegram-bot/python-telegram-bot#3969]
### Issue I am facing

Webserver starts and then crashes. I have set my callurl as my local ngrok server on port 5000. Have patience please i am new. Bot tokens have also been saved in info.py. ANY HELP WOULD BE GREATLY APPRECIATED!

### Traceback to the issue

```python
python main.py
 * Serving Flask app 'main'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\BOT(Telegram)\main.py", line 34, in <module>
    bot.set_webhook(url=callurl)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 437, in set_webhook
    return apihelper.set_webhook(self.token, url, certificate, max_connections, allowed_updates, ip_address,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 288, in set_webhook
    return _make_request(token, method_url, params=payload, files=files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 1
```

### Related part of your code

```python
# Flask connection
app = Flask(__name__)

# Bot connection
bot = telebot.TeleBot(API_TOKEN, threaded=False)
bot.remove_webhook()
bot.set_webhook(url=callurl)



# Process webhook calls
@app.route('/', methods=['GET', 'POST'])
def webhook():
    if flask.request.headers.get('content-type') == 'application/json':
        json_string = flask.request.get_data().decode('utf-8')
        update = telebot.types.Update.de_json(json_string)
        bot.process_new_updates([update])
        return ''
    else:
        print("error")
        flask.abort(403)
```

### Operating System

Windows NT

### Version of Python, python-telegram-bot & dependencies

```shell
3.11 PYTHON
```

**Comment by Poolitzer** [comment]
hi, this is the python-telegram-bot library, not telebot.
