### ISSUE TITLE
[BUG] Error getting updates

### ISSUE THREAD

**Issue by alvmarrod** [python-telegram-bot/python-telegram-bot#4018]
### Steps to Reproduce

1.  Just leave the bot running time enough...

### Expected behaviour

All `update`s are processed properly.

### Actual behaviour

At some point, some `update` is expected to be processed but the `telegram.ext._application` but it generates an `exception` instead. There are different exceptions being triggered, but the root cause seems to be the same.

In the relevant logs section, I'm adding 2 exceptions separated by a long `---` string line. The first one is an exception when the new `update` retrieval fails. The second, seems to be the same but the stacktrace is down to a `httpcore.ReadError` error.

### Operating System

Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.11.4 (main, Jun 13 2023, 07:27:45) [GCC 8.3.0]
```

### Relevant log output

```python
2023-12-18 15:08:11,091 - telegram.ext._updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-12-18 15:08:11,092 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 3510, in get_updates
    await self._post(
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
--------------------------------------------------------------------------
2023-12-18 17:38:19,917 - telegram.ext._updater - ERROR - Error while getting Updates: httpx.ReadError:
2023-12-18 17:38:19,919 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 198, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1104, in receive
    raise self._protocol.exception from None
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 199, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 3510, in get_updates
    await self._post(
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 223, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ReadError:
```

### Additional Context

I have a hunch that this is related to difficult (too many hops) connectivity between my bot host location and telegram servers/API. Due to previous [different issues](https://github.com/python-telegram-bot/python-telegram-bot/issues/3556#issuecomment-1435928383) with this, I have configured  (or tried to) my bot with the following parameters:

```
    bot: Application = ApplicationBuilder().\
        token(BOT_TOKEN).\
        request(HTTPXRequest(
            http_version="1.1",
            read_timeout=60,
            write_timeout=60
            )
        ).\
        get_updates_request(HTTPXRequest(
            http_version="1.1",
            read_timeout=60,
            write_timeout=60
            )
        ).\
        build()
```

From experience I can't even tell if this configuration is properly working, but if I increment it further the bot kind of breaks, so I guess it is.

Edit: I tagged this as BUG mainly because of the output of the first log shared: `Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`, but please change it if you believe it's not appropriate.

**Comment by Bibo-Joshi** [comment]
Hi. I'll have to answer similarly to how I answered in #4019: as long as these exceptions do not occur reproducibly, but only once every blue moon, I don't see that PTB could do anything about them. In particular about the Conflict error, this is most likely due to the nature of long polling (opening a new request *immediately* after the old one timed out) in combination with slight inaccuracies in all servers taking part in the communication. I can tell you that I see such exceptions with my bots as well every now and then and they still run fine. You should be worried only when the `Conflict` exception is there consistently on every call to `get_updates`.

**Comment by alvmarrod** [comment]
I see, thanks for you response. Let me add some references for further information and a couple of questions.

- **Frequency**: in my case, I am suffering these issues between [0-10] times a day. Some bad days it may increase, but not reaching the next magnitude order in any case.
- **Impact**: 
    - My bot does some actions over the channels, like removing an user message and sending a message itself in replacement of the user's one.
    - When this issues occur, this kind of behavior is broken. Either the removal of the user message or the new message may not be sent as per the update timeout. (Among others, this is just a sample)

Questions:
- Is there any appropriate/recommended way to capture such kind of low level `update` issues, to retry it and avoid my app logic flow being broken? 
- If not, is there any way to configure a retry factor or alike to give it more chances to process a non properly received `update`?

About those questions, I am thinking about library/framework level options, but if it can be somehow captured at app level registering some kind of handler and making it being processed the same way as a regular update for a second chance it would also be OK in my case, as I don't need to preserv (in 99% of the situations) order for the updates input.

**Comment by Bibo-Joshi** [comment]
> Is there any appropriate/recommended way to […] capture/[…] retry it

* One straight-forward approach is to `try-except` in places where it is crucial for your logic that a specific call to TG always makes it
* If you want all requests to TG to be retried on failure, I recommend subclassing `BaseRequest` or `HTTPXRequest` and to override the `do_request` method to do the retrying.
* As "last-resort" error handling option, PTB provides `Application.add_error_handler`. Retrying specific parts of the other handler callbacks is not feasible this way. However, if in the error handler you decide that the update was crucial enough to be processed again, you can insert it back into `Application.update_queue`. the application will then pick it up again and process it again. Note that by this approach any logic that *did* work before an exception occured will be run again, so users could get messages twice etc. Moreover, for time-critical updates like inline/callback query that need to be answered quickly, this is probably not the best approach.
