### ISSUE TITLE
[BUG] RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by gronnmann** [python-telegram-bot/python-telegram-bot#4023]
### Steps to Reproduce

1. Create a loop where you send multiple messages

For exmaple:
```python
class TelegramNotificationAgent(NotificationAgent):
    """Agent that sends notifications to Telegram
    """

    def __init__(self):
        super().__init__("telegram", "Telegram Agent")
        self.bot_token = os.environ['TELEGRAM_BOT_TOKEN']
        self.bot = telegram.Bot(token=self.bot_token)

        # https://copyprogramming.com/howto/asyncio-runtimeerror-event-loop-is-closed
        self.loop = asyncio.get_event_loop()
        self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=5)
        self.loop.set_default_executor(self.executor)

    def __del__(self):
        self.executor.shutdown(wait=False)
        self.loop.close()

    def send_notification(self, user_id, event):
        na = event.get_newly_available()
        nu = event.get_newly_unavailable()

        if len(na) == 0 and len(nu) == 0:
            return

        text_lines = []
        text_lines.append(f"Notification for product {event.product_id} at {event.datasource_id}")
        # now available
        if len(na) > 0:
            text_lines.append("Newly available at:")
        for entry in na:
            loc, sizes = entry
            text_lines.append(f"{loc.display_name} ({loc.address}): {','.join(sizes)}")

        # no longer unavailable
        if len(nu) > 0:
            text_lines.append("No longer available at:")
        for entry in nu:
            loc, sizes = entry

            text_lines.append(f"{loc.display_name} ({loc.address}): {','.join(sizes)}")

        asyncio.run(self.bot.send_message(user_id, "\n".join(text_lines)))
```

This is called upon by:
```python
            for agent_id, agentUsername in sub.agents.items():
                agent = get_notification_agent(agent_id)

                if agent is None:
                    logging.error(f"Agent {agent_id} not found (configured for {sub}. Skipping...")
                    continue

                agent.send_notification(agentUsername, event)
```

So, `asyncio.run(self.bot.send_message)` is called multiple times right after each other

### Expected behaviour

All messages sent, and program finish gracefully

### Actual behaviour

Gives error and last message before error not sent

### Operating System

MacOS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.7
Bot API 6.9
Python 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)]
```

### Relevant log output

```python
Traceback (most recent call last):
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    result = func(*args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 888, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2633)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
    data = await self._network_stream.read(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/anyio/streams/tls.py", line 205, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1122, in receive
    self._transport.resume_reading()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 808, in resume_reading
    self._add_reader(self._sock_fd, self._read_ready)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 754, in _add_reader
    self._loop._add_reader(fd, callback, *args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 258, in _add_reader
    self._check_closed()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/http11.py", line 132, in handle_async_request
    await self._response_closed()
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/http11.py", line 245, in _response_closed
    await self.aclose()
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_async/http11.py", line 253, in aclose
    await self._network_stream.aclose()
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 54, in aclose
    await self._stream.aclose()
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/anyio/streams/tls.py", line 202, in aclose
    await self.transport_stream.aclose()
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1181, in aclose
    self._transport.close()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 700, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bartosz/Programowanie/AvailbleAler/bin/availablenow", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/bartosz/Programowanie/Python/AvailbleAler/availablenow/main.py", line 25, in main_cli
    refresh_all()
  File "/Users/bartosz/Programowanie/Python/AvailbleAler/availablenow/webstore_data/DataSource.py", line 93, in refresh_all
    source.refresh_tracked()
  File "/Users/bartosz/Programowanie/Python/AvailbleAler/availablenow/webstore_data/DataSource.py", line 70, in refresh_tracked
    get_event_manager().dispatch_event(ProductSizesChangeEvent(product, old, new, self.id))
  File "/Users/bartosz/Programowanie/Python/AvailbleAler/availablenow/events/EventManager.py", line 23, in dispatch_event
    listener.on_event(event)
  File "/Users/bartosz/Programowanie/Python/AvailbleAler/availablenow/usernotifier/SubscriptionDelegator.py", line 71, in on_event
    agent.send_notification(agentUsername, event)
  File "/Users/bartosz/Programowanie/Python/AvailbleAler/availablenow/usernotifier/agents/TelegramNotificationAgent.py", line 52, in send_notification
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/_bot.py", line 846, in send_message
    return await self._send_message(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/_bot.py", line 703, in _send_message
    result = await self._post(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/_bot.py", line 613, in _post
    return await self._do_post(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/_bot.py", line 641, in _do_post
    return await request.post(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/Users/bartosz/Programowanie/AvailbleAler/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {exc!r}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: RuntimeError('Event loop is closed')
```

**Comment by Bibo-Joshi** [comment]
Hi. Unless you have a very specific reason to do so, I recommend not to manually create or close event loops. My first intuition is that this exception is due to you calling loop.close. however, this is somewhat hard to judge without understanding your general setup. Maybe you can try to provide an [mwe](../wiki/MWE)?

**Comment by Bibo-Joshi** [comment]
Closing due to inactivity.
