### ISSUE TITLE
updater = Updater(telegram_token, use_context=True)

### ISSUE THREAD

**Issue by Byex0** [python-telegram-bot/python-telegram-bot#4049]
### Issue I am facing

I need a friend who can help me solve this problem and send me my code again. Thanks in advance.

The purpose of the code is as follows: - I want this bot to be private only to my Telegram account. I want the bot to send water messages for those who start this bot, those who send messages and those who use commands, except me; CANNOT BE USED EXCEPT AS THE BOSS! CRY IN YOUR CORNER, LOSER :)
 
  - I want to get the following response when I give the /start command to the bot; Bot is active Boss, you can get information via /check.
 
  - I want to manually check my metamask account. I want to get an answer as soon as I type the /check command into the bot. I can give the following example:

  Your Avax Balance: 25 AVAX
  Current Price Value (USD): $1000
  Current Price Value (TRY): 30000 TRY
 
  Of course, I want these values to be real.
 
  - Finally, when I type the /market command into the bot, I want to find out how much USD and TRY value 1 Bitcoin and 1 Avax Coin has instantly. Of course, these values have to be real. Example:

  1 BTC = $43,341
  1 BTC = 1.273.500 TRY
 
  1 AVAX = $43.06
  1 AVAX = 1265.39 TRY

### Traceback to the issue

```python
Microsoft Windows [Version 10.0.22621.2861]
(c) Microsoft Corporation. Tüm hakları saklıdır.

C:\Users\victus\Desktop\kodlar>C:/Users/victus/AppData/Local/Programs/Python/Python312/python.exe c:/Users/victus/Desktop/kodlar/avax-telegram-bot/eleman_checker.py
Traceback (most recent call last):
  File "c:\Users\victus\Desktop\kodlar\avax-telegram-bot\eleman_checker.py", line 79, in <module>
    main()
  File "c:\Users\victus\Desktop\kodlar\avax-telegram-bot\eleman_checker.py", line 63, in main
    updater = Updater(telegram_token, use_context=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Updater.__init__() got an unexpected keyword argument 'use_context'

C:\Users\victus\Desktop\kodlar>
```

### Related part of your code

```python
import requests
from telegram import Bot, Update
from telegram.ext import CommandHandler, CallbackContext, Updater, MessageHandler, filters

# Add bot and wallet information here
telegram_token = "TOKEN OF MY BOTTOM"
telegram_user_id = USER ID OF MY TELEGRAM ACCOUNT
avax_address = "MY AVAX ADDRESS"

# CoinGecko API
coingecko_api_url = "https://api.coingecko.com/api/v3/simple/price"
coingecko_params = {
     "ids": "bitcoin,avalanche-2",
     "vs_currencies": "usd,try",
}

# Main functions
def start(update: Update, context: CallbackContext) -> None:
     if update.message.from_user.id == telegram_user_id:
         update.message.reply_text("Bot is active Boss, you can get information with /check.")
     else:
         update.message.reply_text("NOT USABLE EXCEPT AS A BOSS! CRY IN YOUR CORNER, LOSER.")

def check(update: Update, context: CallbackContext) -> None:
     if update.message.from_user.id == telegram_user_id:
         avax_balance, usd_price, try_price = get_balances()
         message = f"Your Avax Balance: {avax_balance} AVAX\nCurrent Price Value (USD): {usd_price:.2f}$\nCurrent Price Value (TRY): {try_price:.2f} TRY"
         update.message.reply_text(message)
     else:
         update.message.reply_text("NOT USABLE EXCEPT AS A BOSS! CRY IN YOUR CORNER, LOSER.")

def market(update: Update, context: CallbackContext) -> None:
     market_prices = get_market_prices()
     message = f"1 BTC = {market_prices['bitcoin']['usd']}$\n1 BTC = {market_prices['bitcoin']['try']} TRY\n\n1 AVAX = {market_prices['avalanche -2']['usd']}$\n1 AVAX = {market_prices['avalanche-2']['try']} TRY"
     update.message.reply_text(message)

def get_balances():
     # AVAX balance
     avax_response = requests.post(
         "https://api.avax.network/ext/bc/C/rpc",
         json={
             "jsonrpc": "2.0",
             "id": 1,
             "method": "eth_getBalance",
             "params": [avax_address, "latest"],
         },
     )
     avax_balance_wei = int(avax_response.json()["result"], 16)
     avax_balance = avax_balance_wei / 10**18

     # Current price information (using CoinGecko API)
     coingecko_response = requests.get(coingecko_api_url, params=coingecko_params)
     usd_price = coingecko_response.json()["avalanche-2"]["usd"]
     try_price = coingecko_response.json()["avalanche-2"]["try"]

     return avax_balance, usd_price, try_price

def get_market_prices():
     coingecko_response = requests.get(coingecko_api_url, params=coingecko_params)
     return coingecko_response.json()

def main():
     updater = Updater(telegram_token, use_context=True)
     dispatcher = updater.dispatcher

     # Commands
     dispatcher.add_handler(CommandHandler("start", start))
     dispatcher.add_handler(CommandHandler("check", check))
     dispatcher.add_handler(CommandHandler("market", market))

     # Custom user control (allow only a specific user)
     dispatcher.add_handler(MessageHandler(Filters.chat(telegram_user_id) & Filters.command, start))

     # Start bot
     updater.start_polling()
     updater.idle()

if __name__ == "__main__":
     main()
```

### Operating System

Windows 11 PRO

### Version of Python, python-telegram-bot & dependencies

```shell
C:\Users\victus\Desktop\kodlar>python -m telegram
python-telegram-bot 20.7
Bot API 6.9
Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]

C:\Users\victus\Desktop\kodlar>
```

**Comment by Bibo-Joshi** [comment]
@Byex0 Hey. You seem to be using a version &gt;=20.0 of <code>python-telegram-bot</code>  but your code is written for version &lt;=13.15. Please either upgrade your code to  v20 by reading the release notes and the transition guide linked below or install a version of PTB that is compatible with your code base.
Please note that we only provide support for the latest stable version and that the library has undergone significant changes in v20.

**Comment by Byex0** [comment]
> @Byex0 Hey. You seem to be using a version >=20.0 of `python-telegram-bot` but your code is written for version <=13.15. Please either upgrade your code to v20 by reading the release notes and the transition guide linked below or install a version of PTB that is compatible with your code base. Please note that we only provide support for the latest stable version and that the library has undergone significant changes in v20.

I AM GETTING AN ERROR NOW MY CODE: import requests
from telegram import Update
from telegram.ext import CommandHandler, CallbackContext, Updater, MessageHandler, filters, CallbackContext

# Add bot and wallet information here
telegram_token = "BOT TOKEN"
telegram_user_id = USER ID
avax_address = "MY AVAX ADDRESS"

# CoinGecko API
coingecko_api_url = "https://api.coingecko.com/api/v3/simple/price"
coingecko_params = {
     "ids": "bitcoin,avalanche-2",
     "vs_currencies": "usd,try",
}

# Main functions
def start(update: Update, context: CallbackContext) -> None:
     if update.message.from_user.id == telegram_user_id:
         update.message.reply_text("Bot is active Boss, you can get information with /check.")
     else:
         update.message.reply_text("NOT USABLE EXCEPT AS A BOSS! CRY IN YOUR CORNER, LOSER.")

def check(update: Update, context: CallbackContext) -> None:
     if update.message.from_user.id == telegram_user_id:
         avax_balance, usd_price, try_price = get_balances()
         message = f"Your Avax Balance: {avax_balance} AVAX\nCurrent Price Value (USD): {usd_price:.2f}$\nCurrent Price Value (TRY): {try_price:.2f} TRY"
         update.message.reply_text(message)
     else:
         update.message.reply_text("NOT USABLE EXCEPT AS A BOSS! CRY IN YOUR CORNER, LOSER.")

def market(update: Update, context: CallbackContext) -> None:
     market_prices = get_market_prices()
     message = f"1 BTC = {market_prices['bitcoin']['usd']}$\n1 BTC = {market_prices['bitcoin']['try']} TRY\n\n1 AVAX = {market_prices['avalanche -2']['usd']}$\n1 AVAX = {market_prices['avalanche-2']['try']} TRY"
     update.message.reply_text(message)

def get_balances():
     try:
         # AVAX balance
         avax_response = requests.post(
             "https://api.avax.network/ext/bc/C/rpc",
             json={
                 "jsonrpc": "2.0",
                 "id": 1,
                 "method": "eth_getBalance",
                 "params": [avax_address, "latest"],
             },
         )
         avax_balance_wei = int(avax_response.json()["result"], 16)
         avax_balance = avax_balance_wei / 10**18

         # Current price information (using CoinGecko API)
         coingecko_response = requests.get(coingecko_api_url, params=coingecko_params)
         usd_price = coingecko_response.json()["avalanche-2"]["usd"]
         try_price = coingecko_response.json()["avalanche-2"]["try"]

         return avax_balance, usd_price, try_price
     except Exception as e:
         print(f"Error occurred: {e}")
         return None, None, None

def get_market_prices():
     try:
         coingecko_response = requests.get(coingecko_api_url, params=coingecko_params)
         return coingecko_response.json()
     except Exception as e:
         print(f"Error occurred: {e}")
         return None

def main():
     updater = Updater(telegram_token, use_context=True, persistence=None)
     dispatcher = updater.dispatcher

     # Commands
     dispatcher.add_handler(CommandHandler("start", start))
     dispatcher.add_handler(CommandHandler("check", check))
     dispatcher.add_handler(CommandHandler("market", market))

     # Custom user control (allow only a specific user)
     dispatcher.add_handler(MessageHandler(filters.Chat(telegram_user_id) & filters.Command, start))

     # Start bot
     updater.start_polling()
     updater.idle()

if __name__ == "__main__":
     main()


TERMINAL ERROR: Microsoft Windows [Version 10.0.22621.2861]
(c) Microsoft Corporation. All rights reserved.

C:\Users\victus\Desktop\kodlar>C:/Users/victus/AppData/Local/Programs/Python/Python312/python.exe c:/Users/victus/Desktop/kodlar/avax-telegram-bot/eleman_checker. py
Traceback (most recent call last):
   File "c:\Users\victus\Desktop\kodlar\avax-telegram-bot\eleman_checker.py", line 87, in <module>
     main()
   File "c:\Users\victus\Desktop\kodlar\avax-telegram-bot\eleman_checker.py", line 71, in main
     updater = Updater(telegram_token, use_context=True, persistence=None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^
TypeError: Updater.__init__() got an unexpected keyword argument 'use_context'

C:\Users\victus\Desktop\codes>


MY TELEGRAM BOT LIBRARY VERSION: Microsoft Windows [Version 10.0.22621.2861]
(c) Microsoft Corporation. All rights reserved.

C:\Users\victus\Desktop\codes>pip show python-telegram-bot
Name: python-telegram-bot
Version: 20.7
Summary: We have made you a wrapper you can't refuse
Home-page: https://python-telegram-bot.org/
Author: Leandro Toledo
Author-email: devs@python-telegram-bot.org
License: LGPLv3
Location: C:\Users\victus\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: httpx
Required-by:

C:\Users\victus\Desktop\codes>

**Comment by Bibo-Joshi** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0

Kindl read this transition guide. Sorry for missing the link in my earlier reply.

https://telegra.ph/Release-notes-for-python-telegram-bot-v200a0-05-06

**Comment by Byex0** [comment]
> https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0
> 
> Kindl read this transition guide. Sorry for missing the link in my earlier reply.
> 
> https://telegra.ph/Release-notes-for-python-telegram-bot-v200a0-05-06

My friend, I have already made this code for the farmer to write something. I have no knowledge of code. I gave up on the project. I don't understand these things right now. Thank you for your help.
