### ISSUE TITLE
[QUESTION] reply_photo & send_photo raise TimedOut for an actually completed request

### ISSUE THREAD

**Issue by ynad** [python-telegram-bot/python-telegram-bot#4071]
### Issue I am facing

Hello all.
I'm facing the exact same issue described here, in a slightly different situation:
https://github.com/python-telegram-bot/python-telegram-bot/issues/3704
Given the above issue was closed without a proper solution I'm writing here.

My bot can send image files in 2 different scenarios: 
1. on user prompt, via a `telegram.ext.Application` run with polling, using the method `update.message.reply_photo()`
2. on a schedule, to a predefined set of different users, via `telegram.Bot` instance using the method `bot.send_photo()`

Now and then a `telegram.error.TimedOut: Timed out` exception is raised when sending a single image in either one of the 2 above scenarios. 
File size and upload bandwidth should not be an issue: files are always around 200 kB, upload bandwidth is over 100Mbps. 

Despite of the timeout raised, the image is actually sent and the user receives it. If I catch the execption and try again sending it, it gets sent twice, or even more if I keep retrying.

I tried tweaking timeouts with the following values. The issue is slightly less frequent but still happens. 
```
read_timeout=10,
write_timeout=20,  # (default)
connect_timeout=10,
pool_timeout=5
```
When a timeout occurs in scenario number 2, the thread involved in that request awaits slowing down the entire process.

The attached traceback refers to scenario 1. If needed I can find one for the second scenario.
Related part of code is a very short abstract.
Tested on 2 machines, with different OS and python version. Same behavior.

What should I do? Completely ignore TimedOut exceptions, or increase read_timeout?
Sending a content multiple times may become annoying for the final user.

### Traceback to the issue

```python
2024-01-16 13:48:41,001 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 921, in read
    v = self._sslobj.read(len)
        ^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2546)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/anyio/streams/tls.py", line 205, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1123, in receive
    await self._protocol.read_event.wait()
  File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f1aa4240610

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1118, in __create_task_callback
    return await coroutine  # type: ignore[misc]
           ^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/ext/_basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/bot.py", line 597, in my_callback
    msg_details = await update.message.reply_photo(open(myfile, 'rb'), caption=descr, parse_mode=ParseMode.MARKDOWN_V2, read_timeout=5, write_timeout=20, connect_timeout=5, pool_timeout=5)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/_message.py", line 1393, in reply_photo
    return await self.get_bot().send_photo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 2666, in send_photo
    return await super().send_photo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 1081, in send_photo
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 522, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 703, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git-repo/myproject/.venv/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 285, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

### Related part of your code

```python
### scenario 1

# set up
tg_app = Application.builder().token(TOKEN).concurrent_updates(N).build()

# add error handler - here I log the exception with traceback.format_exception(None, context.error, context.error.__traceback__)
tg_app.add_error_handler(error_handler_callback)

# add all handlers
tg_app.add_handler(CommandHandler("mycmd", my_callback, block=False))
# ...


# run polling
tg_app.run_polling()

async def my_callback(update: Update, context: CallbackContext) -> None:
    msg_details = await update.message.reply_photo(open(myfile, 'rb'), caption=descr, parse_mode=ParseMode.MARKDOWN_V2, read_timeout=10, write_timeout=20, connect_timeout=10, pool_timeout=5)

    if msg_details:
        #save file_id for later use
        file_id = msg_details.photo[-1].file_id




### scenario 2

bot = telegram.Bot(token=TOKEN)

try:
    msg_details = await self.bot.send_photo(
                    chat_id=_id, 
                    photo=open(myfile, 'rb'), 
                    caption=f"my description", 
                    parse_mode=ParseMode.MARKDOWN_V2,
                    read_timeout=10,
                    write_timeout=20,
                    connect_timeout=10,
                    pool_timeout=5
                )

    return msg_details   # for later use with file_id

except telegram.error.BadRequest as e:
    ...
except telegram.error.TimedOut as e:
    ...
# and other exceptions

```

### Operating System

debian 12 & ubuntu 22.04

### Version of Python, python-telegram-bot & dependencies

```shell
debian machine:
python-telegram-bot 20.7
Bot API 6.9
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]


ubuntu machine:
python-telegram-bot 20.7
Bot API 6.9
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```

**Comment by Poolitzer** [comment]
@ynad Best you can do is increase timeout. There is no way for PTB to know if the request actually came through without telegram returning the appropriate answer, and it times out before telegram does that.

You could build in some hacky check via forwarding the next message id and check if that is the expected photo. Or you opt into sending it twice in the worst case 🤷‍♀

**Comment by ynad** [comment]
> @ynad Best you can do is increase timeout. There is no way for PTB to know if the request actually came through without telegram returning the appropriate answer, and it times out before telegram does that.
> 
> You could build in some hacky check via forwarding the next message id and check if that is the expected photo. Or you opt into sending it twice in the worst case 🤷‍♀

I see, thank you for the suggestion. 
Indeed at the moment I have read_timeout set to 10s, and only 1 retry in case of TimedOut. Previously I had up to 3 retries with a sleep in between.

I forgot to mention that this issues started as I recently migrated from PTB v13 to v20. In the previous synchronous environment with v13, timeouts were a very rare occasion.
I don't know if this depends on PTB or on telegram's API servers.

**Comment by Poolitzer** [comment]
I don't believe urllib or httpx handle timeouts much differently, and I doubt telegram changed something on their servers
