### ISSUE TITLE
[QUESTION] Error when importing package

### ISSUE THREAD

**Issue by cevinov** [python-telegram-bot/python-telegram-bot#4074]
### Issue I am facing

Hello everyone, I have a question when I try to import python-telegram-bot package. I got this error msg: ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.11/collections/__init__.py).

OS: Ubuntu 22.04.3 LTS
Python: 3.11.6

Thanks.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/config/workspace/codebase/func_telegram_notif.py", line 3, in <module>
    import telegram
  File "/root/anaconda3/lib/python3.11/site-packages/telegram/__init__.py", line 197, in <module>
    from . import _version, constants, error, helpers, request, warnings
  File "/root/anaconda3/lib/python3.11/site-packages/telegram/helpers.py", line 38, in <module>
    from telegram._utils.types import MarkdownVersion
  File "/root/anaconda3/lib/python3.11/site-packages/telegram/_utils/types.py", line 26, in <module>
    from pathlib import Path
  File "/root/anaconda3/lib/python3.11/site-packages/pathlib.py", line 10, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
```

### Related part of your code

```python
import sys
sys.path.insert(1, "/root/anaconda3/lib/python3.11/site-packages")
import telegram
```

### Operating System

Ubuntu 22.04

### Version of Python, python-telegram-bot & dependencies

```shell
(base) root@vino:/config/workspace/codebase# pip install python-telegram-bot
Requirement already satisfied: python-telegram-bot in /root/anaconda3/lib/python3.11/site-packages (20.7)
Requirement already satisfied: httpx~=0.25.2 in /root/anaconda3/lib/python3.11/site-packages (from python-telegram-bot) (0.25.2)
Requirement already satisfied: anyio in /root/anaconda3/lib/python3.11/site-packages (from httpx~=0.25.2->python-telegram-bot) (3.5.0)
Requirement already satisfied: certifi in /root/anaconda3/lib/python3.11/site-packages (from httpx~=0.25.2->python-telegram-bot) (2023.7.22)
Requirement already satisfied: httpcore==1.* in /root/anaconda3/lib/python3.11/site-packages (from httpx~=0.25.2->python-telegram-bot) (1.0.2)
Requirement already satisfied: idna in /root/anaconda3/lib/python3.11/site-packages (from httpx~=0.25.2->python-telegram-bot) (3.4)
Requirement already satisfied: sniffio in /root/anaconda3/lib/python3.11/site-packages (from httpx~=0.25.2->python-telegram-bot) (1.2.0)
Requirement already satisfied: h11<0.15,>=0.13 in /root/anaconda3/lib/python3.11/site-packages (from httpcore==1.*->httpx~=0.25.2->python-telegram-bot) (0.14.0)
```

**Comment by Poolitzer** [comment]
Hi, you need to run at least python 3.11.8

**Comment by cevinov** [comment]
I see, okay let me upgrade it. Thanks

**Comment by Poolitzer** [comment]
Sorry, it was too early in the morning and I mixed something up. You should be able to run this with any 3.11 version.

But this error actually doesn't come from PTB, rather pathlib, which is just a standard python package. I googled a bit but didn't find anything helpful, sorry.

**Comment by Bibo-Joshi** [comment]
> ```python
> import sys
> sys.path.insert(1, "/root/anaconda3/lib/python3.11/site-packages")
> import telegram
> ```

This part looks suspicious to me. Please make sure that you install PTB to the same python environment (venv/pipenv/anaconda environment/whatever) that you use to run PTB instead of manually linking to other directories.
