### ISSUE TITLE
[QUESTION] Running telegram-bot in a seperate process

### ISSUE THREAD

**Issue by aadi58002** [python-telegram-bot/python-telegram-bot#4107]
### Issue I am facing

Local environment has many cpu cores so it work fine on the local machine.
But since the deployment environment only has a single thread.It errors out with `This event loop is already running.`

### Traceback to the issue

```python
INFO:     Started server process [1532]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     152.58.157.203:55842 - "GET / HTTP/1.1" 200 OK
INFO:     152.58.157.203:33236 - "POST /submit/ HTTP/1.1" 200 OK
Process Process-1:
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1006, in __run
    raise exc
  File "/home/azureuser/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 995, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1017, in __run
    loop.run_until_complete(self.shutdown())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 818, in run_polling
    return self.__run(
  File "/home/azureuser/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1022, in __run
    loop.close()
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 89, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
/usr/lib/python3.8/multiprocessing/process.py:331: RuntimeWarning: coroutine 'Application.shutdown' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.8/multiprocessing/process.py:331: RuntimeWarning: coroutine 'Application.initialize' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1532]
```

### Related part of your code

```python
import logging
from multiprocessing import Process

from telegram import Update
from telegram.ext import Application,ApplicationBuilder, MessageHandler, filters

async def echo(update: Update,_) -> None:
    message = update.message.text
    await update.message.reply_text(message)

class TelegramBot:
    app: Application

    def __init__(self,token: str) -> None:
        logging.info(f"Starting bot for {token}")
        self.app = ApplicationBuilder().token(token).build()
        self.app.add_handler(MessageHandler(filters.TEXT, echo))

    def start(self) -> Process:
        p = Process(target=self.app.run_polling,args=())
        p.start()
        return p
```

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
Deployment:-
python-telegram-bot 20.7
Bot API 6.9
Python 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]

Local:-
python-telegram-bot 20.7
Bot API 6.9
Python 3.12.1 (main, Dec 26 2023, 18:42:33) [GCC 12.2.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. Why are you running PTB via multiprocessing? How is uvicorn related to your question (I see it in the logs)? One reason for your problem could be that you create the `app` in one event loop but then try to run it in a different one. At least this is a problem in multi-threading and I can imagine that it carries over in multiprocessing.

**Comment by aadi58002** [comment]
I am starting a fastapi endpoint with unicorn. It spawn a new instance of the TelegramBot class which should manage a running state of a telegram bot. I tried to make it work with multi threading but that didn't also error out when creating a event loop or trying to get a event loop. If it helps I can also send the logs of the multithread code as well

**Comment by Bibo-Joshi** [comment]
@aadi58002 I highly recommend to utilize asyncios native concurrency for this. Please have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks">Running PTB alongside other asyncio frameworks</a> and <a href="https://docs.python-telegram-bot.org/examples.customwebhookbot.html">examples.customwebhookbot</a>. Those should give you some pointers.

**Comment by aadi58002** [comment]
In both the above examples. It already has the token before starting the api framework. In my use it registers a new token from a web page and has to run a new bot for each new token submitted at the web page.

```py
import logging
import uvicorn

from fastapi import FastAPI, Request
from fastapi.templating import Jinja2Templates
from fastapi.responses import HTMLResponse

from telegramBot import TelegramBot

app = FastAPI()
templates = Jinja2Templates(directory="templates")
list_processes = dict()

@app.get("/", response_class=HTMLResponse)
async def read_form(request: Request):
    return templates.TemplateResponse("form.html", {"request": request})

@app.post("/submit/")
async def submit_form(request: Request):
    data = (await request.json())['input_text']
    logging.info(data)
    if not data in list_processes:
        telegramBot = TelegramBot(data)
        telegramBot.start()
        logging.info("Telebot started")
        list_processes[data] = telegramBot
        return "Successfully registered bot"
    else:
        return "Already registered bot"

if __name__ == "__main__":
    uvicorn.run(app,port=8000)
```

**Comment by Bibo-Joshi** [comment]
Yes, I understood the idea. This is still very well possible. Just create a new `telegram.ext.Application` command on command and call `application.start`. You'll ofc need to fetch updates for this application as well, and since you already have a webserver running, I recommend to set up an endpoint that listenst to `https://yourdomain.tld/bots/<token>` and calls `application.update_queue.put(update)` for the application with that bot token. You'll call `application.updater.start_webhook` with the corresponding arguments. Please have a look at at our wiki page on [webhooks](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#custom-solution) for more details on that.

**Comment by aadi58002** [comment]
Thanks I looked into webhook and they are are a better fit for my project.
