### ISSUE TITLE
Error handler doesn't handle

### ISSUE THREAD

**Issue by ahrajabi** [python-telegram-bot/python-telegram-bot#416]
It may be my programming fault! I am using django.
I add error_callback function to error_handler same as your explain in wiki:

```
def error_callback(bot, update, error):
    try:
        raise error
    except Unauthorized:
        print(update)
    except BadRequest:
        print("# handle malformed requests - read more below!")
    except TimedOut:
        print("# handle slow connection problems")
    except NetworkError:
        print("# handle other connection problems")
    except TelegramError:
        print("# handle all other telegram related errors")

dispatcher.add_error_handler(error_callback)
```
I am sure that the function was added
```
In[5]: updater.dispatcher.error_handlers
Out[5]: [<function telegrambot.bottask.error_callback>]
```
But handler doesn't handle error and I get uncaught error

```
An uncaught error was raised while executing job publish_handler (jobqueue.py:132)
Traceback (most recent call last):
  File "/lib/python3.5/site-packages/telegram/ext/jobqueue.py", line 128, in tick
    job.run(self.bot)
  File "/lib/python3.5/site-packages/telegram/ext/jobqueue.py", line 233, in run
    self.callback(bot, self)
  File "/telegrambot/publish.py", line 28, in publish_handler
    live_publish_news(bot, job)
  File "/telegrambot/publish.py", line 99, in live_publish_news
    bot_send.send_telegram_user(bot, user, "output")
  File "/telegrambot/bot_send.py", line 32, in send_telegram_user
    parse_mode=telegram.ParseMode.HTML)
  File "/lib/python3.5/site-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/lib/python3.5/site-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/lib/python3.5/site-packages/telegram/utils/request.py", line 235, in post
    **urlopen_kwargs)
  File "/lib/python3.5/site-packages/telegram/utils/request.py", line 178, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized

```
Can you show me where i should check? thanks

**Comment by jh0ker** [comment]
Hi!

The log you posted indicates that the error was raised by a job in the `JobQueue`. These are not covered by the `Dispatcher` error handlers. That means you have to catch exceptions in your job callback functions manually.

Perhaps we can change that in a future release - so thank you for bringing this to our attention!
