### ISSUE TITLE
[QUESTION] problem with reading timeout.

### ISSUE THREAD

**Issue by XCisCoX** [python-telegram-bot/python-telegram-bot#4203]
### Steps to Reproduce

1. some times when my network speed is not the best it have problem with send document.
2. size of document is like 10 mg.
3. timeout is kinda too low i guess.

### Expected behaviour

the problem is with  timeout reading... it's too low i guess. and the pool_timeout dosen't affect the reading timeout.
what i am sending to telegram is a sqlite db with 10 mg size.
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/37977047/eb898550-ac09-448d-b937-242b48116e7c)

### Actual behaviour

Timeout error

### Operating System

10

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Package             Version
------------------- --------
aiocache            0.12.2
aiohttp             3.9.3
aiosignal           1.3.1
annotated-types     0.6.0
anyio               4.3.0
APScheduler         3.10.4
attrs               23.2.0
beautifulsoup4      4.12.3
cachetools          5.3.3
certifi             2024.2.2
charset-normalizer  3.3.2
cx_Freeze           6.15.16
cx_Logging          3.2.0
docutils            0.20.1
enka.py             1.2.1
enkanetwork.py      1.4.4
frozenlist          1.4.1
h11                 0.14.0
httpcore            1.0.4
httpx               0.27.0
idna                3.6
Kivy                2.3.0
kivy-deps.angle     0.4.0
kivy-deps.glew      0.3.1
kivy-deps.sdl2      0.7.0
Kivy-Garden         0.1.5
kivymd              1.2.0
lief                0.14.1
multidict           6.0.5
pillow              10.2.0
pip                 24.0
pydantic            2.6.3
pydantic_core       2.16.3
Pygments            2.17.2
pypiwin32           223
python-telegram-bot 21.0.1
pytz                2024.1
pywin32             306
requests            2.31.0
setuptools          65.5.0
six                 1.16.0
sniffio             1.3.1
soupsieve           2.5
typing_extensions   4.10.0
tzdata              2024.1
tzlocal             5.2
urllib3             2.2.1
wheel               0.43.0
yarl                1.9.4
```

### Relevant log output

```python
PS C:\Users\cisco\source\github\paimonak>  c:; cd 'c:\Users\cisco\source\github\paimonak'; & 'c:\Users\cisco\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\cisco\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '14809' '--' 'C:\Users\cisco\source\github\paimonak\main.py'
<blockquote> 2024-04-12 23:21:11 </blockquote>Bot Started...
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions    
    yield
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request      
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http_proxy.py", line 344, in handle_async_request     
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 143, in handle_async_request
    raise exc
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_headers    
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_backends\anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request      
    with map_httpcore_exceptions():
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions    
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_jobqueue.py", line 966, in _run
    await self.callback(context)
  File "C:\Users\cisco\source\github\paimonak\main.py", line 937, in db_backup
    await h_bot.send_document(chat_id = PAIMONAK_ERROR_CHANNEL, document = "telegram_db.sqlite", caption=formatted_time,
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2572, in send_document
    return await super().send_document(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 541, in decorator
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1667, in send_document
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 581, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 735, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 629, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 657, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper      
    raise exc
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper      
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cisco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_httpxrequest.py", line 293, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

**Comment by Bibo-Joshi** [comment]
@XCisCoX Hi. Please carefully read the descriptions of the 4 different timeout parameters of <a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.send_document">telegram.Bot.send_document</a> <a href="https://core.telegram.org/bots/api#senddocument">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>. I&#x27;m pretty sure that this will answer your question.

**Comment by XCisCoX** [comment]
yes i did, my mistake skiping documents as usual,  thank you

**Comment by XCisCoX** [comment]
@Bibo-Joshi yes i did, my mistake skiping documents as usual,  thank you
