### ISSUE TITLE
[QUESTION] echobot.py is not working.

### ISSUE THREAD

**Issue by OutOfHell56** [python-telegram-bot/python-telegram-bot#4256]
### Issue I am facing

(I'm new to programming so sorry if it's a stupid question)
Used python venv

codes used:
python3 -m venv Bot1_test
cd Bot1_test
source bin/activate
pip3 install python-telegram-bot
nano main.py
(copied the echobot.py file from examples and put my token in the "TOKEN" section)
python3 main.py
(encountered the following error)

Please help. Thank you in advance

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/main.py", line 72, in <module>
    main()
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/main.py", line 67, in main
    application.run_polling(allowed_updates=Update.ALL_TYPES)
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/ext/_application.py", line 838, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/ext/_application.py", line 1049, in __run
    raise exc
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/ext/_application.py", line 1038, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/ext/_application.py", line 497, in initialize
    await self.bot.initialize()
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/ext/_extbot.py", line 295, in initialize
    await super().initialize()
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/_bot.py", line 763, in initialize
    await self.get_me()
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/ext/_extbot.py", line 1880, in get_me
    return await super().get_me(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/_bot.py", line 896, in get_me
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/_bot.py", line 615, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/ext/_extbot.py", line 349, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/_bot.py", line 644, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/request/_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeal/Documents/Programming/Python/TelegramBot/Bot1_test/lib64/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno -2] Name or service not known
```

### Related part of your code

```python
#!/usr/bin/env python
# pylint: disable=unused-argument
# This program is dedicated to the public domain under the CC0 license.

"""
Simple Bot to reply to Telegram messages.

First, a few handler functions are defined. Then, those functions are passed to
the Application and registered at their respective places.
Then, the bot is started and runs until we press Ctrl-C on the command line.

Usage:
Basic Echobot example, repeats messages.
Press Ctrl-C on the command line or send a signal to the process to stop the
bot.
"""

import logging

from telegram import ForceReply, Update
from telegram.ext import Application, CommandHandler, ContextTypes, MessageHandler, filters

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
# set higher logging level for httpx to avoid all GET and POST requests being logged
logging.getLogger("httpx").setLevel(logging.WARNING)

logger = logging.getLogger(__name__)


# Define a few command handlers. These usually take the two arguments update and
# context.
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Send a message when the command /start is issued."""
    user = update.effective_user
    await update.message.reply_html(
        rf"Hi {user.mention_html()}!",
        reply_markup=ForceReply(selective=True),
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Send a message when the command /help is issued."""
    await update.message.reply_text("Help!")


async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Echo the user message."""
    await update.message.reply_text(update.message.text)


def main() -> None:
    """Start the bot."""
    # Create the Application and pass it your bot's token.
    application = Application.builder().token("<yes-i-did-put-the-correct-token>").build()

    # on different commands - answer in Telegram
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))

    # on non command i.e message - echo the message on Telegram
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))

    # Run the bot until the user presses Ctrl-C
    application.run_polling(allowed_updates=Update.ALL_TYPES)
    # application.stop


if __name__ == "__main__":
    main()
```

### Operating System

Fedora Linux 39

### Version of Python, python-telegram-bot & dependencies

```shell
anyio               4.3.0
async               0.6.2
asyncio             3.4.3
certifi             2024.2.2
charset-normalizer  3.3.2
h11                 0.14.0
httpcore            1.0.5
httpx               0.27.0
idna                3.7
logging             0.4.9.6
pip                 24.0
python-telegram-bot 21.1.1
requests            2.31.0
sniffio             1.3.1
typing              3.7.4.3
urllib3             2.2.1
```

**Comment by Poolitzer** [comment]
Hi, the program can't reach telegrams servers. Try pinging api.telegram.org, it will also fail.

**Comment by OutOfHell56** [comment]
> ping api.telegram.org
ping: api.telegram.org: Name or service not known

**Comment by OutOfHell56** [comment]
@Poolitzer 

$ ping api.telegram.org
ping: api.telegram.org: Name or service not known

What can i do?

**Comment by Poolitzer** [comment]
You need to fix the internet connection to telegrams API. Either via resolving whatever stops you from reaching it in your OS/the hoster, or use a proxy/VPN.

**Comment by OutOfHell56** [comment]
@Poolitzer 
solved. it was dns. added 8.8.8.8 as defaut dns and now its working.
Thank you.
