### ISSUE TITLE
[BUG] Timeout when start polling

### ISSUE THREAD

**Issue by ffleader1** [python-telegram-bot/python-telegram-bot#4268]
### Steps to Reproduce

Run the default example

`
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes

async def hello(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(f'Hello {update.effective_user.first_name}')

app = ApplicationBuilder().token("YOUR TOKEN HERE").build()

app.add_handler(CommandHandler("hello", hello))

app.run_polling()
`

### Expected behaviour

The bot connect to from telegram.

### Actual behaviour

Time out on pooling (log below)

### Operating System

Ubuntu 20.04.6 LTS

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.12.3
```

### Relevant log output

```python
Traceback (most recent call last):
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpcore/_async/connection.py", line 154, in _connect
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 68, in start_tls
    with map_exceptions(exc_map):
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/simple.py", line 13, in <module>
    app.run_polling(close_loop=False)
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/ext/_application.py", line 871, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/ext/_application.py", line 1069, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/ext/_application.py", line 498, in initialize
    await self.bot.initialize()
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 299, in initialize
    await super().initialize()
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/_bot.py", line 766, in initialize
    await self.get_me()
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 1900, in get_me
    return await super().get_me(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/_bot.py", line 898, in get_me
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysadmin/PycharmProjects/tele-spectral-color-bot/venvp/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

### Additional Context

Worked on Windows, on the same router. Can also ping api.telegram.org 

`
ping  api.telegram.org
PING api.telegram.org(2001:67c:4e8:f004::9 (2001:67c:4e8:f004::9)) 56 data bytes
64 bytes from 2001:67c:4e8:f004::9 (2001:67c:4e8:f004::9): icmp_seq=1 ttl=47 time=249 ms
64 bytes from 2001:67c:4e8:f004::9 (2001:67c:4e8:f004::9): icmp_seq=2 ttl=47 time=245 ms
64 bytes from 2001:67c:4e8:f004::9 (2001:67c:4e8:f004::9): icmp_seq=3 ttl=47 time=245 ms
64 bytes from 2001:67c:4e8:f004::9 (2001:67c:4e8:f004::9): icmp_seq=4 ttl=47 time=245 ms
^C
--- api.telegram.org ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4000ms
rtt min/avg/max/mdev = 244.824/246.055/249.025/1.720 ms
`

So definitely not a network issue

**Comment by ffleader1** [comment]
It's brobably my own DNS problem

**Comment by Poolitzer** [comment]
Alright you closed this but I already typed out the response so still commenting in case I need to link back to it later: If you get this error after 200 seconds, I would assume the process is somehow blocked by a firewall to connect to the internet.

You could reduce overhead and just make a simple httpx request and see what that gets you

```python
import httpx
import asyncio


async def main():
    async with httpx.AsyncClient() as client:
        r = await client.get('https://api.telegram.org/botTOKEN/getMe')
        print(r.json())

asyncio.run(main())
```

**Comment by ffleader1** [comment]
> Alright you closed this but I already typed out the response so still commenting in case I need to link back to it later: If you get this error after 200 seconds, I would assume the process is somehow blocked by a firewall to connect to the internet.
> 
> You could reduce overhead and just make a simple httpx request and see what that gets you
> 
> ```python
> import httpx
> import asyncio
> 
> 
> async def main():
>     async with httpx.AsyncClient() as client:
>         r = await client.get('https://api.telegram.org/botTOKEN/getMe')
>         print(r.json())
> 
> asyncio.run(main())
> ```

Alright I found the problem
My Ubuntu was using Ipv6, and so for whatever reason, when connecting to api.telegram/org, Python, curl,... uses Ipv6, which timedout.
So yeah, any future person ran into this situation, maybe doucle check your Ipv6. It will break with telegram API.
