### ISSUE TITLE
[FEATURE] Telegram types/objects entities as a standalone package

### ISSUE THREAD

**Issue by begoon** [python-telegram-bot/python-telegram-bot#4289]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Having Telegram types/objects as a package without the communication layer would be helpful.

For example, the current version uses async communications. It is impossible to use the library in the sync code, for instance, flask. It is possible to use the previous version, which is sync, but it has a bit of outdated Telegram protocol.

Types, object serialization, and deserialization may exist separately from the Telegram communication routines. 

### Describe the solution you'd like

Ship types and data entities in a separate package.

**Comment by Poolitzer** [comment]
Hi, it is definitely possible to use this with sync, you just need to work around the async calls but that is rather easy (in the end just use asyncio.run() whenever you encounter one basically). But you can actually build class instances with a sync call since de_json is a sync function. You might have to pass a mock bot instance but initiating that is actually also a sync thing so typing this out I don't even see where you would be forced to use asyncio when initiating an object :D

**Comment by begoon** [comment]
@Poolitzer Unfortunately, asyncio.run() is not reentrant.

I tried to use async PTB in serverless functions (AWS lambda, GCP cloud function, Azure function -- all these frameworks are sync), and PTB async calls crash due to the global event loop in asyncio.

Yes, using only de_json() may work, but in this case, the PTB dependency brings lots of bloat (comms, scheduler etc.). So having just data entities would be much better in this use case.

**Comment by Poolitzer** [comment]
the comms dependency (httpx) wheel size is 75.6 kB, PTB 618kb. The rest is optional and not installed if you don't specify it in the pip install.

I cant see how you crashed, if you want to elaborate that we might be able to help. I can easily do this without having any asyncio interaction.

```python
bot = Bot("123:T")
update = Update.de_json({update_data})
```

**Comment by Bibo-Joshi** [comment]
Let me just add some links to the discussion:

* [PTB dependencies](https://docs.python-telegram-bot.org/en/v21.2/#dependencies-their-versions)
* [using ptb with flask](https://docs.python-telegram-bot.org/en/v21.2/examples.customwebhookbot.html)
* [notes on using ptb in serverless functions](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#alternative-no-long-running-tasks) ("no long running tasks")

**Comment by begoon** [comment]
Sure, there are ways to work around it. However, the main inconvenience I have encountered so far is "RuntimeError: Event loop is closed" when I wrap async calls to PTB into "asyncio.run()". As I understand, this happens when "asyncio.run()" is used in re-entrant code.

I tried AWS lambda, GCP function (gen2 but deployed from sources, not a docker image), and Azure Function App. All these frameworks are synchronous, and they crash async code with "RuntimeError: Event loop is closed."

Of course, I can deploy differently via docker, where I can run the async server myself with FastAPI and the latest async PTB. However, I need a pure serverless function deployment that uses frameworks provided by AWS, GCP, and Azure.

Alas, I switched back to PTB 13.15. Even though I have to do something like
```python
  data: JSONDict = {
      'chat_id': message.chat.id,
      'message_id': message.message_id,
      'reaction': [{"type": "emoji", "emoji": emoji}],
      'is_big': 'a lot' in text,
  }

  bot._post('setMessageReaction', data)
```
to do newer API calls, unsupported by PTB 13.15.

13.15 is still excellent, though the packaging is not as granular as the latest version. 

Of course, isolating the data entities from comms in PTB is not straightforward because some entities can do comms (like sending a reply from Message, CallbackQuery, etc.). 

The potential split data objects from comms may need another layer in between, where it would be possible to control how to do comms: sync or async.

**Comment by Poolitzer** [comment]
You can fix the asyncio issue, it gets a bit more complex if you call asyncio twice (I think this is what you mean with re-entrant), since you can not use asyncio.run but need to indeed keep the loop open but thats like 5 lines more code overall.

My point is: You can absolutely use our objects and transfer from json dict to them and back from them to post the json by yourself with a sync network solution, so without any asyncio (which is what your original suggestion is about). And you can go the extra mile and integrate proper asyncio calls using a bit deeper asyncio level then asyncio.run.

But when we decided to develop V20, we made the decision against separating a sync level. The extra code (and thus maintenance work) is too much work for us for not enough demand.

**Comment by begoon** [comment]
I understand. "asyncio" in Python, in general, is a valid point going forward. No doubts.

However, when you cannot control the comms plumbing and you only provide a callback, being stuck bending async code into sync is not easy :-)

Anyways, if anyone is curious, here is the adapter code that uses PTB as a webhook in different controlled environments:

- [AWS lambda](https://github.com/begoon/tmpz/blob/main/telegram-py-webhook/function_aws.py)

- [GCP function](https://github.com/begoon/tmpz/blob/main/telegram-py-webhook/function_gcp.py)

- [Azure function](https://github.com/begoon/tmpz/blob/main/telegram-py-webhook/function_azure.py)

[bot.py](https://github.com/begoon/tmpz/blob/main/telegram-py-webhook/bot.py) is generic.

As an experiment, I implemented a simple bot without PTB as [bot_.py](https://github.com/begoon/tmpz/blob/main/telegram-py-webhook/bot_.py) and [telegram_.py](https://github.com/begoon/tmpz/blob/main/telegram-py-webhook/telegram_.py), just using the official API definition. This is okay, but of course, using Python data entities is more convenient. 

Please, close the issue if necessary.

**Comment by Poolitzer** [comment]
Alright, I took this challenge. If I understand correctly, AWS (or any else) calls the whole python file whenever an update happens. So doing smth as simple as this should work, no? You can ofc replace bot with application and use the full possibilities of handlers etc, kinda like the custom webhook examples do.

sync file called by the service (I emulated this by calling the function in the file but this should not matter at all, at most you need to move the loop creating in the function)

```python
import time

import bot
import asyncio

loop = asyncio.new_event_loop()

def lambda_handler(request):
    loop.run_until_complete(bot.take_care_of_update(request["data"]))

lambda_handler({"data": {
  "update_id": 144444933,
  "message": {
    "message_id": 1201258,
    "from": {
      "id": 208589966,
      "is_bot": False,
      "first_name": "Poolitzer X",
      "username": "Poolitzer",
      "language_code": "en",
      "is_premium": True
    },
    "chat": {
      "id": 208589966,
      "first_name": "Poolitzer X",
      "username": "Poolitzer",
      "type": "private"
    },
    "date": 1712859960,
    "dice": {
      "emoji": "🎲",
      "value": 4
    }
  }
}})

time.sleep(5)

lambda_handler({"data": {
  "update_id": 144444933,
  "message": {
    "message_id": 1201258,
    "from": {
      "id": 208589966,
      "is_bot": False,
      "first_name": "Poolitzer X",
      "username": "Poolitzer",
      "language_code": "en",
      "is_premium": True
    },
    "chat": {
      "id": 208589966,
      "first_name": "Poolitzer X",
      "username": "Poolitzer",
      "type": "private"
    },
    "date": 1712859960,
    "dice": {
      "emoji": "🎲",
      "value": 4
    }
  }
}})
```

And then in bot.py which is imported this is like. But again you can use application in here if you want to.

```python
from telegram.ext import ExtBot
from telegram import Update

bot = ExtBot("1234:TOKEN")

async def take_care_of_update(update_json):
    async with bot:
        update = Update.de_json(update_json, bot)
        await update.effective_user.send_message("Wuhu")

```

**Comment by begoon** [comment]
I attempted [the following to wrap](https://github.com/begoon/tmpz/commit/f4f7e742bd51b7ede6d0b050ac6ed4a45c0b2f7d) async again by creating the event loop explicitly.

Alas, even when running locally under the sync flask, it is failing:

```
2024-06-03 17:25:43,180 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot12345678901234567891234567890/getWebhookInfo "HTTP/1.1 200 OK"
2024-06-03 17:25:43,183 - werkzeug - INFO - 127.0.0.1 - - [03/Jun/2024 17:25:43] "GET /health HTTP/1.1" 200 -
2024-06-03 17:25:43,851 - bot - INFO - bot token 12345678901234567891234567890
2024-06-03 17:25:43,930 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot12345678901234567891234567890/getMe "HTTP/1.1 200 OK"
2024-06-03 17:25:43,930 - bot - INFO - me super_bot
2024-06-03 17:25:43,930 - bot - INFO - wheel 1234567890
2024-06-03 17:25:43,987 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot12345678901234567891234567890/sendMessage "HTTP/1.1 200 OK"
2024-06-03 17:25:44,041 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot12345678901234567891234567890/sendMessage "HTTP/1.1 200 OK"
2024-06-03 17:25:44,042 - bot - INFO - /ping cmd.description='ping'
2024-06-03 17:25:44,042 - bot - INFO - /html cmd.description='html message'
2024-06-03 17:25:44,042 - bot - INFO - /markdown cmd.description='markdown message'
2024-06-03 17:25:44,042 - bot - INFO - /file cmd.description='file info'
2024-06-03 17:25:44,042 - bot - INFO - /ls cmd.description='list files'
2024-06-03 17:25:44,042 - bot - INFO - /me cmd.description='me'
2024-06-03 17:25:44,074 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot12345678901234567891234567890/setMyCommands "HTTP/1.1 200 OK"



2024-06-03 17:25:57,390 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot12345678901234567891234567890/answerCallbackQuery "HTTP/1.1 200 OK"
2024-06-03 17:25:57,392 - bot - INFO - cmd='/me' args=[]
2024-06-03 17:25:57,392 - main - ERROR - Exception on /bot [POST]
Traceback (most recent call last):
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/main.py", line 25, in update
    bot.update(request_)
  File "./github/tmpz/telegram-py-webhook/bot.py", line 267, in update
    loop.run_until_complete(update_async(request))
  File "./.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/bot.py", line 357, in update_async
    await action(update, args)
  File "./github/tmpz/telegram-py-webhook/bot.py", line 237, in me
    info = health()
           ^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/bot.py", line 119, in health
    return loop.run_until_complete(health_async())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 629, in run_until_complete
    self._check_running()
  File "./.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 588, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2024-06-03 17:25:57,401 - werkzeug - INFO - 127.0.0.1 - - [03/Jun/2024 17:25:57] "POST /bot HTTP/1.1" 500 -
2024-06-03 17:25:57,465 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot12345678901234567891234567890/answerCallbackQuery "HTTP/1.1 200 OK"
2024-06-03 17:25:57,465 - bot - INFO - cmd='/me' args=[]
2024-06-03 17:25:57,465 - main - ERROR - Exception on /bot [POST]
Traceback (most recent call last):
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/.venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/main.py", line 25, in update
    bot.update(request_)
  File "./github/tmpz/telegram-py-webhook/bot.py", line 267, in update
    loop.run_until_complete(update_async(request))
  File "./.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/bot.py", line 357, in update_async
    await action(update, args)
  File "./github/tmpz/telegram-py-webhook/bot.py", line 237, in me
    info = health()
           ^^^^^^^^
  File "./github/tmpz/telegram-py-webhook/bot.py", line 119, in health
    return loop.run_until_complete(health_async())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 629, in run_until_complete
    self._check_running()
  File "./.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 588, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2024-06-03 17:25:57,467 - werkzeug - INFO - 127.0.0.1 - - [03/Jun/2024 17:25:57] "POST /bot HTTP/1.1" 500 -
```

**Comment by Bibo-Joshi** [comment]
Hey. Coming back to this issue, IMO there are two separate topics in here:

1. Using data types provided by PTB without doing any networking communication. This is already possible as-is. Calling `TelegraObject.de_json/dict` and `TelegraObject.to_json/dict` can be done without making a single request to Telegram. There are two minor downsides to this:
    1.  `TO.de_json` expects a `Bot` object as second argument since that's used form all the shortcuts like `Message.reply_text`. You should be able to just pass `None` (and tell your static type checker to shut up …). We could look into making this argument optional.
    2. PTB still has a requirement to `httpx` for the networking stuff. When going for v20 we discussed making this optional as well, but keeping the vast majority of use cases in mind where networking is actually required, we opted to support the main use case here.
2. Making asyncio function calls in a non-asyncio framework. This problem is not specific to PTB but rather a question related to asyncio programming in python in general. Looking up asyncio in the context of the mentioned frameworks Azure, GCP & AWS yields feature requests, SO entries & similar for each one. In terms of PTB, the only question to pose in this thread here would be "Does PTB want to support a non-asyncio interface as well?" and as pool already pointed out, the answer to that is no.

**Comment by Bibo-Joshi** [comment]
Closing as #4320 has been merged and no further reply was received.
