### ISSUE TITLE
Handling telegram.NetworkError while using application.run_polling()

### ISSUE THREAD

**Issue by Heroeskeeper** [python-telegram-bot/python-telegram-bot#4343]
### Issue I am facing

Hey there.
After studying [this](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors) page and [this](https://github.com/python-telegram-bot/python-telegram-bot/issues/3430) and the code in the examples section I cannot seem to find a way to call the error handler function while using run_polling() for a async nested conversation bot.

If there is none this quote from the first link above states that: 

> Note that for (network) errors that happen as part of **[Application.run_polling](https://docs.python-telegram-bot.org/en/stable/telegram.ext.application.html#telegram.ext.Application.run_polling)/[Updater.start_polling](https://docs.python-telegram-bot.org/en/stable/telegram.ext.updater.html#telegram.ext.Updater.start_polling) are processed via the [error_callback](https://docs.python-telegram-bot.org/en/stable/telegram.ext.updater.html#telegram.ext.Updater.start_polling.params.error_callback) parameter** of Updater.start_polling rather than [Application.process_error](https://docs.python-telegram-bot.org/en/stable/telegram.ext.application.html#telegram.ext.Application.process_error). If you whish to handle also those as part of Application.process_error, you can e.g. use.....

---but the run_polling() function does not have an argument: 'error_callback'?

If what was quoted there is true, how could one access the error_callback parameter?
A code example would be hugely appreciated!

I disable the network adaptor to force the network error and get ConnectError, but the sporadic error from service outage is NetworkError: Bad gateway.

All I want to do is de-clutter the logger terminal  while using application.run_polling() as our service provider has stability issues.
Any help would be so welcome.
Thanks.

### Traceback to the issue

```python
2024-07-03 12:28:42,385 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2024-07-03 12:28:42,410 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quinten\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
yesss
2024-07-03 12:28:42,443 - __main__ - CRITICAL - Telegram network error.
```

### Related part of your code

```python
import traceback
from telegram import Update, error

...

async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE) -> None:
    logger.error("Exception while handling an update:", exc_info=context.error)
    tb_list = traceback.format_exception(None, context.error, context.error.__traceback__, limit=None)
    tb_string = "".join(tb_list[-2:])
    message = (
        "An exception was raised while handling an update\n"
        f"<pre>{html.escape(tb_string)}</pre>"
    )

    if isinstance(context.error, error.NetworkError):
            message = "Telegram network error."
            logger.critical(message)
    else:
        await context.bot.send_message(
            chat_id=DEVELOPER_CHAT_ID, text=message, parse_mode='HTML'
        )

if __name__ == '__main__':
    application = ApplicationBuilder().read_timeout(7).get_updates_read_timeout(42).token(TOKEN).build()

...

    application.add_error_handler(error_handler)

    try:

...

        application.run_polling(allowed_updates=Update.ALL_TYPES)
    except Exception as err:
        print(err)
```

### Operating System

Win 10/RPI

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.11
PTB 21.1.1
```

**Comment by Poolitzer** [comment]
Hi this method is indeed not exposed via application.run_polling but can rather easily be added. You can for now follow https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks and add the error callback in the polling call there, or you edit the library by yourself :)

**Comment by Poolitzer** [comment]
Oh I just had a look in the code by default this should actually call a registered error handler with the update set to None, is this not happening for you?

**Comment by Heroeskeeper** [comment]
Hi Poolitzer.
Thanks for your effort.
Yes I do catch the error in the error_handler() which then prints:

> 2024-07-03 12:28:42,443 - __main__ - CRITICAL - Telegram network error.

Something else happens before that which triggers the traceback on the logger terminal. I'm hoping to catch and handle that too wherever it comes from. 

So the advice in your first reply is my next step?

**Comment by Poolitzer** [comment]
> Something else happens before that which triggers the traceback on the logger terminal.

No I dont think so, I think this it the one error which happens, and you also log it, in your provided example code with the line
`logger.error("Exception while handling an update:", exc_info=context.error)`

**Comment by Heroeskeeper** [comment]
Ok yes, that is suddenly so obvious and silly of me.

I've updated the handler function as follows:
```Python
async def error_handler(update: None, context: ContextTypes.DEFAULT_TYPE) -> None:

    tb_list = traceback.format_exception(None, context.error, context.error.__traceback__, limit=None)
    tb_string = "".join(tb_list[-2:])
    print_tb_string = "\n".join(tb_list[-2:])
    message = (
        "An exception was raised while handling an update\n"
        f"<pre>{html.escape(tb_string)}</pre>"
    )

    if isinstance(context.error, error.NetworkError):
            network_error = "Telegram network error."
            logger.critical(network_error)
            # logger.critical(print_tb_string)
    else:
        logger.error(print_tb_string)
        await context.bot.send_message(
            chat_id=DEVELOPER_CHAT_ID, text=message, parse_mode='HTML'
        )
```

I will leave this running overnight and if it handles uber early morning network errors correctly I will close this issue.
Thanks again Poolitzer!
