### ISSUE TITLE
[BUG] Application stops polling after an error

### ISSUE THREAD

**Issue by itshesam** [python-telegram-bot/python-telegram-bot#4405]
### Steps to Reproduce

Actually I don't know how to reproduce it, but for some reasons i use polling and set proxy to connect to telegram bot like below:
```python3
application = Application.builder().token(bot_token)

if settings.BOT_TELEGRAM_PROXY_URL:
    application = application.proxy(
        settings.BOT_TELEGRAM_PROXY_URL,
    ).get_updates_proxy(
        settings.BOT_TELEGRAM_PROXY_URL,
    )
```
After a random time the below error occurs, and the bot is no longer responsive and no polling log occurs.

```
Error while getting Updates: httpx.RemoteProtocolError: Server disconnected without sending a response.
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http_proxy.py", line 344, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/httpx.py", line 137, in send
    rv = await real_send(self, request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 4364, in get_updates
    await self._post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 622, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 355, in _do_post
    return await super()._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 651, in _do_post
    result = await request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.RemoteProtocolError: Server disconnected without sending a response.
Error while getting Updates: Unknown error in HTTP implementation: SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/httpx.py", line 137, in send
    rv = await real_send(self, request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http_proxy.py", line 317, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 383, in start_tls
    return await self._stream.start_tls(ssl_context, server_hostname, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 80, in start_tls
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 71, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/tls.py", line 132, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    result = func(*args)
  File "/usr/local/lib/python3.9/ssl.py", line 945, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1133)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 4364, in get_updates
    await self._post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 622, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 355, in _do_post
    return await super()._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 651, in _do_post
    result = await request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 344, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {exc!r}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')
```

### Expected behaviour

I expect that after the error occurs, it continues to poll and recover from the error if there was some network issues or problems with the proxy.

### Actual behaviour

The telegram bot halts in that state and no longer polls and never respond.

### Operating System

Docker python3:9 

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.4
Bot API 7.7
Python 3.9.19 (main, Jul 10 2024, 19:03:52)  [GCC 12.2.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. PTB handles exceptions that happen while fetching updates internally. They don't stop PTB from getting additonal updates. Please also have a look at https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exceptions%2C-Warnings-and-Logging

At the top of your console output you can also see

> Error while getting Updates: httpx.RemoteProtocolError: Server disconnected without sending a response.
> No error handlers are registered, logging exception.

note the second line here.
What exactly makes you think that the bot stops polling updates?

**Comment by itshesam** [comment]
> Hi. PTB handles exceptions that happen while fetching updates internally. They don't stop PTB from getting additonal updates. Please also have a look at https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exceptions%2C-Warnings-and-Logging
> 
> At the top of your console output you can also see
> 
> > Error while getting Updates: httpx.RemoteProtocolError: Server disconnected without sending a response.
> > No error handlers are registered, logging exception.
> 
> note the second line here. What exactly makes you think that the bot stops polling updates?

Logs of polling will no longer get logged after this error happens, it seems that the application halts after this error.

**Comment by Bibo-Joshi** [comment]
Does the log output just stop completely? Or do you keep seeing errors on getting updates? Can you provide a more complete log output? Please use the config as shown in the examples:

https://github.com/python-telegram-bot/python-telegram-bot/blob/6578c76068e1b48bf63216fddb8fe88d28499daf/examples/echobot.py#L23-L26

but use `level=logging.DEBUG`.

Can you please also double check if you can reproduce this behavior outside of docker and/or without a proxy?

**Comment by itshesam** [comment]
> Does the log output just stop completely? Or do you keep seeing errors on getting updates? Can you provide a more complete log output? Please use the config as shown in the examples:
> 
> https://github.com/python-telegram-bot/python-telegram-bot/blob/6578c76068e1b48bf63216fddb8fe88d28499daf/examples/echobot.py#L23-L26
> 
> but use `level=logging.DEBUG`.
> 
> Can you please also double check if you can reproduce this behavior outside of docker and/or without a proxy?

No more log errors happen after that error happens.
I tried to reproduce this condition. I first run my telegram bot program, and proxy was set correctly, after that i change the proxy server so it won't be valid anymore, in this condition the logs below come and the last logs repeat forever and the program won't recover when i set the proxy back to the valid state. 

```
2024-08-02 13:21:53 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.RemoteProtocolError: Server disconnected without sending a response.
2024-08-02 13:21:53 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http_proxy.py", line 344, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 4364, in get_updates
    await self._post(
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 622, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 355, in _do_post
    return await super()._do_post(
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 651, in _do_post
    result = await request.post(
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.RemoteProtocolError: Server disconnected without sending a response.
2024-08-02 13:21:54 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 529417788}`
2024-08-02 13:21:54 - httpcore.connection - DEBUG - connect_tcp.started host='v2ray' port=10809 local_address=None timeout=5.0 socket_options=None
2024-08-02 13:21:55 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f5edfb27c10>
2024-08-02 13:21:55 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'CONNECT']>
2024-08-02 13:21:55 - httpcore.http11 - DEBUG - send_request_headers.complete
2024-08-02 13:21:55 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'CONNECT']>
2024-08-02 13:21:55 - httpcore.http11 - DEBUG - send_request_body.complete
2024-08-02 13:21:55 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'CONNECT']>
2024-08-02 13:21:55 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'Connection established', [])
2024-08-02 13:21:55 - httpcore.proxy - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x7f5edfdf7ac0> server_hostname='api.telegram.org' timeout=5.0


2024-08-02 13:22:00 - httpcore.proxy - DEBUG - start_tls.failed exception=ConnectTimeout(TimeoutError())
2024-08-02 13:22:00 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Timed out
2024-08-02 13:22:00 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 529417788}`
2024-08-02 13:22:01 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Pool timeout: All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.
2024-08-02 13:22:01 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 529417788}`
2024-08-02 13:22:02 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Pool timeout: All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.
2024-08-02 13:22:02 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 529417788}`
2024-08-02 13:22:03 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Pool timeout: All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.
2024-08-02 13:22:03 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 529417788}`
2024-08-02 13:22:04 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Pool timeout: All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.
```

**Comment by Bibo-Joshi** [comment]
> ```
> 2024-08-02 13:22:03 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 529417788}`
> 2024-08-02 13:22:04 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Pool timeout: All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.
> ```

This looks like the exceptions causes the single connection that's being kept alive in the connection pool to be stuck. So subsequent calls to `get_updates` won't be processed. On firts glance, this looks like an issue with `httpx` to me.
It would be good if you could try to reproduce the issue by directly using the `httpx` package. I can also try to do that but I'm not sure if I'll get around to that in the next ~2 weeks …

**Comment by Bibo-Joshi** [comment]
Closing due to inactivity.
