### ISSUE TITLE
[BUG]'CertificateIssuerPublicKeyTypes' 

### ISSUE THREAD

**Issue by winter-warm-sun** [python-telegram-bot/python-telegram-bot#4430]
### Steps to Reproduce

1. The script agent executes in the background，Deploy on the server
2.Open the proxy on the client by IP+port number
3.Frequent errors will occur the next day

### Expected behaviour

Able to operate normally

### Actual behaviour

Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 5, in <module>
    from mitmproxy.tools.main import mitmdump
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 15, in <module>
    from mitmproxy import master
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/master.py", line 5, in <module>
    from .addons import termlog
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/addons/__init__.py", line 6, in <module>
    from mitmproxy.addons import clientplayback
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/addons/clientplayback.py", line 25, in <module>
    from mitmproxy.proxy import layers
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/__init__.py", line 3, in <module>
    from .http import HttpLayer
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 14, in <module>
    from ..quic import QuicStreamEvent
  File "/usr/local/lib/python3.10/site-packages/mitmproxy/proxy/layers/quic.py", line 13, in <module>
    from aioquic.h3.connection import ErrorCode as H3ErrorCode
  File "/usr/local/lib/python3.10/site-packages/aioquic/h3/connection.py", line 19, in <module>
    from aioquic.quic.connection import QuicConnection, stream_is_unidirectional
  File "/usr/local/lib/python3.10/site-packages/aioquic/quic/connection.py", line 21, in <module>
    from .. import tls
  File "/usr/local/lib/python3.10/site-packages/aioquic/tls.py", line 41, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import (
ImportError: cannot import name 'CertificateIssuerPublicKeyTypes' from 'cryptography.hazmat.primitives.asymmetric.types' (/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/types.py)

### Operating System

centos linux

### Version of Python, python-telegram-bot & dependencies

```shell
Mitmproxy: 10.4.2
Python:    3.10.9
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Linux-3.10.107-1-tlinux2_kvm_guest-0054-x86_64-with-glibc2.17
```

### Additional Context

Tried through the command pip install cryptography -U update the corresponding dependencies，
the problem could be solved and executed normally at that time, but the same error would occur again the next day.

**Comment by Bibo-Joshi** [comment]
I see no relation to PTB. Closing
