### ISSUE TITLE
[FEATURE] Working with more recent versions of urllib3? (Removed urllib3.contrib.appengine.AppEngineManage in version 2.0)

### ISSUE THREAD

**Issue by fernand0** [python-telegram-bot/python-telegram-bot#4444]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

urllib3 "Removed urllib3.contrib.appengine.AppEngineManage  and support for Google App Engine Standard Environment " in version 2.0. That means that when you import telegram you get an error like:

`
>>> import telegram
/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/utils/request.py:54: UserWarning: python-telegram-bot wasn't properly installed. Please refer to README.rst on how to properly install.
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/utils/request.py", line 36, in <module>
    import telegram.vendor.ptb_urllib3.urllib3 as urllib3
  File "/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/vendor/ptb_urllib3/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/vendor/ptb_urllib3/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'telegram.vendor.ptb_urllib3.urllib3.packages.six.moves'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/__init__.py", line 187, in <module>
        from .bot import Bot
      File "/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/bot.py", line 107, in <module>
        from telegram.utils.request import Request
      File "/home/user/.errbot-ve_12/lib/python3.12/site-packages/telegram/utils/request.py", line 44, in <module>
        import urllib3.contrib.appengine as appengine  # type: ignore[no-redef]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ModuleNotFoundError: No module named 'urllib3.contrib.appengine'

### Describe the solution you'd like

It would be nice to solve this problem. Any hint or workaround would also be welcomed.

### Additional context

I'm using python 3.12.1, but I think the problem is because the changes in urllib3 from version 2.0.

**Comment by Poolitzer** [comment]
Hi, you are apparently using a pre V20 version of this library, which we do not support anymore.
