### ISSUE TITLE
[QUESTION] Bot now working inside docker

### ISSUE THREAD

**Issue by galloramiro** [python-telegram-bot/python-telegram-bot#4447]
### Issue I am facing

Im trying to run the bot inside a docker container but it's not working. 
Im geting time out error

### Traceback to the issue

```python
❯ make run
docker run \
        -v `pwd`:/app \
        --env-file .env \
        -it "armoni-bot" python3 /app/src/main.py \

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/src/main.py", line 16, in <module>
    application.run_polling()
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1079, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 503, in initialize
    await self.bot.initialize()
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 301, in initialize
    await super().initialize()
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 776, in initialize
    await self.get_me()
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1920, in get_me
    return await super().get_me(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 908, in get_me
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 622, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 651, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
make: *** [Makefile:20: run] Error 1
```

### Related part of your code

```Dockerfile
FROM python:3.11.4-bullseye

WORKDIR /app

# Installing dependencies
RUN pip install --user poetry
ENV PATH="/root/.local/bin:${PATH}"
ENV PYTHONWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY poetry.lock /app/
COPY pyproject.toml /app/
COPY logging.conf /app/

ENV POETRY_VIRTUALENVS_CREATE=false
RUN poetry lock
RUN poetry install

# Copy core project
COPY src /app/src

EXPOSE 8000
```

```python
import logging
from telegram.ext import ApplicationBuilder
from config import TOKEN
from bot import start_handler

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

if __name__ == '__main__':
    application = ApplicationBuilder().token(TOKEN).build()

    application.add_handler(start_handler)

    application.run_polling()
```

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
[tool.poetry.dependencies]
python = "^3.11.4"

[tool.poetry.dev-dependencies]
isort = "^5.13.2"
black = "^24.8.0"
coverage = "^7.6.1"
ipdb = "^0.13.13"
pylint = "^3.2.6"
pytest = "^8.3.2"
pytest-asyncio = "^0.23.8"
requests = "^2.32.3"
python-telegram-bot= "^21.4"
```

**Comment by Bibo-Joshi** [comment]
Hi. What we're seeing here is a timeout error. This means that either there is a connectivity problem on your machine/docker or at least it's not stable enough. Please have a look at [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors).

**Comment by tuxone** [comment]
Hello! I am getting the same error with the Home Assistant Telegram integration. Indeed, there seems to be a connectivity issue with the Telegram API endpoint:
```
time curl -X GET https://api.telegram.org/bot[my_token]/getUpdates
{"ok":true,"result":[]}
real	0m5.125s
user 0m0.058s
sys	0m0.004s
```
This delay causes the timeout which is hardcoded in `request/_httpxrequest.py`. Specifically it appears to be a namelookup issue. I didn't dig too much into it: my ISP provided DNS servers have the issue, Cloudflare DNS servers don't. I just increased connect_timeout to 10 seconds and now all is good. Alternatively one could switch to Cloudflare DNS servers (1.1.1.1, 1.0.0.1).
