### ISSUE TITLE
[BUG] AttributeError: 'AsyncIOExecutor' object has no attribute '_pending_futures'

### ISSUE THREAD

**Issue by psykokwak-com** [python-telegram-bot/python-telegram-bot#4479]
### Steps to Reproduce

1. Create a simple bot with the following (async polling mode) :
```
async def start():
    application = ApplicationBuilder().token("TOKEN").build()

    job_defaults = {'misfire_grace_time': 60, 'max_instances':10, 'coalesce':False}
    application.job_queue.scheduler.configure(job_defaults=job_defaults)

    await application.initialize()
    await application.start()
    await application.updater.start_polling()

    await asyncio.sleep(5)
    
    await application.updater.stop()
    await application.stop()
    await application.shutdown()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(start())
```

### Expected behaviour

Start during 5 seconds then gracefully stops.

### Actual behaviour

At the stop, I have the following error : 

> Traceback (most recent call last):
>   File "C:\Users\Jyce\Desktop\bot\telegram_bot.py", line 3174, in <module>
>     loop.run_until_complete(start())
>   File "C:\Users\Jyce\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "C:\Users\Jyce\Desktop\bot\telegram_bot.py", line 3169, in start
>     await application.stop()
>   File "C:\Users\Jyce\Desktop\bot\venv\lib\site-packages\telegram\ext\_application.py", line 683, in stop
>     await self._job_queue.stop(wait=True)  # type: ignore[union-attr]
>   File "C:\Users\Jyce\Desktop\bot\venv\lib\site-packages\telegram\ext\_jobqueue.py", line 691, in stop
>     *self._executor._pending_futures,  # pylint: disable=protected-access
> AttributeError: 'AsyncIOExecutor' object has no attribute '_pending_futures'

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
(venv) PS C:\Users\Jyce\Desktop\bot> python -m telegram
python-telegram-bot 21.0.1
Bot API 7.1
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```

### Additional Context

I don't have any error if I remove the line:
application.job_queue.scheduler.configure(job_defaults=job_defaults)

Also, I don't have any error if I use I do an application.run_polling() instead of initialize()/start()/start_polling()

**Comment by psykokwak-com** [comment]
I also have the issue with :
> python-telegram-bot 21.5
> Bot API 7.9

**Comment by psykokwak-com** [comment]
Ok, Fixed by replacing by  :
`application.job_queue.scheduler.configure(job_defaults=job_defaults, **application.job_queue.scheduler_configuration)`
