### ISSUE TITLE
telegram.error.Unauthorized: Unauthorized only on ec2

### ISSUE THREAD

**Issue by Waffleboy** [python-telegram-bot/python-telegram-bot#448]
### Steps to reproduce
1. python bot.py (on an ec2 instance)

2. Upon loading the updater and trying ti add a command handler it crashes.

3.

### Expected behaviour
Tell us what should happen

Bot should run normally. It works fine on my local computer, and on Heroku. This is seriously strange, ufw is also set to allow, so I dont see whats wrong

### Actual behaviour
Tell us what happens instead

Crashed with unhandled exception, unauthorized.

```
ubuntu@ip-172-31-31-237:~/git/diary-bot$ python diarybot.py 
2016-11-01 05:20:09,967 - __main__ - INFO - Starting Bot!
2016-11-01 05:20:09,968 - __main__ - INFO - Using Production key
2016-11-01 05:20:11,715 - telegram.ext.updater - ERROR - unhandled exception
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/ext/updater.py", line 115, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/ext/updater.py", line 228, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/ext/updater.py", line 335, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/bot.py", line 124, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/bot.py", line 1272, in setWebhook
    result = self._request.post(url, data, timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/utils/request.py", line 205, in post
    **urlopen_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/utils/request.py", line 150, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized
Exception in thread updater:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/ext/updater.py", line 115, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/ext/updater.py", line 228, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/ext/updater.py", line 335, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/bot.py", line 124, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/bot.py", line 1272, in setWebhook
    result = self._request.post(url, data, timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/utils/request.py", line 205, in post
    **urlopen_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/telegram/utils/request.py", line 150, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized

```

### Configuration
**Operating System:**

Ubuntu 16.04 on EC2

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 5.2.0
urllib3 1.18.1
certifi 2016.09.26
future 0.16.0
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

### Logs
Insert logs here (if necessary)

**Comment by Waffleboy** [comment]
Bump. Would appreciate help!

**Comment by jh0ker** [comment]
@Waffleboy Did you try asking in our Telegram group? There your question will reach more people, one of them might have encountered the same problem as you.

**Comment by Waffleboy** [comment]
@jh0ker I did join it, but I can't speak in it. This one right? https://web.telegram.org/#/im?p=@pythontelegrambotchannel

**Comment by jh0ker** [comment]
@Waffleboy That is our channel, our group is https://telegram.me/pythontelegrambotgroup

**Comment by tsnoam** [comment]
@Waffleboy 
Have you managed getting assistance in the telegram group?
Otherwise, have you tried contacting botsupport?

In any case, this doesn't seem like a bug with python-telegram-bot library, but rather a misconfiguration on your side or a bug with telegram servers.

If you find info that something is not properly handled in the library, feel free to reopen this issue.
