### ISSUE TITLE
[QUESTION] Silence Error while getting Updates: Conflict: terminated by other getUpdates request

### ISSUE THREAD

**Issue by slyapustin** [python-telegram-bot/python-telegram-bot#4499]
### Issue I am facing

I use [Zero Downtime Deploy](https://dokku.com/docs/deployment/zero-downtime-deploys/) for my application. 
Which basically runs two versions of the application while it's deployed. 

Due to that - there is a two function trying to pull data for the same Telegram Token. 
That is fine for me and I don't want to see that error in the logs or even being sent to error tracking app (like Sentry).

I was trying to fix it with multiple ways without any luck. For example:

```python
        try:
            async with self.application:
                # Start the bot asynchronously
                await self.application.start()
                logger.info("Bot started")

                # Run polling asynchronously

                await self.application.updater.start_polling()

                logger.info("Bot is polling for messages")
                # Keep the bot running
                while not shutdown_flag:
                    await asyncio.sleep(1)

                await self.application.updater.stop()
                await self.application.stop()
        except Conflict:
            logger.info("Conflict detected, stopping bot...")
```
Is there an easy way to do that? Am I missing something?

### Traceback to the issue

```python
2024-09-25T12:19:45.404307175Z app[assistant_bots.1]: Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-09-25T12:19:45.423706240Z app[assistant_bots.1]: Exception happened while polling for updates.
2024-09-25T12:19:45.423739976Z app[assistant_bots.1]: Traceback (most recent call last):
2024-09-25T12:19:45.423744059Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
2024-09-25T12:19:45.423747410Z app[assistant_bots.1]:     if not await do_action():
2024-09-25T12:19:45.423751058Z app[assistant_bots.1]:            ^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.423754081Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
2024-09-25T12:19:45.424156649Z app[assistant_bots.1]:     return action_cb_task.result()
2024-09-25T12:19:45.424164834Z app[assistant_bots.1]:            ^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.424169531Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
2024-09-25T12:19:45.424173909Z app[assistant_bots.1]:     raise exc
2024-09-25T12:19:45.424194758Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
2024-09-25T12:19:45.424199415Z app[assistant_bots.1]:     updates = await self.bot.get_updates(
2024-09-25T12:19:45.424203625Z app[assistant_bots.1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.424207817Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 649, in get_updates
2024-09-25T12:19:45.424212195Z app[assistant_bots.1]:     updates = await super().get_updates(
2024-09-25T12:19:45.424227896Z app[assistant_bots.1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.424232164Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/_bot.py", line 4364, in get_updates
2024-09-25T12:19:45.424236218Z app[assistant_bots.1]:     await self._post(
2024-09-25T12:19:45.424240196Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/_bot.py", line 622, in _post
2024-09-25T12:19:45.424244067Z app[assistant_bots.1]:     return await self._do_post(
2024-09-25T12:19:45.424248502Z app[assistant_bots.1]:            ^^^^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.424252395Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 355, in _do_post
2024-09-25T12:19:45.424256888Z app[assistant_bots.1]:     return await super()._do_post(
2024-09-25T12:19:45.424260829Z app[assistant_bots.1]:            ^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.424264565Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/_bot.py", line 651, in _do_post
2024-09-25T12:19:45.424268913Z app[assistant_bots.1]:     result = await request.post(
2024-09-25T12:19:45.424272887Z app[assistant_bots.1]:              ^^^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.424276821Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
2024-09-25T12:19:45.424281009Z app[assistant_bots.1]:     result = await self._request_wrapper(
2024-09-25T12:19:45.424284968Z app[assistant_bots.1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25T12:19:45.424288952Z app[assistant_bots.1]:   File "/usr/local/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 383, in _request_wrapper
2024-09-25T12:19:45.424304908Z app[assistant_bots.1]:     raise Conflict(message)
2024-09-25T12:19:45.424309202Z app[assistant_bots.1]: telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```

### Related part of your code

```python
try:
    async with self.application:
        # Start the bot asynchronously
        await self.application.start()
        logger.info("Bot started")

        # Run polling asynchronously

        await self.application.updater.start_polling()

        logger.info("Bot is polling for messages")
        # Keep the bot running
        while not shutdown_flag:
            await asyncio.sleep(1)

        await self.application.updater.stop()
        await self.application.stop()
except Conflict:
    logger.info("Conflict detected, stopping bot...")
```

### Operating System

ubuntu 

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot==21.4
```

**Comment by Poolitzer** [comment]
@slyapustin Telegram does not allow two simultaneous get updates requests.

Switch to a webhook implementation where you have a reverse proxy (or I guess two in your scenario) which delegate the updates appropriately.

**Comment by slyapustin** [comment]
@Poolitzer I know that, thanks. 
But in my case I don't care about that much. 
I just want to silence that error in my application.

**Comment by Poolitzer** [comment]
But wont that error break your setup?

Anyway, you need to register a filter for that and just drop the record. https://docs.python.org/3/library/logging.html#filter-objects

**Comment by slyapustin** [comment]
I see, thanks for the hint. But I wonder why that exception was not bubbled to where I run my polling?

**Comment by Poolitzer** [comment]
@slyapustin Good question, I assume because it is supposed to keep running and not abort when a network error occurs? But I am not that deep in logging/exception behaviour

**Comment by slyapustin** [comment]
@Poolitzer I was able to silence that error by using custom error_callback:

```python
    def error_callback(exc: TelegramError):
        if isinstance(exc, Conflict):
            logger.info(f"Conflict detected...")
        else:
            logger.warning(
                f"Exception happened while polling for updates: {exc}",
                exc_info=exc,
            )
            
    await application.updater.start_polling(error_callback=error_callback)
```

**Comment by Poolitzer** [comment]
Sure, that works as well, good solution! Didn't think of it
