### ISSUE TITLE
[BUG] Proxy conflicts with CommandHandler.

### ISSUE THREAD

**Issue by downdawn** [python-telegram-bot/python-telegram-bot#4526]
### Steps to Reproduce

```
from loguru import logger
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes

bot_token = "xxxx"
proxy = "http://127.0.0.1:1080"


async def get_config(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        chat_id = update.effective_chat.id
        print(chat_id)
    except Exception as e:
        logger.exception(e)


if __name__ == '__main__':
    application = ApplicationBuilder().token(bot_token).proxy(proxy=proxy).build()

    application.add_handler(CommandHandler('get_config', get_config))

    application.run_polling(allowed_updates=Update.ALL_TYPES)
```

### Expected behaviour

Input /get_config on the Telegram bot, and the console will output the chat_id.

### Actual behaviour

With this proxy setup, the command handler is not working; the get_config method is not being entered, and there is no output for chat_id.

### Operating System

windows10

### Version of Python, python-telegram-bot & dependencies

python3.10
python-telegram-bot>=21.6

**Comment by AryanVBW** [comment]
```python
from loguru import logger
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes

bot_token = "xxxx"
proxy = "http://127.0.0.1:1080"


async def get_config(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        chat_id = update.effective_chat.id
        print(chat_id)
    except Exception as e:
        logger.exception(e)


if __name__ == '__main__':
    application = ApplicationBuilder().token(bot_token).proxy(proxy=proxy).build()

    application.add_handler(CommandHandler('get_config', get_config))

    application.run_polling(allowed_updates=Update.ALL_TYPES)
```

**Expected behavior:**

Input `/get_config` on the Telegram bot, and the console will output the chat_id.

**Actual behavior:**

With this proxy setup, the command handler is not working; the `get_config` method is not being entered, and there is no output for chat_id.

**Operating System:**

Windows 10

**Version of Python, python-telegram-bot & dependencies:**

Python 3.10
python-telegram-bot>=21.6

**Solution:**

The problem lies in the way you're setting up the proxy for your Telegram bot. Here's the breakdown and how to fix it:

**Issue:**

- The `proxy` variable is set to `"http://127.0.0.1:1080"` which specifies an HTTP proxy. However, the `telegram` library likely uses a different protocol (SOCKS5) by default for proxies.

**Fix:**

There are two ways to address this:

1. **Use SOCKS5 proxy:** If your proxy server supports SOCKS5, modify the `proxy` variable to use the correct format:

```python
proxy = "socks5://127.0.0.1:1080"
```

2. **Explicitly configure HTTP proxy with authentication (if needed):**

- If your HTTP proxy requires authentication, use a dictionary to specify the proxy details:

```python
proxy = {
    "http": "http://username:password@127.0.0.1:1080",
    "https": "https://username:password@127.0.0.1:1080"
}
```

**Additional Checks:**

- **Proxy Functionality:** Verify that your proxy server is running and accessible. You can test it using tools like `curl` with the proxy set.
- **Firewall:** Make sure your firewall is not blocking communication between your bot and Telegram servers.
- **Error Logs:** Check your bot's logs (using `logger.exception(e)`) for any errors related to proxy connection issues.

**Updated Code:**

```python
from loguru import logger
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes

bot_token = "xxxx"

# Option 1: SOCKS5 proxy
proxy = "socks5://127.0.0.1:1080"

# Option 2: HTTP proxy with authentication (replace username and password)
# proxy = {
#     "http": "http://username:password@127.0.0.1:1080",
#     "https": "https://username:password@127.0.0.1:1080"
# }


async def get_config(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        chat_id = update.effective_chat.id
        print(chat_id)
    except Exception as e:
        logger.exception(e)


if __name__ == '__main__':
    application = ApplicationBuilder().token(bot_token).proxy(proxy=proxy).build()

    application.add_handler(CommandHandler('get_config', get_config))

    application.run_polling(allowed_updates=Update.ALL_TYPES)
```

**Comment by Bibo-Joshi** [comment]
> However, the telegram library likely uses a different protocol (SOCKS5) by default for proxies.

This is false. Please don't blindly copy-paste AI answers as replies to issues

**Comment by downdawn** [comment]
So is there a correct solution to this problem at the moment? Or should we wait for a fix? 
Thank you

**Comment by Poolitzer** [comment]
Please provide some debug logging output

**Comment by downdawn** [comment]
> Please provide some debug logging output

The expected output is chat_id, but in reality, nothing was output, and no exceptions were caught.

**Comment by Poolitzer** [comment]
Set the logging level to debug, send the command in telegram and share the resulting log please

**Comment by downdawn** [comment]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxxxxx\lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
  File "xxxxxx\lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
  File "xxxxxx\lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
  File "xxxxxx\lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
  File "xxxxxx\lib\site-packages\telegram\_bot.py", line 4367, in get_updates
    await self._post(
  File "xxxxxx\lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
  File "xxxxxx\lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
  File "xxxxxx\lib\site-packages\telegram\_bot.py", line 653, in _do_post
    result = await request.post(
  File "xxxxxx\lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
  File "xxxxxx\lib\site-packages\telegram\request\_baserequest.py", line 333, in _request_wrapper
    code, payload = await self.do_request(
  File "xxxxxx\lib\site-packages\telegram\request\_httpxrequest.py", line 317, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.telegram.org'. (_ssl.c:1007)
```

**Comment by downdawn** [comment]
```
import logging

from loguru import logger
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes
from telegram.request import HTTPXRequest

bot_token = "123:xxx"
proxy = "http://127.0.0.1:7890"

# 设置日志级别为 DEBUG
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.DEBUG
)


async def get_config(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        chat_id = update.effective_chat.id
        print(chat_id)
    except Exception as e:
        logging.exception(e)


if __name__ == '__main__':
    request = HTTPXRequest(proxy=proxy, httpx_kwargs={"verify": False})
    application = ApplicationBuilder().token(bot_token).proxy(proxy=proxy).build()

    application.add_handler(CommandHandler('get_config', get_config))

    application.run_polling(allowed_updates=Update.ALL_TYPES)
```

2024-10-18 17:28:49,696 - httpx - DEBUG - load_ssl_context verify=False cert=None trust_env=True http2=False
2024-10-18 17:28:49,697 - httpx - DEBUG - load_ssl_context verify=False cert=None trust_env=True http2=False
2024-10-18 17:28:49,697 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-18 17:28:49,697 - httpx - DEBUG - load_verify_locations cafile='E:\\Program Files\\miniconda3\\envs\\tg_trade_bot\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-18 17:28:49,853 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-18 17:28:49,854 - httpx - DEBUG - load_verify_locations cafile='E:\\Program Files\\miniconda3\\envs\\tg_trade_bot\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-18 17:28:50,000 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-18 17:28:50,001 - httpx - DEBUG - load_verify_locations cafile='E:\\Program Files\\miniconda3\\envs\\tg_trade_bot\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-18 17:28:50,146 - asyncio - DEBUG - Using proactor: IocpProactor
2024-10-18 17:28:50,160 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2024-10-18 17:28:50,162 - httpcore.connection - DEBUG - connect_tcp.started host='127.0.0.1' port=7890 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:28:50,163 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000268A5EA3880>
2024-10-18 17:28:50,163 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'CONNECT']>
2024-10-18 17:28:50,163 - httpcore.http11 - DEBUG - send_request_headers.complete
2024-10-18 17:28:50,164 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'CONNECT']>
2024-10-18 17:28:50,164 - httpcore.http11 - DEBUG - send_request_body.complete
2024-10-18 17:28:50,164 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'CONNECT']>
2024-10-18 17:28:50,164 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'Connection established', [])
2024-10-18 17:28:50,164 - httpcore.proxy - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x00000268A5DCF6C0> server_hostname='api.telegram.org' timeout=5.0
2024-10-18 17:28:51,000 - httpcore.proxy - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000268A5EEE9B0>
2024-10-18 17:28:51,000 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2024-10-18 17:28:51,000 - httpcore.http11 - DEBUG - send_request_headers.complete
2024-10-18 17:28:51,000 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2024-10-18 17:28:51,000 - httpcore.http11 - DEBUG - send_request_body.complete
2024-10-18 17:28:51,000 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2024-10-18 17:28:51,336 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Fri, 18 Oct 2024 09:28:53 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'273'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2024-10-18 17:28:51,336 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot123:xxx/getMe "HTTP/1.1 200 OK"
2024-10-18 17:28:51,336 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2024-10-18 17:28:51,336 - httpcore.http11 - DEBUG - receive_response_body.complete
2024-10-18 17:28:51,336 - httpcore.http11 - DEBUG - response_closed.started
2024-10-18 17:28:51,336 - httpcore.http11 - DEBUG - response_closed.complete
2024-10-18 17:28:51,337 - telegram.ext.ExtBot - DEBUG - Call to Bot API endpoint `getMe` finished with return value `{'id': 8186664904, 'is_bot': True, 'first_name': '交易机器人', 'username': 'xkg_trade_bot', 'can_join_groups': True, 'can_read_all_group_messages': False, 'supports_inline_queries': False, 'can_connect_to_business': False, 'has_main_web_app': False}`
2024-10-18 17:28:51,337 - telegram.ext.ExtBot - DEBUG - This Bot is already initialized.
2024-10-18 17:28:51,337 - telegram.ext.Updater - DEBUG - Updater started (polling)
2024-10-18 17:28:51,337 - telegram.ext.Updater - DEBUG - Start network loop retry bootstrap del webhook
2024-10-18 17:28:51,337 - telegram.ext.Updater - DEBUG - Deleting webhook
2024-10-18 17:28:51,337 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `deleteWebhook` with parameters `{}`
2024-10-18 17:28:51,337 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2024-10-18 17:28:51,337 - httpcore.http11 - DEBUG - send_request_headers.complete
2024-10-18 17:28:51,337 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2024-10-18 17:28:51,337 - httpcore.http11 - DEBUG - send_request_body.complete
2024-10-18 17:28:51,337 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2024-10-18 17:28:51,670 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Fri, 18 Oct 2024 09:28:53 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'68'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2024-10-18 17:28:51,670 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot123:xxx/deleteWebhook "HTTP/1.1 200 OK"
2024-10-18 17:28:51,670 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2024-10-18 17:28:51,670 - httpcore.http11 - DEBUG - receive_response_body.complete
2024-10-18 17:28:51,670 - httpcore.http11 - DEBUG - response_closed.started
2024-10-18 17:28:51,671 - httpcore.http11 - DEBUG - response_closed.complete
2024-10-18 17:28:51,671 - telegram.ext.ExtBot - DEBUG - Call to Bot API endpoint `deleteWebhook` finished with return value `True`
2024-10-18 17:28:51,671 - telegram.ext.Updater - DEBUG - Bootstrap done
2024-10-18 17:28:51,671 - telegram.ext.Updater - DEBUG - Waiting for polling to start
2024-10-18 17:28:51,671 - telegram.ext.Updater - DEBUG - Polling updates from Telegram started
2024-10-18 17:28:51,671 - telegram.ext.Updater - DEBUG - Start network loop retry getting Updates
2024-10-18 17:28:51,671 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:28:51,672 - apscheduler.scheduler - INFO - Scheduler started
2024-10-18 17:28:51,672 - telegram.ext.Application - DEBUG - JobQueue started
2024-10-18 17:28:51,672 - telegram.ext.Application - INFO - Application started
2024-10-18 17:28:51,672 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:28:51,674 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2024-10-18 17:28:51,674 - apscheduler.scheduler - DEBUG - No jobs; waiting until a job is added
2024-10-18 17:28:56,686 - httpcore.connection - DEBUG - connect_tcp.failed exception=ConnectTimeout(TimeoutError())
2024-10-18 17:28:56,686 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Timed out
2024-10-18 17:28:56,686 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:28:56,687 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:29:01,688 - httpcore.connection - DEBUG - connect_tcp.failed exception=ConnectTimeout(TimeoutError())
2024-10-18 17:29:01,688 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Timed out
2024-10-18 17:29:01,689 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:29:01,689 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:29:01,982 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000268A5EEEA40>
2024-10-18 17:29:01,982 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x00000268A5DCFDC0> server_hostname='api.telegram.org' timeout=5.0




2024-10-18 17:29:07,000 - httpcore.connection - DEBUG - start_tls.failed exception=ConnectTimeout(TimeoutError())
2024-10-18 17:29:07,001 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Timed out
2024-10-18 17:29:07,001 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:29:07,001 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:29:07,265 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000268A5EEEDA0>
2024-10-18 17:29:07,265 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x00000268A5DCFDC0> server_hostname='api.telegram.org' timeout=5.0
2024-10-18 17:29:12,280 - httpcore.connection - DEBUG - start_tls.failed exception=ConnectTimeout(TimeoutError())
2024-10-18 17:29:12,281 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Timed out
2024-10-18 17:29:12,282 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:29:12,284 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:29:12,545 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000268A5EEEEC0>
2024-10-18 17:29:12,545 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x00000268A5DCFDC0> server_hostname='api.telegram.org' timeout=5.0
2024-10-18 17:29:17,559 - httpcore.connection - DEBUG - start_tls.failed exception=ConnectTimeout(TimeoutError())
2024-10-18 17:29:17,560 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Timed out
2024-10-18 17:29:17,560 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:29:17,562 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:29:17,821 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000268A5F578E0>
2024-10-18 17:29:17,821 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x00000268A5DCFDC0> server_hostname='api.telegram.org' timeout=5.0
2024-10-18 17:29:22,824 - httpcore.connection - DEBUG - start_tls.failed exception=ConnectTimeout(TimeoutError())
2024-10-18 17:29:22,825 - telegram.ext.Updater - DEBUG - Timed out getting Updates: Timed out
2024-10-18 17:29:22,825 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:29:22,825 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2024-10-18 17:29:23,089 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000268A5F570A0>
2024-10-18 17:29:23,089 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x00000268A5DCFDC0> server_hostname='api.telegram.org' timeout=5.0
2024-10-18 17:29:26,122 - telegram.ext.Application - DEBUG - Application received stop signal. Shutting down.
2024-10-18 17:29:26,122 - telegram.ext.Updater - DEBUG - Stopping Updater
2024-10-18 17:29:26,122 - telegram.ext.Updater - DEBUG - Waiting background polling task to finish up.
2024-10-18 17:29:26,122 - telegram.ext.Updater - DEBUG - Network loop retry getting Updates was cancelled
2024-10-18 17:29:26,122 - httpcore.connection - DEBUG - start_tls.failed exception=CancelledError()
2024-10-18 17:29:26,123 - telegram.ext.Updater - DEBUG - Calling `get_updates` one more time to mark all fetched updates as read.
2024-10-18 17:29:26,123 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 0, 'offset': 0, 'allowed_updates': [<UpdateType.MESSAGE>, <UpdateType.EDITED_MESSAGE>, <UpdateType.CHANNEL_POST>, <UpdateType.EDITED_CHANNEL_POST>, <UpdateType.INLINE_QUERY>, <UpdateType.CHOSEN_INLINE_RESULT>, <UpdateType.CALLBACK_QUERY>, <UpdateType.SHIPPING_QUERY>, <UpdateType.PRE_CHECKOUT_QUERY>, <UpdateType.POLL>, <UpdateType.POLL_ANSWER>, <UpdateType.MY_CHAT_MEMBER>, <UpdateType.CHAT_MEMBER>, <UpdateType.CHAT_JOIN_REQUEST>, <UpdateType.CHAT_BOOST>, <UpdateType.REMOVED_CHAT_BOOST>, <UpdateType.MESSAGE_REACTION>, <UpdateType.MESSAGE_REACTION_COUNT>, <UpdateType.BUSINESS_CONNECTION>, <UpdateType.BUSINESS_MESSAGE>, <UpdateType.EDITED_BUSINESS_MESSAGE>, <UpdateType.DELETED_BUSINESS_MESSAGES>, <UpdateType.PURCHASED_PAID_MEDIA>]}`
2024-10-18 17:29:26,123 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None

**Comment by Poolitzer** [comment]
@downdawn Oh I am blind should have seen/realized this earlier. We have two HTTPXRequest instances, one for getting updates, one for everything else. So you set the proxy correctly for the everything else instance, but the get updates one also needs it. start_tls.failed

**Comment by downdawn** [comment]
Okay, thank you. Why not integrate it into one setting? The bot proxy is also set separately:

```python
request = HTTPXRequest(
    proxy=proxy,
)
bot = Bot(token=config.bot_token, request=request)
```
