### ISSUE TITLE
[BUG] telegram.error.NetworkError: httpx.ConnectError

### ISSUE THREAD

**Issue by rtadewald** [python-telegram-bot/python-telegram-bot#4541]
### Steps to Reproduce

Hello, guys. I'm unable to run a basic bot.

I'm using this simple basic code (with my TOKEN inside a .env file)
```python
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes
from dotenv import load_dotenv
import os

load_dotenv()

BOT_USERNAME = "isaac21_bot"

async def start_command(update: Update, 
                        context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Hello World")


async def handle_message(update: Update, 
                         context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text.lower()

    if "hello" in text:
        return "Hello World"
    
    if "how are you" in text:
        return "I am fine"
    
    return f"You said: {text}"


async def error(update: Update, 
                context: ContextTypes.DEFAULT_TYPE):
    print(f"Update {update} caused error {context.error}")


if __name__ == "__main__":
    print("Starting bot")
    app = ApplicationBuilder().token(os.environ["TELEGRAM_BOT"]).build()

    app.add_handler(CommandHandler("start", start_command))
    app.add_handler(MessageHandler(filters.TEXT, handle_message))
    app.add_error_handler(error)


    print("Pooling...")
    app.run_polling()
```

### Expected behaviour

A working bot

### Actual behaviour

When I run i got the following error:

<details>

```python
python main.py                                                                                                         1 х │ base Py │ 18:26:30 
Starting bot
Pooling...
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/opt/homebrew/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpcore/_async/connection.py", line 154, in _connect
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 69, in start_tls
    with map_exceptions(exc_map):
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rtadewald/Projetos-Locais/AI/Telegram AI Assistant/main.py", line 53, in <module>
    app.run_polling()
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_application.py", line 727, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_application.py", line 921, in __run
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_application.py", line 910, in __run
    loop.run_until_complete(self.initialize())
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_application.py", line 399, in initialize
    await self.bot.initialize()
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 271, in initialize
    await super().initialize()
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 591, in initialize
    await self.get_me()
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1706, in get_me
    return await super().get_me(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 381, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 736, in get_me
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 469, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 325, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 497, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 291, in _request_wrapper
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 277, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 240, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: 
```

</details>

### Operating System

MacOS

### Version of Python, python-telegram-bot & dependencies

python-telegram-bot 20.3
Bot API 6.7
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

**Comment by Bibo-Joshi** [comment]
Hi. It looks like there is a network connectivity issue. I fear that there's not overly much that PTB itself can do about that. Plesae also have a look at [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors)

**Comment by Bibo-Joshi** [comment]
Closing b/c PTB can't help with connectivity problems and due to lack of activity
