### ISSUE TITLE
RuntimeWarning: coroutine 'Application.shutdown' was never awaited

### ISSUE THREAD

**Issue by HaoBanLu** [python-telegram-bot/python-telegram-bot#4561]
### Steps to Reproduce

**fastapi  How do asynchronous functions run?**

```python
import logging
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

# 设置日志记录
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)
logger = logging.getLogger(__name__)

# 定义启动命令的处理函数
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply("Hello! I'm your bot!")

# 定义一个错误处理函数
async def error(update: Update, context: ContextTypes.DEFAULT_TYPE):
    logger.warning(f"Update {update} caused error {context.error}")

async def main():
    """启动 Telegram bot"""
    # 使用你的 Bot Token 创建 Application 对象
    application = Application.builder().token("token").build()

    # 添加命令处理器
    application.add_handler(CommandHandler("start", start))

    # 错误处理
    application.add_error_handler(error)

    # 初始化并启动 Telegram bot
    await application.initialize()
    await application.run_polling()

# 如果是直接运行脚本，不使用 asyncio.run()
if __name__ == "__main__":
    import asyncio
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())


```

```python
d:\Python-www\foxwork_url_class\app\routers\bot_test.py:36: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
2024-11-09 00:54:30,768 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8194578328:AAE6qP6BOCrrPzOjspF03d1lWy3gQlbsWn8/getMe "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\foxwork-url-class-L0ZmmuzN-py3.12\Lib\site-packages\telegram\ext\_application.py", line 1063, in __run
    loop.run_until_complete(self.initialize())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 663, in run_until_complete
    self._check_running()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 622, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\foxwork-url-class-L0ZmmuzN-py3.12\Lib\site-packages\telegram\ext\_application.py", line 1088, in __run
    loop.run_until_complete(self.shutdown())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 663, in run_until_complete
    self._check_running()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 622, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Python-www\foxwork_url_class\app\routers\bot_test.py", line 37, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\Python-www\foxwork_url_class\app\routers\bot_test.py", line 31, in main
    await application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\foxwork-url-class-L0ZmmuzN-py3.12\Lib\site-packages\telegram\ext\_application.py", line 865, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\foxwork-url-class-L0ZmmuzN-py3.12\Lib\site-packages\telegram\ext\_application.py", line 1093, in __run
    loop.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 687, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
sys:1: RuntimeWarning: coroutine 'Application.shutdown' was never awaited
sys:1: RuntimeWarning: coroutine 'Application.initialize' was never awaited
```

### Expected behaviour

how run?

### Actual behaviour

```python
sys:1: RuntimeWarning: coroutine 'Application.shutdown' was never awaited
sys:1: RuntimeWarning: coroutine 'Application.initialize' was never awaited
```

### Operating System

win11

### Version of Python, python-telegram-bot & dependencies

```shell
python3.13
```

### Relevant log output

```python
文件“C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\foxwork-url-class-L0ZmmuzN-py3.12\Lib\site-packages\telegram\ext_application.py”, 第 1093 行，在 __run
loop.close()
文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py”, 第 687 行，关闭时
引发 RuntimeError(“无法关闭正在运行的事件loop”）
RuntimeError：无法关闭正在运行的事件循环
sys：1：RuntimeWarning：从未等待协程“Application.shutdown”
sys：1：RuntimeWarning：从未等待协程“Application.initialize”
```

**Comment by Bibo-Joshi** [comment]
Hi. [`Application.run_polling`](https://docs.python-telegram-bot.org/en/stable/telegram.ext.application.html#telegram.ext.Application.run_polling) is not a coroutine function and can not be awaited. But you're trying to do that:

```python
    # 初始化并启动 Telegram bot
    await application.initialize()
    await application.run_polling()
```

I'm not sure what you're trying to achieve here. Since you mentioned fastapi, let me point you [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks) and [here](https://docs.python-telegram-bot.org/en/stable/examples.customwebhookbot.html).
However, so far I don't see a Bug in PTB here.
