### ISSUE TITLE
401 Unauthorized Error When Attempting to Send Messages Using Bot API

### ISSUE THREAD

**Issue by RoyBidani** [python-telegram-bot/python-telegram-bot#4610]
### Issue I am facing

I'm encountering a 401 Unauthorized error when attempting to send messages using the python-telegram-bot library, despite revoking and regenerating my bot token via [@BotFather](https://t.me/BotFather).

### Traceback to the issue

```python
telegram.error.InvalidToken: Unauthorized

Traceback (most recent call last):
  File "/home/roy/Desktop/MY Projects/Yad2Search/test_bot.py", line 56, in <module>
    asyncio.run(send_test_message())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/roy/Desktop/MY Projects/Yad2Search/test_bot.py", line 53, in send_test_message
    await bot.close()
  File "/home/roy/Desktop/MY Projects/Yad2Search/venv/lib/python3.10/site-packages/telegram/_bot.py", line 7809, in close
    return await self._post(
  File "/home/roy/Desktop/MY Projects/Yad2Search/venv/lib/python3.10/site-packages/telegram/_bot.py", line 619, in _post
    return await self._do_post(
  File "/home/roy/Desktop/MY Projects/Yad2Search/venv/lib/python3.10/site-packages/telegram/_bot.py", line 648, in _do_post
    result = await request.post(
  File "/home/roy/Desktop/MY Projects/Yad2Search/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
  File "/home/roy/Desktop/MY Projects/Yad2Search/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise InvalidToken(message)
telegram.error.InvalidToken: Unauthorized
```

### Related part of your code

```python
import os
import asyncio
from telegram import Bot
from telegram.request import HTTPXRequest
from dotenv import load_dotenv
import logging

# Load environment variables from .env file
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.DEBUG,  # Set to DEBUG for detailed logs
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.FileHandler("test_bot.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

async def send_test_message():
    bot_token = os.getenv('TELEGRAM_BOT_TOKEN')
    chat_id = os.getenv('CHAT_ID_USER')

    if not bot_token:
        logger.error("TELEGRAM_BOT_TOKEN is not set.")
        return
    if not chat_id:
        logger.error("CHAT_ID_USER is not set.")
        return

    try:
        chat_id = int(chat_id)
    except ValueError:
        logger.error("CHAT_ID_USER must be an integer.")
        return

    # Initialize the Bot with HTTPXRequest with increased connection pool size and proper timeouts
    request = HTTPXRequest(
        connection_pool_size=20,
        connect_timeout=60,  # Connection timeout in seconds
        read_timeout=60      # Read timeout in seconds
    )
    bot = Bot(token=bot_token, request=request)

    try:
        await bot.send_message(chat_id=chat_id, text="Hello from your bot!", parse_mode='Markdown')
        logger.info("Test message sent successfully!")
    except Exception as e:
        logger.error(f"Failed to send test message: {e}")
    finally:
        await bot.close()

if __name__ == "__main__":
    asyncio.run(send_test_message())
```

### Operating System

ubuntu 22.04

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.10.12

(venv) roy@RoysPc:~/Desktop/MY Projects/Yad2Search$ pip list
Package             Version
------------------- ----------
aiohappyeyeballs    2.4.4
aiohttp             3.11.11
aiosignal           1.3.2
anyio               4.7.0
async-timeout       5.0.1
attrs               24.3.0
certifi             2024.12.14
charset-normalizer  3.4.0
exceptiongroup      1.2.2
frozenlist          1.5.0
h11                 0.14.0
httpcore            1.0.7
httpx               0.28.1
idna                3.10
multidict           6.1.0
pip                 24.3.1
propcache           0.2.1
python-dotenv       1.0.1
python-telegram-bot 21.9
setuptools          75.6.0
sniffio             1.3.1
typing_extensions   4.12.2
yarl                1.18.3
(venv) roy@RoysPc:~/Desktop/MY Proj
```

**Comment by Bibo-Joshi** [comment]
Hi. Please triple check that the bot token is passed correctly. I recommend hard coding it directly in the python code for a test. If that works, then it's an issue in your env var setup. You can also double check that the token is correct by entering https://api.telegram.org/botTOKEN/getMe in your browser.

**Comment by RoyBidani** [comment]
You’re absolutely right. It did work. It seems it took token from somewhere else. 
Now it work.!
Thanks !
