### ISSUE TITLE
switch_inline_query_current_chat raises BadRequest error.

### ISSUE THREAD

**Issue by vhdmsm** [python-telegram-bot/python-telegram-bot#475]
Method `switch_inline_query_current_chat` doesn't work in v5.2. I'm using Webhook and after adding a `[InlineKeyboardButton(text='Sticker', **{'switch_inline_query_current_chat':'sticker'})]` to my `InlineKeyboardMarkup` keyboards, it will raise a `BadRequest` error. What's wrong?

**Comment by jh0ker** [comment]
@vhdmsm What does the error message say?

**Comment by vhdmsm** [comment]
Here is the log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/kalkal/dev/kalkal/tgbot/tasks.py", line 251, in end_game
    reply_markup=reply_markup)
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 152, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/site-packages/telegram/utils/request.py", line 201, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/utils/request.py", line 148, in _request_wrapper
    raise BadRequest(repr(message))
telegram.error.BadRequest
```

**Comment by tsnoam** [comment]
@vhdmsm 
Can you please provide a code to recreate the problem?
Please make sure you use the latest release of python-telegram-bot (v5.3.0 at the moment) or the master branch while doing so.

**Comment by vhdmsm** [comment]
I've tested it again right now with the new version of my mac telegram client and figured out that the  problem was from [mac telegram client](https://github.com/overtake/telegram) version and it's not your library. It works fine in my android app but still mac client still have a problem that i should report to them.
Thanks.
