### ISSUE TITLE
ImportError: No module named telegram.error ?

### ISSUE THREAD

**Issue by TelegramBotAPIuz** [python-telegram-bot/python-telegram-bot#490]
Hello i me help
### Steps to reproduce
1.Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/devtools/cdbg/debuglets/python/deferred_modules.py", line 231, in _ImportHook
    module = _real_import(name, globals, locals, fromlist, level)
  File "/base/data/home/apps/b~xitoy2/1.398007812891697490/main.py", line 10, in <module>
    from telegram.error import NetworkError, Unauthorized
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/devtools/cdbg/debuglets/python/deferred_modules.py", line 231, in _ImportHook
    module = _real_import(name, globals, locals, fromlist, level)
ImportError: No module named telegram.error

**Comment by bomjacob** [comment]
Please use the supplied issue template when reporting issues. Without it we cannot help you as we do not know what you're trying to do, or the environment you're using.

**Comment by tsnoam** [comment]
Closing as of no response from @TelegramBotAPIuz
