### ISSUE TITLE
Problem with InlineQueryResultGame

### ISSUE THREAD

**Issue by pperehozhih** [python-telegram-bot/python-telegram-bot#524]
Hi all.

I have problem with inline query result, after add InlineQueryResultGame object to response answer queue, module raise error

`TypeError: UUID('1e5c5b46-0a60-4c0c-9487-473fc5648d76') is not JSON serializable`

```
    query = update.inline_query.query
    results = list()

    results.append(InlineQueryResultGame(id=uuid4(),
                                         game_short_name="egg",
                                         reply_markup = InlineKeyboardMarkup([[InlineKeyboardButton('reply_markup')]])))

    update.inline_query.answer(results)
```

Maybe problem in override field id in inlinequeryresultgame.py file

```
    def __init__(self, id, game_short_name, reply_markup=None, **kwargs):
        # Required
        super(InlineQueryResultGame, self).__init__('game', id)
        self.id = id
        self.game_short_name = game_short_name
```

### Configuration
**Operating System:**
Mac OS 10.12.3

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
```
python-telegram-bot 5.3.0
urllib3 1.20
certifi 2017.01.23
future 0.16.0
Python 2.7.10 (default, Jul 30 2016, 19:40:32)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### Logs
```
2017-02-14 22:26:17,108 - telegram.bot - DEBUG - Entering: answerInlineQuery
2017-02-14 22:26:17,110 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "<cut>/python-telegram-bot/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "<cut>/python-telegram-bot/telegram/ext/inlinequeryhandler.py", line 106, in handle_upda
te
    return self.callback(dispatcher.bot, update, **optional_args)
  File "<cut>/python-telegram-bot/telegram-bot.py", line 63, in inlinequery
    update.inline_query.answer(results)
  File "<cut>/python-telegram-bot/telegram/inlinequery.py", line 93, in answer
    return self.bot.answerInlineQuery(self.id, *args, **kwargs)
  File "<cut>/python-telegram-bot/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "<cut>/python-telegram-bot/telegram/bot.py", line 878, in answerInlineQuery
    result = self._request.post(url, data, timeout=timeout)
  File "<cut>/python-telegram-bot/telegram/utils/request.py", line 228, in post
    data = json.dumps(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: UUID('1e5c5b46-0a60-4c0c-9487-473fc5648d76') is not JSON serializable
```

**Comment by bomjacob** [comment]
As a temporary fix you should be able to do `id=str(uuid4()),` in your InlineQueryResultGame initalization.

**Comment by pperehozhih** [comment]
Thnx
