### ISSUE TITLE
Issue with cert

### ISSUE THREAD

**Issue by edge33** [python-telegram-bot/python-telegram-bot#526]
I'm trying to get the snippet I got here: [https://gist.githubusercontent.com/leandrotoledo/4e9362acdc5db33ae16c/raw/76ad0feb21946042101ca8aa8ec5a6d0f122f509/main.py](url)

the script is 

```
`#!/usr/bin/env python

'''Using Webhook and self-signed certificate'''

# This file is an annotated example of a webhook based bot for
# telegram. It does not do anything useful, other than provide a quick
# template for whipping up a testbot. Basically, fill in the CONFIG
# section and run it.
# Dependencies (use pip to install them):
# - python-telegram-bot: https://github.com/leandrotoledo/python-telegram-bot
# - Flask              : http://flask.pocoo.org/
# Self-signed SSL certificate (make sure 'Common Name' matches your FQDN):
# $ openssl req -new -x509 -nodes -newkey rsa:1024 -keyout server.key -out server.crt -days 3650
# You can test SSL handshake running this script and trying to connect using wget:
# $ wget -O /dev/null https://$HOST:$PORT/

from flask import Flask, request

import telegram

# CONFIG
TOKEN    = 'I_AM_THE_TOKEN'
HOST     = 'hostnameIusedAsFQDN.com' # Same FQDN used when generating SSL Cert
PORT     = 8443
CERT     = 'server.pem'
CERT_KEY = 'server.key'

bot = telegram.Bot(TOKEN)
app = Flask(__name__)
context = (CERT, CERT_KEY)

@app.route('/')
def hello():
    return 'Hello World!'

@app.route('/' + TOKEN, methods=['POST'])
def webhook():
    update = telegram.update.Update.de_json(request.get_json(force=True))
    bot.sendMessage(chat_id=update.message.chat_id, text='Hello, there')

    return 'OK'


def setWebhook():
    bot.setWebhook(webhook_url='https://%s:%s/%s' % (HOST, PORT, TOKEN),
                   certificate=open(CERT, 'rb'))

if __name__ == '__main__':
    
    setWebhook()

    app.run(host='0.0.0.0',
            port=PORT,
            ssl_context=context,
            debug=True)

`
```

the output is:

```
` * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "./movieScraper.py", line 50, in <module>
    setWebhook()
  File "./movieScraper.py", line 46, in setWebhook
    certificate=open(CERT, 'rb'))
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 1280, in setWebhook
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 199, in post
    result = self._request_wrapper('POST', url, body=data.to_form(), headers=data.headers)
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 145, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 111, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 1 seconds`

```

what am I doing wrong?

**Comment by jh0ker** [comment]
You're running `setWebhook` two times in a row, very fast, probably because `* Restarting with stat`, which triggers telegram flood control

**Comment by tiantian1645** [comment]
@edge33 
`    setWebhook()
    time,sleep(5)
    app.run(host='0.0.0.0',
            port=PORT,
            ssl_context=context,
            debug=True)`
