### ISSUE TITLE
'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by mehrdadbahri** [python-telegram-bot/python-telegram-bot#557]
Recently I'm getting this error a lot:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 269, in process_update
    if handler.check_update(update):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 121, in check_update
    key = (chat.id, user.id) if chat else (None, user.id)
AttributeError: 'NoneType' object has no attribute 'id'`

I have no Idea why does it occur. But it occurs several times every day.

**Comment by jh0ker** [comment]
@mehrdadbahri Please use the issue template provided.
