### ISSUE TITLE
url lib 1.21

### ISSUE THREAD

**Issue by persian-telegram** [python-telegram-bot/python-telegram-bot#581]
### Steps to reproduce
1. running simple echo bot
I wasn't sure if I should make a new issue or if its the same as the last issue i made. 

2.

3.

### Expected behaviour
Tell us what should happen
connect to telegram 

### Actual behaviour
Tell us what happens instead
shows error 

### Configuration
**Operating System:**
ubuntu 14.04

**Version of Python, python-telegram-bot & dependencies:**
last version python-telegram-bot 
python 2.7
``$ python -m telegram``

### Logs
Insert logs here (if necessary)

telegram-bot)root@persian-telegram-bot:~# python script6.py
ERROR:telegram.ext.updater:unhandled exception
Traceback (most recent call last):
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 115, in _thread_wrapper
    target(*args, **kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 228, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 335, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/bot.py", line 1280, in setWebhook
    result = self._request.post(url, data, timeout=timeout)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/utils/request.py", line 207, in post
    **urlopen_kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 303, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 219, in connection_from_host
    return self.connection_from_context(request_context)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 232, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 245, in connection_from_pool_key
    pool = self.pools.get(pool_key)
  File "/root/telegram-bot/lib/python2.7/_abcoll.py", line 363, in get
    return self[key]
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/_collections.py", line 53, in __getitem__
    item = self._container.pop(key)
  File "/usr/lib/python2.7/collections.py", line 138, in pop
    if key in self:
TypeError: unhashable type: 'list'
Exception in thread updater:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 115, in _thread_wrapper
    target(*args, **kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 228, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 335, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/bot.py", line 1280, in setWebhook
    result = self._request.post(url, data, timeout=timeout)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/utils/request.py", line 207, in post
    **urlopen_kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 303, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 219, in connection_from_host
    return self.connection_from_context(request_context)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 232, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 245, in connection_from_pool_key
    pool = self.pools.get(pool_key)
  File "/root/telegram-bot/lib/python2.7/_abcoll.py", line 363, in get
    return self[key]
  File "/root/telegram-bot/local/lib/python2.7/site-packages/urllib3/_collections.py", line 53, in __getitem__
    item = self._container.pop(key)
  File "/usr/lib/python2.7/collections.py", line 138, in pop
    if key in self:
TypeError: unhashable type: 'list'

CRITICAL:telegram.ext.dispatcher:stopping due to exception in another thread

**Comment by Badiboy** [comment]
+1. All bots are down on simple "sendMessage".

**Comment by jh0ker** [comment]
@Badiboy https://github.com/python-telegram-bot/python-telegram-bot/issues/579

**Comment by persian-telegram** [comment]
My other bot on pythonAnywhere works though

**Comment by jh0ker** [comment]
probably because it doesn't use 1.21

**Comment by persian-telegram** [comment]
yes true, its using urrlib3 = 1.16

**Comment by Badiboy** [comment]
@jh0ker thnx, it rolled back the urllib3 1.20 and works again. Before upgrade to 5.3.1 everything works well...  Seems I'd upgrade the packages in wrong order...

**Comment by persian-telegram** [comment]
@Badiboy did you fix it?
do you mind telling me how you fixed it??

**Comment by Badiboy** [comment]
@persian-telegram yep, this adivse from @jh0ker rolled back the urllib 1.21 to 1.20 and bot starts working.
https://github.com/python-telegram-bot/python-telegram-bot/issues/579#issuecomment-297059189

**Comment by persian-telegram** [comment]
Thank you @Badiboy and @jh0ker

**Comment by tsnoam** [comment]
We're switching to vendoring our own fork of urllib3. See #533 .
We'll rebase our fork to upstream once we see a feature worth while for our users.
