### ISSUE TITLE
MessageHandler filters don't work: object() takes no parameters

### ISSUE THREAD

**Issue by amihaic** [python-telegram-bot/python-telegram-bot#585]
### Steps to reproduce
1. Create a handler from MessageHandler.
I tried several, one with a `MergedFilter`, one with `Filters.status_update`, and one with `None `in the filters position.
E.g., `updater.dispatcher.add_handler(MessageHandler(Filters.status_update, my_callback))`

2. Create a message to trigger the handler, e.g., add a user to group of which your bot is a member

### Expected behaviour
callback function specified in the filter should be triggered

### Actual behaviour
For any filter listed in Step 1, the behavior is the same:
`Traceback (most recent call last):
  File "X:\dev\envs\python35\lib\site-packages\telegram\ext\dispatcher.py", line 269, in process_update
    if handler.check_update(update):
  File "X:\dev\envs\python35\lib\site-packages\telegram\ext\messagehandler.py", line 113, in check_update
    res = self.filters(message)
TypeError: object() takes no parameters`

### Configuration
Windows 10
Used both command line and PyCharm

**Version of Python, python-telegram-bot & dependencies:**
Tested in Python 3.5 and Python 3.6

python-telegram-bot 5.3.1
urllib3 1.20
certifi 2017.04.17
future 0.16.0
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]

python-telegram-bot 5.3.1
urllib3 1.20
certifi 2017.04.17
future 0.16.0
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]

### Logs (scrubbed)
```
2017-04-28 16:36:07,019 - telegram.bot - DEBUG - Getting updates: [979015111]
2017-04-28 16:36:07,021 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x0000024AD7B24F28>]
2017-04-28 16:36:07,022 - telegram.bot - DEBUG - Exiting: getUpdates
2017-04-28 16:36:07,022 - telegram.ext.dispatcher - DEBUG - Processing Update: {'message': {'group_chat_created': False, 'left_chat_member': {'id': 96917135, 'username': '', 'first_name': 'XXX', 'type': '', 'last_name': 'XXX'}, 'delete_chat_photo': False, 'new_chat_photo': [], 'supergroup_chat_created': False, 'chat': {'id': 999999, 'type': 'group', 'last_name': '', 'all_members_are_admins': False, 'username': '', 'first_name': '', 'title': 'xxxxxxxxx'}, 'message_id': 17, 'date': 1493386567, 'photo': [], 'migrate_to_chat_id': 0, 'text': '', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'new_chat_title': '', 'caption': '', 'entities': [], 'from': {'id': 83835887, 'username': 'xxxxx', 'first_name': 'XXXX', 'type': '', 'last_name': 'XXXX'}}, 'update_id': 9999999}
2017-04-28 16:36:07,022 - telegram.bot - DEBUG - Entering: getUpdates
2017-04-28 16:36:07,023 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "X:\dev\envs\python35\lib\site-packages\telegram\ext\dispatcher.py", line 269, in process_update
    if handler.check_update(update):
  File "X:\dev\envs\python35\lib\site-packages\telegram\ext\messagehandler.py", line 113, in check_update
    res = self.filters(message)
TypeError: object() takes no parameters
```

**Comment by bomjacob** [comment]
Hmm, I seem to be unable to replicate this...
Could you try the following and and report back?
``` python
>>> import telegram
>>> import telegram.ext
>>> telegram.ext.Filters.status_update(telegram.Message(0, None, None, None))
```
If that fails then please do `type(telegram.ext.Filters.status_update)`

**Comment by amihaic** [comment]
This is what I get:
```text
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import telegram
>>> import telegram.ext
>>> telegram.ext.Filters.status_update(telegram.Message(0, None, None, None))
False
>>> type(telegram.ext.Filters.status_update)
<class 'telegram.ext.filters.Filters._StatusUpdate'>
>>>
```

**Comment by bomjacob** [comment]
You seem to have a bot running based on your log output, could you try posting the entire code to it, where this error happens?

**Comment by bomjacob** [comment]
Closing to due no response. Feel free to open again if you need to.
