### ISSUE TITLE
During updater bootstrap phase, retry on network errors

### ISSUE THREAD

**Issue by gloomy-ghost** [python-telegram-bot/python-telegram-bot#605]
### Steps to reproduce
1. Start bot by using `telegram.ext.updater.start_polling()`
2. Wait for network errors

### Expected behaviour
There should be some retry mechanism before stopping the whole bot

### Actual behaviour
The bot stopped on network errors

### Configuration
Ubuntu 16.04.2 LTS

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 5.3.1
urllib3 1.20
certifi 2017.04.17
future 0.16.0
Python 3.6.1 (default, Apr 22 2017, 20:17:23)  [GCC 5.4.0 20160609]

<details><summary>Logs</summary>

```python
2017-05-13 15:13:40,243 - telegram.ext.updater - ERROR - unhandled exception
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.6/site-packages/telegram/ext/updater.py", line 115, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.6/site-packages/telegram/ext/updater.py", line 233, in _start_polling
    self.last_update_id, timeout=timeout, network_delay=network_delay)
  File "/home/ghost/.local/lib/python3.6/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.6/site-packages/telegram/bot.py", line 1241, in getUpdates
    result = self._request.post(url, data, timeout=urlopen_timeout)
  File "/home/ghost/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 207, in post
    **urlopen_kwargs)
  File "/home/ghost/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ghost/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15.0)
2017-05-13 15:13:41,195 - telegram.ext.dispatcher - CRITICAL - stopping due to exception in another thread
```

</details>

**Comment by lossurdo** [comment]
Any idea how to recover bot normal execution after this exception? I guess it is the same Network Problem mentioned.

> ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15.0)

**$ python -m telegram**
python-telegram-bot 5.3.1
urllib3 1.20
certifi 2017.04.17
future 0.16.0
Python 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]

**Comment by zweistein22** [comment]
You want network errors: Here you go:  I have a raspberri Pi3 running a bot on a sailing boat connected with a 3G router.

Have the same problem with the bot unresponsive after network problems (a router reboot is also sufficient).

Maybe useful info:  My python app is running as a service with systemctl etc.

the dispatcher thread ends with a  CRITICAL exception in dispatcher.py  line#209 .
The error is not propagated to error handlers ( have tried 👍 updater = Updater("xxxxxxxxxxxxxxxx",user_sig_handler=sigHandler)  and  dp.add_error_handler(error_callback)

A:) Couldn't you just send a SIGTERM  to the main thread from dispatcher.py #209 ?
B:) Other idea is to set up a watch thread and check for dispatcher.running ==false.

Any tips here from people who know python better ( I was a Windows C++ guy years ago) are welcome, thank you

Andreas

using urllib3 v 1.22 and python-telegram-bot 6.1.0
Log here:

Jul 21 08:27:01 raspberrypi3 python3[477]: File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 180, in _request_wrapper
Jul 21 08:27:01 raspberrypi3 python3[477]: raise NetworkError('urllib3 HTTPError {0}'.format(error))
Jul 21 08:27:01 raspberrypi3 python3[477]: telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/setWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x76281790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Jul 21 08:27:01 raspberrypi3 python3[477]: CRITICAL:telegram.ext.dispatcher:stopping due to exception in another thread

**Comment by zweistein22** [comment]
I checked again above (CRITICAL error and resulting hang of dispatcher thread.

It also dipends on the logger settings.

When I user logging.basicConfig(level=logging.DEBUG)  then I cannot reproduce the CRITICAL error
When I use logging.basicConfig(level=logging.ERROR)  then the CRITICAL error comes up

Andreas

**Comment by tsnoam** [comment]
@zweistein22 
I am missing a log line which looks like "unhandled exception .... <exception data>"  produced by updater.py:136
Can you check your logs to see if it's there? If not, I would try to manually switch between lines 135-136 (don't think it should matter).
This log line in question should explain what was the very fundamental error which triggered the problem.

Anyway, when you respond, can you please create a new issue? (I'm not sure it's the same problem as the original report here)
