### ISSUE TITLE
KeyError:0 when using ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by yusufk** [python-telegram-bot/python-telegram-bot#690]
### Steps to reproduce
```
def start(bot, update):
    keyboard = [telegram.KeyboardButton(text="Send Location", request_location=True)]
    reply_markup = telegram.ReplyKeyboardMarkup(keyboard)
    update.message.reply_text("Click \"Send Location\" to find places in your vicinity..", reply_markup=reply_markup)

```

### Expected behaviour
Expect a keyboard to be shown

### Actual behaviour
KeyError: 0

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
```
2017-06-24 15:01:12,182 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/telegram/ext/dispatcher.py", line 265, in process_update
    handler.handle_update(update, self)
  File "/Library/Python/2.7/site-packages/telegram/ext/commandhandler.py", line 136, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "masjid_bot.py", line 72, in start
    bot.send_message(chat_id=update.message.chat_id, text="Click \"Send Location\" to find places in your vicinity..", reply_markup=reply_markup)
  File "/Library/Python/2.7/site-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/telegram/bot.py", line 64, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/telegram/bot.py", line 152, in _message_wrapper
    data['reply_markup'] = reply_markup.to_json()
  File "/Library/Python/2.7/site-packages/telegram/base.py", line 62, in to_json
    return json.dumps(self.to_dict())
  File "/Library/Python/2.7/site-packages/telegram/replykeyboardmarkup.py", line 82, in to_dict
    for button in row:
  File "/Library/Python/2.7/site-packages/telegram/base.py", line 38, in __getitem__
    return self.__dict__[item]
KeyError: 0

```

**Comment by Eldinnie** [comment]
A `ReplyKeyboardMarkup` should get a list of lists as buttons. So in you case the second line should be:
```
keyboard = [[telegram.KeyboardButton(text="Send Location", request_location=True)]]
```

For further questions regarding the use that are not actual issues with the code of the library you might want to use our support-chat [here](https://t.me/pythontelegrambotgroup)

**Comment by yusufk** [comment]
Thank you. Works well.
