### ISSUE TITLE
Having troubles with running my bot with crontab

### ISSUE THREAD

**Issue by MrMarble** [python-telegram-bot/python-telegram-bot#704]
### Expected behaviour
If I run my bot manually everything works just fine, but when I set a task in cron to run my bot on boot I always get an error 

### Actual behaviour
Bunch of erros of the internal api

### Configuration
**Operating System:**
Ubuntu

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 6.1.0
urllib3 1.21.1
certifi 2017.04.17
future 0.16.0
Python 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]

### Logs
```
<urlopen error [Errno 111] Connection refused>
2017-07-02 14:16:29,261 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb64a1890>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot364785677:MY_TOKEN/setWebhook
2017-07-02 14:16:29,265 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb64a1b90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot364785677:MY_TOKEN/setWebhook
2017-07-02 14:16:29,268 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb64a1bd0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot364785677:MY_TOKEN/setWebhook
2017-07-02 14:16:29,271 - telegram.ext.updater - ERROR - error in bootstrap phase; try=0 max_retries=0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/updater.py", line 375, in _bootstrap
    url=webhook_url, certificate=cert, allowed_updates=allowed_updates)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1467, in set_webhook
    result = self._request.post(url_, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 252, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 180, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot364785677:MY_TOKEN/setWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb64a18f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2017-07-02 14:16:29,284 - telegram.ext.updater - ERROR - unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/updater.py", line 133, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/updater.py", line 263, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/updater.py", line 375, in _bootstrap
    url=webhook_url, certificate=cert, allowed_updates=allowed_updates)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1467, in set_webhook
    result = self._request.post(url_, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 252, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 180, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot364785677:MY_TOKEN/setWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb64a18f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Exception in thread updater:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/updater.py", line 133, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/updater.py", line 263, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/updater.py", line 375, in _bootstrap
    url=webhook_url, certificate=cert, allowed_updates=allowed_updates)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1467, in set_webhook
    result = self._request.post(url_, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 252, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 180, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot364785677:MY_TOKEN/setWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb64a18f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

2017-07-02 14:16:30,263 - telegram.ext.dispatcher - CRITICAL - stopping due to exception in another thread

```

**Comment by bomjacob** [comment]
Since the bot works when you run it normally, this presumably isn't directly related to the library so I'm closing this issue. 

I do have a few suggestions to help you out:
- What user does crontab run the bot as?
    - Does that user have access to the internet?
- Is your DNS set up properly?
- Is it only bots run from crontab that can't access the internet or is it eveything?
- You're welcome to [public telegram support group](https://t.me/pythontelegrambotgroup) to see if you can find any help there :D
