### ISSUE TITLE
Editing two messages simultaneously causes TimeoutError

### ISSUE THREAD

**Issue by MelomanCool** [python-telegram-bot/python-telegram-bot#714]
### Steps to reproduce
1. Send two messages
2. Edit them one after another without any delay between the edits
3. You get the exception

### Expected behaviour
The messages should be edited without any errors

### Actual behaviour
The exception is being raised while the second message is being edited. *But*, that message is actually being changed just *after* the exception.
Also, I've noticed that if you *send* two messages simultaneously, it works just fine every time. I don't know if that's the Telegram API's behavior or not, but that seems weird to me.

### Example code
```python
from time import sleep
import telegram

TOKEN = 'TOKEN'
CHAT_ID = '999999'

bot = telegram.Bot(TOKEN)

# no exception here
message1 = bot.send_message(CHAT_ID, 'some message 1')
message2 = bot.send_message(CHAT_ID, 'some message 2')

sleep(10)

# but here we do get it!
message1.edit_text('1: edited')
message2.edit_text('2: edited')
```

### Configuration
**Operating System:**
Debian Buster

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 6.1.0
urllib3 1.19.1
certifi 2017.04.17
future 0.16.0
Python 3.6.2rc1 (default, Jun 20 2017, 12:51:36)  [GCC 6.3.0 20170516]
```

**Comment by MelomanCool** [comment]
Hrm, for some reason, not getting the exception anymore right now. Maybe it has something to do with Telegram servers load?

**Comment by MelomanCool** [comment]
Now, the exception is back. Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 174, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PycharmProjects/SilverRainNowPlaying/test.py", line 21, in <module>
    main()
  File "PycharmProjects/SilverRainNowPlaying/test.py", line 17, in main
    message2.edit_text('2: edited {} times!'.format(i))
  File "/usr/local/lib/python3.6/dist-packages/telegram/message.py", line 545, in edit_text
    chat_id=self.chat_id, message_id=self.message_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 64, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 156, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 252, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 176, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out
```

**Comment by bomjacob** [comment]
I can't seem to reproduce this.. Could you try increasing the timeouts and seeing if that fixes it?

**Comment by MelomanCool** [comment]
Okay, how can I do that?

**Comment by MelomanCool** [comment]
Okay, when I use `message2.edit_text('2: edited', timeout=10)`, I don't get the exception.
But that doesn't fix my main problem — I want to edit two messages simultaneously. So, this is the limitation of the API, not of the library?

**Comment by Eldinnie** [comment]
I think this is closer to being a "problem" with telegram's servers. It seems the server takes some time to answer on the edit you send. If you increase the time-out does it also take longer for the messages to be edited?

**Comment by tsnoam** [comment]
Ok. Closing this issue as it appears to be behaviour of the Telegram servers.
Of course you can contact telegram's bot support, but unfortunately this is not something we can help you with.
