### ISSUE TITLE
Flood control exceeded (in ConversationHandler with run_async)

### ISSUE THREAD

**Issue by korcky** [python-telegram-bot/python-telegram-bot#783]
### Code example:
```python
import logging
from telegram import KeyboardButton, ReplyKeyboardMarkup
from telegram.ext import Updater
from telegram.ext import CommandHandler, ConversationHandler, RegexHandler
from telegram.ext.dispatcher import run_async

import config as cfg

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)
logger = logging.getLogger(__name__)

main = 1

kb = ReplyKeyboardMarkup([[KeyboardButton('Button 1'), KeyboardButton('Button 2')]],
                         resize_keyboard=True)


@run_async
def start(bot, update):
    update.message.reply_text('start', reply_markup=kb)
    return main


@run_async
def some1(bot, update):
    update.message.reply_text(cfg.BIG_TEXT_1
                              reply_markup=kb, parse_mode='Markdown')
    return main


@run_async
def some2(bot, update):
    update.message.reply_text(cfg.BIG_TEXT_2,
                              reply_markup=kb, parse_mode='Markdown')
    return main


@run_async
def back(bot, update):
    update.message.reply_text('back', reply_markup=kb)
    return main


@run_async
def error(bot, update, error):
    logger.warning('Update {} caused error {}'.format(str(update), str(error)))
    update.message.reply_text('Error occur', reply_markup=kb)
    return main

if __name__ == '__main__':
    updater = Updater(token=cfg.TOKEN, workers=8)
    dispatcher = updater.dispatcher

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],
        states={
            main: [RegexHandler('^(Button 1)$', some1),
                   RegexHandler('^(Button 2)$', some2)]
        },
        fallbacks=[RegexHandler('Back', back)]
    )

    dispatcher.add_handler(conv_handler)
    dispatcher.add_error_handler(error)

    updater.start_polling()
    updater.idle()
```

### Steps to reproduce
1. print `/start` to bot
2. press very fast on `Button 1` (and/or `Button 2`) (text that bot reply should be big, in my case it was over 900 chars)

### Expected behaviour
Appear `telegram.error.RetryAfter: Flood control exceeded. Retry in N seconds`, after N seconds communication with bot should restore.

### Actual behaviour
Appear `telegram.error.RetryAfter: Flood control exceeded. Retry in N seconds`, after N seconds communication with bot still doesn't work.

### Configuration
**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 6.1.0
urllib3 1.21.1
certifi 2017.04.17
future 0.16.0
Python 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
```

### Logs
Without `@run_async` bot works fine (if appear ` Flood control exceeded. Retry in N seconds`, after N seconds i can communicate with bot), but with `@run_async` i have logs like that:
First appear that message:
```
2017-08-09 12:26:02,776 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 42, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "test.py", line 28, in some1
    update.message.reply_text(cfg.BIG_TEXT_1, reply_markup=kb, parse_mode='Markdown')
  File "/usr/local/lib/python3.5/dist-packages/telegram/message.py", line 340, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 64, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 156, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 252, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 187, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 147, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 295 seconds
```
Then, if continue pressing buttons, this message will be duplicated, **BUT** number of seconds in this text will always be the same (295 in this particular example) and every new duplicate will have new strings (number of this strings correlates with "serial number" of duplicate:
```
File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 191, in check_update
    res = new_state.result(timeout=self.run_async_timeout)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 57, in result
    raise self._exception  # pylint: disable=raising-bad-type
```
like this (4th duplicate):
```
2017-08-09 12:26:18,296 - telegram.ext.conversationhandler - ERROR - Promise function raised exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 191, in check_update
    res = new_state.result(timeout=self.run_async_timeout)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 57, in result
    raise self._exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 191, in check_update
    res = new_state.result(timeout=self.run_async_timeout)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 57, in result
    raise self._exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 191, in check_update
    res = new_state.result(timeout=self.run_async_timeout)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 57, in result
    raise self._exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 191, in check_update
    res = new_state.result(timeout=self.run_async_timeout)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 57, in result
    raise self._exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 42, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "test.py", line 28, in some1
    update.message.reply_text(cfg.BIG_TEXT_1, reply_markup=kb, parse_mode='Markdown')
  File "/usr/local/lib/python3.5/dist-packages/telegram/message.py", line 340, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 64, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 156, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 252, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 187, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 147, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 295 seconds
```
Btw, without `@run_async`, text still will be duplicated, but number of seconds will decrease and no new strings were added in duplicates.

**Comment by bomjacob** [comment]
AFAIK, we don't handle RetryAfter in any special way currently. If you're interested in avoiding this error at all the [Avoiding spam limits](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-spam-limits) wiki page about the upcoming (but already usable) feature MessageQueue might be helpful :)

**Comment by korcky** [comment]
@bomjacob, thanks, that will be useful, but main question is "why without `@run_async` i can communicate with bot (after ~5 minute), and with `@run_async` i can't?". Or should i ask this question elsewhere?

**Comment by bomjacob** [comment]
Hmm, that indeed might be a bug, could you maybe make some minimal example code that fails? (I know you have some code above, but it's a bit big and we can't see what's in cfg).
@tsnoam or @jh0ker any ideas?

**Comment by korcky** [comment]
Code is still big, but now you can just replace `TOKEN` with some real bot token, run it, send `/start` to bot and pres `Button 1` really fast.
```python
import logging
from telegram import KeyboardButton, ReplyKeyboardMarkup
from telegram.ext import Updater
from telegram.ext import CommandHandler, ConversationHandler, RegexHandler
from telegram.ext.dispatcher import run_async

TOKEN = ''
TEXT = """
Hello! I am bot that hate receiving a lot of spam asynchronous.
This strange thing discuss on \
[GitHub](https://github.com/python-telegram-bot/python-telegram-bot/issues/783#issuecomment-321241418).

When I receive a lot of spam asynchronous, I raise Flood control exceeded and stay silence \
with [spamer](http://www.urbandictionary.com/define.php?term=spamer) (*BECAUSE I HATE HIM SO MUCH!*).

But this strange behavior of my only exist when I try to reply with really big text, like one that you
read right now.

And, probably, this text should have a lot of links:
[Google](google.com), [GwTB](http://www.blastwave-comic.com/index.php), \
[Sara](http://sarahcandersen.com/), [Wiki](https://en.wikipedia.org/wiki/Main_Page).

And, of course, a lot of text:
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
"""

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)
logger = logging.getLogger(__name__)

main = 1

kb = ReplyKeyboardMarkup([[KeyboardButton('Button 1')]], resize_keyboard=True)


@run_async
def start(bot, update):
    update.message.reply_text('start', reply_markup=kb)
    return main


@run_async
def some1(bot, update):
    update.message.reply_text(TEXT, reply_markup=kb, parse_mode='Markdown')
    return main


@run_async
def back(bot, update):
    update.message.reply_text('back', reply_markup=kb)
    return main

if __name__ == '__main__':
    updater = Updater(token=TOKEN, workers=8)
    dispatcher = updater.dispatcher

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],
        states={
            main: [RegexHandler('^(Button 1)$', some1)]
        },
        fallbacks=[RegexHandler('Back', back)]
    )

    dispatcher.add_handler(conv_handler)

    updater.start_polling()
    updater.idle()
```

**Comment by korcky** [comment]
Just notice, that this exception rising when number of chars in `TEXT` is ~745 (+-10) or above.

**Comment by korcky** [comment]
Just update lib to 7.0.1 and looks like everything fine now.

**Comment by BugDeveloper** [comment]
I have the same exact problem, but with using of MessageQueue. I keep getting `telegram.error.RetryAfter: Flood control exceeded. Retry in N seconds` when I flooding from the client (by pressing reply keyboard buttons really-really quickly) to my bot and it answers me. MessageQueue actually works, I can see the delay during sending big number of messages at once (with for loop) and it's definitely not exceeding the restriction of 30 msg/sec.

You can see more details [here](https://stackoverflow.com/questions/51423139/python-telegram-bot-flood-control-exceeded).

Thank you for any suggestions.
