### ISSUE TITLE
after send many file  coule not send file over 10M success

### ISSUE THREAD

**Issue by mengyyy** [python-telegram-bot/python-telegram-bot#891]
### Steps to reproduce
1. use bot.send_document() sent many file
2. use bot.send_document() sent a document which size is over 10M timeout set to 240S

cc = bot.send_document(chat_id=chat_id,document=open( file_name, 'rb'),  timeout=240)
bot.send_message(chat_id=chat_id, text=cc.document.file_id)

### Expected behaviour
send success and get the file_id from return message object

### Actual behaviour
send file failed and get `telegram.error.TelegramError: Invalid server response`
but telegram client get the file
after split the file under 10M send file success 

### Configuration
Ubuntu 14.04.5 LTS
Ubuntu 16.04.3 LTS

**Version of Python, python-telegram-bot & dependencies:**
Python 3.4.3
Python 3.5.2
python-telegram-bot==8.1.1

### Logs
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 150, in _parse
    data = json.loads(decoded_s)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/emagazine_scapy.py", line 154, in deal_vk_gen_sql_info
    timeout=240)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 82, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 264, in post
    'POST', url, body=data.to_form(), headers=data.headers, **urlopen_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 203, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 152, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response

**Comment by tsnoam** [comment]
@mengyyy Is that problem consistent? i.e. you can recreate it every time?

We need to modify the code so it will be able to log the exact server response when it is invalid then we'll analyze it further.

**Comment by mengyyy** [comment]
Yes, the problem is  consistent now. Shoud i give my bot token to you?

**Comment by mengyyy** [comment]
Now try send at most 2 times can send success

**Comment by tsnoam** [comment]
@mengyyy Do you mean that you can't recreate at the moment?

**Comment by mengyyy** [comment]
Yes

**Comment by tsnoam** [comment]
@mengyyy Ok. We'll still add the ability to log invalid server responses.
However, for your specific case, this might have been an error with telegram servers which was later fixed.

**Comment by mengyyy** [comment]
Thank you . I try send more times to check if the telegram server problem.

**Comment by mengyyy** [comment]
I think it should some limit about send file to telegram server.
Because i got **`Invalid server response`**  just after 2 second i sent docuemt .
But i use proxy to send ,it works no problem.

Form  **2017-10-27 06:28:21,254**  to **2017-10-27 08:09:33,464** i got this like that  
```
2017-10-27 08:09:33,464 - DEBUG - try send Adventures_of_Tymm_-_Alien_Circus_002_2008__Platinum__wowio_com__Throbbing_Member-TCR.cbr size 14281145 | 1/3
2017-10-27 08:09:34,715 - ERROR - Send to telegram failed Adventures_of_Tymm_-_Alien_Circus_002_2008__Platinum__wowio_com__Throbbing_Member-TCR.cbr | 1/3
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 150, in _parse
    data = json.loads(decoded_s)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./emagezinepdf_scapy.py", line 154, in deal_vk_gen_sql_info
    timeout=240)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 82, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 264, in post
    'POST', url, body=data.to_form(), headers=data.headers, **urlopen_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 203, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 152, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response
```

**Comment by mengyyy** [comment]
These days i had not seen these error. I think it is telegram server problem.
And i found when i meet this problem,  not only use another bot to send file on the same vps but also use the same bot on other vps could not send file success.
But after about 12 hours everything is ok.
