### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by dimitar-petrov** [python-telegram-bot/python-telegram-bot#917]
Hello,

I am facing trouble using the module in subclassed multiprocessing.Process with "spawn" context. If I fork the Process, it is working, but I would like to spawn it.

### Steps to reproduce
```
import multiprocessing as mp
import time
from telegram.ext import Updater

class SubProc(mp.Process):
    def __init__(self, chatbot_token):
        super(SubProc, self).__init__()
        self.updater = Updater(token=chatbot_token)

    def run(self):
        cp = mp.current_process()
        print('In - Name: {} PID: {}'.format(
            cp.name, cp.pid))
        time.sleep(10)

if __name__ == '__main__':
    cp = mp.current_process()
    print('In - Name: {} PID: {}'.format(
        cp.name, cp.pid))

    mp.set_start_method('spawn')
    proc = SubProc(CHATBOT_TOKEN)
    proc.start()
    proc.join()

```
### Expected behaviour
Successfull spawn of new process

### Configuration
**Operating System:**
Archlinux

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
```
python-telegram-bot 8.0
certifi 2017.11.05
future 0.16.0
Python 3.6.3 (default, Oct  7 2017, 12:53:41)  [GCC 7.1.1 20170630
```
### Logs
```
In - Name: MainProcess PID: 22936                                  
Traceback (most recent call last):                                                                                                                                                                                 
  File "multiproc_example.py", line 36, in <module>
    proc.start()
  File "/home/dpetrov/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/process.py", line 105, in start                                                                                                          
    self._popen = self._Popen(self)
  File "/home/dpetrov/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)                                                                                                                                              
  File "/home/dpetrov/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/dpetrov/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__                                                                                              
    super().__init__(process_obj)
  File "/home/dpetrov/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/dpetrov/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/dpetrov/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

**Comment by dimitar-petrov** [comment]
I managed to pickle the class by adding __reduce__ to Updater.

```
    def __reduce__(self):
        return (self.__class__, (self.bot.token,))
```

Any side effects of doing that?

**Comment by rahiel** [comment]
Could you check if using the [dill](https://github.com/uqfoundation/dill) library helps with this issue? Install and import it, then it should extend Python's pickling abilities.

**Comment by tsnoam** [comment]
@dimitar-petrov 

On a quick glance, the `__reduce__` should be sufficient if it was only the `Updater` in question (with the exception that you only return the token and for a more general approach you'd need to return all the arguments passed to `__init__`).

However, `Updater` is not the only problem. There's a Lock being used in the dispatcher as well. This Lock is generated during `import` (look on the comments in dispatcher.py for more explanation about it). AFAIK, behaviour of such locks is undefined after fork. This might not pose a problem for you, but you should be aware of it.

In general, the Updater is not designed for this kind of usage pattern, but if you come into problems feel free to contact us about this and we can discuss how to improve the code.

One last thing, if you can simply your app X times externally to python (a shell script for example) I believe that it'll be "safer".

I'm closing this issue for now.
