### ISSUE TITLE
Payment is not working if written AFTER a conversation handler

### ISSUE THREAD

**Issue by CeuxDruman** [python-telegram-bot/python-telegram-bot#927]
### Steps to reproduce
1. Just make a test payment as shown in the official example https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/paymentbot.py

2. Add the payment handlers **AFTER a conversation handler**, like this:
```
conv_handler = ConversationHandler(
    ...
)

# Add command handler to start the payment invoice
dp.add_handler(CommandHandler("shipping", start_with_shipping_callback))
dp.add_handler(CommandHandler("noshipping", start_without_shipping_callback))

# Optional handler if your product requires shipping
dp.add_handler(ShippingQueryHandler(shipping_callback))

# Pre-checkout handler to final check
dp.add_handler(PreCheckoutQueryHandler(precheckout_callback))

# Success! Notify your user!
dp.add_handler(MessageHandler(Filters.successful_payment, successful_payment_callback))
```

3. Run it and try to make a payment (I used /noshipping).

### Expected behaviour
It should let you make the full payment successfully.

### Actual behaviour
It lets you type all payment information, but in the last step, when clicking the last "Pay" button, it crash (see [Logs](#logs)) and doesn't call precheckout_callback function throw PreCheckoutQueryHandler.

### Additional information

- It works perfectly if you add it BEFORE the ConversationHandler.
- It seems to be recognized as if payment handlers were located inside the ConversationHandler.
- I don't think it to affect this issue, but I'm using Stripe payment in testing mode.

### Configuration
I'm using the last version up to date. (e8fac19de31b3d246d0253ac0267f7253a22d526)

### Logs
```
2017-12-02 17:31:52,827 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\Carlos\Documents\Programacion\TelegramBots\Pickatext\telegram\ext\dispatcher.py", line 278, in process_update
    for handler in (x for x in self.handlers[group] if x.check_update(update)):
  File "C:\Users\Carlos\Documents\Programacion\TelegramBots\Pickatext\telegram\ext\dispatcher.py", line 278, in <genexpr>
    for handler in (x for x in self.handlers[group] if x.check_update(update)):
  File "C:\Users\Carlos\Documents\Programacion\TelegramBots\Pickatext\telegram\ext\conversationhandler.py", line 215, in check_update
    key = self._get_key(update)
  File "C:\Users\Carlos\Documents\Programacion\TelegramBots\Pickatext\telegram\ext\conversationhandler.py", line 185, in _get_key
    key.append(chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by Eldinnie** [comment]
I believe this was already resolved in chat. Can you confirm?

**Comment by CeuxDruman** [comment]
@Eldinnie It was given a temporary/fast solution by chat, the one which is indicated in the "**Additional information**" section:

> - It works perfectly if you add it BEFORE the ConversationHandler.

But it is still a bug that you can't add it after the ConversationHandler. I think it should be solved and/or clearly specified in the documentation. If I wouldn't have asked in chat, I'd "never" have be able to solve this issue.

I also opened this issue due to the @jh0ker recommendation.

**Comment by Eldinnie** [comment]
Ok, I missed that. I will take a closer look soon. Thanks for your clarification.

**Comment by elatonsev** [comment]
It doesn't work for me even if I placed it before conversation handler, the same error

```def main(dp):
    # Pre-checkout handler to final check
    dp.add_handler(PreCheckoutQueryHandler(precheckout_callback, pass_user_data=True))

    # Success! Notify your user!
    dp.add_handler(MessageHandler(Filters.successful_payment, successful_payment_callback,
                                  pass_user_data=True))

    dp.add_handler(CallbackQueryHandler(calendar_next_month,
                                        pattern=r'^calendar-next-month',
                                        pass_user_data=True))

    dp.add_handler(CallbackQueryHandler(calendar_previous_month,
                                        pattern=r'^calendar-previous-month',
                                        pass_user_data=True))

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler("bike", point, pass_user_data=True)],

        states={
            BIKE: [CallbackQueryHandler(bike,
                                        pattern=r'^point-',
                                        pass_user_data=True)],
            AMOUNT: [CallbackQueryHandler(amount,
                                          pattern=r'^product-',
                                          pass_user_data=True)],
            DURATION: [CallbackQueryHandler(duration,
                                            pattern=r'^amount-',
                                            pass_user_data=True)],
            DATE: [CallbackQueryHandler(ride_date,
                                        pattern=r'^duration-',
                                        pass_user_data=True)],
            TIME: [CallbackQueryHandler(ride_time,
                                        pattern=r'^calendar-day-',
                                        pass_user_data=True)],
            PHONE: [CallbackQueryHandler(phone,
                                         pattern=r'^time-',
                                         pass_user_data=True)],
            EMAIL: [MessageHandler(Filters.text, email, pass_user_data=True)],
            PAYMENT: [MessageHandler(Filters.text, payment, pass_user_data=True)]
        },

        fallbacks=[CommandHandler('cancel', cancel)]
    )

    dp.add_handler(conv_handler)
```

```
2017-12-10 23:42:05,120 ERROR [telegram.ext.dispatcher:301][dispatcher] An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/mihailelatonsev/Projects/my_projects/bike_rentals/eggs/python_telegram_bot-9.0.0-py3.6.egg/telegram/ext/dispatcher.py", line 278, in process_update
    for handler in (x for x in self.handlers[group] if x.check_update(update)):
  File "/Users/mihailelatonsev/Projects/my_projects/bike_rentals/eggs/python_telegram_bot-9.0.0-py3.6.egg/telegram/ext/dispatcher.py", line 278, in <genexpr>
    for handler in (x for x in self.handlers[group] if x.check_update(update)):
  File "/Users/mihailelatonsev/Projects/my_projects/bike_rentals/eggs/python_telegram_bot-9.0.0-py3.6.egg/telegram/ext/conversationhandler.py", line 215, in check_update
    key = self._get_key(update)
  File "/Users/mihailelatonsev/Projects/my_projects/bike_rentals/eggs/python_telegram_bot-9.0.0-py3.6.egg/telegram/ext/conversationhandler.py", line 185, in _get_key
    key.append(chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
```
