### ISSUE TITLE
telegram.error.RetryAfter: Flood control exceeded. Retry in { } seconds

### ISSUE THREAD

**Issue by deepsorrow** [python-telegram-bot/python-telegram-bot#939]
### Steps to reproduce
1. Start bot

2. Click consequentially exactly 20 times on various Inline buttons to edit the same message.
Making interval of 1 second between clicks doesn't do a thing

### Expected behaviour
The bot should respond to user's request and edit a message.

### Actual behaviour
The error raises and doesn't let me use bot in a few minutes.

### Configuration
**Operating System:**
Windows 10, Debian 9.3

**Version of Python, python-telegram-bot & dependencies:**
> 
> python-telegram-bot 9.0.0
> certifi 2017.11.05
> future 0.16.0
> Python 3.6.4rc1 (default, Dec 6 2017, 10:08:29) [GCC 7.2.0]

After some time developing methods inside `button_pressed_handler`, my bot began to receive flood control limits, even though I didn't touch `main()` function and it's `updater`. Tried to change `poll_interval` up to 2 seconds, but no avail.
#### main() code
```
def main():
    # Create the EventHandler and pass it your bot's token.
    updater = Updater("token")

    updater.dispatcher.add_handler(CommandHandler('start', start_message))
    updater.dispatcher.add_handler(CallbackQueryHandler(button_pressed_handler))
    updater.dispatcher.add_handler(MessageHandler(Filters.text, income_message_handler))
    updater.dispatcher.add_handler(MessageHandler(Filters.document, doc_image_handler))
    updater.dispatcher.add_handler(MessageHandler(Filters.photo, image_handler))

    # Start the Bot
    updater.start_polling(read_latency=6)

    updater.idle()
```
#### structure of button_pressed_handler
```
def button_pressed_handler(bot, update):
    info = update.callback_query
    _id = info.data
    chat_id = info["message"]["chat"]["id"]
    message_id = int(info["message"]["message_id"])

    if "menu" in _id:
        catalog.show_time(bot, chat_id)

    elif 'questionMenu' in _id:
        catalog.open_available_movies(bot=bot, chat_id=chat_id, message_id=message_id)

    elif '...' in _id:
        ...
```
### Logs

> 2017-12-20 04:56:47,634 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
2017-12-20 04:56:47,634 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception...
Traceback (most recent call last):
  File "C:\Users\superuser\.virtualenvs\test\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\superuser\.virtualenvs\test\lib\site-packages\telegram\ext\callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:/Users/superuser/PycharmProjects/test/main.py", line 320, in button_pressed_handler
    catalog.start_message(bot, chat_id, message_id, True)
  File "C:\Users\superuser\PycharmProjects\test\Interface.py", line 753, in start_message
    parse_mode='HTML')
  File "C:\Users\superuser\.virtualenvs\test\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\superuser\.virtualenvs\test\lib\site-packages\telegram\bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "C:\Users\superuser\.virtualenvs\test\lib\site-packages\telegram\utils\request.py", line 272, in post
    **urlopen_kwargs)
  File "C:\Users\superuser\.virtualenvs\test\lib\site-packages\telegram\utils\request.py", line 203, in _request_wrapper
    message = self._parse(resp.data)
  File "C:\Users\superuser\.virtualenvs\test\lib\site-packages\telegram\utils\request.py", line 163, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 273 seconds

Could you hint me what might be the reason for the error?

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).
