### ISSUE TITLE
long time to telegram.bot - DEBUG - Entering: sendMessage

### ISSUE THREAD

**Issue by diakbar** [python-telegram-bot/python-telegram-bot#94]
why i got 3 minutes delayed from first command ?

here's log:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 730: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/rosady/akbar/telebot/dodolbot.py", line 235, in <module>
    main()
  File "/home/rosady/akbar/telebot/dodolbot.py", line 45, in main
    LAST_UPDATE_ID = bot.getUpdates()[-1].update_id
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 683, in getUpdates
    result = request.post(url, data)
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 93, in post
    result = urlopen(request).read()
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1224, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1186, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by leandrotoledo** [comment]
Would you please upgrade to latest version, v2.9.1, and check if it's gone?
``pip install python-telegram-bot --upgrade``

Thanks!

**Comment by leandrotoledo** [comment]
Hi @diakbar, feel free to reopen if this issue persists.

**Comment by diakbar** [comment]
still occured 
```

2016-05-18 00:48:21,375 - telegram.bot - DEBUG - Entering: getUpdates
Traceback (most recent call last):
  File "newbot.py", line 588, in <module>
    main()
  File "newbot.py", line 49, in main
    LAST_UPDATE_ID = bot.getUpdates()[-1].update_id
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 109, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1215, in getUpdates
    result = request.post(url, data, timeout=urlopen_timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 83, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
telegram.error.NetworkError: URLError: ('_ssl.c:574: The handshake operation timed out',)

```

**Comment by leandrotoledo** [comment]
@diakbar are you using the latest version of this library?

**Comment by jh0ker** [comment]
Try increasing `network_delay`. It controls the `urlopen` timeout - if it's too low for your network connection, it will abort prematurely and raise an exception.

**Comment by leandrotoledo** [comment]
@diakbar feel free to reopen if the solution above does not work for you.
