### ISSUE TITLE
Sending media fails - connection timeout - even though other methods work fine

### ISSUE THREAD

**Issue by spookyahell** [python-telegram-bot/python-telegram-bot#947]
### Steps to reproduce
1. Use `bot.send_audio` method anywhere / 
also happens with all the other media upload methods anywhere...
even though it's seems implemented correctly
`bot.send_audio(chat_id=update.message.chat_id, audio=open(r'C:\Users\User\Music\MyMP3File.mp3', 'rb'))`
It even fails on sending an URL to Telegram - also: Network timeout

network timout doesn't normally happen at my end at all -- all other telegram API method calls like SendMessage seem to work perfektly fine

### Expected behaviour
Send audio file (mp3) to Telegram

### Actual behaviour
Connection timeout -- can't tell why this should happen

### Configuration
**Operating System:** Windows 7 - 64 bit

**Version of Python, python-telegram-bot & dependencies:**
beautifulsoup4==4.6.0
bs4==0.0.1
certifi==2017.7.27.1
chardet==3.0.4
cx-Freeze==5.0.2
future==0.16.0
idna==2.5
PyInstaller==3.2.1
pypiwin32==220
python-telegram-bot==9.0.0
requests==2.8.1
termcolor==1.1.0
urllib3==1.22

(not sure if those are all needed but want to make sure I'm not missing anything...)

### Logs
2017-12-23 02:58:14,105 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
2017-12-23 02:58:14,105 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 636, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\utils\request.py", line 190, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 70, in request
    **urlopen_kw)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Program Files (x86)\Python\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 636, in write
    return self._sslobj.write(data)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:\Users\User\Downloads\FlacBot.py", line 21, in start
    bot.send_audio(chat_id=update.message.chat_id, audio=open(r'C:\File.mp3', 'rb'))
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\utils\request.py", line 264, in post
    'POST', url, body=data.to_form(), headers=data.headers, **urlopen_kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\telegram\utils\request.py", line 196, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out',))

**Comment by Eldinnie** [comment]
can you try setting the `timeout` argument for the send_* method to a higher value (999 for example) and see if the problem still occurs?

**Comment by spookyahell** [comment]
Oh wow that was an easy fix. Thanks. Can't believe I didn't think of that myself...
