### ISSUE TITLE
ImportError: No module named 'future'

### ISSUE THREAD

**Issue by Obey138** [python-telegram-bot/python-telegram-bot#982]
### Steps to reproduce
1. Fresh installation of python-telegram-bot using
``$ pip install python-telegram-bot``

2.  Run [this code](https://gist.github.com/Obey138/b66a0ce6fff4850f30df54c62cea864d) using any IDE for Python

### Expected behavior
Script prints name of my bot

### Actual behavior
`ImportError: No module named 'future'`

Note: Runs without error when executing with python shell through terminal window

### Configuration
**Operating System:**
Raspbian 9.3, Linux 4.9.59-v7+ armv7l
on Raspberry Pi 3 Model B

**Version of Python, python-telegram-bot & dependencies:**
```
$ python -m telegram
python-telegram-bot 9.0.0
certifi 2018.01.18
future 0.16.0
Python 2.7.13 (default, Nov 24 2017, 17:33:09)  [GCC 6.3.0 20170516]
```

### Logs
```python
Traceback (most recent call last):
  File "/home/pi/bot.py", line 4, in <module>
    import telegram
  File "/usr/local/lib/python2.7/dist-packages/telegram/__init__.py", line 45, in <module>
    from .files.file import File
  File "/usr/local/lib/python2.7/dist-packages/telegram/files/file.py", line 22, in <module>
    from future.backports.urllib import parse as urllib_parse
ImportError: No module named 'future'
```

**Comment by Obey138** [comment]
After moving some files between '/usr/lib' and '/usr/local/lib' and adding one more path to sys.path I made it work.
Both IDEs I tried to use didn't load modules installed for Python 2.7
